// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
/**
 * Attitude Comprehensive Message
 */
export class ACM {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsACM(bb, obj) {
        return (obj || new ACM()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsACM(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ACM()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static bufferHasIdentifier(bb) {
        return bb.__has_identifier('$ACM');
    }
    CCSDS_ACM_VERS(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    CREATION_DATE(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    ORIGINATOR(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    OBJECT_NAME(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    OBJECT_ID(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    static startACM(builder) {
        builder.startObject(5);
    }
    static addCcsdsAcmVers(builder, CCSDS_ACM_VERSOffset) {
        builder.addFieldOffset(0, CCSDS_ACM_VERSOffset, 0);
    }
    static addCreationDate(builder, CREATION_DATEOffset) {
        builder.addFieldOffset(1, CREATION_DATEOffset, 0);
    }
    static addOriginator(builder, ORIGINATOROffset) {
        builder.addFieldOffset(2, ORIGINATOROffset, 0);
    }
    static addObjectName(builder, OBJECT_NAMEOffset) {
        builder.addFieldOffset(3, OBJECT_NAMEOffset, 0);
    }
    static addObjectId(builder, OBJECT_IDOffset) {
        builder.addFieldOffset(4, OBJECT_IDOffset, 0);
    }
    static endACM(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static finishACMBuffer(builder, offset) {
        builder.finish(offset, '$ACM');
    }
    static finishSizePrefixedACMBuffer(builder, offset) {
        builder.finish(offset, '$ACM', true);
    }
    static createACM(builder, CCSDS_ACM_VERSOffset, CREATION_DATEOffset, ORIGINATOROffset, OBJECT_NAMEOffset, OBJECT_IDOffset) {
        ACM.startACM(builder);
        ACM.addCcsdsAcmVers(builder, CCSDS_ACM_VERSOffset);
        ACM.addCreationDate(builder, CREATION_DATEOffset);
        ACM.addOriginator(builder, ORIGINATOROffset);
        ACM.addObjectName(builder, OBJECT_NAMEOffset);
        ACM.addObjectId(builder, OBJECT_IDOffset);
        return ACM.endACM(builder);
    }
    unpack() {
        return new ACMT(this.CCSDS_ACM_VERS(), this.CREATION_DATE(), this.ORIGINATOR(), this.OBJECT_NAME(), this.OBJECT_ID());
    }
    unpackTo(_o) {
        _o.CCSDS_ACM_VERS = this.CCSDS_ACM_VERS();
        _o.CREATION_DATE = this.CREATION_DATE();
        _o.ORIGINATOR = this.ORIGINATOR();
        _o.OBJECT_NAME = this.OBJECT_NAME();
        _o.OBJECT_ID = this.OBJECT_ID();
    }
}
export class ACMT {
    constructor(CCSDS_ACM_VERS = null, CREATION_DATE = null, ORIGINATOR = null, OBJECT_NAME = null, OBJECT_ID = null) {
        this.CCSDS_ACM_VERS = CCSDS_ACM_VERS;
        this.CREATION_DATE = CREATION_DATE;
        this.ORIGINATOR = ORIGINATOR;
        this.OBJECT_NAME = OBJECT_NAME;
        this.OBJECT_ID = OBJECT_ID;
    }
    pack(builder) {
        const CCSDS_ACM_VERS = (this.CCSDS_ACM_VERS !== null ? builder.createString(this.CCSDS_ACM_VERS) : 0);
        const CREATION_DATE = (this.CREATION_DATE !== null ? builder.createString(this.CREATION_DATE) : 0);
        const ORIGINATOR = (this.ORIGINATOR !== null ? builder.createString(this.ORIGINATOR) : 0);
        const OBJECT_NAME = (this.OBJECT_NAME !== null ? builder.createString(this.OBJECT_NAME) : 0);
        const OBJECT_ID = (this.OBJECT_ID !== null ? builder.createString(this.OBJECT_ID) : 0);
        return ACM.createACM(builder, CCSDS_ACM_VERS, CREATION_DATE, ORIGINATOR, OBJECT_NAME, OBJECT_ID);
    }
}
