import * as flatbuffers from 'flatbuffers';
/**
 * Attitude Data Point
 */
export declare class ATD implements flatbuffers.IUnpackableObject<ATDT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): ATD;
    static getRootAsATD(bb: flatbuffers.ByteBuffer, obj?: ATD): ATD;
    static getSizePrefixedRootAsATD(bb: flatbuffers.ByteBuffer, obj?: ATD): ATD;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    AS_ID(): string | null;
    AS_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SAT_NO(): number;
    ORIG_OBJECT_ID(): string | null;
    ORIG_OBJECT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TS(): string | null;
    TS(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MOTION_TYPE(): string | null;
    MOTION_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    Q1(): number;
    Q2(): number;
    Q3(): number;
    QC(): number;
    Q1_DOT(): number;
    Q2_DOT(): number;
    Q3_DOT(): number;
    QC_DOT(): number;
    X_ANGLE(index: number): string;
    X_ANGLE(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    xAngleLength(): number;
    Y_ANGLE(index: number): string;
    Y_ANGLE(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    yAngleLength(): number;
    Z_ANGLE(index: number): string;
    Z_ANGLE(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    zAngleLength(): number;
    X_RATE(index: number): string;
    X_RATE(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    xRateLength(): number;
    Y_RATE(index: number): string;
    Y_RATE(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    yRateLength(): number;
    Z_RATE(index: number): string;
    Z_RATE(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    zRateLength(): number;
    RA(): number;
    DECLINATION(): number;
    CONING_ANGLE(): number;
    PREC_PERIOD(): number;
    SPIN_PERIOD(): number;
    static startATD(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addAsId(builder: flatbuffers.Builder, AS_IDOffset: flatbuffers.Offset): void;
    static addSatNo(builder: flatbuffers.Builder, SAT_NO: number): void;
    static addOrigObjectId(builder: flatbuffers.Builder, ORIG_OBJECT_IDOffset: flatbuffers.Offset): void;
    static addTs(builder: flatbuffers.Builder, TSOffset: flatbuffers.Offset): void;
    static addMotionType(builder: flatbuffers.Builder, MOTION_TYPEOffset: flatbuffers.Offset): void;
    static addQ1(builder: flatbuffers.Builder, Q1: number): void;
    static addQ2(builder: flatbuffers.Builder, Q2: number): void;
    static addQ3(builder: flatbuffers.Builder, Q3: number): void;
    static addQc(builder: flatbuffers.Builder, QC: number): void;
    static addQ1Dot(builder: flatbuffers.Builder, Q1_DOT: number): void;
    static addQ2Dot(builder: flatbuffers.Builder, Q2_DOT: number): void;
    static addQ3Dot(builder: flatbuffers.Builder, Q3_DOT: number): void;
    static addQcDot(builder: flatbuffers.Builder, QC_DOT: number): void;
    static addXAngle(builder: flatbuffers.Builder, X_ANGLEOffset: flatbuffers.Offset): void;
    static createXAngleVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startXAngleVector(builder: flatbuffers.Builder, numElems: number): void;
    static addYAngle(builder: flatbuffers.Builder, Y_ANGLEOffset: flatbuffers.Offset): void;
    static createYAngleVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startYAngleVector(builder: flatbuffers.Builder, numElems: number): void;
    static addZAngle(builder: flatbuffers.Builder, Z_ANGLEOffset: flatbuffers.Offset): void;
    static createZAngleVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startZAngleVector(builder: flatbuffers.Builder, numElems: number): void;
    static addXRate(builder: flatbuffers.Builder, X_RATEOffset: flatbuffers.Offset): void;
    static createXRateVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startXRateVector(builder: flatbuffers.Builder, numElems: number): void;
    static addYRate(builder: flatbuffers.Builder, Y_RATEOffset: flatbuffers.Offset): void;
    static createYRateVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startYRateVector(builder: flatbuffers.Builder, numElems: number): void;
    static addZRate(builder: flatbuffers.Builder, Z_RATEOffset: flatbuffers.Offset): void;
    static createZRateVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startZRateVector(builder: flatbuffers.Builder, numElems: number): void;
    static addRa(builder: flatbuffers.Builder, RA: number): void;
    static addDeclination(builder: flatbuffers.Builder, DECLINATION: number): void;
    static addConingAngle(builder: flatbuffers.Builder, CONING_ANGLE: number): void;
    static addPrecPeriod(builder: flatbuffers.Builder, PREC_PERIOD: number): void;
    static addSpinPeriod(builder: flatbuffers.Builder, SPIN_PERIOD: number): void;
    static endATD(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishATDBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedATDBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createATD(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, AS_IDOffset: flatbuffers.Offset, SAT_NO: number, ORIG_OBJECT_IDOffset: flatbuffers.Offset, TSOffset: flatbuffers.Offset, MOTION_TYPEOffset: flatbuffers.Offset, Q1: number, Q2: number, Q3: number, QC: number, Q1_DOT: number, Q2_DOT: number, Q3_DOT: number, QC_DOT: number, X_ANGLEOffset: flatbuffers.Offset, Y_ANGLEOffset: flatbuffers.Offset, Z_ANGLEOffset: flatbuffers.Offset, X_RATEOffset: flatbuffers.Offset, Y_RATEOffset: flatbuffers.Offset, Z_RATEOffset: flatbuffers.Offset, RA: number, DECLINATION: number, CONING_ANGLE: number, PREC_PERIOD: number, SPIN_PERIOD: number): flatbuffers.Offset;
    unpack(): ATDT;
    unpackTo(_o: ATDT): void;
}
export declare class ATDT implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    AS_ID: string | Uint8Array | null;
    SAT_NO: number;
    ORIG_OBJECT_ID: string | Uint8Array | null;
    TS: string | Uint8Array | null;
    MOTION_TYPE: string | Uint8Array | null;
    Q1: number;
    Q2: number;
    Q3: number;
    QC: number;
    Q1_DOT: number;
    Q2_DOT: number;
    Q3_DOT: number;
    QC_DOT: number;
    X_ANGLE: (string)[];
    Y_ANGLE: (string)[];
    Z_ANGLE: (string)[];
    X_RATE: (string)[];
    Y_RATE: (string)[];
    Z_RATE: (string)[];
    RA: number;
    DECLINATION: number;
    CONING_ANGLE: number;
    PREC_PERIOD: number;
    SPIN_PERIOD: number;
    constructor(ID?: string | Uint8Array | null, AS_ID?: string | Uint8Array | null, SAT_NO?: number, ORIG_OBJECT_ID?: string | Uint8Array | null, TS?: string | Uint8Array | null, MOTION_TYPE?: string | Uint8Array | null, Q1?: number, Q2?: number, Q3?: number, QC?: number, Q1_DOT?: number, Q2_DOT?: number, Q3_DOT?: number, QC_DOT?: number, X_ANGLE?: (string)[], Y_ANGLE?: (string)[], Z_ANGLE?: (string)[], X_RATE?: (string)[], Y_RATE?: (string)[], Z_RATE?: (string)[], RA?: number, DECLINATION?: number, CONING_ANGLE?: number, PREC_PERIOD?: number, SPIN_PERIOD?: number);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=ATD.d.ts.map