import * as flatbuffers from 'flatbuffers';
import { dssSyncState } from './dssSyncState.js';
export declare class DSS implements flatbuffers.IUnpackableObject<DSST> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): DSS;
    static getRootAsDSS(bb: flatbuffers.ByteBuffer, obj?: DSS): DSS;
    static getSizePrefixedRootAsDSS(bb: flatbuffers.ByteBuffer, obj?: DSS): DSS;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    STATUS(): dssSyncState;
    SYNCED_ROWS(): bigint;
    TOTAL_ROWS(): bigint;
    LOCAL_ROWS(): bigint;
    PINNED_ROWS(): bigint;
    MISSING_ROWS(): bigint;
    CACHED_BYTES(): bigint;
    PINNED_BYTES(): bigint;
    DOWNLOADED_BYTES(): bigint;
    DOWNLOAD_SPEED_BYTES_PER_SECOND(): bigint;
    MEASURED_WIRE_SPEED_BYTES_PER_SECOND(): bigint;
    HAS_WIRE_SPEED_UTILIZATION(): boolean;
    WIRE_SPEED_UTILIZATION(): number;
    WIRE_SPEED_TARGET(): number;
    HAS_WIRE_SPEED_TARGET_MET(): boolean;
    WIRE_SPEED_TARGET_MET(): boolean;
    MANIFEST_DISCOVERY_MS(): bigint;
    NETWORK_TRANSFER_MS(): bigint;
    VERIFICATION_MS(): bigint;
    FLATSQL_MATERIALIZATION_MS(): bigint;
    PROVIDER_PEER_ID(): string | null;
    PROVIDER_PEER_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    PROVIDER_PUBLIC_KEY(): string | null;
    PROVIDER_PUBLIC_KEY(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SNAPSHOT_ID(): string | null;
    SNAPSHOT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    HEAD(): string | null;
    HEAD(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    CURSOR(): string | null;
    CURSOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    NEXT_CURSOR(): string | null;
    NEXT_CURSOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    HIGH_WATER_MARK(): string | null;
    HIGH_WATER_MARK(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    QUERY_PROFILE(): string | null;
    QUERY_PROFILE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    CHUNK_HASH(): string | null;
    CHUNK_HASH(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SYNC_PROTOCOL(): string | null;
    SYNC_PROTOCOL(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SYNC_FILTER(): string | null;
    SYNC_FILTER(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    VERIFIED_CHUNKS(index: number): string;
    VERIFIED_CHUNKS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    verifiedChunksLength(): number;
    LAST_SYNCED_AT(): string | null;
    LAST_SYNCED_AT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ERROR(): string | null;
    ERROR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    static startDSS(builder: flatbuffers.Builder): void;
    static addStatus(builder: flatbuffers.Builder, STATUS: dssSyncState): void;
    static addSyncedRows(builder: flatbuffers.Builder, SYNCED_ROWS: bigint): void;
    static addTotalRows(builder: flatbuffers.Builder, TOTAL_ROWS: bigint): void;
    static addLocalRows(builder: flatbuffers.Builder, LOCAL_ROWS: bigint): void;
    static addPinnedRows(builder: flatbuffers.Builder, PINNED_ROWS: bigint): void;
    static addMissingRows(builder: flatbuffers.Builder, MISSING_ROWS: bigint): void;
    static addCachedBytes(builder: flatbuffers.Builder, CACHED_BYTES: bigint): void;
    static addPinnedBytes(builder: flatbuffers.Builder, PINNED_BYTES: bigint): void;
    static addDownloadedBytes(builder: flatbuffers.Builder, DOWNLOADED_BYTES: bigint): void;
    static addDownloadSpeedBytesPerSecond(builder: flatbuffers.Builder, DOWNLOAD_SPEED_BYTES_PER_SECOND: bigint): void;
    static addMeasuredWireSpeedBytesPerSecond(builder: flatbuffers.Builder, MEASURED_WIRE_SPEED_BYTES_PER_SECOND: bigint): void;
    static addHasWireSpeedUtilization(builder: flatbuffers.Builder, HAS_WIRE_SPEED_UTILIZATION: boolean): void;
    static addWireSpeedUtilization(builder: flatbuffers.Builder, WIRE_SPEED_UTILIZATION: number): void;
    static addWireSpeedTarget(builder: flatbuffers.Builder, WIRE_SPEED_TARGET: number): void;
    static addHasWireSpeedTargetMet(builder: flatbuffers.Builder, HAS_WIRE_SPEED_TARGET_MET: boolean): void;
    static addWireSpeedTargetMet(builder: flatbuffers.Builder, WIRE_SPEED_TARGET_MET: boolean): void;
    static addManifestDiscoveryMs(builder: flatbuffers.Builder, MANIFEST_DISCOVERY_MS: bigint): void;
    static addNetworkTransferMs(builder: flatbuffers.Builder, NETWORK_TRANSFER_MS: bigint): void;
    static addVerificationMs(builder: flatbuffers.Builder, VERIFICATION_MS: bigint): void;
    static addFlatsqlMaterializationMs(builder: flatbuffers.Builder, FLATSQL_MATERIALIZATION_MS: bigint): void;
    static addProviderPeerId(builder: flatbuffers.Builder, PROVIDER_PEER_IDOffset: flatbuffers.Offset): void;
    static addProviderPublicKey(builder: flatbuffers.Builder, PROVIDER_PUBLIC_KEYOffset: flatbuffers.Offset): void;
    static addSnapshotId(builder: flatbuffers.Builder, SNAPSHOT_IDOffset: flatbuffers.Offset): void;
    static addHead(builder: flatbuffers.Builder, HEADOffset: flatbuffers.Offset): void;
    static addCursor(builder: flatbuffers.Builder, CURSOROffset: flatbuffers.Offset): void;
    static addNextCursor(builder: flatbuffers.Builder, NEXT_CURSOROffset: flatbuffers.Offset): void;
    static addHighWaterMark(builder: flatbuffers.Builder, HIGH_WATER_MARKOffset: flatbuffers.Offset): void;
    static addQueryProfile(builder: flatbuffers.Builder, QUERY_PROFILEOffset: flatbuffers.Offset): void;
    static addChunkHash(builder: flatbuffers.Builder, CHUNK_HASHOffset: flatbuffers.Offset): void;
    static addSyncProtocol(builder: flatbuffers.Builder, SYNC_PROTOCOLOffset: flatbuffers.Offset): void;
    static addSyncFilter(builder: flatbuffers.Builder, SYNC_FILTEROffset: flatbuffers.Offset): void;
    static addVerifiedChunks(builder: flatbuffers.Builder, VERIFIED_CHUNKSOffset: flatbuffers.Offset): void;
    static createVerifiedChunksVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startVerifiedChunksVector(builder: flatbuffers.Builder, numElems: number): void;
    static addLastSyncedAt(builder: flatbuffers.Builder, LAST_SYNCED_ATOffset: flatbuffers.Offset): void;
    static addError(builder: flatbuffers.Builder, ERROROffset: flatbuffers.Offset): void;
    static endDSS(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishDSSBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedDSSBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createDSS(builder: flatbuffers.Builder, STATUS: dssSyncState, SYNCED_ROWS: bigint, TOTAL_ROWS: bigint, LOCAL_ROWS: bigint, PINNED_ROWS: bigint, MISSING_ROWS: bigint, CACHED_BYTES: bigint, PINNED_BYTES: bigint, DOWNLOADED_BYTES: bigint, DOWNLOAD_SPEED_BYTES_PER_SECOND: bigint, MEASURED_WIRE_SPEED_BYTES_PER_SECOND: bigint, HAS_WIRE_SPEED_UTILIZATION: boolean, WIRE_SPEED_UTILIZATION: number, WIRE_SPEED_TARGET: number, HAS_WIRE_SPEED_TARGET_MET: boolean, WIRE_SPEED_TARGET_MET: boolean, MANIFEST_DISCOVERY_MS: bigint, NETWORK_TRANSFER_MS: bigint, VERIFICATION_MS: bigint, FLATSQL_MATERIALIZATION_MS: bigint, PROVIDER_PEER_IDOffset: flatbuffers.Offset, PROVIDER_PUBLIC_KEYOffset: flatbuffers.Offset, SNAPSHOT_IDOffset: flatbuffers.Offset, HEADOffset: flatbuffers.Offset, CURSOROffset: flatbuffers.Offset, NEXT_CURSOROffset: flatbuffers.Offset, HIGH_WATER_MARKOffset: flatbuffers.Offset, QUERY_PROFILEOffset: flatbuffers.Offset, CHUNK_HASHOffset: flatbuffers.Offset, SYNC_PROTOCOLOffset: flatbuffers.Offset, SYNC_FILTEROffset: flatbuffers.Offset, VERIFIED_CHUNKSOffset: flatbuffers.Offset, LAST_SYNCED_ATOffset: flatbuffers.Offset, ERROROffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): DSST;
    unpackTo(_o: DSST): void;
}
export declare class DSST implements flatbuffers.IGeneratedObject {
    STATUS: dssSyncState;
    SYNCED_ROWS: bigint;
    TOTAL_ROWS: bigint;
    LOCAL_ROWS: bigint;
    PINNED_ROWS: bigint;
    MISSING_ROWS: bigint;
    CACHED_BYTES: bigint;
    PINNED_BYTES: bigint;
    DOWNLOADED_BYTES: bigint;
    DOWNLOAD_SPEED_BYTES_PER_SECOND: bigint;
    MEASURED_WIRE_SPEED_BYTES_PER_SECOND: bigint;
    HAS_WIRE_SPEED_UTILIZATION: boolean;
    WIRE_SPEED_UTILIZATION: number;
    WIRE_SPEED_TARGET: number;
    HAS_WIRE_SPEED_TARGET_MET: boolean;
    WIRE_SPEED_TARGET_MET: boolean;
    MANIFEST_DISCOVERY_MS: bigint;
    NETWORK_TRANSFER_MS: bigint;
    VERIFICATION_MS: bigint;
    FLATSQL_MATERIALIZATION_MS: bigint;
    PROVIDER_PEER_ID: string | Uint8Array | null;
    PROVIDER_PUBLIC_KEY: string | Uint8Array | null;
    SNAPSHOT_ID: string | Uint8Array | null;
    HEAD: string | Uint8Array | null;
    CURSOR: string | Uint8Array | null;
    NEXT_CURSOR: string | Uint8Array | null;
    HIGH_WATER_MARK: string | Uint8Array | null;
    QUERY_PROFILE: string | Uint8Array | null;
    CHUNK_HASH: string | Uint8Array | null;
    SYNC_PROTOCOL: string | Uint8Array | null;
    SYNC_FILTER: string | Uint8Array | null;
    VERIFIED_CHUNKS: (string)[];
    LAST_SYNCED_AT: string | Uint8Array | null;
    ERROR: string | Uint8Array | null;
    constructor(STATUS?: dssSyncState, SYNCED_ROWS?: bigint, TOTAL_ROWS?: bigint, LOCAL_ROWS?: bigint, PINNED_ROWS?: bigint, MISSING_ROWS?: bigint, CACHED_BYTES?: bigint, PINNED_BYTES?: bigint, DOWNLOADED_BYTES?: bigint, DOWNLOAD_SPEED_BYTES_PER_SECOND?: bigint, MEASURED_WIRE_SPEED_BYTES_PER_SECOND?: bigint, HAS_WIRE_SPEED_UTILIZATION?: boolean, WIRE_SPEED_UTILIZATION?: number, WIRE_SPEED_TARGET?: number, HAS_WIRE_SPEED_TARGET_MET?: boolean, WIRE_SPEED_TARGET_MET?: boolean, MANIFEST_DISCOVERY_MS?: bigint, NETWORK_TRANSFER_MS?: bigint, VERIFICATION_MS?: bigint, FLATSQL_MATERIALIZATION_MS?: bigint, PROVIDER_PEER_ID?: string | Uint8Array | null, PROVIDER_PUBLIC_KEY?: string | Uint8Array | null, SNAPSHOT_ID?: string | Uint8Array | null, HEAD?: string | Uint8Array | null, CURSOR?: string | Uint8Array | null, NEXT_CURSOR?: string | Uint8Array | null, HIGH_WATER_MARK?: string | Uint8Array | null, QUERY_PROFILE?: string | Uint8Array | null, CHUNK_HASH?: string | Uint8Array | null, SYNC_PROTOCOL?: string | Uint8Array | null, SYNC_FILTER?: string | Uint8Array | null, VERIFIED_CHUNKS?: (string)[], LAST_SYNCED_AT?: string | Uint8Array | null, ERROR?: string | Uint8Array | null);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=DSS.d.ts.map