// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
/**
 * One signed integer coefficient in an intermodulation product. The product
 * frequency is the exact sum of COEFFICIENT * SOURCE_FREQUENCY_HZ terms.
 */
export class EMCIntermodulationTerm {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsEMCIntermodulationTerm(bb, obj) {
        return (obj || new EMCIntermodulationTerm()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsEMCIntermodulationTerm(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new EMCIntermodulationTerm()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    SOURCE_ENDPOINT_ID(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    SOURCE_FREQUENCY_HZ() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    COEFFICIENT() {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    }
    static startEMCIntermodulationTerm(builder) {
        builder.startObject(3);
    }
    static addSourceEndpointId(builder, SOURCE_ENDPOINT_IDOffset) {
        builder.addFieldOffset(0, SOURCE_ENDPOINT_IDOffset, 0);
    }
    static addSourceFrequencyHz(builder, SOURCE_FREQUENCY_HZ) {
        builder.addFieldFloat64(1, SOURCE_FREQUENCY_HZ, 0.0);
    }
    static addCoefficient(builder, COEFFICIENT) {
        builder.addFieldInt32(2, COEFFICIENT, 0);
    }
    static endEMCIntermodulationTerm(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createEMCIntermodulationTerm(builder, SOURCE_ENDPOINT_IDOffset, SOURCE_FREQUENCY_HZ, COEFFICIENT) {
        EMCIntermodulationTerm.startEMCIntermodulationTerm(builder);
        EMCIntermodulationTerm.addSourceEndpointId(builder, SOURCE_ENDPOINT_IDOffset);
        EMCIntermodulationTerm.addSourceFrequencyHz(builder, SOURCE_FREQUENCY_HZ);
        EMCIntermodulationTerm.addCoefficient(builder, COEFFICIENT);
        return EMCIntermodulationTerm.endEMCIntermodulationTerm(builder);
    }
    unpack() {
        return new EMCIntermodulationTermT(this.SOURCE_ENDPOINT_ID(), this.SOURCE_FREQUENCY_HZ(), this.COEFFICIENT());
    }
    unpackTo(_o) {
        _o.SOURCE_ENDPOINT_ID = this.SOURCE_ENDPOINT_ID();
        _o.SOURCE_FREQUENCY_HZ = this.SOURCE_FREQUENCY_HZ();
        _o.COEFFICIENT = this.COEFFICIENT();
    }
}
export class EMCIntermodulationTermT {
    constructor(SOURCE_ENDPOINT_ID = null, SOURCE_FREQUENCY_HZ = 0.0, COEFFICIENT = 0) {
        this.SOURCE_ENDPOINT_ID = SOURCE_ENDPOINT_ID;
        this.SOURCE_FREQUENCY_HZ = SOURCE_FREQUENCY_HZ;
        this.COEFFICIENT = COEFFICIENT;
    }
    pack(builder) {
        const SOURCE_ENDPOINT_ID = (this.SOURCE_ENDPOINT_ID !== null ? builder.createString(this.SOURCE_ENDPOINT_ID) : 0);
        return EMCIntermodulationTerm.createEMCIntermodulationTerm(builder, SOURCE_ENDPOINT_ID, this.SOURCE_FREQUENCY_HZ, this.COEFFICIENT);
    }
}
