import * as flatbuffers from 'flatbuffers';
import { FieldStreamAudience, FieldStreamAudienceT } from './FieldStreamAudience.js';
import { FieldStreamRule, FieldStreamRuleT } from './FieldStreamRule.js';
import { fieldStreamOperationCategory } from './fieldStreamOperationCategory.js';
import { fieldStreamRevocationCategory } from './fieldStreamRevocationCategory.js';
export declare class FSP implements flatbuffers.IUnpackableObject<FSPT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): FSP;
    static getRootAsFSP(bb: flatbuffers.ByteBuffer, obj?: FSP): FSP;
    static getSizePrefixedRootAsFSP(bb: flatbuffers.ByteBuffer, obj?: FSP): FSP;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    POLICY_ID(): string;
    POLICY_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    POLICY_VERSION(): number;
    PROVIDER_PEER_ID(): string;
    PROVIDER_PEER_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    LISTING_ID(): string;
    LISTING_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    STREAM_ID(): string;
    STREAM_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    SCHEMA_CODE(): string;
    SCHEMA_CODE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    SCHEMA_HASH(index: number): number | null;
    schemaHashLength(): number;
    schemaHashArray(): Uint8Array | null;
    AUDIENCES(index: number, obj?: FieldStreamAudience): FieldStreamAudience | null;
    audiencesLength(): number;
    RULES(index: number, obj?: FieldStreamRule): FieldStreamRule | null;
    rulesLength(): number;
    ALLOWED_OPERATIONS(index: number): fieldStreamOperationCategory | null;
    allowedOperationsLength(): number;
    allowedOperationsArray(): Int8Array | null;
    KEY_SCOPE(): string | null;
    KEY_SCOPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    KEY_EPOCH(): string | null;
    KEY_EPOCH(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    VALID_FROM(): bigint;
    EXPIRES_AT(): bigint;
    REVOCATION_STATUS(): fieldStreamRevocationCategory;
    REVOKED_AT(): bigint;
    REVOCATION_REASON(): string | null;
    REVOCATION_REASON(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    PROVIDER_SIGNATURE(index: number): number | null;
    providerSignatureLength(): number;
    providerSignatureArray(): Uint8Array | null;
    static startFSP(builder: flatbuffers.Builder): void;
    static addPolicyId(builder: flatbuffers.Builder, POLICY_IDOffset: flatbuffers.Offset): void;
    static addPolicyVersion(builder: flatbuffers.Builder, POLICY_VERSION: number): void;
    static addProviderPeerId(builder: flatbuffers.Builder, PROVIDER_PEER_IDOffset: flatbuffers.Offset): void;
    static addListingId(builder: flatbuffers.Builder, LISTING_IDOffset: flatbuffers.Offset): void;
    static addStreamId(builder: flatbuffers.Builder, STREAM_IDOffset: flatbuffers.Offset): void;
    static addSchemaCode(builder: flatbuffers.Builder, SCHEMA_CODEOffset: flatbuffers.Offset): void;
    static addSchemaHash(builder: flatbuffers.Builder, SCHEMA_HASHOffset: flatbuffers.Offset): void;
    static createSchemaHashVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset;
    static startSchemaHashVector(builder: flatbuffers.Builder, numElems: number): void;
    static addAudiences(builder: flatbuffers.Builder, AUDIENCESOffset: flatbuffers.Offset): void;
    static createAudiencesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startAudiencesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addRules(builder: flatbuffers.Builder, RULESOffset: flatbuffers.Offset): void;
    static createRulesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startRulesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addAllowedOperations(builder: flatbuffers.Builder, ALLOWED_OPERATIONSOffset: flatbuffers.Offset): void;
    static createAllowedOperationsVector(builder: flatbuffers.Builder, data: fieldStreamOperationCategory[]): flatbuffers.Offset;
    static startAllowedOperationsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addKeyScope(builder: flatbuffers.Builder, KEY_SCOPEOffset: flatbuffers.Offset): void;
    static addKeyEpoch(builder: flatbuffers.Builder, KEY_EPOCHOffset: flatbuffers.Offset): void;
    static addValidFrom(builder: flatbuffers.Builder, VALID_FROM: bigint): void;
    static addExpiresAt(builder: flatbuffers.Builder, EXPIRES_AT: bigint): void;
    static addRevocationStatus(builder: flatbuffers.Builder, REVOCATION_STATUS: fieldStreamRevocationCategory): void;
    static addRevokedAt(builder: flatbuffers.Builder, REVOKED_AT: bigint): void;
    static addRevocationReason(builder: flatbuffers.Builder, REVOCATION_REASONOffset: flatbuffers.Offset): void;
    static addProviderSignature(builder: flatbuffers.Builder, PROVIDER_SIGNATUREOffset: flatbuffers.Offset): void;
    static createProviderSignatureVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset;
    static startProviderSignatureVector(builder: flatbuffers.Builder, numElems: number): void;
    static endFSP(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishFSPBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedFSPBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createFSP(builder: flatbuffers.Builder, POLICY_IDOffset: flatbuffers.Offset, POLICY_VERSION: number, PROVIDER_PEER_IDOffset: flatbuffers.Offset, LISTING_IDOffset: flatbuffers.Offset, STREAM_IDOffset: flatbuffers.Offset, SCHEMA_CODEOffset: flatbuffers.Offset, SCHEMA_HASHOffset: flatbuffers.Offset, AUDIENCESOffset: flatbuffers.Offset, RULESOffset: flatbuffers.Offset, ALLOWED_OPERATIONSOffset: flatbuffers.Offset, KEY_SCOPEOffset: flatbuffers.Offset, KEY_EPOCHOffset: flatbuffers.Offset, VALID_FROM: bigint, EXPIRES_AT: bigint, REVOCATION_STATUS: fieldStreamRevocationCategory, REVOKED_AT: bigint, REVOCATION_REASONOffset: flatbuffers.Offset, PROVIDER_SIGNATUREOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): FSPT;
    unpackTo(_o: FSPT): void;
}
export declare class FSPT implements flatbuffers.IGeneratedObject {
    POLICY_ID: string | Uint8Array | null;
    POLICY_VERSION: number;
    PROVIDER_PEER_ID: string | Uint8Array | null;
    LISTING_ID: string | Uint8Array | null;
    STREAM_ID: string | Uint8Array | null;
    SCHEMA_CODE: string | Uint8Array | null;
    SCHEMA_HASH: (number)[];
    AUDIENCES: (FieldStreamAudienceT)[];
    RULES: (FieldStreamRuleT)[];
    ALLOWED_OPERATIONS: (fieldStreamOperationCategory)[];
    KEY_SCOPE: string | Uint8Array | null;
    KEY_EPOCH: string | Uint8Array | null;
    VALID_FROM: bigint;
    EXPIRES_AT: bigint;
    REVOCATION_STATUS: fieldStreamRevocationCategory;
    REVOKED_AT: bigint;
    REVOCATION_REASON: string | Uint8Array | null;
    PROVIDER_SIGNATURE: (number)[];
    constructor(POLICY_ID?: string | Uint8Array | null, POLICY_VERSION?: number, PROVIDER_PEER_ID?: string | Uint8Array | null, LISTING_ID?: string | Uint8Array | null, STREAM_ID?: string | Uint8Array | null, SCHEMA_CODE?: string | Uint8Array | null, SCHEMA_HASH?: (number)[], AUDIENCES?: (FieldStreamAudienceT)[], RULES?: (FieldStreamRuleT)[], ALLOWED_OPERATIONS?: (fieldStreamOperationCategory)[], KEY_SCOPE?: string | Uint8Array | null, KEY_EPOCH?: string | Uint8Array | null, VALID_FROM?: bigint, EXPIRES_AT?: bigint, REVOCATION_STATUS?: fieldStreamRevocationCategory, REVOKED_AT?: bigint, REVOCATION_REASON?: string | Uint8Array | null, PROVIDER_SIGNATURE?: (number)[]);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=FSP.d.ts.map