// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var LeadMethod;
(function (LeadMethod) {
    LeadMethod[LeadMethod["NONE"] = 0] = "NONE";
    LeadMethod[LeadMethod["PREDICTIVE"] = 1] = "PREDICTIVE";
    LeadMethod[LeadMethod["COLLISION"] = 2] = "COLLISION";
    LeadMethod[LeadMethod["CONSTANT_BEARING"] = 3] = "CONSTANT_BEARING";
    LeadMethod[LeadMethod["PURSUIT"] = 4] = "PURSUIT";
})(LeadMethod || (LeadMethod = {}));
