export { ACL, ACLT } from './ACL.js';
export { ACM, ACMT } from './ACM.js';
export { ACR, ACRT } from './ACR.js';
export { AEM, AEMT } from './AEM.js';
export { AEMSegment, AEMSegmentT } from './AEMSegment.js';
export { AOF, AOFT } from './AOF.js';
export { APM, APMT } from './APM.js';
export { ARM, ARMT } from './ARM.js';
export { AST, ASTT } from './AST.js';
export { ATD, ATDT } from './ATD.js';
export { ATM, ATMT } from './ATM.js';
export { AbsoluteTimeParameterType, AbsoluteTimeParameterTypeT } from './AbsoluteTimeParameterType.js';
export { Address, AddressT } from './Address.js';
export { AggregateArgumentType, AggregateArgumentTypeT } from './AggregateArgumentType.js';
export { AggregateMember, AggregateMemberT } from './AggregateMember.js';
export { AggregateParameterType, AggregateParameterTypeT } from './AggregateParameterType.js';
export { AircraftType } from './AircraftType.js';
export { AlarmRange, AlarmRangeT } from './AlarmRange.js';
export { AlarmSeverityType } from './AlarmSeverityType.js';
export { AlgorithmInput, AlgorithmInputT } from './AlgorithmInput.js';
export { AlgorithmOutput, AlgorithmOutputT } from './AlgorithmOutput.js';
export { AlgorithmSet, AlgorithmSetT } from './AlgorithmSet.js';
export { AlgorithmTrigger, AlgorithmTriggerT } from './AlgorithmTrigger.js';
export { AmmoType } from './AmmoType.js';
export { AntennaPattern } from './AntennaPattern.js';
export { Argument, ArgumentT } from './Argument.js';
export { ArgumentAssignment, ArgumentAssignmentT } from './ArgumentAssignment.js';
export { ArgumentRefEntry, ArgumentRefEntryT } from './ArgumentRefEntry.js';
export { ArgumentTypeSet, ArgumentTypeSetT } from './ArgumentTypeSet.js';
export { ArmorMaterial } from './ArmorMaterial.js';
export { ArrayDimension, ArrayDimensionT } from './ArrayDimension.js';
export { ArrayParameterRefEntry, ArrayParameterRefEntryT } from './ArrayParameterRefEntry.js';
export { ArrayParameterType, ArrayParameterTypeT } from './ArrayParameterType.js';
export { AssociationMethod } from './AssociationMethod.js';
export { AtmosphereModel } from './AtmosphereModel.js';
export { AtmosphericModelFamily } from './AtmosphericModelFamily.js';
export { BAL, BALT } from './BAL.js';
export { BEM, BEMT } from './BEM.js';
export { BMC, BMCT } from './BMC.js';
export { BOV, BOVT } from './BOV.js';
export { BallisticModel } from './BallisticModel.js';
export { Band, BandT } from './Band.js';
export { BandType } from './BandType.js';
export { BaseContainer, BaseContainerT } from './BaseContainer.js';
export { BaseMetaCommand, BaseMetaCommandT } from './BaseMetaCommand.js';
export { BinaryArgumentType, BinaryArgumentTypeT } from './BinaryArgumentType.js';
export { BinaryDataEncoding, BinaryDataEncodingT } from './BinaryDataEncoding.js';
export { BinaryParameterType, BinaryParameterTypeT } from './BinaryParameterType.js';
export { BooleanArgumentType, BooleanArgumentTypeT } from './BooleanArgumentType.js';
export { BooleanExpression, BooleanExpressionT } from './BooleanExpression.js';
export { BooleanOperatorType } from './BooleanOperatorType.js';
export { BooleanParameterType, BooleanParameterTypeT } from './BooleanParameterType.js';
export { BottomType } from './BottomType.js';
export { ByteOrderType } from './ByteOrderType.js';
export { CAT, CATT } from './CAT.js';
export { CDM, CDMT } from './CDM.js';
export { CDMObject, CDMObjectT } from './CDMObject.js';
export { CFP, CFPT } from './CFP.js';
export { CHN, CHNT } from './CHN.js';
export { CLT, CLTT } from './CLT.js';
export { CMS, CMST } from './CMS.js';
export { COM, COMT } from './COM.js';
export { CRD, CRDT } from './CRD.js';
export { CRM, CRMT } from './CRM.js';
export { CSM, CSMT } from './CSM.js';
export { CTR, CTRT } from './CTR.js';
export { CelestialFrame } from './CelestialFrame.js';
export { CelestialFrameWrapper, CelestialFrameWrapperT } from './CelestialFrameWrapper.js';
export { CentralBody } from './CentralBody.js';
export { ClockType } from './ClockType.js';
export { CollectMethod } from './CollectMethod.js';
export { CollisionShape } from './CollisionShape.js';
export { CommandContainer, CommandContainerT } from './CommandContainer.js';
export { CommandContainerEntry, CommandContainerEntryT } from './CommandContainerEntry.js';
export { CommandMetaData, CommandMetaDataT } from './CommandMetaData.js';
export { CommandSignificance, CommandSignificanceT } from './CommandSignificance.js';
export { CommandVerifier, CommandVerifierT } from './CommandVerifier.js';
export { ComparisonOperator } from './ComparisonOperator.js';
export { ContainerBinaryEncoding, ContainerBinaryEncodingT } from './ContainerBinaryEncoding.js';
export { ContainerEntry, ContainerEntryT } from './ContainerEntry.js';
export { ContainerRefEntry, ContainerRefEntryT } from './ContainerRefEntry.js';
export { ContainerSet, ContainerSetT } from './ContainerSet.js';
export { ContextAlarm, ContextAlarmT } from './ContextAlarm.js';
export { ContextCalibrator, ContextCalibratorT } from './ContextCalibrator.js';
export { CoordFrame } from './CoordFrame.js';
export { CountermeasureStatus } from './CountermeasureStatus.js';
export { CrewRole } from './CrewRole.js';
export { CrewState } from './CrewState.js';
export { CryptoKey, CryptoKeyT } from './CryptoKey.js';
export { CustomAlgorithm, CustomAlgorithmT } from './CustomAlgorithm.js';
export { CustomFrame } from './CustomFrame.js';
export { CustomFrameWrapper, CustomFrameWrapperT } from './CustomFrameWrapper.js';
export { CustomStream, CustomStreamT } from './CustomStream.js';
export { DCState } from './DCState.js';
export { DFH, DFHT } from './DFH.js';
export { DMG, DMGT } from './DMG.js';
export { DOA, DOAT } from './DOA.js';
export { DataCoverage, DataCoverageT } from './DataCoverage.js';
export { DataLinkType } from './DataLinkType.js';
export { DataMode } from './DataMode.js';
export { DataSourceType } from './DataSourceType.js';
export { DataType } from './DataType.js';
export { DateFormat } from './DateFormat.js';
export { DefaultAlarm, DefaultAlarmT } from './DefaultAlarm.js';
export { DestructionCause } from './DestructionCause.js';
export { DeviceType } from './DeviceType.js';
export { DragModel } from './DragModel.js';
export { DriveType } from './DriveType.js';
export { EME, EMET } from './EME.js';
export { ENC, ENCT } from './ENC.js';
export { ENGINE, ENGINET } from './ENGINE.js';
export { ENGINE_TYPE } from './ENGINE_TYPE.js';
export { ENV, ENVT } from './ENV.js';
export { EOO, EOOT } from './EOO.js';
export { EOP, EOPT } from './EOP.js';
export { EPM, EPMT } from './EPM.js';
export { ESMFunction } from './ESMFunction.js';
export { EWR, EWRT } from './EWR.js';
export { Ellipsoid } from './Ellipsoid.js';
export { EngineType } from './EngineType.js';
export { EntryFunction, EntryFunctionT } from './EntryFunction.js';
export { EnumeratedArgumentType, EnumeratedArgumentTypeT } from './EnumeratedArgumentType.js';
export { EnumeratedParameterType, EnumeratedParameterTypeT } from './EnumeratedParameterType.js';
export { EnumerationAlarm, EnumerationAlarmT } from './EnumerationAlarm.js';
export { EnumerationValue, EnumerationValueT } from './EnumerationValue.js';
export { EpochType } from './EpochType.js';
export { ErrorDetectionType } from './ErrorDetectionType.js';
export { F107DataType } from './F107DataType.js';
export { FCS, FCST } from './FCS.js';
export { FCSMode } from './FCSMode.js';
export { FilterType } from './FilterType.js';
export { FixedFrameStream, FixedFrameStreamT } from './FixedFrameStream.js';
export { FixedValueEntry, FixedValueEntryT } from './FixedValueEntry.js';
export { FlightPhase } from './FlightPhase.js';
export { FloatArgumentType, FloatArgumentTypeT } from './FloatArgumentType.js';
export { FloatDataEncoding, FloatDataEncodingT } from './FloatDataEncoding.js';
export { FloatEncodingType } from './FloatEncodingType.js';
export { FloatParameterType, FloatParameterTypeT } from './FloatParameterType.js';
export { FluxQualifier } from './FluxQualifier.js';
export { ForceModel } from './ForceModel.js';
export { ForceType } from './ForceType.js';
export { FrequencyRange, FrequencyRangeT } from './FrequencyRange.js';
export { FusionMethod } from './FusionMethod.js';
export { FuzeType } from './FuzeType.js';
export { GDI, GDIT } from './GDI.js';
export { GEO, GEOT } from './GEO.js';
export { GNO, GNOT } from './GNO.js';
export { GRV, GRVT } from './GRV.js';
export { GVH, GVHT } from './GVH.js';
export { GVHEngineType } from './GVHEngineType.js';
export { GearState } from './GearState.js';
export { Geometry, GeometryT } from './Geometry.js';
export { GravityModelName } from './GravityModelName.js';
export { GravityModelType } from './GravityModelType.js';
export { GuidanceLaw } from './GuidanceLaw.js';
export { HEL, HELT } from './HEL.js';
export { HYP, HYPT } from './HYP.js';
export { Header, HeaderT } from './Header.js';
export { IDM, IDMT } from './IDM.js';
export { IRO, IROT } from './IRO.js';
export { IntegerArgumentType, IntegerArgumentTypeT } from './IntegerArgumentType.js';
export { IntegerDataEncoding, IntegerDataEncodingT } from './IntegerDataEncoding.js';
export { IntegerEncodingType } from './IntegerEncodingType.js';
export { IntegerParameterType, IntegerParameterTypeT } from './IntegerParameterType.js';
export { IntegrationMethod } from './IntegrationMethod.js';
export { IntegratorType } from './IntegratorType.js';
export { Interlock, InterlockT } from './Interlock.js';
export { JammingType } from './JammingType.js';
export { KDF } from './KDF.js';
export { KeyExchange } from './KeyExchange.js';
export { KeyType } from './KeyType.js';
export { LCC, LCCT } from './LCC.js';
export { LDM, LDMT } from './LDM.js';
export { LKS, LKST } from './LKS.js';
export { LND, LNDT } from './LND.js';
export { LNE, LNET } from './LNE.js';
export { LandCoverType } from './LandCoverType.js';
export { LeadMethod } from './LeadMethod.js';
export { LocationInContainer, LocationInContainerT } from './LocationInContainer.js';
export { MET, METT } from './MET.js';
export { MFE, MFET } from './MFE.js';
export { MNF, MNFT } from './MNF.js';
export { MNV, MNVT } from './MNV.js';
export { MPE, MPET } from './MPE.js';
export { MSL, MSLT } from './MSL.js';
export { MST, MSTT } from './MST.js';
export { MTI, MTIT } from './MTI.js';
export { Maneuver, ManeuverT } from './Maneuver.js';
export { MatchCriteria, MatchCriteriaT } from './MatchCriteria.js';
export { MaterialType } from './MaterialType.js';
export { MathAlgorithm, MathAlgorithmT } from './MathAlgorithm.js';
export { MathOperation, MathOperationT } from './MathOperation.js';
export { MeasurementType } from './MeasurementType.js';
export { MetaCommand, MetaCommandT } from './MetaCommand.js';
export { MetaCommandSet, MetaCommandSetT } from './MetaCommandSet.js';
export { Metadata, MetadataT } from './Metadata.js';
export { MissilePhase } from './MissilePhase.js';
export { MissileType } from './MissileType.js';
export { ModulationType } from './ModulationType.js';
export { ModuleState } from './ModuleState.js';
export { ModuleType } from './ModuleType.js';
export { MotionModel } from './MotionModel.js';
export { NAV, NAVT } from './NAV.js';
export { NoiseSource } from './NoiseSource.js';
export { OBD, OBDT } from './OBD.js';
export { OBT, OBTT } from './OBT.js';
export { OCM, OCMT } from './OCM.js';
export { OEM, OEMT } from './OEM.js';
export { OMM, OMMT } from './OMM.js';
export { OOD, OODT } from './OOD.js';
export { OOE, OOET } from './OOE.js';
export { OOI, OOIT } from './OOI.js';
export { OOL, OOLT } from './OOL.js';
export { OON, OONT } from './OON.js';
export { OPM, OPMT } from './OPM.js';
export { OSM, OSMT } from './OSM.js';
export { ObservationPosition } from './ObservationPosition.js';
export { OrbitDetermination, OrbitDeterminationT } from './OrbitDetermination.js';
export { OrbitFrame } from './OrbitFrame.js';
export { OrbitFrameWrapper, OrbitFrameWrapperT } from './OrbitFrameWrapper.js';
export { OrbitalRegime } from './OrbitalRegime.js';
export { PCF, PCFT } from './PCF.js';
export { PHY, PHYT } from './PHY.js';
export { PLD, PLDT } from './PLD.js';
export { PLG, PLGT } from './PLG.js';
export { PLK, PLKT } from './PLK.js';
export { PNM, PNMT } from './PNM.js';
export { PRG, PRGT } from './PRG.js';
export { PUR, PURT } from './PUR.js';
export { Parameter, ParameterT } from './Parameter.js';
export { ParameterComparison, ParameterComparisonT } from './ParameterComparison.js';
export { ParameterProperties, ParameterPropertiesT } from './ParameterProperties.js';
export { ParameterRefEntry, ParameterRefEntryT } from './ParameterRefEntry.js';
export { ParameterSet, ParameterSetT } from './ParameterSet.js';
export { ParameterTypeSet, ParameterTypeSetT } from './ParameterTypeSet.js';
export { PenResult } from './PenResult.js';
export { PenetrationModel } from './PenetrationModel.js';
export { Perturbations, PerturbationsT } from './Perturbations.js';
export { PhysicalProperties, PhysicalPropertiesT } from './PhysicalProperties.js';
export { PluginCapability, PluginCapabilityT } from './PluginCapability.js';
export { PluginDependency, PluginDependencyT } from './PluginDependency.js';
export { PolarizationType } from './PolarizationType.js';
export { PolynomialCalibrator, PolynomialCalibratorT } from './PolynomialCalibrator.js';
export { PricingTier, PricingTierT } from './PricingTier.js';
export { ProjectilePhase } from './ProjectilePhase.js';
export { ProjectileType } from './ProjectileType.js';
export { PropagationModel } from './PropagationModel.js';
export { PropagatorMethod } from './PropagatorMethod.js';
export { PropulsionType } from './PropulsionType.js';
export { RAF, RAFT } from './RAF.js';
export { RCF, RCFT } from './RCF.js';
export { RDM, RDMT } from './RDM.js';
export { RDO, RDOT } from './RDO.js';
export { REC, RECT } from './REC.js';
export { REV, REVT } from './REV.js';
export { RFB, RFBT } from './RFB.js';
export { RFE, RFET } from './RFE.js';
export { RFM, RFMT } from './RFM.js';
export { RFMUnion } from './RFMUnion.js';
export { RFO, RFOT } from './RFO.js';
export { ROC, ROCT } from './ROC.js';
export { RangefinderType } from './RangefinderType.js';
export { RateBasisType } from './RateBasisType.js';
export { RateInStream, RateInStreamT } from './RateInStream.js';
export { Record, RecordT } from './Record.js';
export { RecordType } from './RecordType.js';
export { ReferenceFrame } from './ReferenceFrame.js';
export { ReferenceLocationType } from './ReferenceLocationType.js';
export { RelativeTimeParameterType, RelativeTimeParameterTypeT } from './RelativeTimeParameterType.js';
export { RepeatEntry, RepeatEntryT } from './RepeatEntry.js';
export { RotorFlags } from './RotorFlags.js';
export { RotorType } from './RotorType.js';
export { SAR, SART } from './SAR.js';
export { SCHEMA_STANDARD, SCHEMA_STANDARDT } from './SCHEMA_STANDARD.js';
export { SCM, SCMT } from './SCM.js';
export { SDL, SDLT } from './SDL.js';
export { SEO, SEOT } from './SEO.js';
export { SEV, SEVT } from './SEV.js';
export { SIT, SITT } from './SIT.js';
export { SKI, SKIT } from './SKI.js';
export { SNR, SNRT } from './SNR.js';
export { SOI, SOIT } from './SOI.js';
export { SON, SONT } from './SON.js';
export { SONPropagationModel } from './SONPropagationModel.js';
export { SPP, SPPT } from './SPP.js';
export { SPW, SPWT } from './SPW.js';
export { SPWCOLLECTION, SPWCOLLECTIONT } from './SPWCOLLECTION.js';
export { STAGE, STAGET } from './STAGE.js';
export { STF, STFT } from './STF.js';
export { STR, STRT } from './STR.js';
export { STV, STVT } from './STV.js';
export { STVReferenceFrame } from './STVReferenceFrame.js';
export { SUSTAINER, SUSTAINERT } from './SUSTAINER.js';
export { SWR, SWRT } from './SWR.js';
export { Score, ScoreT } from './Score.js';
export { ScoreType } from './ScoreType.js';
export { SeaState } from './SeaState.js';
export { SeekerStatus } from './SeekerStatus.js';
export { SeekerType } from './SeekerType.js';
export { SensorMode } from './SensorMode.js';
export { SensorType } from './SensorType.js';
export { SequenceContainer, SequenceContainerT } from './SequenceContainer.js';
export { Service, ServiceT } from './Service.js';
export { ServiceSet, ServiceSetT } from './ServiceSet.js';
export { SimplePolarization } from './SimplePolarization.js';
export { SiteType } from './SiteType.js';
export { SonarType } from './SonarType.js';
export { SpacecraftFrame } from './SpacecraftFrame.js';
export { SpacecraftFrameWrapper, SpacecraftFrameWrapperT } from './SpacecraftFrameWrapper.js';
export { SpatialCoverage, SpatialCoverageT } from './SpatialCoverage.js';
export { SplineCalibrator, SplineCalibratorT } from './SplineCalibrator.js';
export { SplinePoint, SplinePointT } from './SplinePoint.js';
export { StabilizationType } from './StabilizationType.js';
export { StateVector, StateVectorT } from './StateVector.js';
export { StaticAlarmRanges, StaticAlarmRangesT } from './StaticAlarmRanges.js';
export { StokesParameters, StokesParametersT } from './StokesParameters.js';
export { StreamSet, StreamSetT } from './StreamSet.js';
export { StringArgumentType, StringArgumentTypeT } from './StringArgumentType.js';
export { StringDataEncoding, StringDataEncodingT } from './StringDataEncoding.js';
export { StringEncodingType } from './StringEncodingType.js';
export { StringParameterType, StringParameterTypeT } from './StringParameterType.js';
export { StringSizeType } from './StringSizeType.js';
export { SymmetricAlgo } from './SymmetricAlgo.js';
export { TCF, TCFT } from './TCF.js';
export { TDM, TDMT } from './TDM.js';
export { TIM, TIMT } from './TIM.js';
export { TKG, TKGT } from './TKG.js';
export { TME, TMET } from './TME.js';
export { TMF, TMFT } from './TMF.js';
export { TPN, TPNT } from './TPN.js';
export { TRK, TRKT } from './TRK.js';
export { TRN, TRNT } from './TRN.js';
export { TargetType } from './TargetType.js';
export { TelemetryMetaData, TelemetryMetaDataT } from './TelemetryMetaData.js';
export { TemporalCoverage, TemporalCoverageT } from './TemporalCoverage.js';
export { TerrainDataSource } from './TerrainDataSource.js';
export { TerrainInterpolation } from './TerrainInterpolation.js';
export { TerrainType } from './TerrainType.js';
export { ThreatCategory } from './ThreatCategory.js';
export { TimeReference } from './TimeReference.js';
export { TimeScale } from './TimeScale.js';
export { TimeWindowRefType } from './TimeWindowRefType.js';
export { TorpedoGuidanceMode } from './TorpedoGuidanceMode.js';
export { TrackQuality } from './TrackQuality.js';
export { TrackStatus } from './TrackStatus.js';
export { USR, USRT } from './USR.js';
export { Unit, UnitT } from './Unit.js';
export { UserDefinedParameters, UserDefinedParametersT } from './UserDefinedParameters.js';
export { VCM, VCMT } from './VCM.js';
export { VCMAtmosphericModelData, VCMAtmosphericModelDataT } from './VCMAtmosphericModelData.js';
export { VCMStateVector, VCMStateVectorT } from './VCMStateVector.js';
export { VariableFrameStream, VariableFrameStreamT } from './VariableFrameStream.js';
export { VehicleType } from './VehicleType.js';
export { VerifierType } from './VerifierType.js';
export { VesselType } from './VesselType.js';
export { WPN, WPNT } from './WPN.js';
export { WTH, WTHT } from './WTH.js';
export { WaveformType } from './WaveformType.js';
export { WeaponType } from './WeaponType.js';
export { WeatherCondition } from './WeatherCondition.js';
export { XTC, XTCT } from './XTC.js';
export { XTCHeader, XTCHeaderT } from './XTCHeader.js';
export { accessType } from './accessType.js';
export { anomalyType } from './anomalyType.js';
export { atmosphericModel } from './atmosphericModel.js';
export { cltuPduType } from './cltuPduType.js';
export { covarianceMatrixLine, covarianceMatrixLineT } from './covarianceMatrixLine.js';
export { covarianceMethod } from './covarianceMethod.js';
export { dataStatusCode } from './dataStatusCode.js';
export { elementType } from './elementType.js';
export { ephemerisDataBlock, ephemerisDataBlockT } from './ephemerisDataBlock.js';
export { ephemerisDataLine, ephemerisDataLineT } from './ephemerisDataLine.js';
export { ephemerisType } from './ephemerisType.js';
export { equinoctialElements, equinoctialElementsT } from './equinoctialElements.js';
export { geopotentialModel } from './geopotentialModel.js';
export { keplerianElements, keplerianElementsT } from './keplerianElements.js';
export { legacyCountryCode } from './legacyCountryCode.js';
export { licenseType } from './licenseType.js';
export { lunarPerturbationModel } from './lunarPerturbationModel.js';
export { massType } from './massType.js';
export { meanElementTheory } from './meanElementTheory.js';
export { objectType } from './objectType.js';
export { opsStatusCode } from './opsStatusCode.js';
export { orbitType } from './orbitType.js';
export { packetType } from './packetType.js';
export { paymentMethod } from './paymentMethod.js';
export { pduType } from './pduType.js';
export { perturbationStatus } from './perturbationStatus.js';
export { pluginType } from './pluginType.js';
export { propagatorConfig, propagatorConfigT } from './propagatorConfig.js';
export { propagatorType } from './propagatorType.js';
export { rafPduType } from './rafPduType.js';
export { rcfPduType } from './rcfPduType.js';
export { resonanceModel } from './resonanceModel.js';
export { screeningVolumeShape } from './screeningVolumeShape.js';
export { solarPerturbationModel } from './solarPerturbationModel.js';
export { solarRadiationPressureModel } from './solarRadiationPressureModel.js';
export { timeSystem } from './timeSystem.js';
export { transmissionMode } from './transmissionMode.js';
export { uvwSigmas, uvwSigmasT } from './uvwSigmas.js';
export { zonalHarmonic } from './zonalHarmonic.js';
//# sourceMappingURL=main.d.ts.map