import * as flatbuffers from 'flatbuffers';
/**
 * Orbit Determination Results
 */
export declare class OBD implements flatbuffers.IUnpackableObject<OBDT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): OBD;
    static getRootAsOBD(bb: flatbuffers.ByteBuffer, obj?: OBD): OBD;
    static getSizePrefixedRootAsOBD(bb: flatbuffers.ByteBuffer, obj?: OBD): OBD;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    START_TIME(): string | null;
    START_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    END_TIME(): string | null;
    END_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_OBJECT_ID(): string | null;
    ORIG_OBJECT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SAT_NO(): number;
    APRIORI_ID_ELSET(): string | null;
    APRIORI_ID_ELSET(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    APRIORI_ELSET(): string | null;
    APRIORI_ELSET(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    APRIORI_ID_STATE_VECTOR(): string | null;
    APRIORI_ID_STATE_VECTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    APRIORI_STATE_VECTOR(): string | null;
    APRIORI_STATE_VECTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    INITIAL_OD(): boolean;
    LAST_OB_START(): string | null;
    LAST_OB_START(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    LAST_OB_END(): string | null;
    LAST_OB_END(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TIME_SPAN(): number;
    EFFECTIVE_FROM(): string | null;
    EFFECTIVE_FROM(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    EFFECTIVE_UNTIL(): string | null;
    EFFECTIVE_UNTIL(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    WRMS(): number;
    PREVIOUS_WRMS(): number;
    FIRST_PASS_WRMS(): number;
    BEST_PASS_WRMS(): number;
    ERROR_GROWTH_RATE(): number;
    EDR(): number;
    METHOD(): string | null;
    METHOD(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    METHOD_SOURCE(): string | null;
    METHOD_SOURCE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    FIT_SPAN(): number;
    BALLISTIC_COEFF_EST(): boolean;
    BALLISTIC_COEFF_MODEL(): string | null;
    BALLISTIC_COEFF_MODEL(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    AGOM_EST(): boolean;
    AGOM_MODEL(): string | null;
    AGOM_MODEL(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    RMS_CONVERGENCE_CRITERIA(): number;
    NUM_ITERATIONS(): number;
    ACCEPTED_OB_TYPS(index: number): string;
    ACCEPTED_OB_TYPS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    acceptedObTypsLength(): number;
    ACCEPTED_OB_IDS(index: number): string;
    ACCEPTED_OB_IDS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    acceptedObIdsLength(): number;
    REJECTED_OB_TYPS(index: number): string;
    REJECTED_OB_TYPS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    rejectedObTypsLength(): number;
    REJECTED_OB_IDS(index: number): string;
    REJECTED_OB_IDS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    rejectedObIdsLength(): number;
    SENSOR_IDS(index: number): string;
    SENSOR_IDS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    sensorIdsLength(): number;
    ON_ORBIT(): string | null;
    ON_ORBIT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    static startOBD(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addStartTime(builder: flatbuffers.Builder, START_TIMEOffset: flatbuffers.Offset): void;
    static addEndTime(builder: flatbuffers.Builder, END_TIMEOffset: flatbuffers.Offset): void;
    static addOrigObjectId(builder: flatbuffers.Builder, ORIG_OBJECT_IDOffset: flatbuffers.Offset): void;
    static addSatNo(builder: flatbuffers.Builder, SAT_NO: number): void;
    static addAprioriIdElset(builder: flatbuffers.Builder, APRIORI_ID_ELSETOffset: flatbuffers.Offset): void;
    static addAprioriElset(builder: flatbuffers.Builder, APRIORI_ELSETOffset: flatbuffers.Offset): void;
    static addAprioriIdStateVector(builder: flatbuffers.Builder, APRIORI_ID_STATE_VECTOROffset: flatbuffers.Offset): void;
    static addAprioriStateVector(builder: flatbuffers.Builder, APRIORI_STATE_VECTOROffset: flatbuffers.Offset): void;
    static addInitialOd(builder: flatbuffers.Builder, INITIAL_OD: boolean): void;
    static addLastObStart(builder: flatbuffers.Builder, LAST_OB_STARTOffset: flatbuffers.Offset): void;
    static addLastObEnd(builder: flatbuffers.Builder, LAST_OB_ENDOffset: flatbuffers.Offset): void;
    static addTimeSpan(builder: flatbuffers.Builder, TIME_SPAN: number): void;
    static addEffectiveFrom(builder: flatbuffers.Builder, EFFECTIVE_FROMOffset: flatbuffers.Offset): void;
    static addEffectiveUntil(builder: flatbuffers.Builder, EFFECTIVE_UNTILOffset: flatbuffers.Offset): void;
    static addWrms(builder: flatbuffers.Builder, WRMS: number): void;
    static addPreviousWrms(builder: flatbuffers.Builder, PREVIOUS_WRMS: number): void;
    static addFirstPassWrms(builder: flatbuffers.Builder, FIRST_PASS_WRMS: number): void;
    static addBestPassWrms(builder: flatbuffers.Builder, BEST_PASS_WRMS: number): void;
    static addErrorGrowthRate(builder: flatbuffers.Builder, ERROR_GROWTH_RATE: number): void;
    static addEdr(builder: flatbuffers.Builder, EDR: number): void;
    static addMethod(builder: flatbuffers.Builder, METHODOffset: flatbuffers.Offset): void;
    static addMethodSource(builder: flatbuffers.Builder, METHOD_SOURCEOffset: flatbuffers.Offset): void;
    static addFitSpan(builder: flatbuffers.Builder, FIT_SPAN: number): void;
    static addBallisticCoeffEst(builder: flatbuffers.Builder, BALLISTIC_COEFF_EST: boolean): void;
    static addBallisticCoeffModel(builder: flatbuffers.Builder, BALLISTIC_COEFF_MODELOffset: flatbuffers.Offset): void;
    static addAgomEst(builder: flatbuffers.Builder, AGOM_EST: boolean): void;
    static addAgomModel(builder: flatbuffers.Builder, AGOM_MODELOffset: flatbuffers.Offset): void;
    static addRmsConvergenceCriteria(builder: flatbuffers.Builder, RMS_CONVERGENCE_CRITERIA: number): void;
    static addNumIterations(builder: flatbuffers.Builder, NUM_ITERATIONS: number): void;
    static addAcceptedObTyps(builder: flatbuffers.Builder, ACCEPTED_OB_TYPSOffset: flatbuffers.Offset): void;
    static createAcceptedObTypsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startAcceptedObTypsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addAcceptedObIds(builder: flatbuffers.Builder, ACCEPTED_OB_IDSOffset: flatbuffers.Offset): void;
    static createAcceptedObIdsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startAcceptedObIdsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addRejectedObTyps(builder: flatbuffers.Builder, REJECTED_OB_TYPSOffset: flatbuffers.Offset): void;
    static createRejectedObTypsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startRejectedObTypsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addRejectedObIds(builder: flatbuffers.Builder, REJECTED_OB_IDSOffset: flatbuffers.Offset): void;
    static createRejectedObIdsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startRejectedObIdsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSensorIds(builder: flatbuffers.Builder, SENSOR_IDSOffset: flatbuffers.Offset): void;
    static createSensorIdsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSensorIdsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addOnOrbit(builder: flatbuffers.Builder, ON_ORBITOffset: flatbuffers.Offset): void;
    static endOBD(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishOBDBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedOBDBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createOBD(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, START_TIMEOffset: flatbuffers.Offset, END_TIMEOffset: flatbuffers.Offset, ORIG_OBJECT_IDOffset: flatbuffers.Offset, SAT_NO: number, APRIORI_ID_ELSETOffset: flatbuffers.Offset, APRIORI_ELSETOffset: flatbuffers.Offset, APRIORI_ID_STATE_VECTOROffset: flatbuffers.Offset, APRIORI_STATE_VECTOROffset: flatbuffers.Offset, INITIAL_OD: boolean, LAST_OB_STARTOffset: flatbuffers.Offset, LAST_OB_ENDOffset: flatbuffers.Offset, TIME_SPAN: number, EFFECTIVE_FROMOffset: flatbuffers.Offset, EFFECTIVE_UNTILOffset: flatbuffers.Offset, WRMS: number, PREVIOUS_WRMS: number, FIRST_PASS_WRMS: number, BEST_PASS_WRMS: number, ERROR_GROWTH_RATE: number, EDR: number, METHODOffset: flatbuffers.Offset, METHOD_SOURCEOffset: flatbuffers.Offset, FIT_SPAN: number, BALLISTIC_COEFF_EST: boolean, BALLISTIC_COEFF_MODELOffset: flatbuffers.Offset, AGOM_EST: boolean, AGOM_MODELOffset: flatbuffers.Offset, RMS_CONVERGENCE_CRITERIA: number, NUM_ITERATIONS: number, ACCEPTED_OB_TYPSOffset: flatbuffers.Offset, ACCEPTED_OB_IDSOffset: flatbuffers.Offset, REJECTED_OB_TYPSOffset: flatbuffers.Offset, REJECTED_OB_IDSOffset: flatbuffers.Offset, SENSOR_IDSOffset: flatbuffers.Offset, ON_ORBITOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): OBDT;
    unpackTo(_o: OBDT): void;
}
export declare class OBDT implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    START_TIME: string | Uint8Array | null;
    END_TIME: string | Uint8Array | null;
    ORIG_OBJECT_ID: string | Uint8Array | null;
    SAT_NO: number;
    APRIORI_ID_ELSET: string | Uint8Array | null;
    APRIORI_ELSET: string | Uint8Array | null;
    APRIORI_ID_STATE_VECTOR: string | Uint8Array | null;
    APRIORI_STATE_VECTOR: string | Uint8Array | null;
    INITIAL_OD: boolean;
    LAST_OB_START: string | Uint8Array | null;
    LAST_OB_END: string | Uint8Array | null;
    TIME_SPAN: number;
    EFFECTIVE_FROM: string | Uint8Array | null;
    EFFECTIVE_UNTIL: string | Uint8Array | null;
    WRMS: number;
    PREVIOUS_WRMS: number;
    FIRST_PASS_WRMS: number;
    BEST_PASS_WRMS: number;
    ERROR_GROWTH_RATE: number;
    EDR: number;
    METHOD: string | Uint8Array | null;
    METHOD_SOURCE: string | Uint8Array | null;
    FIT_SPAN: number;
    BALLISTIC_COEFF_EST: boolean;
    BALLISTIC_COEFF_MODEL: string | Uint8Array | null;
    AGOM_EST: boolean;
    AGOM_MODEL: string | Uint8Array | null;
    RMS_CONVERGENCE_CRITERIA: number;
    NUM_ITERATIONS: number;
    ACCEPTED_OB_TYPS: (string)[];
    ACCEPTED_OB_IDS: (string)[];
    REJECTED_OB_TYPS: (string)[];
    REJECTED_OB_IDS: (string)[];
    SENSOR_IDS: (string)[];
    ON_ORBIT: string | Uint8Array | null;
    constructor(ID?: string | Uint8Array | null, START_TIME?: string | Uint8Array | null, END_TIME?: string | Uint8Array | null, ORIG_OBJECT_ID?: string | Uint8Array | null, SAT_NO?: number, APRIORI_ID_ELSET?: string | Uint8Array | null, APRIORI_ELSET?: string | Uint8Array | null, APRIORI_ID_STATE_VECTOR?: string | Uint8Array | null, APRIORI_STATE_VECTOR?: string | Uint8Array | null, INITIAL_OD?: boolean, LAST_OB_START?: string | Uint8Array | null, LAST_OB_END?: string | Uint8Array | null, TIME_SPAN?: number, EFFECTIVE_FROM?: string | Uint8Array | null, EFFECTIVE_UNTIL?: string | Uint8Array | null, WRMS?: number, PREVIOUS_WRMS?: number, FIRST_PASS_WRMS?: number, BEST_PASS_WRMS?: number, ERROR_GROWTH_RATE?: number, EDR?: number, METHOD?: string | Uint8Array | null, METHOD_SOURCE?: string | Uint8Array | null, FIT_SPAN?: number, BALLISTIC_COEFF_EST?: boolean, BALLISTIC_COEFF_MODEL?: string | Uint8Array | null, AGOM_EST?: boolean, AGOM_MODEL?: string | Uint8Array | null, RMS_CONVERGENCE_CRITERIA?: number, NUM_ITERATIONS?: number, ACCEPTED_OB_TYPS?: (string)[], ACCEPTED_OB_IDS?: (string)[], REJECTED_OB_TYPS?: (string)[], REJECTED_OB_IDS?: (string)[], SENSOR_IDS?: (string)[], ON_ORBIT?: string | Uint8Array | null);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=OBD.d.ts.map