import * as flatbuffers from 'flatbuffers';
/**
 * Orbit Track
 */
export declare class OBT implements flatbuffers.IUnpackableObject<OBTT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): OBT;
    static getRootAsOBT(bb: flatbuffers.ByteBuffer, obj?: OBT): OBT;
    static getSizePrefixedRootAsOBT(bb: flatbuffers.ByteBuffer, obj?: OBT): OBT;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SAT_NO(): number;
    ON_ORBIT(): string | null;
    ON_ORBIT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_OBJECT_ID(): string | null;
    ORIG_OBJECT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TS(): string | null;
    TS(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    LAT(): number;
    LON(): number;
    ALT(): number;
    RDF_RF(): number;
    CALL_SIGN(): string | null;
    CALL_SIGN(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    RPT_NUM(): string | null;
    RPT_NUM(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBJ_IDENT(): string | null;
    OBJ_IDENT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    IDENT_AMP(): string | null;
    IDENT_AMP(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SAT_STATUS(): string | null;
    SAT_STATUS(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBJECT_TYPE(): string | null;
    OBJECT_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    COUNTRY_CODE(): string | null;
    COUNTRY_CODE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DECAY(): number;
    CHARLIE_LINE(): string | null;
    CHARLIE_LINE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    AOU_TYPE(): string | null;
    AOU_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    AOU_DATA(index: number): string;
    AOU_DATA(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    aouDataLength(): number;
    SPD(): number;
    ANG_ELEV(): number;
    CNTNMNT(): number;
    XREF(): string | null;
    XREF(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    CH_XREF(): string | null;
    CH_XREF(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    AMPLIFICATION(): string | null;
    AMPLIFICATION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    IFF(): string | null;
    IFF(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    REINFORCED(): boolean;
    REDUCED(): boolean;
    HQ(): boolean;
    DUMMY(): boolean;
    TASK_FORCE(): boolean;
    FEINT(): boolean;
    INSTALLATION(): boolean;
    VEH_TYPE(): string | null;
    VEH_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRK_ID(): string | null;
    TRK_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRACK_SENSORS(index: number): string;
    TRACK_SENSORS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    trackSensorsLength(): number;
    static startOBT(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addSatNo(builder: flatbuffers.Builder, SAT_NO: number): void;
    static addOnOrbit(builder: flatbuffers.Builder, ON_ORBITOffset: flatbuffers.Offset): void;
    static addOrigObjectId(builder: flatbuffers.Builder, ORIG_OBJECT_IDOffset: flatbuffers.Offset): void;
    static addTs(builder: flatbuffers.Builder, TSOffset: flatbuffers.Offset): void;
    static addLat(builder: flatbuffers.Builder, LAT: number): void;
    static addLon(builder: flatbuffers.Builder, LON: number): void;
    static addAlt(builder: flatbuffers.Builder, ALT: number): void;
    static addRdfRf(builder: flatbuffers.Builder, RDF_RF: number): void;
    static addCallSign(builder: flatbuffers.Builder, CALL_SIGNOffset: flatbuffers.Offset): void;
    static addRptNum(builder: flatbuffers.Builder, RPT_NUMOffset: flatbuffers.Offset): void;
    static addObjIdent(builder: flatbuffers.Builder, OBJ_IDENTOffset: flatbuffers.Offset): void;
    static addIdentAmp(builder: flatbuffers.Builder, IDENT_AMPOffset: flatbuffers.Offset): void;
    static addSatStatus(builder: flatbuffers.Builder, SAT_STATUSOffset: flatbuffers.Offset): void;
    static addObjectType(builder: flatbuffers.Builder, OBJECT_TYPEOffset: flatbuffers.Offset): void;
    static addCountryCode(builder: flatbuffers.Builder, COUNTRY_CODEOffset: flatbuffers.Offset): void;
    static addDecay(builder: flatbuffers.Builder, DECAY: number): void;
    static addCharlieLine(builder: flatbuffers.Builder, CHARLIE_LINEOffset: flatbuffers.Offset): void;
    static addAouType(builder: flatbuffers.Builder, AOU_TYPEOffset: flatbuffers.Offset): void;
    static addAouData(builder: flatbuffers.Builder, AOU_DATAOffset: flatbuffers.Offset): void;
    static createAouDataVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startAouDataVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSpd(builder: flatbuffers.Builder, SPD: number): void;
    static addAngElev(builder: flatbuffers.Builder, ANG_ELEV: number): void;
    static addCntnmnt(builder: flatbuffers.Builder, CNTNMNT: number): void;
    static addXref(builder: flatbuffers.Builder, XREFOffset: flatbuffers.Offset): void;
    static addChXref(builder: flatbuffers.Builder, CH_XREFOffset: flatbuffers.Offset): void;
    static addAmplification(builder: flatbuffers.Builder, AMPLIFICATIONOffset: flatbuffers.Offset): void;
    static addIff(builder: flatbuffers.Builder, IFFOffset: flatbuffers.Offset): void;
    static addReinforced(builder: flatbuffers.Builder, REINFORCED: boolean): void;
    static addReduced(builder: flatbuffers.Builder, REDUCED: boolean): void;
    static addHq(builder: flatbuffers.Builder, HQ: boolean): void;
    static addDummy(builder: flatbuffers.Builder, DUMMY: boolean): void;
    static addTaskForce(builder: flatbuffers.Builder, TASK_FORCE: boolean): void;
    static addFeint(builder: flatbuffers.Builder, FEINT: boolean): void;
    static addInstallation(builder: flatbuffers.Builder, INSTALLATION: boolean): void;
    static addVehType(builder: flatbuffers.Builder, VEH_TYPEOffset: flatbuffers.Offset): void;
    static addTrkId(builder: flatbuffers.Builder, TRK_IDOffset: flatbuffers.Offset): void;
    static addTrackSensors(builder: flatbuffers.Builder, TRACK_SENSORSOffset: flatbuffers.Offset): void;
    static createTrackSensorsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startTrackSensorsVector(builder: flatbuffers.Builder, numElems: number): void;
    static endOBT(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishOBTBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedOBTBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createOBT(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, SAT_NO: number, ON_ORBITOffset: flatbuffers.Offset, ORIG_OBJECT_IDOffset: flatbuffers.Offset, TSOffset: flatbuffers.Offset, LAT: number, LON: number, ALT: number, RDF_RF: number, CALL_SIGNOffset: flatbuffers.Offset, RPT_NUMOffset: flatbuffers.Offset, OBJ_IDENTOffset: flatbuffers.Offset, IDENT_AMPOffset: flatbuffers.Offset, SAT_STATUSOffset: flatbuffers.Offset, OBJECT_TYPEOffset: flatbuffers.Offset, COUNTRY_CODEOffset: flatbuffers.Offset, DECAY: number, CHARLIE_LINEOffset: flatbuffers.Offset, AOU_TYPEOffset: flatbuffers.Offset, AOU_DATAOffset: flatbuffers.Offset, SPD: number, ANG_ELEV: number, CNTNMNT: number, XREFOffset: flatbuffers.Offset, CH_XREFOffset: flatbuffers.Offset, AMPLIFICATIONOffset: flatbuffers.Offset, IFFOffset: flatbuffers.Offset, REINFORCED: boolean, REDUCED: boolean, HQ: boolean, DUMMY: boolean, TASK_FORCE: boolean, FEINT: boolean, INSTALLATION: boolean, VEH_TYPEOffset: flatbuffers.Offset, TRK_IDOffset: flatbuffers.Offset, TRACK_SENSORSOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): OBTT;
    unpackTo(_o: OBTT): void;
}
export declare class OBTT implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    SAT_NO: number;
    ON_ORBIT: string | Uint8Array | null;
    ORIG_OBJECT_ID: string | Uint8Array | null;
    TS: string | Uint8Array | null;
    LAT: number;
    LON: number;
    ALT: number;
    RDF_RF: number;
    CALL_SIGN: string | Uint8Array | null;
    RPT_NUM: string | Uint8Array | null;
    OBJ_IDENT: string | Uint8Array | null;
    IDENT_AMP: string | Uint8Array | null;
    SAT_STATUS: string | Uint8Array | null;
    OBJECT_TYPE: string | Uint8Array | null;
    COUNTRY_CODE: string | Uint8Array | null;
    DECAY: number;
    CHARLIE_LINE: string | Uint8Array | null;
    AOU_TYPE: string | Uint8Array | null;
    AOU_DATA: (string)[];
    SPD: number;
    ANG_ELEV: number;
    CNTNMNT: number;
    XREF: string | Uint8Array | null;
    CH_XREF: string | Uint8Array | null;
    AMPLIFICATION: string | Uint8Array | null;
    IFF: string | Uint8Array | null;
    REINFORCED: boolean;
    REDUCED: boolean;
    HQ: boolean;
    DUMMY: boolean;
    TASK_FORCE: boolean;
    FEINT: boolean;
    INSTALLATION: boolean;
    VEH_TYPE: string | Uint8Array | null;
    TRK_ID: string | Uint8Array | null;
    TRACK_SENSORS: (string)[];
    constructor(ID?: string | Uint8Array | null, SAT_NO?: number, ON_ORBIT?: string | Uint8Array | null, ORIG_OBJECT_ID?: string | Uint8Array | null, TS?: string | Uint8Array | null, LAT?: number, LON?: number, ALT?: number, RDF_RF?: number, CALL_SIGN?: string | Uint8Array | null, RPT_NUM?: string | Uint8Array | null, OBJ_IDENT?: string | Uint8Array | null, IDENT_AMP?: string | Uint8Array | null, SAT_STATUS?: string | Uint8Array | null, OBJECT_TYPE?: string | Uint8Array | null, COUNTRY_CODE?: string | Uint8Array | null, DECAY?: number, CHARLIE_LINE?: string | Uint8Array | null, AOU_TYPE?: string | Uint8Array | null, AOU_DATA?: (string)[], SPD?: number, ANG_ELEV?: number, CNTNMNT?: number, XREF?: string | Uint8Array | null, CH_XREF?: string | Uint8Array | null, AMPLIFICATION?: string | Uint8Array | null, IFF?: string | Uint8Array | null, REINFORCED?: boolean, REDUCED?: boolean, HQ?: boolean, DUMMY?: boolean, TASK_FORCE?: boolean, FEINT?: boolean, INSTALLATION?: boolean, VEH_TYPE?: string | Uint8Array | null, TRK_ID?: string | Uint8Array | null, TRACK_SENSORS?: (string)[]);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=OBT.d.ts.map