import * as flatbuffers from 'flatbuffers';
/**
 * On-Orbit Object Details
 */
export declare class OOD implements flatbuffers.IUnpackableObject<OODT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): OOD;
    static getRootAsOOD(bb: flatbuffers.ByteBuffer, obj?: OOD): OOD;
    static getSizePrefixedRootAsOOD(bb: flatbuffers.ByteBuffer, obj?: OOD): OOD;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    LAST_OB_TIME(): string | null;
    LAST_OB_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    VISMAG(): number;
    VISMAG_MIN(): number;
    VISMAG_MAX(): number;
    VISMAG_MEAN(): number;
    RCS(): number;
    RCS_MIN(): number;
    RCS_MAX(): number;
    RCS_MEAN(): number;
    BOL_DELTA_V(): number;
    MAX_DELTA_V(): number;
    DELTA_VUNC(): number;
    EST_DELTA_VDURATION(): number;
    NUM_MISSION(): number;
    MISSION_TYPES(index: number): string;
    MISSION_TYPES(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    missionTypesLength(): number;
    BUS_TYPE(): string | null;
    BUS_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    GEO_SLOT(): number;
    DRIFT_RATE(): number;
    DRY_MASS(): number;
    ADDITIONAL_MASS(): number;
    LAUNCH_MASS_MIN(): number;
    LAUNCH_MASS(): number;
    LAUNCH_MASS_MAX(): number;
    BOL_FUEL_MASS(): number;
    CURRENT_MASS(): number;
    TOTAL_MASS_UNC(): number;
    SOLAR_ARRAY_AREA(): number;
    MANEUVERABLE(): boolean;
    FUEL_REMAINING(): number;
    CROSS_SECTION(): number;
    BUS_CROSS_SECTION(): number;
    MAX_RADIUS(): number;
    COLA_RADIUS(): number;
    ADEPT_RADIUS(): number;
    NUM_DEPLOYABLE(): number;
    DEP_NAMES(index: number): string;
    DEP_NAMES(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    depNamesLength(): number;
    DEP_EST_MASSES(index: number): string;
    DEP_EST_MASSES(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    depEstMassesLength(): number;
    DEP_MASS_UNCS(index: number): string;
    DEP_MASS_UNCS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    depMassUncsLength(): number;
    LAST_OB_SOURCE(): string | null;
    LAST_OB_SOURCE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    static startOOD(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addLastObTime(builder: flatbuffers.Builder, LAST_OB_TIMEOffset: flatbuffers.Offset): void;
    static addVismag(builder: flatbuffers.Builder, VISMAG: number): void;
    static addVismagMin(builder: flatbuffers.Builder, VISMAG_MIN: number): void;
    static addVismagMax(builder: flatbuffers.Builder, VISMAG_MAX: number): void;
    static addVismagMean(builder: flatbuffers.Builder, VISMAG_MEAN: number): void;
    static addRcs(builder: flatbuffers.Builder, RCS: number): void;
    static addRcsMin(builder: flatbuffers.Builder, RCS_MIN: number): void;
    static addRcsMax(builder: flatbuffers.Builder, RCS_MAX: number): void;
    static addRcsMean(builder: flatbuffers.Builder, RCS_MEAN: number): void;
    static addBolDeltaV(builder: flatbuffers.Builder, BOL_DELTA_V: number): void;
    static addMaxDeltaV(builder: flatbuffers.Builder, MAX_DELTA_V: number): void;
    static addDeltaVunc(builder: flatbuffers.Builder, DELTA_VUNC: number): void;
    static addEstDeltaVduration(builder: flatbuffers.Builder, EST_DELTA_VDURATION: number): void;
    static addNumMission(builder: flatbuffers.Builder, NUM_MISSION: number): void;
    static addMissionTypes(builder: flatbuffers.Builder, MISSION_TYPESOffset: flatbuffers.Offset): void;
    static createMissionTypesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startMissionTypesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addBusType(builder: flatbuffers.Builder, BUS_TYPEOffset: flatbuffers.Offset): void;
    static addGeoSlot(builder: flatbuffers.Builder, GEO_SLOT: number): void;
    static addDriftRate(builder: flatbuffers.Builder, DRIFT_RATE: number): void;
    static addDryMass(builder: flatbuffers.Builder, DRY_MASS: number): void;
    static addAdditionalMass(builder: flatbuffers.Builder, ADDITIONAL_MASS: number): void;
    static addLaunchMassMin(builder: flatbuffers.Builder, LAUNCH_MASS_MIN: number): void;
    static addLaunchMass(builder: flatbuffers.Builder, LAUNCH_MASS: number): void;
    static addLaunchMassMax(builder: flatbuffers.Builder, LAUNCH_MASS_MAX: number): void;
    static addBolFuelMass(builder: flatbuffers.Builder, BOL_FUEL_MASS: number): void;
    static addCurrentMass(builder: flatbuffers.Builder, CURRENT_MASS: number): void;
    static addTotalMassUnc(builder: flatbuffers.Builder, TOTAL_MASS_UNC: number): void;
    static addSolarArrayArea(builder: flatbuffers.Builder, SOLAR_ARRAY_AREA: number): void;
    static addManeuverable(builder: flatbuffers.Builder, MANEUVERABLE: boolean): void;
    static addFuelRemaining(builder: flatbuffers.Builder, FUEL_REMAINING: number): void;
    static addCrossSection(builder: flatbuffers.Builder, CROSS_SECTION: number): void;
    static addBusCrossSection(builder: flatbuffers.Builder, BUS_CROSS_SECTION: number): void;
    static addMaxRadius(builder: flatbuffers.Builder, MAX_RADIUS: number): void;
    static addColaRadius(builder: flatbuffers.Builder, COLA_RADIUS: number): void;
    static addAdeptRadius(builder: flatbuffers.Builder, ADEPT_RADIUS: number): void;
    static addNumDeployable(builder: flatbuffers.Builder, NUM_DEPLOYABLE: number): void;
    static addDepNames(builder: flatbuffers.Builder, DEP_NAMESOffset: flatbuffers.Offset): void;
    static createDepNamesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startDepNamesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addDepEstMasses(builder: flatbuffers.Builder, DEP_EST_MASSESOffset: flatbuffers.Offset): void;
    static createDepEstMassesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startDepEstMassesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addDepMassUncs(builder: flatbuffers.Builder, DEP_MASS_UNCSOffset: flatbuffers.Offset): void;
    static createDepMassUncsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startDepMassUncsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addLastObSource(builder: flatbuffers.Builder, LAST_OB_SOURCEOffset: flatbuffers.Offset): void;
    static endOOD(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishOODBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedOODBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createOOD(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, LAST_OB_TIMEOffset: flatbuffers.Offset, VISMAG: number, VISMAG_MIN: number, VISMAG_MAX: number, VISMAG_MEAN: number, RCS: number, RCS_MIN: number, RCS_MAX: number, RCS_MEAN: number, BOL_DELTA_V: number, MAX_DELTA_V: number, DELTA_VUNC: number, EST_DELTA_VDURATION: number, NUM_MISSION: number, MISSION_TYPESOffset: flatbuffers.Offset, BUS_TYPEOffset: flatbuffers.Offset, GEO_SLOT: number, DRIFT_RATE: number, DRY_MASS: number, ADDITIONAL_MASS: number, LAUNCH_MASS_MIN: number, LAUNCH_MASS: number, LAUNCH_MASS_MAX: number, BOL_FUEL_MASS: number, CURRENT_MASS: number, TOTAL_MASS_UNC: number, SOLAR_ARRAY_AREA: number, MANEUVERABLE: boolean, FUEL_REMAINING: number, CROSS_SECTION: number, BUS_CROSS_SECTION: number, MAX_RADIUS: number, COLA_RADIUS: number, ADEPT_RADIUS: number, NUM_DEPLOYABLE: number, DEP_NAMESOffset: flatbuffers.Offset, DEP_EST_MASSESOffset: flatbuffers.Offset, DEP_MASS_UNCSOffset: flatbuffers.Offset, LAST_OB_SOURCEOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): OODT;
    unpackTo(_o: OODT): void;
}
export declare class OODT implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    LAST_OB_TIME: string | Uint8Array | null;
    VISMAG: number;
    VISMAG_MIN: number;
    VISMAG_MAX: number;
    VISMAG_MEAN: number;
    RCS: number;
    RCS_MIN: number;
    RCS_MAX: number;
    RCS_MEAN: number;
    BOL_DELTA_V: number;
    MAX_DELTA_V: number;
    DELTA_VUNC: number;
    EST_DELTA_VDURATION: number;
    NUM_MISSION: number;
    MISSION_TYPES: (string)[];
    BUS_TYPE: string | Uint8Array | null;
    GEO_SLOT: number;
    DRIFT_RATE: number;
    DRY_MASS: number;
    ADDITIONAL_MASS: number;
    LAUNCH_MASS_MIN: number;
    LAUNCH_MASS: number;
    LAUNCH_MASS_MAX: number;
    BOL_FUEL_MASS: number;
    CURRENT_MASS: number;
    TOTAL_MASS_UNC: number;
    SOLAR_ARRAY_AREA: number;
    MANEUVERABLE: boolean;
    FUEL_REMAINING: number;
    CROSS_SECTION: number;
    BUS_CROSS_SECTION: number;
    MAX_RADIUS: number;
    COLA_RADIUS: number;
    ADEPT_RADIUS: number;
    NUM_DEPLOYABLE: number;
    DEP_NAMES: (string)[];
    DEP_EST_MASSES: (string)[];
    DEP_MASS_UNCS: (string)[];
    LAST_OB_SOURCE: string | Uint8Array | null;
    constructor(ID?: string | Uint8Array | null, LAST_OB_TIME?: string | Uint8Array | null, VISMAG?: number, VISMAG_MIN?: number, VISMAG_MAX?: number, VISMAG_MEAN?: number, RCS?: number, RCS_MIN?: number, RCS_MAX?: number, RCS_MEAN?: number, BOL_DELTA_V?: number, MAX_DELTA_V?: number, DELTA_VUNC?: number, EST_DELTA_VDURATION?: number, NUM_MISSION?: number, MISSION_TYPES?: (string)[], BUS_TYPE?: string | Uint8Array | null, GEO_SLOT?: number, DRIFT_RATE?: number, DRY_MASS?: number, ADDITIONAL_MASS?: number, LAUNCH_MASS_MIN?: number, LAUNCH_MASS?: number, LAUNCH_MASS_MAX?: number, BOL_FUEL_MASS?: number, CURRENT_MASS?: number, TOTAL_MASS_UNC?: number, SOLAR_ARRAY_AREA?: number, MANEUVERABLE?: boolean, FUEL_REMAINING?: number, CROSS_SECTION?: number, BUS_CROSS_SECTION?: number, MAX_RADIUS?: number, COLA_RADIUS?: number, ADEPT_RADIUS?: number, NUM_DEPLOYABLE?: number, DEP_NAMES?: (string)[], DEP_EST_MASSES?: (string)[], DEP_MASS_UNCS?: (string)[], LAST_OB_SOURCE?: string | Uint8Array | null);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=OOD.d.ts.map