import * as flatbuffers from 'flatbuffers';
/**
 * Object of Interest
 */
export declare class OOI implements flatbuffers.IUnpackableObject<OOIT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): OOI;
    static getRootAsOOI(bb: flatbuffers.ByteBuffer, obj?: OOI): OOI;
    static getSizePrefixedRootAsOOI(bb: flatbuffers.ByteBuffer, obj?: OOI): OOI;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SAT_NO(): number;
    NAME(): string | null;
    NAME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SENSOR_TASKING_START_TIME(): string | null;
    SENSOR_TASKING_START_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SENSOR_TASKING_STOP_TIME(): string | null;
    SENSOR_TASKING_STOP_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    PRIORITY(): number;
    STATUS(): string | null;
    STATUS(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    STATUS_DATE(): string | null;
    STATUS_DATE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DESCRIPTION(): string | null;
    DESCRIPTION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    LAST_OB_TIME(): string | null;
    LAST_OB_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MISSED_OB_TIME(): string | null;
    MISSED_OB_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DELTA_VS(index: number): string;
    DELTA_VS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    deltaVsLength(): number;
    DELTA_TS(index: number): string;
    DELTA_TS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    deltaTsLength(): number;
    SV_EPOCH(): string | null;
    SV_EPOCH(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    X(): number;
    Y(): number;
    Z(): number;
    XVEL(): number;
    YVEL(): number;
    ZVEL(): number;
    ELSET_EPOCH(): string | null;
    ELSET_EPOCH(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MEAN_MOTION(): number;
    ECCENTRICITY(): number;
    INCLINATION(): number;
    RAAN(): number;
    ARG_OF_PERIGEE(): number;
    MEAN_ANOMALY(): number;
    REV_NO(): number;
    B_STAR(): number;
    MEAN_MOTION_DOT(): number;
    MEAN_MOTION_DDOT(): number;
    SEMI_MAJOR_AXIS(): number;
    PERIOD(): number;
    APOGEE(): number;
    PERIGEE(): number;
    AFFECTED_OBJECTS(index: number): string;
    AFFECTED_OBJECTS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    affectedObjectsLength(): number;
    ON_ORBIT(): string | null;
    ON_ORBIT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MANIFOLDS(index: number): string;
    MANIFOLDS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    manifoldsLength(): number;
    static startOOI(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addSatNo(builder: flatbuffers.Builder, SAT_NO: number): void;
    static addName(builder: flatbuffers.Builder, NAMEOffset: flatbuffers.Offset): void;
    static addSensorTaskingStartTime(builder: flatbuffers.Builder, SENSOR_TASKING_START_TIMEOffset: flatbuffers.Offset): void;
    static addSensorTaskingStopTime(builder: flatbuffers.Builder, SENSOR_TASKING_STOP_TIMEOffset: flatbuffers.Offset): void;
    static addPriority(builder: flatbuffers.Builder, PRIORITY: number): void;
    static addStatus(builder: flatbuffers.Builder, STATUSOffset: flatbuffers.Offset): void;
    static addStatusDate(builder: flatbuffers.Builder, STATUS_DATEOffset: flatbuffers.Offset): void;
    static addDescription(builder: flatbuffers.Builder, DESCRIPTIONOffset: flatbuffers.Offset): void;
    static addLastObTime(builder: flatbuffers.Builder, LAST_OB_TIMEOffset: flatbuffers.Offset): void;
    static addMissedObTime(builder: flatbuffers.Builder, MISSED_OB_TIMEOffset: flatbuffers.Offset): void;
    static addDeltaVs(builder: flatbuffers.Builder, DELTA_VSOffset: flatbuffers.Offset): void;
    static createDeltaVsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startDeltaVsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addDeltaTs(builder: flatbuffers.Builder, DELTA_TSOffset: flatbuffers.Offset): void;
    static createDeltaTsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startDeltaTsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSvEpoch(builder: flatbuffers.Builder, SV_EPOCHOffset: flatbuffers.Offset): void;
    static addX(builder: flatbuffers.Builder, X: number): void;
    static addY(builder: flatbuffers.Builder, Y: number): void;
    static addZ(builder: flatbuffers.Builder, Z: number): void;
    static addXvel(builder: flatbuffers.Builder, XVEL: number): void;
    static addYvel(builder: flatbuffers.Builder, YVEL: number): void;
    static addZvel(builder: flatbuffers.Builder, ZVEL: number): void;
    static addElsetEpoch(builder: flatbuffers.Builder, ELSET_EPOCHOffset: flatbuffers.Offset): void;
    static addMeanMotion(builder: flatbuffers.Builder, MEAN_MOTION: number): void;
    static addEccentricity(builder: flatbuffers.Builder, ECCENTRICITY: number): void;
    static addInclination(builder: flatbuffers.Builder, INCLINATION: number): void;
    static addRaan(builder: flatbuffers.Builder, RAAN: number): void;
    static addArgOfPerigee(builder: flatbuffers.Builder, ARG_OF_PERIGEE: number): void;
    static addMeanAnomaly(builder: flatbuffers.Builder, MEAN_ANOMALY: number): void;
    static addRevNo(builder: flatbuffers.Builder, REV_NO: number): void;
    static addBStar(builder: flatbuffers.Builder, B_STAR: number): void;
    static addMeanMotionDot(builder: flatbuffers.Builder, MEAN_MOTION_DOT: number): void;
    static addMeanMotionDdot(builder: flatbuffers.Builder, MEAN_MOTION_DDOT: number): void;
    static addSemiMajorAxis(builder: flatbuffers.Builder, SEMI_MAJOR_AXIS: number): void;
    static addPeriod(builder: flatbuffers.Builder, PERIOD: number): void;
    static addApogee(builder: flatbuffers.Builder, APOGEE: number): void;
    static addPerigee(builder: flatbuffers.Builder, PERIGEE: number): void;
    static addAffectedObjects(builder: flatbuffers.Builder, AFFECTED_OBJECTSOffset: flatbuffers.Offset): void;
    static createAffectedObjectsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startAffectedObjectsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addOnOrbit(builder: flatbuffers.Builder, ON_ORBITOffset: flatbuffers.Offset): void;
    static addManifolds(builder: flatbuffers.Builder, MANIFOLDSOffset: flatbuffers.Offset): void;
    static createManifoldsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startManifoldsVector(builder: flatbuffers.Builder, numElems: number): void;
    static endOOI(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishOOIBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedOOIBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createOOI(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, SAT_NO: number, NAMEOffset: flatbuffers.Offset, SENSOR_TASKING_START_TIMEOffset: flatbuffers.Offset, SENSOR_TASKING_STOP_TIMEOffset: flatbuffers.Offset, PRIORITY: number, STATUSOffset: flatbuffers.Offset, STATUS_DATEOffset: flatbuffers.Offset, DESCRIPTIONOffset: flatbuffers.Offset, LAST_OB_TIMEOffset: flatbuffers.Offset, MISSED_OB_TIMEOffset: flatbuffers.Offset, DELTA_VSOffset: flatbuffers.Offset, DELTA_TSOffset: flatbuffers.Offset, SV_EPOCHOffset: flatbuffers.Offset, X: number, Y: number, Z: number, XVEL: number, YVEL: number, ZVEL: number, ELSET_EPOCHOffset: flatbuffers.Offset, MEAN_MOTION: number, ECCENTRICITY: number, INCLINATION: number, RAAN: number, ARG_OF_PERIGEE: number, MEAN_ANOMALY: number, REV_NO: number, B_STAR: number, MEAN_MOTION_DOT: number, MEAN_MOTION_DDOT: number, SEMI_MAJOR_AXIS: number, PERIOD: number, APOGEE: number, PERIGEE: number, AFFECTED_OBJECTSOffset: flatbuffers.Offset, ON_ORBITOffset: flatbuffers.Offset, MANIFOLDSOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): OOIT;
    unpackTo(_o: OOIT): void;
}
export declare class OOIT implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    SAT_NO: number;
    NAME: string | Uint8Array | null;
    SENSOR_TASKING_START_TIME: string | Uint8Array | null;
    SENSOR_TASKING_STOP_TIME: string | Uint8Array | null;
    PRIORITY: number;
    STATUS: string | Uint8Array | null;
    STATUS_DATE: string | Uint8Array | null;
    DESCRIPTION: string | Uint8Array | null;
    LAST_OB_TIME: string | Uint8Array | null;
    MISSED_OB_TIME: string | Uint8Array | null;
    DELTA_VS: (string)[];
    DELTA_TS: (string)[];
    SV_EPOCH: string | Uint8Array | null;
    X: number;
    Y: number;
    Z: number;
    XVEL: number;
    YVEL: number;
    ZVEL: number;
    ELSET_EPOCH: string | Uint8Array | null;
    MEAN_MOTION: number;
    ECCENTRICITY: number;
    INCLINATION: number;
    RAAN: number;
    ARG_OF_PERIGEE: number;
    MEAN_ANOMALY: number;
    REV_NO: number;
    B_STAR: number;
    MEAN_MOTION_DOT: number;
    MEAN_MOTION_DDOT: number;
    SEMI_MAJOR_AXIS: number;
    PERIOD: number;
    APOGEE: number;
    PERIGEE: number;
    AFFECTED_OBJECTS: (string)[];
    ON_ORBIT: string | Uint8Array | null;
    MANIFOLDS: (string)[];
    constructor(ID?: string | Uint8Array | null, SAT_NO?: number, NAME?: string | Uint8Array | null, SENSOR_TASKING_START_TIME?: string | Uint8Array | null, SENSOR_TASKING_STOP_TIME?: string | Uint8Array | null, PRIORITY?: number, STATUS?: string | Uint8Array | null, STATUS_DATE?: string | Uint8Array | null, DESCRIPTION?: string | Uint8Array | null, LAST_OB_TIME?: string | Uint8Array | null, MISSED_OB_TIME?: string | Uint8Array | null, DELTA_VS?: (string)[], DELTA_TS?: (string)[], SV_EPOCH?: string | Uint8Array | null, X?: number, Y?: number, Z?: number, XVEL?: number, YVEL?: number, ZVEL?: number, ELSET_EPOCH?: string | Uint8Array | null, MEAN_MOTION?: number, ECCENTRICITY?: number, INCLINATION?: number, RAAN?: number, ARG_OF_PERIGEE?: number, MEAN_ANOMALY?: number, REV_NO?: number, B_STAR?: number, MEAN_MOTION_DOT?: number, MEAN_MOTION_DDOT?: number, SEMI_MAJOR_AXIS?: number, PERIOD?: number, APOGEE?: number, PERIGEE?: number, AFFECTED_OBJECTS?: (string)[], ON_ORBIT?: string | Uint8Array | null, MANIFOLDS?: (string)[]);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=OOI.d.ts.map