import * as flatbuffers from 'flatbuffers';
/**
 * On-Orbit Object
 */
export declare class OON implements flatbuffers.IUnpackableObject<OONT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): OON;
    static getRootAsOON(bb: flatbuffers.ByteBuffer, obj?: OON): OON;
    static getSizePrefixedRootAsOON(bb: flatbuffers.ByteBuffer, obj?: OON): OON;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    SAT_NO(): number;
    COMMON_NAME(): string | null;
    COMMON_NAME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    CONSTELLATION(): string | null;
    CONSTELLATION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    INTL_DES(): string | null;
    INTL_DES(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    LAUNCH_DATE(): string | null;
    LAUNCH_DATE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DECAY_DATE(): string | null;
    DECAY_DATE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBJECT_TYPE(): string | null;
    OBJECT_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MISSION_NUMBER(): string | null;
    MISSION_NUMBER(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    CATEGORY(): string | null;
    CATEGORY(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    LIFETIME_YEARS(): number;
    ALT_NAME(): string | null;
    ALT_NAME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    LAUNCH_SITE_ID(): string | null;
    LAUNCH_SITE_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ANTENNAS(index: number): string;
    ANTENNAS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    antennasLength(): number;
    BATTERIES(index: number): string;
    BATTERIES(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    batteriesLength(): number;
    SOLAR_ARRAYS(index: number): string;
    SOLAR_ARRAYS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    solarArraysLength(): number;
    THRUSTERS(index: number): string;
    THRUSTERS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    thrustersLength(): number;
    ONORBIT_DETAILS(index: number): string;
    ONORBIT_DETAILS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    onorbitDetailsLength(): number;
    COUNTRY_CODE(): string | null;
    COUNTRY_CODE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ENTITY_COLLECTION(index: number): string;
    ENTITY_COLLECTION(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    entityCollectionLength(): number;
    static startOON(builder: flatbuffers.Builder): void;
    static addSatNo(builder: flatbuffers.Builder, SAT_NO: number): void;
    static addCommonName(builder: flatbuffers.Builder, COMMON_NAMEOffset: flatbuffers.Offset): void;
    static addConstellation(builder: flatbuffers.Builder, CONSTELLATIONOffset: flatbuffers.Offset): void;
    static addIntlDes(builder: flatbuffers.Builder, INTL_DESOffset: flatbuffers.Offset): void;
    static addLaunchDate(builder: flatbuffers.Builder, LAUNCH_DATEOffset: flatbuffers.Offset): void;
    static addDecayDate(builder: flatbuffers.Builder, DECAY_DATEOffset: flatbuffers.Offset): void;
    static addObjectType(builder: flatbuffers.Builder, OBJECT_TYPEOffset: flatbuffers.Offset): void;
    static addMissionNumber(builder: flatbuffers.Builder, MISSION_NUMBEROffset: flatbuffers.Offset): void;
    static addCategory(builder: flatbuffers.Builder, CATEGORYOffset: flatbuffers.Offset): void;
    static addLifetimeYears(builder: flatbuffers.Builder, LIFETIME_YEARS: number): void;
    static addAltName(builder: flatbuffers.Builder, ALT_NAMEOffset: flatbuffers.Offset): void;
    static addLaunchSiteId(builder: flatbuffers.Builder, LAUNCH_SITE_IDOffset: flatbuffers.Offset): void;
    static addAntennas(builder: flatbuffers.Builder, ANTENNASOffset: flatbuffers.Offset): void;
    static createAntennasVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startAntennasVector(builder: flatbuffers.Builder, numElems: number): void;
    static addBatteries(builder: flatbuffers.Builder, BATTERIESOffset: flatbuffers.Offset): void;
    static createBatteriesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startBatteriesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSolarArrays(builder: flatbuffers.Builder, SOLAR_ARRAYSOffset: flatbuffers.Offset): void;
    static createSolarArraysVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSolarArraysVector(builder: flatbuffers.Builder, numElems: number): void;
    static addThrusters(builder: flatbuffers.Builder, THRUSTERSOffset: flatbuffers.Offset): void;
    static createThrustersVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startThrustersVector(builder: flatbuffers.Builder, numElems: number): void;
    static addOnorbitDetails(builder: flatbuffers.Builder, ONORBIT_DETAILSOffset: flatbuffers.Offset): void;
    static createOnorbitDetailsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startOnorbitDetailsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addCountryCode(builder: flatbuffers.Builder, COUNTRY_CODEOffset: flatbuffers.Offset): void;
    static addEntityCollection(builder: flatbuffers.Builder, ENTITY_COLLECTIONOffset: flatbuffers.Offset): void;
    static createEntityCollectionVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startEntityCollectionVector(builder: flatbuffers.Builder, numElems: number): void;
    static endOON(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishOONBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedOONBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createOON(builder: flatbuffers.Builder, SAT_NO: number, COMMON_NAMEOffset: flatbuffers.Offset, CONSTELLATIONOffset: flatbuffers.Offset, INTL_DESOffset: flatbuffers.Offset, LAUNCH_DATEOffset: flatbuffers.Offset, DECAY_DATEOffset: flatbuffers.Offset, OBJECT_TYPEOffset: flatbuffers.Offset, MISSION_NUMBEROffset: flatbuffers.Offset, CATEGORYOffset: flatbuffers.Offset, LIFETIME_YEARS: number, ALT_NAMEOffset: flatbuffers.Offset, LAUNCH_SITE_IDOffset: flatbuffers.Offset, ANTENNASOffset: flatbuffers.Offset, BATTERIESOffset: flatbuffers.Offset, SOLAR_ARRAYSOffset: flatbuffers.Offset, THRUSTERSOffset: flatbuffers.Offset, ONORBIT_DETAILSOffset: flatbuffers.Offset, COUNTRY_CODEOffset: flatbuffers.Offset, ENTITY_COLLECTIONOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): OONT;
    unpackTo(_o: OONT): void;
}
export declare class OONT implements flatbuffers.IGeneratedObject {
    SAT_NO: number;
    COMMON_NAME: string | Uint8Array | null;
    CONSTELLATION: string | Uint8Array | null;
    INTL_DES: string | Uint8Array | null;
    LAUNCH_DATE: string | Uint8Array | null;
    DECAY_DATE: string | Uint8Array | null;
    OBJECT_TYPE: string | Uint8Array | null;
    MISSION_NUMBER: string | Uint8Array | null;
    CATEGORY: string | Uint8Array | null;
    LIFETIME_YEARS: number;
    ALT_NAME: string | Uint8Array | null;
    LAUNCH_SITE_ID: string | Uint8Array | null;
    ANTENNAS: (string)[];
    BATTERIES: (string)[];
    SOLAR_ARRAYS: (string)[];
    THRUSTERS: (string)[];
    ONORBIT_DETAILS: (string)[];
    COUNTRY_CODE: string | Uint8Array | null;
    ENTITY_COLLECTION: (string)[];
    constructor(SAT_NO?: number, COMMON_NAME?: string | Uint8Array | null, CONSTELLATION?: string | Uint8Array | null, INTL_DES?: string | Uint8Array | null, LAUNCH_DATE?: string | Uint8Array | null, DECAY_DATE?: string | Uint8Array | null, OBJECT_TYPE?: string | Uint8Array | null, MISSION_NUMBER?: string | Uint8Array | null, CATEGORY?: string | Uint8Array | null, LIFETIME_YEARS?: number, ALT_NAME?: string | Uint8Array | null, LAUNCH_SITE_ID?: string | Uint8Array | null, ANTENNAS?: (string)[], BATTERIES?: (string)[], SOLAR_ARRAYS?: (string)[], THRUSTERS?: (string)[], ONORBIT_DETAILS?: (string)[], COUNTRY_CODE?: string | Uint8Array | null, ENTITY_COLLECTION?: (string)[]);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=OON.d.ts.map