import * as flatbuffers from 'flatbuffers';
import { ACLT } from './ACL.js';
import { ACMT } from './ACM.js';
import { ACRT } from './ACR.js';
import { AEMT } from './AEM.js';
import { AOFT } from './AOF.js';
import { APMT } from './APM.js';
import { ARMT } from './ARM.js';
import { ASTT } from './AST.js';
import { ATDT } from './ATD.js';
import { ATMT } from './ATM.js';
import { BALT } from './BAL.js';
import { BEMT } from './BEM.js';
import { BMCT } from './BMC.js';
import { BOVT } from './BOV.js';
import { CATT } from './CAT.js';
import { CDMT } from './CDM.js';
import { CFPT } from './CFP.js';
import { CHNT } from './CHN.js';
import { CLTT } from './CLT.js';
import { CMST } from './CMS.js';
import { COMT } from './COM.js';
import { CRDT } from './CRD.js';
import { CRMT } from './CRM.js';
import { CSMT } from './CSM.js';
import { CTRT } from './CTR.js';
import { DFHT } from './DFH.js';
import { DMGT } from './DMG.js';
import { DOAT } from './DOA.js';
import { EMET } from './EME.js';
import { ENVT } from './ENV.js';
import { EOOT } from './EOO.js';
import { EOPT } from './EOP.js';
import { EPMT } from './EPM.js';
import { EWRT } from './EWR.js';
import { FCST } from './FCS.js';
import { GDIT } from './GDI.js';
import { GEOT } from './GEO.js';
import { GNOT } from './GNO.js';
import { GRVT } from './GRV.js';
import { GVHT } from './GVH.js';
import { HELT } from './HEL.js';
import { HYPT } from './HYP.js';
import { IDMT } from './IDM.js';
import { IROT } from './IRO.js';
import { LCCT } from './LCC.js';
import { LDMT } from './LDM.js';
import { LKST } from './LKS.js';
import { LNDT } from './LND.js';
import { LNET } from './LNE.js';
import { METT } from './MET.js';
import { MFET } from './MFE.js';
import { MNFT } from './MNF.js';
import { MNVT } from './MNV.js';
import { MPET } from './MPE.js';
import { MSLT } from './MSL.js';
import { MSTT } from './MST.js';
import { MTIT } from './MTI.js';
import { NAVT } from './NAV.js';
import { OBDT } from './OBD.js';
import { OBTT } from './OBT.js';
import { OCMT } from './OCM.js';
import { OEMT } from './OEM.js';
import { OMMT } from './OMM.js';
import { OODT } from './OOD.js';
import { OOET } from './OOE.js';
import { OOIT } from './OOI.js';
import { OOLT } from './OOL.js';
import { OONT } from './OON.js';
import { OPMT } from './OPM.js';
import { OSMT } from './OSM.js';
import { PCFT } from './PCF.js';
import { PHYT } from './PHY.js';
import { PLDT } from './PLD.js';
import { PLGT } from './PLG.js';
import { PLKT } from './PLK.js';
import { PNMT } from './PNM.js';
import { PRGT } from './PRG.js';
import { PURT } from './PUR.js';
import { RAFT } from './RAF.js';
import { RCFT } from './RCF.js';
import { RDMT } from './RDM.js';
import { RDOT } from './RDO.js';
import { REVT } from './REV.js';
import { RFBT } from './RFB.js';
import { RFET } from './RFE.js';
import { RFMT } from './RFM.js';
import { RFOT } from './RFO.js';
import { ROCT } from './ROC.js';
import { RecordType } from './RecordType.js';
import { SART } from './SAR.js';
import { SCMT } from './SCM.js';
import { SDLT } from './SDL.js';
import { SEOT } from './SEO.js';
import { SEVT } from './SEV.js';
import { SITT } from './SIT.js';
import { SKIT } from './SKI.js';
import { SNRT } from './SNR.js';
import { SOIT } from './SOI.js';
import { SONT } from './SON.js';
import { SPPT } from './SPP.js';
import { SPWT } from './SPW.js';
import { STFT } from './STF.js';
import { STRT } from './STR.js';
import { STVT } from './STV.js';
import { SWRT } from './SWR.js';
import { TCFT } from './TCF.js';
import { TDMT } from './TDM.js';
import { TIMT } from './TIM.js';
import { TKGT } from './TKG.js';
import { TMET } from './TME.js';
import { TMFT } from './TMF.js';
import { TPNT } from './TPN.js';
import { TRKT } from './TRK.js';
import { TRNT } from './TRN.js';
import { VCMT } from './VCM.js';
import { WPNT } from './WPN.js';
import { WTHT } from './WTH.js';
import { XTCT } from './XTC.js';
export declare class Record implements flatbuffers.IUnpackableObject<RecordT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): Record;
    static getRootAsRecord(bb: flatbuffers.ByteBuffer, obj?: Record): Record;
    static getSizePrefixedRootAsRecord(bb: flatbuffers.ByteBuffer, obj?: Record): Record;
    valueType(): RecordType;
    value<T extends flatbuffers.Table>(obj: any): any | null;
    standard(): string | null;
    standard(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    static startRecord(builder: flatbuffers.Builder): void;
    static addValueType(builder: flatbuffers.Builder, valueType: RecordType): void;
    static addValue(builder: flatbuffers.Builder, valueOffset: flatbuffers.Offset): void;
    static addStandard(builder: flatbuffers.Builder, standardOffset: flatbuffers.Offset): void;
    static endRecord(builder: flatbuffers.Builder): flatbuffers.Offset;
    static createRecord(builder: flatbuffers.Builder, valueType: RecordType, valueOffset: flatbuffers.Offset, standardOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): RecordT;
    unpackTo(_o: RecordT): void;
}
export declare class RecordT implements flatbuffers.IGeneratedObject {
    valueType: RecordType;
    value: ACLT | ACMT | ACRT | AEMT | AOFT | APMT | ARMT | ASTT | ATDT | ATMT | BALT | BEMT | BMCT | BOVT | CATT | CDMT | CFPT | CHNT | CLTT | CMST | COMT | CRDT | CRMT | CSMT | CTRT | DFHT | DMGT | DOAT | EMET | ENVT | EOOT | EOPT | EPMT | EWRT | FCST | GDIT | GEOT | GNOT | GRVT | GVHT | HELT | HYPT | IDMT | IROT | LCCT | LDMT | LKST | LNDT | LNET | METT | MFET | MNFT | MNVT | MPET | MSLT | MSTT | MTIT | NAVT | OBDT | OBTT | OCMT | OEMT | OMMT | OODT | OOET | OOIT | OOLT | OONT | OPMT | OSMT | PCFT | PHYT | PLDT | PLGT | PLKT | PNMT | PRGT | PURT | RAFT | RCFT | RDMT | RDOT | REVT | RFBT | RFET | RFMT | RFOT | ROCT | SART | SCMT | SDLT | SEOT | SEVT | SITT | SKIT | SNRT | SOIT | SONT | SPPT | SPWT | STFT | STRT | STVT | SWRT | TCFT | TDMT | TIMT | TKGT | TMET | TMFT | TPNT | TRKT | TRNT | VCMT | WPNT | WTHT | XTCT | null;
    standard: string | Uint8Array | null;
    constructor(valueType?: RecordType, value?: ACLT | ACMT | ACRT | AEMT | AOFT | APMT | ARMT | ASTT | ATDT | ATMT | BALT | BEMT | BMCT | BOVT | CATT | CDMT | CFPT | CHNT | CLTT | CMST | COMT | CRDT | CRMT | CSMT | CTRT | DFHT | DMGT | DOAT | EMET | ENVT | EOOT | EOPT | EPMT | EWRT | FCST | GDIT | GEOT | GNOT | GRVT | GVHT | HELT | HYPT | IDMT | IROT | LCCT | LDMT | LKST | LNDT | LNET | METT | MFET | MNFT | MNVT | MPET | MSLT | MSTT | MTIT | NAVT | OBDT | OBTT | OCMT | OEMT | OMMT | OODT | OOET | OOIT | OOLT | OONT | OPMT | OSMT | PCFT | PHYT | PLDT | PLGT | PLKT | PNMT | PRGT | PURT | RAFT | RCFT | RDMT | RDOT | REVT | RFBT | RFET | RFMT | RFOT | ROCT | SART | SCMT | SDLT | SEOT | SEVT | SITT | SKIT | SNRT | SOIT | SONT | SPPT | SPWT | STFT | STRT | STVT | SWRT | TCFT | TDMT | TIMT | TKGT | TMET | TMFT | TPNT | TRKT | TRNT | VCMT | WPNT | WTHT | XTCT | null, standard?: string | Uint8Array | null);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=Record.d.ts.map