import * as flatbuffers from 'flatbuffers';
/**
 * SAR Observation
 */
export declare class SAR implements flatbuffers.IUnpackableObject<SART> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): SAR;
    static getRootAsSAR(bb: flatbuffers.ByteBuffer, obj?: SAR): SAR;
    static getSizePrefixedRootAsSAR(bb: flatbuffers.ByteBuffer, obj?: SAR): SAR;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SAT_NO(): number;
    ORIG_OBJECT_ID(): string | null;
    ORIG_OBJECT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ID_SENSOR(): string | null;
    ID_SENSOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_SENSOR_ID(): string | null;
    ORIG_SENSOR_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    EXTERNAL_ID(): string | null;
    EXTERNAL_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    COLLECTION_ID(): string | null;
    COLLECTION_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DETECTION_ID(): string | null;
    DETECTION_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    COLLECTION_START(): string | null;
    COLLECTION_START(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    COLLECTION_END(): string | null;
    COLLECTION_END(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    CENTER_TIME(): string | null;
    CENTER_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DETECTION_START(): string | null;
    DETECTION_START(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DETECTION_END(): string | null;
    DETECTION_END(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DWELL_TIME(): number;
    ORBIT_STATE(): string | null;
    ORBIT_STATE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SAR_MODE(): string | null;
    SAR_MODE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OPERATING_BAND(): string | null;
    OPERATING_BAND(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OPERATING_FREQ(): number;
    SNR(): number;
    TX_POLARIZATION(): string | null;
    TX_POLARIZATION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    RX_POLARIZATION(): string | null;
    RX_POLARIZATION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    GRAZE_ANGLE(): number;
    INCIDENCE_ANGLE(): number;
    SQUINT_ANGLE(): number;
    PULSE_BANDWIDTH(): number;
    PULSE_DURATION(): number;
    CONTINUOUS_SPOT_ANGLE(): number;
    SLANT_RANGE(): number;
    NEAR_RANGE(): number;
    FAR_RANGE(): number;
    SWATH_LENGTH(): number;
    AREA(): string | null;
    AREA(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ATEXT(): string | null;
    ATEXT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    AGJSON(): string | null;
    AGJSON(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ATYPE(): string | null;
    ATYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ANDIMS(): number;
    ASRID(): number;
    SPACING_RANGE(): number;
    SPACING_AZIMUTH(): number;
    LOOKS_AZIMUTH(): number;
    LOOKS_RANGE(): number;
    RESOLUTION_RANGE(): number;
    RESOLUTION_AZIMUTH(): number;
    OB_DIRECTION(): string | null;
    OB_DIRECTION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    COORD_SYS(): string | null;
    COORD_SYS(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TARGETPOSX(): number;
    TARGETPOSY(): number;
    TARGETPOSZ(): number;
    SENALT(): number;
    SENVELX(): number;
    SENVELY(): number;
    SENVELZ(): number;
    SENLAT_START(): number;
    SENLON_START(): number;
    SENLAT_END(): number;
    SENLON_END(): number;
    TRANSACTION_ID(): string | null;
    TRANSACTION_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TAGS(index: number): string;
    TAGS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    tagsLength(): number;
    SRC_TYPS(index: number): string;
    SRC_TYPS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    srcTypsLength(): number;
    SRC_IDS(index: number): string;
    SRC_IDS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    srcIdsLength(): number;
    ON_ORBIT(): string | null;
    ON_ORBIT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    static startSAR(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addSatNo(builder: flatbuffers.Builder, SAT_NO: number): void;
    static addOrigObjectId(builder: flatbuffers.Builder, ORIG_OBJECT_IDOffset: flatbuffers.Offset): void;
    static addIdSensor(builder: flatbuffers.Builder, ID_SENSOROffset: flatbuffers.Offset): void;
    static addOrigSensorId(builder: flatbuffers.Builder, ORIG_SENSOR_IDOffset: flatbuffers.Offset): void;
    static addExternalId(builder: flatbuffers.Builder, EXTERNAL_IDOffset: flatbuffers.Offset): void;
    static addCollectionId(builder: flatbuffers.Builder, COLLECTION_IDOffset: flatbuffers.Offset): void;
    static addDetectionId(builder: flatbuffers.Builder, DETECTION_IDOffset: flatbuffers.Offset): void;
    static addCollectionStart(builder: flatbuffers.Builder, COLLECTION_STARTOffset: flatbuffers.Offset): void;
    static addCollectionEnd(builder: flatbuffers.Builder, COLLECTION_ENDOffset: flatbuffers.Offset): void;
    static addCenterTime(builder: flatbuffers.Builder, CENTER_TIMEOffset: flatbuffers.Offset): void;
    static addDetectionStart(builder: flatbuffers.Builder, DETECTION_STARTOffset: flatbuffers.Offset): void;
    static addDetectionEnd(builder: flatbuffers.Builder, DETECTION_ENDOffset: flatbuffers.Offset): void;
    static addDwellTime(builder: flatbuffers.Builder, DWELL_TIME: number): void;
    static addOrbitState(builder: flatbuffers.Builder, ORBIT_STATEOffset: flatbuffers.Offset): void;
    static addSarMode(builder: flatbuffers.Builder, SAR_MODEOffset: flatbuffers.Offset): void;
    static addOperatingBand(builder: flatbuffers.Builder, OPERATING_BANDOffset: flatbuffers.Offset): void;
    static addOperatingFreq(builder: flatbuffers.Builder, OPERATING_FREQ: number): void;
    static addSnr(builder: flatbuffers.Builder, SNR: number): void;
    static addTxPolarization(builder: flatbuffers.Builder, TX_POLARIZATIONOffset: flatbuffers.Offset): void;
    static addRxPolarization(builder: flatbuffers.Builder, RX_POLARIZATIONOffset: flatbuffers.Offset): void;
    static addGrazeAngle(builder: flatbuffers.Builder, GRAZE_ANGLE: number): void;
    static addIncidenceAngle(builder: flatbuffers.Builder, INCIDENCE_ANGLE: number): void;
    static addSquintAngle(builder: flatbuffers.Builder, SQUINT_ANGLE: number): void;
    static addPulseBandwidth(builder: flatbuffers.Builder, PULSE_BANDWIDTH: number): void;
    static addPulseDuration(builder: flatbuffers.Builder, PULSE_DURATION: number): void;
    static addContinuousSpotAngle(builder: flatbuffers.Builder, CONTINUOUS_SPOT_ANGLE: number): void;
    static addSlantRange(builder: flatbuffers.Builder, SLANT_RANGE: number): void;
    static addNearRange(builder: flatbuffers.Builder, NEAR_RANGE: number): void;
    static addFarRange(builder: flatbuffers.Builder, FAR_RANGE: number): void;
    static addSwathLength(builder: flatbuffers.Builder, SWATH_LENGTH: number): void;
    static addArea(builder: flatbuffers.Builder, AREAOffset: flatbuffers.Offset): void;
    static addAtext(builder: flatbuffers.Builder, ATEXTOffset: flatbuffers.Offset): void;
    static addAgjson(builder: flatbuffers.Builder, AGJSONOffset: flatbuffers.Offset): void;
    static addAtype(builder: flatbuffers.Builder, ATYPEOffset: flatbuffers.Offset): void;
    static addAndims(builder: flatbuffers.Builder, ANDIMS: number): void;
    static addAsrid(builder: flatbuffers.Builder, ASRID: number): void;
    static addSpacingRange(builder: flatbuffers.Builder, SPACING_RANGE: number): void;
    static addSpacingAzimuth(builder: flatbuffers.Builder, SPACING_AZIMUTH: number): void;
    static addLooksAzimuth(builder: flatbuffers.Builder, LOOKS_AZIMUTH: number): void;
    static addLooksRange(builder: flatbuffers.Builder, LOOKS_RANGE: number): void;
    static addResolutionRange(builder: flatbuffers.Builder, RESOLUTION_RANGE: number): void;
    static addResolutionAzimuth(builder: flatbuffers.Builder, RESOLUTION_AZIMUTH: number): void;
    static addObDirection(builder: flatbuffers.Builder, OB_DIRECTIONOffset: flatbuffers.Offset): void;
    static addCoordSys(builder: flatbuffers.Builder, COORD_SYSOffset: flatbuffers.Offset): void;
    static addTargetposx(builder: flatbuffers.Builder, TARGETPOSX: number): void;
    static addTargetposy(builder: flatbuffers.Builder, TARGETPOSY: number): void;
    static addTargetposz(builder: flatbuffers.Builder, TARGETPOSZ: number): void;
    static addSenalt(builder: flatbuffers.Builder, SENALT: number): void;
    static addSenvelx(builder: flatbuffers.Builder, SENVELX: number): void;
    static addSenvely(builder: flatbuffers.Builder, SENVELY: number): void;
    static addSenvelz(builder: flatbuffers.Builder, SENVELZ: number): void;
    static addSenlatStart(builder: flatbuffers.Builder, SENLAT_START: number): void;
    static addSenlonStart(builder: flatbuffers.Builder, SENLON_START: number): void;
    static addSenlatEnd(builder: flatbuffers.Builder, SENLAT_END: number): void;
    static addSenlonEnd(builder: flatbuffers.Builder, SENLON_END: number): void;
    static addTransactionId(builder: flatbuffers.Builder, TRANSACTION_IDOffset: flatbuffers.Offset): void;
    static addTags(builder: flatbuffers.Builder, TAGSOffset: flatbuffers.Offset): void;
    static createTagsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startTagsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSrcTyps(builder: flatbuffers.Builder, SRC_TYPSOffset: flatbuffers.Offset): void;
    static createSrcTypsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSrcTypsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSrcIds(builder: flatbuffers.Builder, SRC_IDSOffset: flatbuffers.Offset): void;
    static createSrcIdsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSrcIdsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addOnOrbit(builder: flatbuffers.Builder, ON_ORBITOffset: flatbuffers.Offset): void;
    static endSAR(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishSARBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedSARBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createSAR(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, SAT_NO: number, ORIG_OBJECT_IDOffset: flatbuffers.Offset, ID_SENSOROffset: flatbuffers.Offset, ORIG_SENSOR_IDOffset: flatbuffers.Offset, EXTERNAL_IDOffset: flatbuffers.Offset, COLLECTION_IDOffset: flatbuffers.Offset, DETECTION_IDOffset: flatbuffers.Offset, COLLECTION_STARTOffset: flatbuffers.Offset, COLLECTION_ENDOffset: flatbuffers.Offset, CENTER_TIMEOffset: flatbuffers.Offset, DETECTION_STARTOffset: flatbuffers.Offset, DETECTION_ENDOffset: flatbuffers.Offset, DWELL_TIME: number, ORBIT_STATEOffset: flatbuffers.Offset, SAR_MODEOffset: flatbuffers.Offset, OPERATING_BANDOffset: flatbuffers.Offset, OPERATING_FREQ: number, SNR: number, TX_POLARIZATIONOffset: flatbuffers.Offset, RX_POLARIZATIONOffset: flatbuffers.Offset, GRAZE_ANGLE: number, INCIDENCE_ANGLE: number, SQUINT_ANGLE: number, PULSE_BANDWIDTH: number, PULSE_DURATION: number, CONTINUOUS_SPOT_ANGLE: number, SLANT_RANGE: number, NEAR_RANGE: number, FAR_RANGE: number, SWATH_LENGTH: number, AREAOffset: flatbuffers.Offset, ATEXTOffset: flatbuffers.Offset, AGJSONOffset: flatbuffers.Offset, ATYPEOffset: flatbuffers.Offset, ANDIMS: number, ASRID: number, SPACING_RANGE: number, SPACING_AZIMUTH: number, LOOKS_AZIMUTH: number, LOOKS_RANGE: number, RESOLUTION_RANGE: number, RESOLUTION_AZIMUTH: number, OB_DIRECTIONOffset: flatbuffers.Offset, COORD_SYSOffset: flatbuffers.Offset, TARGETPOSX: number, TARGETPOSY: number, TARGETPOSZ: number, SENALT: number, SENVELX: number, SENVELY: number, SENVELZ: number, SENLAT_START: number, SENLON_START: number, SENLAT_END: number, SENLON_END: number, TRANSACTION_IDOffset: flatbuffers.Offset, TAGSOffset: flatbuffers.Offset, SRC_TYPSOffset: flatbuffers.Offset, SRC_IDSOffset: flatbuffers.Offset, ON_ORBITOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): SART;
    unpackTo(_o: SART): void;
}
export declare class SART implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    SAT_NO: number;
    ORIG_OBJECT_ID: string | Uint8Array | null;
    ID_SENSOR: string | Uint8Array | null;
    ORIG_SENSOR_ID: string | Uint8Array | null;
    EXTERNAL_ID: string | Uint8Array | null;
    COLLECTION_ID: string | Uint8Array | null;
    DETECTION_ID: string | Uint8Array | null;
    COLLECTION_START: string | Uint8Array | null;
    COLLECTION_END: string | Uint8Array | null;
    CENTER_TIME: string | Uint8Array | null;
    DETECTION_START: string | Uint8Array | null;
    DETECTION_END: string | Uint8Array | null;
    DWELL_TIME: number;
    ORBIT_STATE: string | Uint8Array | null;
    SAR_MODE: string | Uint8Array | null;
    OPERATING_BAND: string | Uint8Array | null;
    OPERATING_FREQ: number;
    SNR: number;
    TX_POLARIZATION: string | Uint8Array | null;
    RX_POLARIZATION: string | Uint8Array | null;
    GRAZE_ANGLE: number;
    INCIDENCE_ANGLE: number;
    SQUINT_ANGLE: number;
    PULSE_BANDWIDTH: number;
    PULSE_DURATION: number;
    CONTINUOUS_SPOT_ANGLE: number;
    SLANT_RANGE: number;
    NEAR_RANGE: number;
    FAR_RANGE: number;
    SWATH_LENGTH: number;
    AREA: string | Uint8Array | null;
    ATEXT: string | Uint8Array | null;
    AGJSON: string | Uint8Array | null;
    ATYPE: string | Uint8Array | null;
    ANDIMS: number;
    ASRID: number;
    SPACING_RANGE: number;
    SPACING_AZIMUTH: number;
    LOOKS_AZIMUTH: number;
    LOOKS_RANGE: number;
    RESOLUTION_RANGE: number;
    RESOLUTION_AZIMUTH: number;
    OB_DIRECTION: string | Uint8Array | null;
    COORD_SYS: string | Uint8Array | null;
    TARGETPOSX: number;
    TARGETPOSY: number;
    TARGETPOSZ: number;
    SENALT: number;
    SENVELX: number;
    SENVELY: number;
    SENVELZ: number;
    SENLAT_START: number;
    SENLON_START: number;
    SENLAT_END: number;
    SENLON_END: number;
    TRANSACTION_ID: string | Uint8Array | null;
    TAGS: (string)[];
    SRC_TYPS: (string)[];
    SRC_IDS: (string)[];
    ON_ORBIT: string | Uint8Array | null;
    constructor(ID?: string | Uint8Array | null, SAT_NO?: number, ORIG_OBJECT_ID?: string | Uint8Array | null, ID_SENSOR?: string | Uint8Array | null, ORIG_SENSOR_ID?: string | Uint8Array | null, EXTERNAL_ID?: string | Uint8Array | null, COLLECTION_ID?: string | Uint8Array | null, DETECTION_ID?: string | Uint8Array | null, COLLECTION_START?: string | Uint8Array | null, COLLECTION_END?: string | Uint8Array | null, CENTER_TIME?: string | Uint8Array | null, DETECTION_START?: string | Uint8Array | null, DETECTION_END?: string | Uint8Array | null, DWELL_TIME?: number, ORBIT_STATE?: string | Uint8Array | null, SAR_MODE?: string | Uint8Array | null, OPERATING_BAND?: string | Uint8Array | null, OPERATING_FREQ?: number, SNR?: number, TX_POLARIZATION?: string | Uint8Array | null, RX_POLARIZATION?: string | Uint8Array | null, GRAZE_ANGLE?: number, INCIDENCE_ANGLE?: number, SQUINT_ANGLE?: number, PULSE_BANDWIDTH?: number, PULSE_DURATION?: number, CONTINUOUS_SPOT_ANGLE?: number, SLANT_RANGE?: number, NEAR_RANGE?: number, FAR_RANGE?: number, SWATH_LENGTH?: number, AREA?: string | Uint8Array | null, ATEXT?: string | Uint8Array | null, AGJSON?: string | Uint8Array | null, ATYPE?: string | Uint8Array | null, ANDIMS?: number, ASRID?: number, SPACING_RANGE?: number, SPACING_AZIMUTH?: number, LOOKS_AZIMUTH?: number, LOOKS_RANGE?: number, RESOLUTION_RANGE?: number, RESOLUTION_AZIMUTH?: number, OB_DIRECTION?: string | Uint8Array | null, COORD_SYS?: string | Uint8Array | null, TARGETPOSX?: number, TARGETPOSY?: number, TARGETPOSZ?: number, SENALT?: number, SENVELX?: number, SENVELY?: number, SENVELZ?: number, SENLAT_START?: number, SENLON_START?: number, SENLAT_END?: number, SENLON_END?: number, TRANSACTION_ID?: string | Uint8Array | null, TAGS?: (string)[], SRC_TYPS?: (string)[], SRC_IDS?: (string)[], ON_ORBIT?: string | Uint8Array | null);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=SAR.d.ts.map