import * as flatbuffers from 'flatbuffers';
import { SCVAggregateStatistics, SCVAggregateStatisticsT } from './SCVAggregateStatistics.js';
import { SCVEllipsoid, SCVEllipsoidT } from './SCVEllipsoid.js';
import { SCVHistogramBin, SCVHistogramBinT } from './SCVHistogramBin.js';
import { SCVPackedGeometryChunk, SCVPackedGeometryChunkT } from './SCVPackedGeometryChunk.js';
import { SCVPackedRasterProducts, SCVPackedRasterProductsT } from './SCVPackedRasterProducts.js';
import { SCVSensorContribution, SCVSensorContributionT } from './SCVSensorContribution.js';
import { SCVTargetResult, SCVTargetResultT } from './SCVTargetResult.js';
import { SCVTimeGrid, SCVTimeGridT } from './SCVTimeGrid.js';
import { scvResultState } from './scvResultState.js';
export declare class SCVResult implements flatbuffers.IUnpackableObject<SCVResultT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): SCVResult;
    static getRootAsSCVResult(bb: flatbuffers.ByteBuffer, obj?: SCVResult): SCVResult;
    static getSizePrefixedRootAsSCVResult(bb: flatbuffers.ByteBuffer, obj?: SCVResult): SCVResult;
    JOB_ID(): string | null;
    JOB_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRACE_ID(): bigint;
    STATUS(): scvResultState;
    TIME_GRID(obj?: SCVTimeGrid): SCVTimeGrid | null;
    TARGET_BODY(obj?: SCVEllipsoid): SCVEllipsoid | null;
    TOTAL_SENSORS(): number;
    TOTAL_WINDOWS(): number;
    HISTOGRAMS(index: number, obj?: SCVHistogramBin): SCVHistogramBin | null;
    histogramsLength(): number;
    CONTRIBUTIONS(index: number, obj?: SCVSensorContribution): SCVSensorContribution | null;
    contributionsLength(): number;
    GEOMETRY(obj?: SCVPackedGeometryChunk): SCVPackedGeometryChunk | null;
    RASTER_PRODUCTS(obj?: SCVPackedRasterProducts): SCVPackedRasterProducts | null;
    MESSAGE(): string | null;
    MESSAGE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    AGGREGATE_STATISTICS(obj?: SCVAggregateStatistics): SCVAggregateStatistics | null;
    TARGET_RESULTS(index: number, obj?: SCVTargetResult): SCVTargetResult | null;
    targetResultsLength(): number;
    static startSCVResult(builder: flatbuffers.Builder): void;
    static addJobId(builder: flatbuffers.Builder, JOB_IDOffset: flatbuffers.Offset): void;
    static addTraceId(builder: flatbuffers.Builder, TRACE_ID: bigint): void;
    static addStatus(builder: flatbuffers.Builder, STATUS: scvResultState): void;
    static addTimeGrid(builder: flatbuffers.Builder, TIME_GRIDOffset: flatbuffers.Offset): void;
    static addTargetBody(builder: flatbuffers.Builder, TARGET_BODYOffset: flatbuffers.Offset): void;
    static addTotalSensors(builder: flatbuffers.Builder, TOTAL_SENSORS: number): void;
    static addTotalWindows(builder: flatbuffers.Builder, TOTAL_WINDOWS: number): void;
    static addHistograms(builder: flatbuffers.Builder, HISTOGRAMSOffset: flatbuffers.Offset): void;
    static createHistogramsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startHistogramsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addContributions(builder: flatbuffers.Builder, CONTRIBUTIONSOffset: flatbuffers.Offset): void;
    static createContributionsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startContributionsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addGeometry(builder: flatbuffers.Builder, GEOMETRYOffset: flatbuffers.Offset): void;
    static addRasterProducts(builder: flatbuffers.Builder, RASTER_PRODUCTSOffset: flatbuffers.Offset): void;
    static addMessage(builder: flatbuffers.Builder, MESSAGEOffset: flatbuffers.Offset): void;
    static addAggregateStatistics(builder: flatbuffers.Builder, AGGREGATE_STATISTICSOffset: flatbuffers.Offset): void;
    static addTargetResults(builder: flatbuffers.Builder, TARGET_RESULTSOffset: flatbuffers.Offset): void;
    static createTargetResultsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startTargetResultsVector(builder: flatbuffers.Builder, numElems: number): void;
    static endSCVResult(builder: flatbuffers.Builder): flatbuffers.Offset;
    unpack(): SCVResultT;
    unpackTo(_o: SCVResultT): void;
}
export declare class SCVResultT implements flatbuffers.IGeneratedObject {
    JOB_ID: string | Uint8Array | null;
    TRACE_ID: bigint;
    STATUS: scvResultState;
    TIME_GRID: SCVTimeGridT | null;
    TARGET_BODY: SCVEllipsoidT | null;
    TOTAL_SENSORS: number;
    TOTAL_WINDOWS: number;
    HISTOGRAMS: (SCVHistogramBinT)[];
    CONTRIBUTIONS: (SCVSensorContributionT)[];
    GEOMETRY: SCVPackedGeometryChunkT | null;
    RASTER_PRODUCTS: SCVPackedRasterProductsT | null;
    MESSAGE: string | Uint8Array | null;
    AGGREGATE_STATISTICS: SCVAggregateStatisticsT | null;
    TARGET_RESULTS: (SCVTargetResultT)[];
    constructor(JOB_ID?: string | Uint8Array | null, TRACE_ID?: bigint, STATUS?: scvResultState, TIME_GRID?: SCVTimeGridT | null, TARGET_BODY?: SCVEllipsoidT | null, TOTAL_SENSORS?: number, TOTAL_WINDOWS?: number, HISTOGRAMS?: (SCVHistogramBinT)[], CONTRIBUTIONS?: (SCVSensorContributionT)[], GEOMETRY?: SCVPackedGeometryChunkT | null, RASTER_PRODUCTS?: SCVPackedRasterProductsT | null, MESSAGE?: string | Uint8Array | null, AGGREGATE_STATISTICS?: SCVAggregateStatisticsT | null, TARGET_RESULTS?: (SCVTargetResultT)[]);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=SCVResult.d.ts.map