// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { vepRegime } from './vepRegime.js';
/**
 * One point of the burn-rate table: consumption at a stated regime,
 * altitude, and speed.
 */
export class VEPPerformancePoint {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsVEPPerformancePoint(bb, obj) {
        return (obj || new VEPPerformancePoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsVEPPerformancePoint(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new VEPPerformancePoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    /**
     * Altitude the point is stated at, metres above mean sea level. NaN for
     * surface and subsurface regimes where altitude does not apply.
     */
    ALTITUDE_M() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    /**
     * Speed the point is stated at, metres per second.
     */
    SPEED_MPS() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    /**
     * Operating regime.
     */
    REGIME() {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : vepRegime.UNSPECIFIED;
    }
    /**
     * Consumption rate at this point, in BURN_RATE_UNITS per second unless
     * the unit token itself states another time base.
     */
    BURN_RATE_VALUE() {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    BURN_RATE_UNITS(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return this.bb.__string(this.bb_pos + offset, optionalEncoding);
    }
    /**
     * Distance travelled per unit of energy at this point, metres per
     * CAPACITY_UNITS unit.
     */
    SPECIFIC_RANGE_M_PER_UNIT() {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    /**
     * Gross mass the point is stated at, kilograms.
     */
    GROSS_MASS_KG() {
        const offset = this.bb.__offset(this.bb_pos, 16);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    static startVEPPerformancePoint(builder) {
        builder.startObject(7);
    }
    static addAltitudeM(builder, ALTITUDE_M) {
        builder.addFieldFloat64(0, ALTITUDE_M, 0.0);
    }
    static addSpeedMps(builder, SPEED_MPS) {
        builder.addFieldFloat64(1, SPEED_MPS, 0.0);
    }
    static addRegime(builder, REGIME) {
        builder.addFieldInt8(2, REGIME, vepRegime.UNSPECIFIED);
    }
    static addBurnRateValue(builder, BURN_RATE_VALUE) {
        builder.addFieldFloat64(3, BURN_RATE_VALUE, 0.0);
    }
    static addBurnRateUnits(builder, BURN_RATE_UNITSOffset) {
        builder.addFieldOffset(4, BURN_RATE_UNITSOffset, 0);
    }
    static addSpecificRangeMPerUnit(builder, SPECIFIC_RANGE_M_PER_UNIT) {
        builder.addFieldFloat64(5, SPECIFIC_RANGE_M_PER_UNIT, 0.0);
    }
    static addGrossMassKg(builder, GROSS_MASS_KG) {
        builder.addFieldFloat64(6, GROSS_MASS_KG, 0.0);
    }
    static endVEPPerformancePoint(builder) {
        const offset = builder.endObject();
        builder.requiredField(offset, 12); // BURN_RATE_UNITS
        return offset;
    }
    static createVEPPerformancePoint(builder, ALTITUDE_M, SPEED_MPS, REGIME, BURN_RATE_VALUE, BURN_RATE_UNITSOffset, SPECIFIC_RANGE_M_PER_UNIT, GROSS_MASS_KG) {
        VEPPerformancePoint.startVEPPerformancePoint(builder);
        VEPPerformancePoint.addAltitudeM(builder, ALTITUDE_M);
        VEPPerformancePoint.addSpeedMps(builder, SPEED_MPS);
        VEPPerformancePoint.addRegime(builder, REGIME);
        VEPPerformancePoint.addBurnRateValue(builder, BURN_RATE_VALUE);
        VEPPerformancePoint.addBurnRateUnits(builder, BURN_RATE_UNITSOffset);
        VEPPerformancePoint.addSpecificRangeMPerUnit(builder, SPECIFIC_RANGE_M_PER_UNIT);
        VEPPerformancePoint.addGrossMassKg(builder, GROSS_MASS_KG);
        return VEPPerformancePoint.endVEPPerformancePoint(builder);
    }
    unpack() {
        return new VEPPerformancePointT(this.ALTITUDE_M(), this.SPEED_MPS(), this.REGIME(), this.BURN_RATE_VALUE(), this.BURN_RATE_UNITS(), this.SPECIFIC_RANGE_M_PER_UNIT(), this.GROSS_MASS_KG());
    }
    unpackTo(_o) {
        _o.ALTITUDE_M = this.ALTITUDE_M();
        _o.SPEED_MPS = this.SPEED_MPS();
        _o.REGIME = this.REGIME();
        _o.BURN_RATE_VALUE = this.BURN_RATE_VALUE();
        _o.BURN_RATE_UNITS = this.BURN_RATE_UNITS();
        _o.SPECIFIC_RANGE_M_PER_UNIT = this.SPECIFIC_RANGE_M_PER_UNIT();
        _o.GROSS_MASS_KG = this.GROSS_MASS_KG();
    }
}
export class VEPPerformancePointT {
    constructor(ALTITUDE_M = 0.0, SPEED_MPS = 0.0, REGIME = vepRegime.UNSPECIFIED, BURN_RATE_VALUE = 0.0, BURN_RATE_UNITS = null, SPECIFIC_RANGE_M_PER_UNIT = 0.0, GROSS_MASS_KG = 0.0) {
        this.ALTITUDE_M = ALTITUDE_M;
        this.SPEED_MPS = SPEED_MPS;
        this.REGIME = REGIME;
        this.BURN_RATE_VALUE = BURN_RATE_VALUE;
        this.BURN_RATE_UNITS = BURN_RATE_UNITS;
        this.SPECIFIC_RANGE_M_PER_UNIT = SPECIFIC_RANGE_M_PER_UNIT;
        this.GROSS_MASS_KG = GROSS_MASS_KG;
    }
    pack(builder) {
        const BURN_RATE_UNITS = (this.BURN_RATE_UNITS !== null ? builder.createString(this.BURN_RATE_UNITS) : 0);
        return VEPPerformancePoint.createVEPPerformancePoint(builder, this.ALTITUDE_M, this.SPEED_MPS, this.REGIME, this.BURN_RATE_VALUE, BURN_RATE_UNITS, this.SPECIFIC_RANGE_M_PER_UNIT, this.GROSS_MASS_KG);
    }
}
