import * as flatbuffers from 'flatbuffers';
import { SCVCoverageGrid, SCVCoverageGridT } from './SCVCoverageGrid.js';
import { SCVEllipsoid, SCVEllipsoidT } from './SCVEllipsoid.js';
import { SCVSensor, SCVSensorT } from './SCVSensor.js';
import { SCVStateSample, SCVStateSampleT } from './SCVStateSample.js';
import { SCVTarget, SCVTargetT } from './SCVTarget.js';
import { SCVTargetStateSample, SCVTargetStateSampleT } from './SCVTargetStateSample.js';
import { SCVTimeGrid, SCVTimeGridT } from './SCVTimeGrid.js';
import { scvAnalysisMode } from './scvAnalysisMode.js';
import { scvGeometryEncoding } from './scvGeometryEncoding.js';
import { scvMetricSeriesKind } from './scvMetricSeriesKind.js';
export declare class SCVCoverageRequest implements flatbuffers.IUnpackableObject<SCVCoverageRequestT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): SCVCoverageRequest;
    static getRootAsSCVCoverageRequest(bb: flatbuffers.ByteBuffer, obj?: SCVCoverageRequest): SCVCoverageRequest;
    static getSizePrefixedRootAsSCVCoverageRequest(bb: flatbuffers.ByteBuffer, obj?: SCVCoverageRequest): SCVCoverageRequest;
    JOB_ID(): string | null;
    JOB_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRACE_ID(): bigint;
    ANALYSIS_MODE(): scvAnalysisMode;
    TARGET_BODY(obj?: SCVEllipsoid): SCVEllipsoid | null;
    TIME_GRID(obj?: SCVTimeGrid): SCVTimeGrid | null;
    COVERAGE_GRID(obj?: SCVCoverageGrid): SCVCoverageGrid | null;
    SENSORS(index: number, obj?: SCVSensor): SCVSensor | null;
    sensorsLength(): number;
    STATE_SAMPLES(index: number, obj?: SCVStateSample): SCVStateSample | null;
    stateSamplesLength(): number;
    TARGETS(index: number, obj?: SCVTarget): SCVTarget | null;
    targetsLength(): number;
    TARGET_STATE_SAMPLES(index: number, obj?: SCVTargetStateSample): SCVTargetStateSample | null;
    targetStateSamplesLength(): number;
    REQUESTED_PRODUCTS(index: number): scvMetricSeriesKind | null;
    requestedProductsLength(): number;
    requestedProductsArray(): Uint16Array | null;
    SENSOR_BATCH_START(): number;
    SENSOR_BATCH_COUNT(): number;
    WINDOW_BATCH_START(): number;
    WINDOW_BATCH_COUNT(): number;
    GEOMETRY_ENCODING(): scvGeometryEncoding;
    INCLUDE_PACKED_GEOMETRY(): boolean;
    static startSCVCoverageRequest(builder: flatbuffers.Builder): void;
    static addJobId(builder: flatbuffers.Builder, JOB_IDOffset: flatbuffers.Offset): void;
    static addTraceId(builder: flatbuffers.Builder, TRACE_ID: bigint): void;
    static addAnalysisMode(builder: flatbuffers.Builder, ANALYSIS_MODE: scvAnalysisMode): void;
    static addTargetBody(builder: flatbuffers.Builder, TARGET_BODYOffset: flatbuffers.Offset): void;
    static addTimeGrid(builder: flatbuffers.Builder, TIME_GRIDOffset: flatbuffers.Offset): void;
    static addCoverageGrid(builder: flatbuffers.Builder, COVERAGE_GRIDOffset: flatbuffers.Offset): void;
    static addSensors(builder: flatbuffers.Builder, SENSORSOffset: flatbuffers.Offset): void;
    static createSensorsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSensorsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addStateSamples(builder: flatbuffers.Builder, STATE_SAMPLESOffset: flatbuffers.Offset): void;
    static createStateSamplesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startStateSamplesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addTargets(builder: flatbuffers.Builder, TARGETSOffset: flatbuffers.Offset): void;
    static createTargetsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startTargetsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addTargetStateSamples(builder: flatbuffers.Builder, TARGET_STATE_SAMPLESOffset: flatbuffers.Offset): void;
    static createTargetStateSamplesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startTargetStateSamplesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addRequestedProducts(builder: flatbuffers.Builder, REQUESTED_PRODUCTSOffset: flatbuffers.Offset): void;
    static createRequestedProductsVector(builder: flatbuffers.Builder, data: scvMetricSeriesKind[]): flatbuffers.Offset;
    static startRequestedProductsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSensorBatchStart(builder: flatbuffers.Builder, SENSOR_BATCH_START: number): void;
    static addSensorBatchCount(builder: flatbuffers.Builder, SENSOR_BATCH_COUNT: number): void;
    static addWindowBatchStart(builder: flatbuffers.Builder, WINDOW_BATCH_START: number): void;
    static addWindowBatchCount(builder: flatbuffers.Builder, WINDOW_BATCH_COUNT: number): void;
    static addGeometryEncoding(builder: flatbuffers.Builder, GEOMETRY_ENCODING: scvGeometryEncoding): void;
    static addIncludePackedGeometry(builder: flatbuffers.Builder, INCLUDE_PACKED_GEOMETRY: boolean): void;
    static endSCVCoverageRequest(builder: flatbuffers.Builder): flatbuffers.Offset;
    unpack(): SCVCoverageRequestT;
    unpackTo(_o: SCVCoverageRequestT): void;
}
export declare class SCVCoverageRequestT implements flatbuffers.IGeneratedObject {
    JOB_ID: string | Uint8Array | null;
    TRACE_ID: bigint;
    ANALYSIS_MODE: scvAnalysisMode;
    TARGET_BODY: SCVEllipsoidT | null;
    TIME_GRID: SCVTimeGridT | null;
    COVERAGE_GRID: SCVCoverageGridT | null;
    SENSORS: (SCVSensorT)[];
    STATE_SAMPLES: (SCVStateSampleT)[];
    TARGETS: (SCVTargetT)[];
    TARGET_STATE_SAMPLES: (SCVTargetStateSampleT)[];
    REQUESTED_PRODUCTS: (scvMetricSeriesKind)[];
    SENSOR_BATCH_START: number;
    SENSOR_BATCH_COUNT: number;
    WINDOW_BATCH_START: number;
    WINDOW_BATCH_COUNT: number;
    GEOMETRY_ENCODING: scvGeometryEncoding;
    INCLUDE_PACKED_GEOMETRY: boolean;
    constructor(JOB_ID?: string | Uint8Array | null, TRACE_ID?: bigint, ANALYSIS_MODE?: scvAnalysisMode, TARGET_BODY?: SCVEllipsoidT | null, TIME_GRID?: SCVTimeGridT | null, COVERAGE_GRID?: SCVCoverageGridT | null, SENSORS?: (SCVSensorT)[], STATE_SAMPLES?: (SCVStateSampleT)[], TARGETS?: (SCVTargetT)[], TARGET_STATE_SAMPLES?: (SCVTargetStateSampleT)[], REQUESTED_PRODUCTS?: (scvMetricSeriesKind)[], SENSOR_BATCH_START?: number, SENSOR_BATCH_COUNT?: number, WINDOW_BATCH_START?: number, WINDOW_BATCH_COUNT?: number, GEOMETRY_ENCODING?: scvGeometryEncoding, INCLUDE_PACKED_GEOMETRY?: boolean);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=SCVCoverageRequest.d.ts.map