import * as flatbuffers from 'flatbuffers';
import { SCVCellStat, SCVCellStatT } from './SCVCellStat.js';
import { SCVEllipsoid, SCVEllipsoidT } from './SCVEllipsoid.js';
import { SCVHeatmapCell, SCVHeatmapCellT } from './SCVHeatmapCell.js';
import { SCVHistogramBin, SCVHistogramBinT } from './SCVHistogramBin.js';
import { SCVInterval, SCVIntervalT } from './SCVInterval.js';
import { SCVLatitudeBandStat, SCVLatitudeBandStatT } from './SCVLatitudeBandStat.js';
import { SCVPackedGeometryChunk, SCVPackedGeometryChunkT } from './SCVPackedGeometryChunk.js';
import { SCVSensorContribution, SCVSensorContributionT } from './SCVSensorContribution.js';
import { SCVTimeGrid, SCVTimeGridT } from './SCVTimeGrid.js';
import { SCVTimeSeriesPoint, SCVTimeSeriesPointT } from './SCVTimeSeriesPoint.js';
import { scvResultState } from './scvResultState.js';
export declare class SCVResult implements flatbuffers.IUnpackableObject<SCVResultT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): SCVResult;
    static getRootAsSCVResult(bb: flatbuffers.ByteBuffer, obj?: SCVResult): SCVResult;
    static getSizePrefixedRootAsSCVResult(bb: flatbuffers.ByteBuffer, obj?: SCVResult): SCVResult;
    JOB_ID(): string | null;
    JOB_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRACE_ID(): bigint;
    STATUS(): scvResultState;
    TIME_GRID(obj?: SCVTimeGrid): SCVTimeGrid | null;
    TARGET_BODY(obj?: SCVEllipsoid): SCVEllipsoid | null;
    TOTAL_SENSORS(): number;
    TOTAL_WINDOWS(): number;
    CELL_STATS(index: number, obj?: SCVCellStat): SCVCellStat | null;
    cellStatsLength(): number;
    INTERVALS(index: number, obj?: SCVInterval): SCVInterval | null;
    intervalsLength(): number;
    LATITUDE_BANDS(index: number, obj?: SCVLatitudeBandStat): SCVLatitudeBandStat | null;
    latitudeBandsLength(): number;
    TIME_SERIES(index: number, obj?: SCVTimeSeriesPoint): SCVTimeSeriesPoint | null;
    timeSeriesLength(): number;
    HISTOGRAMS(index: number, obj?: SCVHistogramBin): SCVHistogramBin | null;
    histogramsLength(): number;
    HEATMAP(index: number, obj?: SCVHeatmapCell): SCVHeatmapCell | null;
    heatmapLength(): number;
    CONTRIBUTIONS(index: number, obj?: SCVSensorContribution): SCVSensorContribution | null;
    contributionsLength(): number;
    GEOMETRY(obj?: SCVPackedGeometryChunk): SCVPackedGeometryChunk | null;
    MESSAGE(): string | null;
    MESSAGE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    static startSCVResult(builder: flatbuffers.Builder): void;
    static addJobId(builder: flatbuffers.Builder, JOB_IDOffset: flatbuffers.Offset): void;
    static addTraceId(builder: flatbuffers.Builder, TRACE_ID: bigint): void;
    static addStatus(builder: flatbuffers.Builder, STATUS: scvResultState): void;
    static addTimeGrid(builder: flatbuffers.Builder, TIME_GRIDOffset: flatbuffers.Offset): void;
    static addTargetBody(builder: flatbuffers.Builder, TARGET_BODYOffset: flatbuffers.Offset): void;
    static addTotalSensors(builder: flatbuffers.Builder, TOTAL_SENSORS: number): void;
    static addTotalWindows(builder: flatbuffers.Builder, TOTAL_WINDOWS: number): void;
    static addCellStats(builder: flatbuffers.Builder, CELL_STATSOffset: flatbuffers.Offset): void;
    static createCellStatsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startCellStatsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addIntervals(builder: flatbuffers.Builder, INTERVALSOffset: flatbuffers.Offset): void;
    static createIntervalsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startIntervalsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addLatitudeBands(builder: flatbuffers.Builder, LATITUDE_BANDSOffset: flatbuffers.Offset): void;
    static createLatitudeBandsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startLatitudeBandsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addTimeSeries(builder: flatbuffers.Builder, TIME_SERIESOffset: flatbuffers.Offset): void;
    static createTimeSeriesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startTimeSeriesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addHistograms(builder: flatbuffers.Builder, HISTOGRAMSOffset: flatbuffers.Offset): void;
    static createHistogramsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startHistogramsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addHeatmap(builder: flatbuffers.Builder, HEATMAPOffset: flatbuffers.Offset): void;
    static createHeatmapVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startHeatmapVector(builder: flatbuffers.Builder, numElems: number): void;
    static addContributions(builder: flatbuffers.Builder, CONTRIBUTIONSOffset: flatbuffers.Offset): void;
    static createContributionsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startContributionsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addGeometry(builder: flatbuffers.Builder, GEOMETRYOffset: flatbuffers.Offset): void;
    static addMessage(builder: flatbuffers.Builder, MESSAGEOffset: flatbuffers.Offset): void;
    static endSCVResult(builder: flatbuffers.Builder): flatbuffers.Offset;
    unpack(): SCVResultT;
    unpackTo(_o: SCVResultT): void;
}
export declare class SCVResultT implements flatbuffers.IGeneratedObject {
    JOB_ID: string | Uint8Array | null;
    TRACE_ID: bigint;
    STATUS: scvResultState;
    TIME_GRID: SCVTimeGridT | null;
    TARGET_BODY: SCVEllipsoidT | null;
    TOTAL_SENSORS: number;
    TOTAL_WINDOWS: number;
    CELL_STATS: (SCVCellStatT)[];
    INTERVALS: (SCVIntervalT)[];
    LATITUDE_BANDS: (SCVLatitudeBandStatT)[];
    TIME_SERIES: (SCVTimeSeriesPointT)[];
    HISTOGRAMS: (SCVHistogramBinT)[];
    HEATMAP: (SCVHeatmapCellT)[];
    CONTRIBUTIONS: (SCVSensorContributionT)[];
    GEOMETRY: SCVPackedGeometryChunkT | null;
    MESSAGE: string | Uint8Array | null;
    constructor(JOB_ID?: string | Uint8Array | null, TRACE_ID?: bigint, STATUS?: scvResultState, TIME_GRID?: SCVTimeGridT | null, TARGET_BODY?: SCVEllipsoidT | null, TOTAL_SENSORS?: number, TOTAL_WINDOWS?: number, CELL_STATS?: (SCVCellStatT)[], INTERVALS?: (SCVIntervalT)[], LATITUDE_BANDS?: (SCVLatitudeBandStatT)[], TIME_SERIES?: (SCVTimeSeriesPointT)[], HISTOGRAMS?: (SCVHistogramBinT)[], HEATMAP?: (SCVHeatmapCellT)[], CONTRIBUTIONS?: (SCVSensorContributionT)[], GEOMETRY?: SCVPackedGeometryChunkT | null, MESSAGE?: string | Uint8Array | null);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=SCVResult.d.ts.map