import * as flatbuffers from 'flatbuffers';
import { SCVVec3, SCVVec3T } from './SCVVec3.js';
import { scvCoordinateFrame } from './scvCoordinateFrame.js';
import { scvSensorShapeKind } from './scvSensorShapeKind.js';
export declare class SCVSensor implements flatbuffers.IUnpackableObject<SCVSensorT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): SCVSensor;
    static getRootAsSCVSensor(bb: flatbuffers.ByteBuffer, obj?: SCVSensor): SCVSensor;
    static getSizePrefixedRootAsSCVSensor(bb: flatbuffers.ByteBuffer, obj?: SCVSensor): SCVSensor;
    SENSOR_ID(): number;
    OBJECT_ID(): string | null;
    OBJECT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    NAME(): string | null;
    NAME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SHAPE(): scvSensorShapeKind;
    FRAME(): scvCoordinateFrame;
    POSITION_M(obj?: SCVVec3): SCVVec3 | null;
    VELOCITY_MPS(obj?: SCVVec3): SCVVec3 | null;
    BORESIGHT_UNIT(obj?: SCVVec3): SCVVec3 | null;
    UP_UNIT(obj?: SCVVec3): SCVVec3 | null;
    HALF_ANGLE_DEG(): number;
    CROSS_TRACK_HALF_ANGLE_DEG(): number;
    ALONG_TRACK_HALF_ANGLE_DEG(): number;
    MIN_RANGE_M(): number;
    MAX_RANGE_M(): number;
    POLYGON_VERTICES(index: number, obj?: SCVVec3): SCVVec3 | null;
    polygonVerticesLength(): number;
    POLYGON_FRAME(): scvCoordinateFrame;
    static startSCVSensor(builder: flatbuffers.Builder): void;
    static addSensorId(builder: flatbuffers.Builder, SENSOR_ID: number): void;
    static addObjectId(builder: flatbuffers.Builder, OBJECT_IDOffset: flatbuffers.Offset): void;
    static addName(builder: flatbuffers.Builder, NAMEOffset: flatbuffers.Offset): void;
    static addShape(builder: flatbuffers.Builder, SHAPE: scvSensorShapeKind): void;
    static addFrame(builder: flatbuffers.Builder, FRAME: scvCoordinateFrame): void;
    static addPositionM(builder: flatbuffers.Builder, POSITION_MOffset: flatbuffers.Offset): void;
    static addVelocityMps(builder: flatbuffers.Builder, VELOCITY_MPSOffset: flatbuffers.Offset): void;
    static addBoresightUnit(builder: flatbuffers.Builder, BORESIGHT_UNITOffset: flatbuffers.Offset): void;
    static addUpUnit(builder: flatbuffers.Builder, UP_UNITOffset: flatbuffers.Offset): void;
    static addHalfAngleDeg(builder: flatbuffers.Builder, HALF_ANGLE_DEG: number): void;
    static addCrossTrackHalfAngleDeg(builder: flatbuffers.Builder, CROSS_TRACK_HALF_ANGLE_DEG: number): void;
    static addAlongTrackHalfAngleDeg(builder: flatbuffers.Builder, ALONG_TRACK_HALF_ANGLE_DEG: number): void;
    static addMinRangeM(builder: flatbuffers.Builder, MIN_RANGE_M: number): void;
    static addMaxRangeM(builder: flatbuffers.Builder, MAX_RANGE_M: number): void;
    static addPolygonVertices(builder: flatbuffers.Builder, POLYGON_VERTICESOffset: flatbuffers.Offset): void;
    static createPolygonVerticesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startPolygonVerticesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addPolygonFrame(builder: flatbuffers.Builder, POLYGON_FRAME: scvCoordinateFrame): void;
    static endSCVSensor(builder: flatbuffers.Builder): flatbuffers.Offset;
    unpack(): SCVSensorT;
    unpackTo(_o: SCVSensorT): void;
}
export declare class SCVSensorT implements flatbuffers.IGeneratedObject {
    SENSOR_ID: number;
    OBJECT_ID: string | Uint8Array | null;
    NAME: string | Uint8Array | null;
    SHAPE: scvSensorShapeKind;
    FRAME: scvCoordinateFrame;
    POSITION_M: SCVVec3T | null;
    VELOCITY_MPS: SCVVec3T | null;
    BORESIGHT_UNIT: SCVVec3T | null;
    UP_UNIT: SCVVec3T | null;
    HALF_ANGLE_DEG: number;
    CROSS_TRACK_HALF_ANGLE_DEG: number;
    ALONG_TRACK_HALF_ANGLE_DEG: number;
    MIN_RANGE_M: number;
    MAX_RANGE_M: number;
    POLYGON_VERTICES: (SCVVec3T)[];
    POLYGON_FRAME: scvCoordinateFrame;
    constructor(SENSOR_ID?: number, OBJECT_ID?: string | Uint8Array | null, NAME?: string | Uint8Array | null, SHAPE?: scvSensorShapeKind, FRAME?: scvCoordinateFrame, POSITION_M?: SCVVec3T | null, VELOCITY_MPS?: SCVVec3T | null, BORESIGHT_UNIT?: SCVVec3T | null, UP_UNIT?: SCVVec3T | null, HALF_ANGLE_DEG?: number, CROSS_TRACK_HALF_ANGLE_DEG?: number, ALONG_TRACK_HALF_ANGLE_DEG?: number, MIN_RANGE_M?: number, MAX_RANGE_M?: number, POLYGON_VERTICES?: (SCVVec3T)[], POLYGON_FRAME?: scvCoordinateFrame);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=SCVSensor.d.ts.map