import * as flatbuffers from 'flatbuffers';
/**
 * Space Environment Observation
 */
export declare class SEO implements flatbuffers.IUnpackableObject<SEOT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): SEO;
    static getRootAsSEO(bb: flatbuffers.ByteBuffer, obj?: SEO): SEO;
    static getSizePrefixedRootAsSEO(bb: flatbuffers.ByteBuffer, obj?: SEO): SEO;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MSG_TYPE(): string | null;
    MSG_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    GEN_SYSTEM(): string | null;
    GEN_SYSTEM(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    EXTERNAL_ID(): string | null;
    EXTERNAL_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DATA_TYPE(): string | null;
    DATA_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    GEN_TIME(): string | null;
    GEN_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    FORECAST(): boolean;
    DERIVED(): boolean;
    SAT_NO(): number;
    ORIG_OBJECT_ID(): string | null;
    ORIG_OBJECT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ID_SENSOR(): string | null;
    ID_SENSOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_SENSOR_ID(): string | null;
    ORIG_SENSOR_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBSERVATORY_TYPE(): string | null;
    OBSERVATORY_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBSERVATORY_NAME(): string | null;
    OBSERVATORY_NAME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBSERVATORY_NOTES(): string | null;
    OBSERVATORY_NOTES(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    INSTRUMENT_TYPE(): string | null;
    INSTRUMENT_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    LAT(): number;
    LON(): number;
    ALT(): number;
    SEN_REFERENCE_FRAME(): string | null;
    SEN_REFERENCE_FRAME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SEN_POS(index: number): string;
    SEN_POS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    senPosLength(): number;
    SEN_VEL(index: number): string;
    SEN_VEL(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    senVelLength(): number;
    MEAS_TYPE(): string | null;
    MEAS_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SEN_ENERGY_LEVEL(): string | null;
    SEN_ENERGY_LEVEL(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OB_SET_ID(): string | null;
    OB_SET_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    PARTICLE_TYPE(): string | null;
    PARTICLE_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OB_TIME(): string | null;
    OB_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SEO_LIST(index: number): string;
    SEO_LIST(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    seoListLength(): number;
    QUALITY(): string | null;
    QUALITY(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DESCRIPTION(): string | null;
    DESCRIPTION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DESCRIPTOR(): string | null;
    DESCRIPTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SRC_TYPS(index: number): string;
    SRC_TYPS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    srcTypsLength(): number;
    SRC_IDS(index: number): string;
    SRC_IDS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    srcIdsLength(): number;
    static startSEO(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addMsgType(builder: flatbuffers.Builder, MSG_TYPEOffset: flatbuffers.Offset): void;
    static addGenSystem(builder: flatbuffers.Builder, GEN_SYSTEMOffset: flatbuffers.Offset): void;
    static addExternalId(builder: flatbuffers.Builder, EXTERNAL_IDOffset: flatbuffers.Offset): void;
    static addDataType(builder: flatbuffers.Builder, DATA_TYPEOffset: flatbuffers.Offset): void;
    static addGenTime(builder: flatbuffers.Builder, GEN_TIMEOffset: flatbuffers.Offset): void;
    static addForecast(builder: flatbuffers.Builder, FORECAST: boolean): void;
    static addDerived(builder: flatbuffers.Builder, DERIVED: boolean): void;
    static addSatNo(builder: flatbuffers.Builder, SAT_NO: number): void;
    static addOrigObjectId(builder: flatbuffers.Builder, ORIG_OBJECT_IDOffset: flatbuffers.Offset): void;
    static addIdSensor(builder: flatbuffers.Builder, ID_SENSOROffset: flatbuffers.Offset): void;
    static addOrigSensorId(builder: flatbuffers.Builder, ORIG_SENSOR_IDOffset: flatbuffers.Offset): void;
    static addObservatoryType(builder: flatbuffers.Builder, OBSERVATORY_TYPEOffset: flatbuffers.Offset): void;
    static addObservatoryName(builder: flatbuffers.Builder, OBSERVATORY_NAMEOffset: flatbuffers.Offset): void;
    static addObservatoryNotes(builder: flatbuffers.Builder, OBSERVATORY_NOTESOffset: flatbuffers.Offset): void;
    static addInstrumentType(builder: flatbuffers.Builder, INSTRUMENT_TYPEOffset: flatbuffers.Offset): void;
    static addLat(builder: flatbuffers.Builder, LAT: number): void;
    static addLon(builder: flatbuffers.Builder, LON: number): void;
    static addAlt(builder: flatbuffers.Builder, ALT: number): void;
    static addSenReferenceFrame(builder: flatbuffers.Builder, SEN_REFERENCE_FRAMEOffset: flatbuffers.Offset): void;
    static addSenPos(builder: flatbuffers.Builder, SEN_POSOffset: flatbuffers.Offset): void;
    static createSenPosVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSenPosVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSenVel(builder: flatbuffers.Builder, SEN_VELOffset: flatbuffers.Offset): void;
    static createSenVelVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSenVelVector(builder: flatbuffers.Builder, numElems: number): void;
    static addMeasType(builder: flatbuffers.Builder, MEAS_TYPEOffset: flatbuffers.Offset): void;
    static addSenEnergyLevel(builder: flatbuffers.Builder, SEN_ENERGY_LEVELOffset: flatbuffers.Offset): void;
    static addObSetId(builder: flatbuffers.Builder, OB_SET_IDOffset: flatbuffers.Offset): void;
    static addParticleType(builder: flatbuffers.Builder, PARTICLE_TYPEOffset: flatbuffers.Offset): void;
    static addObTime(builder: flatbuffers.Builder, OB_TIMEOffset: flatbuffers.Offset): void;
    static addSeoList(builder: flatbuffers.Builder, SEO_LISTOffset: flatbuffers.Offset): void;
    static createSeoListVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSeoListVector(builder: flatbuffers.Builder, numElems: number): void;
    static addQuality(builder: flatbuffers.Builder, QUALITYOffset: flatbuffers.Offset): void;
    static addDescription(builder: flatbuffers.Builder, DESCRIPTIONOffset: flatbuffers.Offset): void;
    static addDescriptor(builder: flatbuffers.Builder, DESCRIPTOROffset: flatbuffers.Offset): void;
    static addSrcTyps(builder: flatbuffers.Builder, SRC_TYPSOffset: flatbuffers.Offset): void;
    static createSrcTypsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSrcTypsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSrcIds(builder: flatbuffers.Builder, SRC_IDSOffset: flatbuffers.Offset): void;
    static createSrcIdsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSrcIdsVector(builder: flatbuffers.Builder, numElems: number): void;
    static endSEO(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishSEOBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedSEOBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createSEO(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, MSG_TYPEOffset: flatbuffers.Offset, GEN_SYSTEMOffset: flatbuffers.Offset, EXTERNAL_IDOffset: flatbuffers.Offset, DATA_TYPEOffset: flatbuffers.Offset, GEN_TIMEOffset: flatbuffers.Offset, FORECAST: boolean, DERIVED: boolean, SAT_NO: number, ORIG_OBJECT_IDOffset: flatbuffers.Offset, ID_SENSOROffset: flatbuffers.Offset, ORIG_SENSOR_IDOffset: flatbuffers.Offset, OBSERVATORY_TYPEOffset: flatbuffers.Offset, OBSERVATORY_NAMEOffset: flatbuffers.Offset, OBSERVATORY_NOTESOffset: flatbuffers.Offset, INSTRUMENT_TYPEOffset: flatbuffers.Offset, LAT: number, LON: number, ALT: number, SEN_REFERENCE_FRAMEOffset: flatbuffers.Offset, SEN_POSOffset: flatbuffers.Offset, SEN_VELOffset: flatbuffers.Offset, MEAS_TYPEOffset: flatbuffers.Offset, SEN_ENERGY_LEVELOffset: flatbuffers.Offset, OB_SET_IDOffset: flatbuffers.Offset, PARTICLE_TYPEOffset: flatbuffers.Offset, OB_TIMEOffset: flatbuffers.Offset, SEO_LISTOffset: flatbuffers.Offset, QUALITYOffset: flatbuffers.Offset, DESCRIPTIONOffset: flatbuffers.Offset, DESCRIPTOROffset: flatbuffers.Offset, SRC_TYPSOffset: flatbuffers.Offset, SRC_IDSOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): SEOT;
    unpackTo(_o: SEOT): void;
}
export declare class SEOT implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    MSG_TYPE: string | Uint8Array | null;
    GEN_SYSTEM: string | Uint8Array | null;
    EXTERNAL_ID: string | Uint8Array | null;
    DATA_TYPE: string | Uint8Array | null;
    GEN_TIME: string | Uint8Array | null;
    FORECAST: boolean;
    DERIVED: boolean;
    SAT_NO: number;
    ORIG_OBJECT_ID: string | Uint8Array | null;
    ID_SENSOR: string | Uint8Array | null;
    ORIG_SENSOR_ID: string | Uint8Array | null;
    OBSERVATORY_TYPE: string | Uint8Array | null;
    OBSERVATORY_NAME: string | Uint8Array | null;
    OBSERVATORY_NOTES: string | Uint8Array | null;
    INSTRUMENT_TYPE: string | Uint8Array | null;
    LAT: number;
    LON: number;
    ALT: number;
    SEN_REFERENCE_FRAME: string | Uint8Array | null;
    SEN_POS: (string)[];
    SEN_VEL: (string)[];
    MEAS_TYPE: string | Uint8Array | null;
    SEN_ENERGY_LEVEL: string | Uint8Array | null;
    OB_SET_ID: string | Uint8Array | null;
    PARTICLE_TYPE: string | Uint8Array | null;
    OB_TIME: string | Uint8Array | null;
    SEO_LIST: (string)[];
    QUALITY: string | Uint8Array | null;
    DESCRIPTION: string | Uint8Array | null;
    DESCRIPTOR: string | Uint8Array | null;
    SRC_TYPS: (string)[];
    SRC_IDS: (string)[];
    constructor(ID?: string | Uint8Array | null, MSG_TYPE?: string | Uint8Array | null, GEN_SYSTEM?: string | Uint8Array | null, EXTERNAL_ID?: string | Uint8Array | null, DATA_TYPE?: string | Uint8Array | null, GEN_TIME?: string | Uint8Array | null, FORECAST?: boolean, DERIVED?: boolean, SAT_NO?: number, ORIG_OBJECT_ID?: string | Uint8Array | null, ID_SENSOR?: string | Uint8Array | null, ORIG_SENSOR_ID?: string | Uint8Array | null, OBSERVATORY_TYPE?: string | Uint8Array | null, OBSERVATORY_NAME?: string | Uint8Array | null, OBSERVATORY_NOTES?: string | Uint8Array | null, INSTRUMENT_TYPE?: string | Uint8Array | null, LAT?: number, LON?: number, ALT?: number, SEN_REFERENCE_FRAME?: string | Uint8Array | null, SEN_POS?: (string)[], SEN_VEL?: (string)[], MEAS_TYPE?: string | Uint8Array | null, SEN_ENERGY_LEVEL?: string | Uint8Array | null, OB_SET_ID?: string | Uint8Array | null, PARTICLE_TYPE?: string | Uint8Array | null, OB_TIME?: string | Uint8Array | null, SEO_LIST?: (string)[], QUALITY?: string | Uint8Array | null, DESCRIPTION?: string | Uint8Array | null, DESCRIPTOR?: string | Uint8Array | null, SRC_TYPS?: (string)[], SRC_IDS?: (string)[]);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=SEO.d.ts.map