import * as flatbuffers from 'flatbuffers';
import { FieldStreamValue, FieldStreamValueT } from './FieldStreamValue.js';
export declare class FSM implements flatbuffers.IUnpackableObject<FSMT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): FSM;
    static getRootAsFSM(bb: flatbuffers.ByteBuffer, obj?: FSM): FSM;
    static getSizePrefixedRootAsFSM(bb: flatbuffers.ByteBuffer, obj?: FSM): FSM;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    MESSAGE_ID(): string;
    MESSAGE_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    PROVIDER_PEER_ID(): string;
    PROVIDER_PEER_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    LISTING_ID(): string;
    LISTING_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    STREAM_ID(): string;
    STREAM_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    SCHEMA_CODE(): string;
    SCHEMA_CODE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    SCHEMA_HASH(index: number): number | null;
    schemaHashLength(): number;
    schemaHashArray(): Uint8Array | null;
    POLICY_ID(): string;
    POLICY_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    POLICY_VERSION(): number;
    KEY_EPOCH(): string | null;
    KEY_EPOCH(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SEQUENCE(): bigint;
    PRODUCED_AT(): bigint;
    EXPIRES_AT(): bigint;
    SUBJECT_ID(): string | null;
    SUBJECT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    FIELDS(index: number, obj?: FieldStreamValue): FieldStreamValue | null;
    fieldsLength(): number;
    PAYLOAD_HASH(index: number): number | null;
    payloadHashLength(): number;
    payloadHashArray(): Uint8Array | null;
    PREVIOUS_MESSAGE_HASH(index: number): number | null;
    previousMessageHashLength(): number;
    previousMessageHashArray(): Uint8Array | null;
    PROVIDER_SIGNATURE(index: number): number | null;
    providerSignatureLength(): number;
    providerSignatureArray(): Uint8Array | null;
    static startFSM(builder: flatbuffers.Builder): void;
    static addMessageId(builder: flatbuffers.Builder, MESSAGE_IDOffset: flatbuffers.Offset): void;
    static addProviderPeerId(builder: flatbuffers.Builder, PROVIDER_PEER_IDOffset: flatbuffers.Offset): void;
    static addListingId(builder: flatbuffers.Builder, LISTING_IDOffset: flatbuffers.Offset): void;
    static addStreamId(builder: flatbuffers.Builder, STREAM_IDOffset: flatbuffers.Offset): void;
    static addSchemaCode(builder: flatbuffers.Builder, SCHEMA_CODEOffset: flatbuffers.Offset): void;
    static addSchemaHash(builder: flatbuffers.Builder, SCHEMA_HASHOffset: flatbuffers.Offset): void;
    static createSchemaHashVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset;
    static startSchemaHashVector(builder: flatbuffers.Builder, numElems: number): void;
    static addPolicyId(builder: flatbuffers.Builder, POLICY_IDOffset: flatbuffers.Offset): void;
    static addPolicyVersion(builder: flatbuffers.Builder, POLICY_VERSION: number): void;
    static addKeyEpoch(builder: flatbuffers.Builder, KEY_EPOCHOffset: flatbuffers.Offset): void;
    static addSequence(builder: flatbuffers.Builder, SEQUENCE: bigint): void;
    static addProducedAt(builder: flatbuffers.Builder, PRODUCED_AT: bigint): void;
    static addExpiresAt(builder: flatbuffers.Builder, EXPIRES_AT: bigint): void;
    static addSubjectId(builder: flatbuffers.Builder, SUBJECT_IDOffset: flatbuffers.Offset): void;
    static addFields(builder: flatbuffers.Builder, FIELDSOffset: flatbuffers.Offset): void;
    static createFieldsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startFieldsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addPayloadHash(builder: flatbuffers.Builder, PAYLOAD_HASHOffset: flatbuffers.Offset): void;
    static createPayloadHashVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset;
    static startPayloadHashVector(builder: flatbuffers.Builder, numElems: number): void;
    static addPreviousMessageHash(builder: flatbuffers.Builder, PREVIOUS_MESSAGE_HASHOffset: flatbuffers.Offset): void;
    static createPreviousMessageHashVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset;
    static startPreviousMessageHashVector(builder: flatbuffers.Builder, numElems: number): void;
    static addProviderSignature(builder: flatbuffers.Builder, PROVIDER_SIGNATUREOffset: flatbuffers.Offset): void;
    static createProviderSignatureVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset;
    static startProviderSignatureVector(builder: flatbuffers.Builder, numElems: number): void;
    static endFSM(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishFSMBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedFSMBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createFSM(builder: flatbuffers.Builder, MESSAGE_IDOffset: flatbuffers.Offset, PROVIDER_PEER_IDOffset: flatbuffers.Offset, LISTING_IDOffset: flatbuffers.Offset, STREAM_IDOffset: flatbuffers.Offset, SCHEMA_CODEOffset: flatbuffers.Offset, SCHEMA_HASHOffset: flatbuffers.Offset, POLICY_IDOffset: flatbuffers.Offset, POLICY_VERSION: number, KEY_EPOCHOffset: flatbuffers.Offset, SEQUENCE: bigint, PRODUCED_AT: bigint, EXPIRES_AT: bigint, SUBJECT_IDOffset: flatbuffers.Offset, FIELDSOffset: flatbuffers.Offset, PAYLOAD_HASHOffset: flatbuffers.Offset, PREVIOUS_MESSAGE_HASHOffset: flatbuffers.Offset, PROVIDER_SIGNATUREOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): FSMT;
    unpackTo(_o: FSMT): void;
}
export declare class FSMT implements flatbuffers.IGeneratedObject {
    MESSAGE_ID: string | Uint8Array | null;
    PROVIDER_PEER_ID: string | Uint8Array | null;
    LISTING_ID: string | Uint8Array | null;
    STREAM_ID: string | Uint8Array | null;
    SCHEMA_CODE: string | Uint8Array | null;
    SCHEMA_HASH: (number)[];
    POLICY_ID: string | Uint8Array | null;
    POLICY_VERSION: number;
    KEY_EPOCH: string | Uint8Array | null;
    SEQUENCE: bigint;
    PRODUCED_AT: bigint;
    EXPIRES_AT: bigint;
    SUBJECT_ID: string | Uint8Array | null;
    FIELDS: (FieldStreamValueT)[];
    PAYLOAD_HASH: (number)[];
    PREVIOUS_MESSAGE_HASH: (number)[];
    PROVIDER_SIGNATURE: (number)[];
    constructor(MESSAGE_ID?: string | Uint8Array | null, PROVIDER_PEER_ID?: string | Uint8Array | null, LISTING_ID?: string | Uint8Array | null, STREAM_ID?: string | Uint8Array | null, SCHEMA_CODE?: string | Uint8Array | null, SCHEMA_HASH?: (number)[], POLICY_ID?: string | Uint8Array | null, POLICY_VERSION?: number, KEY_EPOCH?: string | Uint8Array | null, SEQUENCE?: bigint, PRODUCED_AT?: bigint, EXPIRES_AT?: bigint, SUBJECT_ID?: string | Uint8Array | null, FIELDS?: (FieldStreamValueT)[], PAYLOAD_HASH?: (number)[], PREVIOUS_MESSAGE_HASH?: (number)[], PROVIDER_SIGNATURE?: (number)[]);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=FSM.d.ts.map