# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

class acwResultStatus(object):
    # Operation completed.
    OK = 0
    # Request fields are missing, non-finite, or numerically invalid.
    INVALID_INPUT = 1
    # The requested operation is not supported by the module.
    UNSUPPORTED_OPERATION = 2
