# automatically generated by the FlatBuffers compiler, do not modify

# namespace:

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# Dataset lineage and redistribution terms for one track model state.
#
# Required on every record: a redistributed track whose feed, epoch, and
# licence are unstated is not publishable. The standard names no feed,
# provider, or site.
class TMSProvenance(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TMSProvenance()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTMSProvenance(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TMSProvenanceBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x24\x54\x4D\x53", size_prefixed=size_prefixed)

    # TMSProvenance
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Publisher-stable, lowercase identifier for the feed or dataset this
    # state was derived from, unique within the publisher's own dataset
    # registry. Never a display name and never a URL.
    # TMSProvenance
    def DATASET_ID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The feed or dataset's own name, verbatim as its publisher states it.
    # TMSProvenance
    def DATASET_NAME(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Replayable URL of the feed or dataset as published.
    # TMSProvenance
    def DATASET_URL(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RFC 3339 UTC fixed-millisecond epoch of the dataset edition or feed
    # session this state was derived from.
    # TMSProvenance
    def DATASET_EPOCH(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Content identifier of the exact dataset artifact, when one exists.
    # TMSProvenance
    def DATASET_CID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Replayable URL identifying the source material within the dataset.
    # TMSProvenance
    def SOURCE_URL(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The exact query, filter, or subscription used.
    # TMSProvenance
    def SOURCE_QUERY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RFC 3339 UTC fixed-millisecond retrieval timestamp of the observation
    # this state was updated from.
    # TMSProvenance
    def RETRIEVED_AT(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Redistribution terms verbatim. Unknown terms are never public domain
    # and never an implied grant.
    # TMSProvenance
    def LICENSE(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # URL of the full licence text as the source publishes it.
    # TMSProvenance
    def LICENSE_URL(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Attribution text the licence requires a redistributor to display.
    # TMSProvenance
    def ATTRIBUTION(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # The licence forbids commercial use.
    # TMSProvenance
    def NON_COMMERCIAL_ONLY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # The licence obliges derived works to carry the same terms.
    # TMSProvenance
    def SHARE_ALIKE(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # The source's own identifier for the track or observation stream this
    # state was derived from, verbatim.
    # TMSProvenance
    def NATIVE_ID(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RFC 3339 UTC instant the source last modified or emitted the
    # underlying observation, as the source states it.
    # TMSProvenance
    def NATIVE_MODIFIED(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def TMSProvenanceStart(builder):
    builder.StartObject(15)

def Start(builder):
    TMSProvenanceStart(builder)

def TMSProvenanceAddDATASET_ID(builder, DATASET_ID):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(DATASET_ID), 0)

def AddDATASET_ID(builder, DATASET_ID):
    TMSProvenanceAddDATASET_ID(builder, DATASET_ID)

def TMSProvenanceAddDATASET_NAME(builder, DATASET_NAME):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(DATASET_NAME), 0)

def AddDATASET_NAME(builder, DATASET_NAME):
    TMSProvenanceAddDATASET_NAME(builder, DATASET_NAME)

def TMSProvenanceAddDATASET_URL(builder, DATASET_URL):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(DATASET_URL), 0)

def AddDATASET_URL(builder, DATASET_URL):
    TMSProvenanceAddDATASET_URL(builder, DATASET_URL)

def TMSProvenanceAddDATASET_EPOCH(builder, DATASET_EPOCH):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(DATASET_EPOCH), 0)

def AddDATASET_EPOCH(builder, DATASET_EPOCH):
    TMSProvenanceAddDATASET_EPOCH(builder, DATASET_EPOCH)

def TMSProvenanceAddDATASET_CID(builder, DATASET_CID):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(DATASET_CID), 0)

def AddDATASET_CID(builder, DATASET_CID):
    TMSProvenanceAddDATASET_CID(builder, DATASET_CID)

def TMSProvenanceAddSOURCE_URL(builder, SOURCE_URL):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(SOURCE_URL), 0)

def AddSOURCE_URL(builder, SOURCE_URL):
    TMSProvenanceAddSOURCE_URL(builder, SOURCE_URL)

def TMSProvenanceAddSOURCE_QUERY(builder, SOURCE_QUERY):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(SOURCE_QUERY), 0)

def AddSOURCE_QUERY(builder, SOURCE_QUERY):
    TMSProvenanceAddSOURCE_QUERY(builder, SOURCE_QUERY)

def TMSProvenanceAddRETRIEVED_AT(builder, RETRIEVED_AT):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(RETRIEVED_AT), 0)

def AddRETRIEVED_AT(builder, RETRIEVED_AT):
    TMSProvenanceAddRETRIEVED_AT(builder, RETRIEVED_AT)

def TMSProvenanceAddLICENSE(builder, LICENSE):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(LICENSE), 0)

def AddLICENSE(builder, LICENSE):
    TMSProvenanceAddLICENSE(builder, LICENSE)

def TMSProvenanceAddLICENSE_URL(builder, LICENSE_URL):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(LICENSE_URL), 0)

def AddLICENSE_URL(builder, LICENSE_URL):
    TMSProvenanceAddLICENSE_URL(builder, LICENSE_URL)

def TMSProvenanceAddATTRIBUTION(builder, ATTRIBUTION):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(ATTRIBUTION), 0)

def AddATTRIBUTION(builder, ATTRIBUTION):
    TMSProvenanceAddATTRIBUTION(builder, ATTRIBUTION)

def TMSProvenanceAddNON_COMMERCIAL_ONLY(builder, NON_COMMERCIAL_ONLY):
    builder.PrependBoolSlot(11, NON_COMMERCIAL_ONLY, 0)

def AddNON_COMMERCIAL_ONLY(builder, NON_COMMERCIAL_ONLY):
    TMSProvenanceAddNON_COMMERCIAL_ONLY(builder, NON_COMMERCIAL_ONLY)

def TMSProvenanceAddSHARE_ALIKE(builder, SHARE_ALIKE):
    builder.PrependBoolSlot(12, SHARE_ALIKE, 0)

def AddSHARE_ALIKE(builder, SHARE_ALIKE):
    TMSProvenanceAddSHARE_ALIKE(builder, SHARE_ALIKE)

def TMSProvenanceAddNATIVE_ID(builder, NATIVE_ID):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(NATIVE_ID), 0)

def AddNATIVE_ID(builder, NATIVE_ID):
    TMSProvenanceAddNATIVE_ID(builder, NATIVE_ID)

def TMSProvenanceAddNATIVE_MODIFIED(builder, NATIVE_MODIFIED):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(NATIVE_MODIFIED), 0)

def AddNATIVE_MODIFIED(builder, NATIVE_MODIFIED):
    TMSProvenanceAddNATIVE_MODIFIED(builder, NATIVE_MODIFIED)

def TMSProvenanceEnd(builder):
    return builder.EndObject()

def End(builder):
    return TMSProvenanceEnd(builder)


class TMSProvenanceT(object):

    # TMSProvenanceT
    def __init__(
        self,
        DATASET_ID = None,
        DATASET_NAME = None,
        DATASET_URL = None,
        DATASET_EPOCH = None,
        DATASET_CID = None,
        SOURCE_URL = None,
        SOURCE_QUERY = None,
        RETRIEVED_AT = None,
        LICENSE = None,
        LICENSE_URL = None,
        ATTRIBUTION = None,
        NON_COMMERCIAL_ONLY = False,
        SHARE_ALIKE = False,
        NATIVE_ID = None,
        NATIVE_MODIFIED = None,
    ):
        self.DATASET_ID = DATASET_ID  # type: Optional[str]
        self.DATASET_NAME = DATASET_NAME  # type: Optional[str]
        self.DATASET_URL = DATASET_URL  # type: Optional[str]
        self.DATASET_EPOCH = DATASET_EPOCH  # type: Optional[str]
        self.DATASET_CID = DATASET_CID  # type: Optional[str]
        self.SOURCE_URL = SOURCE_URL  # type: Optional[str]
        self.SOURCE_QUERY = SOURCE_QUERY  # type: Optional[str]
        self.RETRIEVED_AT = RETRIEVED_AT  # type: Optional[str]
        self.LICENSE = LICENSE  # type: Optional[str]
        self.LICENSE_URL = LICENSE_URL  # type: Optional[str]
        self.ATTRIBUTION = ATTRIBUTION  # type: Optional[str]
        self.NON_COMMERCIAL_ONLY = NON_COMMERCIAL_ONLY  # type: bool
        self.SHARE_ALIKE = SHARE_ALIKE  # type: bool
        self.NATIVE_ID = NATIVE_ID  # type: Optional[str]
        self.NATIVE_MODIFIED = NATIVE_MODIFIED  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        tmpTmsprovenance = TMSProvenance()
        tmpTmsprovenance.Init(buf, pos)
        return cls.InitFromObj(tmpTmsprovenance)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, tmpTmsprovenance):
        x = TMSProvenanceT()
        x._UnPack(tmpTmsprovenance)
        return x

    # TMSProvenanceT
    def _UnPack(self, TMSProvenance):
        if TMSProvenance is None:
            return
        self.DATASET_ID = TMSProvenance.DATASET_ID()
        self.DATASET_NAME = TMSProvenance.DATASET_NAME()
        self.DATASET_URL = TMSProvenance.DATASET_URL()
        self.DATASET_EPOCH = TMSProvenance.DATASET_EPOCH()
        self.DATASET_CID = TMSProvenance.DATASET_CID()
        self.SOURCE_URL = TMSProvenance.SOURCE_URL()
        self.SOURCE_QUERY = TMSProvenance.SOURCE_QUERY()
        self.RETRIEVED_AT = TMSProvenance.RETRIEVED_AT()
        self.LICENSE = TMSProvenance.LICENSE()
        self.LICENSE_URL = TMSProvenance.LICENSE_URL()
        self.ATTRIBUTION = TMSProvenance.ATTRIBUTION()
        self.NON_COMMERCIAL_ONLY = TMSProvenance.NON_COMMERCIAL_ONLY()
        self.SHARE_ALIKE = TMSProvenance.SHARE_ALIKE()
        self.NATIVE_ID = TMSProvenance.NATIVE_ID()
        self.NATIVE_MODIFIED = TMSProvenance.NATIVE_MODIFIED()

    # TMSProvenanceT
    def Pack(self, builder):
        if self.DATASET_ID is not None:
            DATASET_ID = builder.CreateString(self.DATASET_ID)
        if self.DATASET_NAME is not None:
            DATASET_NAME = builder.CreateString(self.DATASET_NAME)
        if self.DATASET_URL is not None:
            DATASET_URL = builder.CreateString(self.DATASET_URL)
        if self.DATASET_EPOCH is not None:
            DATASET_EPOCH = builder.CreateString(self.DATASET_EPOCH)
        if self.DATASET_CID is not None:
            DATASET_CID = builder.CreateString(self.DATASET_CID)
        if self.SOURCE_URL is not None:
            SOURCE_URL = builder.CreateString(self.SOURCE_URL)
        if self.SOURCE_QUERY is not None:
            SOURCE_QUERY = builder.CreateString(self.SOURCE_QUERY)
        if self.RETRIEVED_AT is not None:
            RETRIEVED_AT = builder.CreateString(self.RETRIEVED_AT)
        if self.LICENSE is not None:
            LICENSE = builder.CreateString(self.LICENSE)
        if self.LICENSE_URL is not None:
            LICENSE_URL = builder.CreateString(self.LICENSE_URL)
        if self.ATTRIBUTION is not None:
            ATTRIBUTION = builder.CreateString(self.ATTRIBUTION)
        if self.NATIVE_ID is not None:
            NATIVE_ID = builder.CreateString(self.NATIVE_ID)
        if self.NATIVE_MODIFIED is not None:
            NATIVE_MODIFIED = builder.CreateString(self.NATIVE_MODIFIED)
        TMSProvenanceStart(builder)
        if self.DATASET_ID is not None:
            TMSProvenanceAddDATASET_ID(builder, DATASET_ID)
        if self.DATASET_NAME is not None:
            TMSProvenanceAddDATASET_NAME(builder, DATASET_NAME)
        if self.DATASET_URL is not None:
            TMSProvenanceAddDATASET_URL(builder, DATASET_URL)
        if self.DATASET_EPOCH is not None:
            TMSProvenanceAddDATASET_EPOCH(builder, DATASET_EPOCH)
        if self.DATASET_CID is not None:
            TMSProvenanceAddDATASET_CID(builder, DATASET_CID)
        if self.SOURCE_URL is not None:
            TMSProvenanceAddSOURCE_URL(builder, SOURCE_URL)
        if self.SOURCE_QUERY is not None:
            TMSProvenanceAddSOURCE_QUERY(builder, SOURCE_QUERY)
        if self.RETRIEVED_AT is not None:
            TMSProvenanceAddRETRIEVED_AT(builder, RETRIEVED_AT)
        if self.LICENSE is not None:
            TMSProvenanceAddLICENSE(builder, LICENSE)
        if self.LICENSE_URL is not None:
            TMSProvenanceAddLICENSE_URL(builder, LICENSE_URL)
        if self.ATTRIBUTION is not None:
            TMSProvenanceAddATTRIBUTION(builder, ATTRIBUTION)
        TMSProvenanceAddNON_COMMERCIAL_ONLY(builder, self.NON_COMMERCIAL_ONLY)
        TMSProvenanceAddSHARE_ALIKE(builder, self.SHARE_ALIKE)
        if self.NATIVE_ID is not None:
            TMSProvenanceAddNATIVE_ID(builder, NATIVE_ID)
        if self.NATIVE_MODIFIED is not None:
            TMSProvenanceAddNATIVE_MODIFIED(builder, NATIVE_MODIFIED)
        TMSProvenance = TMSProvenanceEnd(builder)
        return TMSProvenance
