// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { launchDetectionType } from './launchDetectionType.js';


/**
 * Launch Detection
 */
export class LND implements flatbuffers.IUnpackableObject<LNDT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LND {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLND(bb:flatbuffers.ByteBuffer, obj?:LND):LND {
  return (obj || new LND()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLND(bb:flatbuffers.ByteBuffer, obj?:LND):LND {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LND()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('$LND');
}

/**
 * Unique identifier
 */
ID():string|null
ID(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
ID(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Detection event identifier
 */
EVENT_ID():string|null
EVENT_ID(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
EVENT_ID(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Detection type
 */
DETECTION_TYPE():launchDetectionType {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : launchDetectionType.IR_DETECT;
}

/**
 * Detection message type code
 */
MESSAGE_TYPE():string|null
MESSAGE_TYPE(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
MESSAGE_TYPE(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Time of launch detection (ISO 8601)
 */
LAUNCH_TIME():string|null
LAUNCH_TIME(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
LAUNCH_TIME(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Launch site latitude (degrees)
 */
LAUNCH_LATITUDE():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

/**
 * Launch site longitude (degrees)
 */
LAUNCH_LONGITUDE():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

/**
 * Launch azimuth (degrees from north)
 */
LAUNCH_AZIMUTH():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

/**
 * Estimated RAAN (degrees)
 */
RAAN():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

/**
 * Estimated inclination (degrees)
 */
INCLINATION():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

/**
 * Time of trajectory observation (ISO 8601)
 */
OBSERVATION_TIME():string|null
OBSERVATION_TIME(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
OBSERVATION_TIME(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Observation point latitude (degrees)
 */
OBSERVATION_LATITUDE():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

/**
 * Observation point longitude (degrees)
 */
OBSERVATION_LONGITUDE():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

/**
 * Observation point altitude (km)
 */
OBSERVATION_ALTITUDE():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

/**
 * True if stereo observation (multiple sensors)
 */
STEREO_FLAG():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * True if high zenith angle observation
 */
HIGH_ZENITH_AZIMUTH():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * Sequence number in detection chain
 */
SEQUENCE_NUMBER():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

/**
 * Launch site identifier
 */
LAUNCH_SITE_ID():string|null
LAUNCH_SITE_ID(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
LAUNCH_SITE_ID(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Launch vehicle type (if identified)
 */
LAUNCH_VEHICLE():string|null
LAUNCH_VEHICLE(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
LAUNCH_VEHICLE(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Estimated trajectory type
 */
TRAJECTORY_TYPE():string|null
TRAJECTORY_TYPE(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
TRAJECTORY_TYPE(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Detection confidence (0-1)
 */
CONFIDENCE():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

/**
 * Event descriptor
 */
DESCRIPTOR():string|null
DESCRIPTOR(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
DESCRIPTOR(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Associated tags
 */
TAGS(index: number):string
TAGS(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
TAGS(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

tagsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startLND(builder:flatbuffers.Builder) {
  builder.startObject(23);
}

static addId(builder:flatbuffers.Builder, IDOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, IDOffset, 0);
}

static addEventId(builder:flatbuffers.Builder, EVENT_IDOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, EVENT_IDOffset, 0);
}

static addDetectionType(builder:flatbuffers.Builder, DETECTION_TYPE:launchDetectionType) {
  builder.addFieldInt8(2, DETECTION_TYPE, launchDetectionType.IR_DETECT);
}

static addMessageType(builder:flatbuffers.Builder, MESSAGE_TYPEOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, MESSAGE_TYPEOffset, 0);
}

static addLaunchTime(builder:flatbuffers.Builder, LAUNCH_TIMEOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, LAUNCH_TIMEOffset, 0);
}

static addLaunchLatitude(builder:flatbuffers.Builder, LAUNCH_LATITUDE:number) {
  builder.addFieldFloat64(5, LAUNCH_LATITUDE, 0.0);
}

static addLaunchLongitude(builder:flatbuffers.Builder, LAUNCH_LONGITUDE:number) {
  builder.addFieldFloat64(6, LAUNCH_LONGITUDE, 0.0);
}

static addLaunchAzimuth(builder:flatbuffers.Builder, LAUNCH_AZIMUTH:number) {
  builder.addFieldFloat64(7, LAUNCH_AZIMUTH, 0.0);
}

static addRaan(builder:flatbuffers.Builder, RAAN:number) {
  builder.addFieldFloat64(8, RAAN, 0.0);
}

static addInclination(builder:flatbuffers.Builder, INCLINATION:number) {
  builder.addFieldFloat64(9, INCLINATION, 0.0);
}

static addObservationTime(builder:flatbuffers.Builder, OBSERVATION_TIMEOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, OBSERVATION_TIMEOffset, 0);
}

static addObservationLatitude(builder:flatbuffers.Builder, OBSERVATION_LATITUDE:number) {
  builder.addFieldFloat64(11, OBSERVATION_LATITUDE, 0.0);
}

static addObservationLongitude(builder:flatbuffers.Builder, OBSERVATION_LONGITUDE:number) {
  builder.addFieldFloat64(12, OBSERVATION_LONGITUDE, 0.0);
}

static addObservationAltitude(builder:flatbuffers.Builder, OBSERVATION_ALTITUDE:number) {
  builder.addFieldFloat64(13, OBSERVATION_ALTITUDE, 0.0);
}

static addStereoFlag(builder:flatbuffers.Builder, STEREO_FLAG:boolean) {
  builder.addFieldInt8(14, +STEREO_FLAG, +false);
}

static addHighZenithAzimuth(builder:flatbuffers.Builder, HIGH_ZENITH_AZIMUTH:boolean) {
  builder.addFieldInt8(15, +HIGH_ZENITH_AZIMUTH, +false);
}

static addSequenceNumber(builder:flatbuffers.Builder, SEQUENCE_NUMBER:number) {
  builder.addFieldInt16(16, SEQUENCE_NUMBER, 0);
}

static addLaunchSiteId(builder:flatbuffers.Builder, LAUNCH_SITE_IDOffset:flatbuffers.Offset) {
  builder.addFieldOffset(17, LAUNCH_SITE_IDOffset, 0);
}

static addLaunchVehicle(builder:flatbuffers.Builder, LAUNCH_VEHICLEOffset:flatbuffers.Offset) {
  builder.addFieldOffset(18, LAUNCH_VEHICLEOffset, 0);
}

static addTrajectoryType(builder:flatbuffers.Builder, TRAJECTORY_TYPEOffset:flatbuffers.Offset) {
  builder.addFieldOffset(19, TRAJECTORY_TYPEOffset, 0);
}

static addConfidence(builder:flatbuffers.Builder, CONFIDENCE:number) {
  builder.addFieldFloat64(20, CONFIDENCE, 0.0);
}

static addDescriptor(builder:flatbuffers.Builder, DESCRIPTOROffset:flatbuffers.Offset) {
  builder.addFieldOffset(21, DESCRIPTOROffset, 0);
}

static addTags(builder:flatbuffers.Builder, TAGSOffset:flatbuffers.Offset) {
  builder.addFieldOffset(22, TAGSOffset, 0);
}

static createTagsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTagsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endLND(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishLNDBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, '$LND');
}

static finishSizePrefixedLNDBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, '$LND', true);
}

static createLND(builder:flatbuffers.Builder, IDOffset:flatbuffers.Offset, EVENT_IDOffset:flatbuffers.Offset, DETECTION_TYPE:launchDetectionType, MESSAGE_TYPEOffset:flatbuffers.Offset, LAUNCH_TIMEOffset:flatbuffers.Offset, LAUNCH_LATITUDE:number, LAUNCH_LONGITUDE:number, LAUNCH_AZIMUTH:number, RAAN:number, INCLINATION:number, OBSERVATION_TIMEOffset:flatbuffers.Offset, OBSERVATION_LATITUDE:number, OBSERVATION_LONGITUDE:number, OBSERVATION_ALTITUDE:number, STEREO_FLAG:boolean, HIGH_ZENITH_AZIMUTH:boolean, SEQUENCE_NUMBER:number, LAUNCH_SITE_IDOffset:flatbuffers.Offset, LAUNCH_VEHICLEOffset:flatbuffers.Offset, TRAJECTORY_TYPEOffset:flatbuffers.Offset, CONFIDENCE:number, DESCRIPTOROffset:flatbuffers.Offset, TAGSOffset:flatbuffers.Offset):flatbuffers.Offset {
  LND.startLND(builder);
  LND.addId(builder, IDOffset);
  LND.addEventId(builder, EVENT_IDOffset);
  LND.addDetectionType(builder, DETECTION_TYPE);
  LND.addMessageType(builder, MESSAGE_TYPEOffset);
  LND.addLaunchTime(builder, LAUNCH_TIMEOffset);
  LND.addLaunchLatitude(builder, LAUNCH_LATITUDE);
  LND.addLaunchLongitude(builder, LAUNCH_LONGITUDE);
  LND.addLaunchAzimuth(builder, LAUNCH_AZIMUTH);
  LND.addRaan(builder, RAAN);
  LND.addInclination(builder, INCLINATION);
  LND.addObservationTime(builder, OBSERVATION_TIMEOffset);
  LND.addObservationLatitude(builder, OBSERVATION_LATITUDE);
  LND.addObservationLongitude(builder, OBSERVATION_LONGITUDE);
  LND.addObservationAltitude(builder, OBSERVATION_ALTITUDE);
  LND.addStereoFlag(builder, STEREO_FLAG);
  LND.addHighZenithAzimuth(builder, HIGH_ZENITH_AZIMUTH);
  LND.addSequenceNumber(builder, SEQUENCE_NUMBER);
  LND.addLaunchSiteId(builder, LAUNCH_SITE_IDOffset);
  LND.addLaunchVehicle(builder, LAUNCH_VEHICLEOffset);
  LND.addTrajectoryType(builder, TRAJECTORY_TYPEOffset);
  LND.addConfidence(builder, CONFIDENCE);
  LND.addDescriptor(builder, DESCRIPTOROffset);
  LND.addTags(builder, TAGSOffset);
  return LND.endLND(builder);
}

unpack(): LNDT {
  return new LNDT(
    this.ID(),
    this.EVENT_ID(),
    this.DETECTION_TYPE(),
    this.MESSAGE_TYPE(),
    this.LAUNCH_TIME(),
    this.LAUNCH_LATITUDE(),
    this.LAUNCH_LONGITUDE(),
    this.LAUNCH_AZIMUTH(),
    this.RAAN(),
    this.INCLINATION(),
    this.OBSERVATION_TIME(),
    this.OBSERVATION_LATITUDE(),
    this.OBSERVATION_LONGITUDE(),
    this.OBSERVATION_ALTITUDE(),
    this.STEREO_FLAG(),
    this.HIGH_ZENITH_AZIMUTH(),
    this.SEQUENCE_NUMBER(),
    this.LAUNCH_SITE_ID(),
    this.LAUNCH_VEHICLE(),
    this.TRAJECTORY_TYPE(),
    this.CONFIDENCE(),
    this.DESCRIPTOR(),
    this.bb!.createScalarList<string>(this.TAGS.bind(this), this.tagsLength())
  );
}


unpackTo(_o: LNDT): void {
  _o.ID = this.ID();
  _o.EVENT_ID = this.EVENT_ID();
  _o.DETECTION_TYPE = this.DETECTION_TYPE();
  _o.MESSAGE_TYPE = this.MESSAGE_TYPE();
  _o.LAUNCH_TIME = this.LAUNCH_TIME();
  _o.LAUNCH_LATITUDE = this.LAUNCH_LATITUDE();
  _o.LAUNCH_LONGITUDE = this.LAUNCH_LONGITUDE();
  _o.LAUNCH_AZIMUTH = this.LAUNCH_AZIMUTH();
  _o.RAAN = this.RAAN();
  _o.INCLINATION = this.INCLINATION();
  _o.OBSERVATION_TIME = this.OBSERVATION_TIME();
  _o.OBSERVATION_LATITUDE = this.OBSERVATION_LATITUDE();
  _o.OBSERVATION_LONGITUDE = this.OBSERVATION_LONGITUDE();
  _o.OBSERVATION_ALTITUDE = this.OBSERVATION_ALTITUDE();
  _o.STEREO_FLAG = this.STEREO_FLAG();
  _o.HIGH_ZENITH_AZIMUTH = this.HIGH_ZENITH_AZIMUTH();
  _o.SEQUENCE_NUMBER = this.SEQUENCE_NUMBER();
  _o.LAUNCH_SITE_ID = this.LAUNCH_SITE_ID();
  _o.LAUNCH_VEHICLE = this.LAUNCH_VEHICLE();
  _o.TRAJECTORY_TYPE = this.TRAJECTORY_TYPE();
  _o.CONFIDENCE = this.CONFIDENCE();
  _o.DESCRIPTOR = this.DESCRIPTOR();
  _o.TAGS = this.bb!.createScalarList<string>(this.TAGS.bind(this), this.tagsLength());
}
}

export class LNDT implements flatbuffers.IGeneratedObject {
constructor(
  public ID: string|Uint8Array|null = null,
  public EVENT_ID: string|Uint8Array|null = null,
  public DETECTION_TYPE: launchDetectionType = launchDetectionType.IR_DETECT,
  public MESSAGE_TYPE: string|Uint8Array|null = null,
  public LAUNCH_TIME: string|Uint8Array|null = null,
  public LAUNCH_LATITUDE: number = 0.0,
  public LAUNCH_LONGITUDE: number = 0.0,
  public LAUNCH_AZIMUTH: number = 0.0,
  public RAAN: number = 0.0,
  public INCLINATION: number = 0.0,
  public OBSERVATION_TIME: string|Uint8Array|null = null,
  public OBSERVATION_LATITUDE: number = 0.0,
  public OBSERVATION_LONGITUDE: number = 0.0,
  public OBSERVATION_ALTITUDE: number = 0.0,
  public STEREO_FLAG: boolean = false,
  public HIGH_ZENITH_AZIMUTH: boolean = false,
  public SEQUENCE_NUMBER: number = 0,
  public LAUNCH_SITE_ID: string|Uint8Array|null = null,
  public LAUNCH_VEHICLE: string|Uint8Array|null = null,
  public TRAJECTORY_TYPE: string|Uint8Array|null = null,
  public CONFIDENCE: number = 0.0,
  public DESCRIPTOR: string|Uint8Array|null = null,
  public TAGS: (string)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const ID = (this.ID !== null ? builder.createString(this.ID!) : 0);
  const EVENT_ID = (this.EVENT_ID !== null ? builder.createString(this.EVENT_ID!) : 0);
  const MESSAGE_TYPE = (this.MESSAGE_TYPE !== null ? builder.createString(this.MESSAGE_TYPE!) : 0);
  const LAUNCH_TIME = (this.LAUNCH_TIME !== null ? builder.createString(this.LAUNCH_TIME!) : 0);
  const OBSERVATION_TIME = (this.OBSERVATION_TIME !== null ? builder.createString(this.OBSERVATION_TIME!) : 0);
  const LAUNCH_SITE_ID = (this.LAUNCH_SITE_ID !== null ? builder.createString(this.LAUNCH_SITE_ID!) : 0);
  const LAUNCH_VEHICLE = (this.LAUNCH_VEHICLE !== null ? builder.createString(this.LAUNCH_VEHICLE!) : 0);
  const TRAJECTORY_TYPE = (this.TRAJECTORY_TYPE !== null ? builder.createString(this.TRAJECTORY_TYPE!) : 0);
  const DESCRIPTOR = (this.DESCRIPTOR !== null ? builder.createString(this.DESCRIPTOR!) : 0);
  const TAGS = LND.createTagsVector(builder, builder.createObjectOffsetList(this.TAGS));

  return LND.createLND(builder,
    ID,
    EVENT_ID,
    this.DETECTION_TYPE,
    MESSAGE_TYPE,
    LAUNCH_TIME,
    this.LAUNCH_LATITUDE,
    this.LAUNCH_LONGITUDE,
    this.LAUNCH_AZIMUTH,
    this.RAAN,
    this.INCLINATION,
    OBSERVATION_TIME,
    this.OBSERVATION_LATITUDE,
    this.OBSERVATION_LONGITUDE,
    this.OBSERVATION_ALTITUDE,
    this.STEREO_FLAG,
    this.HIGH_ZENITH_AZIMUTH,
    this.SEQUENCE_NUMBER,
    LAUNCH_SITE_ID,
    LAUNCH_VEHICLE,
    TRAJECTORY_TYPE,
    this.CONFIDENCE,
    DESCRIPTOR,
    TAGS
  );
}
}
