// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ACL

import "strconv"

/// Grant lifecycle status tracked by the provider.
type grantLifecycleStatus int8

const (
	grantLifecycleStatusActive    grantLifecycleStatus = 0
	grantLifecycleStatusRevoked   grantLifecycleStatus = 1
	grantLifecycleStatusExpired   grantLifecycleStatus = 2
	grantLifecycleStatusSuspended grantLifecycleStatus = 3
	grantLifecycleStatusPending   grantLifecycleStatus = 4
)

var EnumNamesgrantLifecycleStatus = map[grantLifecycleStatus]string{
	grantLifecycleStatusActive:    "Active",
	grantLifecycleStatusRevoked:   "Revoked",
	grantLifecycleStatusExpired:   "Expired",
	grantLifecycleStatusSuspended: "Suspended",
	grantLifecycleStatusPending:   "Pending",
}

var EnumValuesgrantLifecycleStatus = map[string]grantLifecycleStatus{
	"Active":    grantLifecycleStatusActive,
	"Revoked":   grantLifecycleStatusRevoked,
	"Expired":   grantLifecycleStatusExpired,
	"Suspended": grantLifecycleStatusSuspended,
	"Pending":   grantLifecycleStatusPending,
}

func (v grantLifecycleStatus) String() string {
	if s, ok := EnumNamesgrantLifecycleStatus[v]; ok {
		return s
	}
	return "grantLifecycleStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
