// automatically generated by the FlatBuffers compiler, do not modify
// @generated

use crate::main_generated::*;
use crate::main_generated::*;
use crate::main_generated::*;
extern crate alloc;

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_PMM_TRUST_TIER: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_PMM_TRUST_TIER: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PMM_TRUST_TIER: [pmmTrustTier; 4] = [
  pmmTrustTier::UNSPECIFIED,
  pmmTrustTier::CORE,
  pmmTrustTier::RECOMMENDED,
  pmmTrustTier::OPTIONAL,
];

/// Provider-declared standing of a module in its own offering. Append new
/// values only; never reorder or reuse existing values.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct pmmTrustTier(pub u8);
#[allow(non_upper_case_globals)]
impl pmmTrustTier {
  /// Not stated. Treated as OPTIONAL by verifiers.
  pub const UNSPECIFIED: Self = Self(0);
  /// The provider declares this module part of its baseline service. Only a
  /// CORE entry may ever be loaded before a user session exists, and only a
  /// CORE entry is presented pre-selected at first sign-in.
  pub const CORE: Self = Self(1);
  /// Offered and endorsed by the provider, but never loaded without an
  /// explicit user selection.
  pub const RECOMMENDED: Self = Self(2);
  /// Offered only.
  pub const OPTIONAL: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::UNSPECIFIED,
    Self::CORE,
    Self::RECOMMENDED,
    Self::OPTIONAL,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::UNSPECIFIED => Some("UNSPECIFIED"),
      Self::CORE => Some("CORE"),
      Self::RECOMMENDED => Some("RECOMMENDED"),
      Self::OPTIONAL => Some("OPTIONAL"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for pmmTrustTier {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for pmmTrustTier {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for pmmTrustTier {
    type Output = pmmTrustTier;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for pmmTrustTier {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for pmmTrustTier {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for pmmTrustTier {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_PMM_ACCESS_POLICY: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_PMM_ACCESS_POLICY: u8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PMM_ACCESS_POLICY: [pmmAccessPolicy; 3] = [
  pmmAccessPolicy::ANONYMOUS,
  pmmAccessPolicy::AUTHENTICATED,
  pmmAccessPolicy::ENTITLED,
];

/// What a client must hold before the artifact may be fetched and
/// instantiated. Append new values only; never reorder or reuse existing
/// values.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct pmmAccessPolicy(pub u8);
#[allow(non_upper_case_globals)]
impl pmmAccessPolicy {
  /// No session, no grant: an unauthenticated client may fetch and run it.
  pub const ANONYMOUS: Self = Self(0);
  /// An authenticated session is required.
  pub const AUTHENTICATED: Self = Self(1);
  /// An entitlement or license grant is required (see `$ENT`, `$PLK`).
  pub const ENTITLED: Self = Self(2);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::ANONYMOUS,
    Self::AUTHENTICATED,
    Self::ENTITLED,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::ANONYMOUS => Some("ANONYMOUS"),
      Self::AUTHENTICATED => Some("AUTHENTICATED"),
      Self::ENTITLED => Some("ENTITLED"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for pmmAccessPolicy {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for pmmAccessPolicy {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for pmmAccessPolicy {
    type Output = pmmAccessPolicy;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for pmmAccessPolicy {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for pmmAccessPolicy {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for pmmAccessPolicy {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_PMM_ENTRY_STATE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_PMM_ENTRY_STATE: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PMM_ENTRY_STATE: [pmmEntryState; 4] = [
  pmmEntryState::ACTIVE,
  pmmEntryState::DEPRECATED,
  pmmEntryState::WITHDRAWN,
  pmmEntryState::REVOKED,
];

/// Lifecycle of one manifest entry. Append new values only; never reorder or
/// reuse existing values.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct pmmEntryState(pub u8);
#[allow(non_upper_case_globals)]
impl pmmEntryState {
  /// Served and loadable.
  pub const ACTIVE: Self = Self(0);
  /// Still served, superseded by another entry. Clients SHOULD migrate.
  pub const DEPRECATED: Self = Self(1);
  /// No longer served. Clients MUST NOT fetch it.
  pub const WITHDRAWN: Self = Self(2);
  /// Actively distrusted by the provider (compromise, bad build). Clients
  /// MUST refuse this CONTENT_HASH even if they already hold the bytes.
  pub const REVOKED: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::ACTIVE,
    Self::DEPRECATED,
    Self::WITHDRAWN,
    Self::REVOKED,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::ACTIVE => Some("ACTIVE"),
      Self::DEPRECATED => Some("DEPRECATED"),
      Self::WITHDRAWN => Some("WITHDRAWN"),
      Self::REVOKED => Some("REVOKED"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for pmmEntryState {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for pmmEntryState {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for pmmEntryState {
    type Output = pmmEntryState;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for pmmEntryState {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for pmmEntryState {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for pmmEntryState {}
pub enum PMMTrustAnchorOffset {}
#[derive(Copy, Clone, PartialEq)]

/// The single key identity every signature in this manifest resolves to, and
/// the two external anchors that give that key its weight: the DNS proof that
/// binds it to the domain, and the Adversarial-Security bond that prices
/// trust in it.
pub struct PMMTrustAnchor<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PMMTrustAnchor<'a> {
  type Inner = PMMTrustAnchor<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PMMTrustAnchor<'a> {
  pub const VT_PROVIDER_DOMAIN: ::flatbuffers::VOffsetT = 4;
  pub const VT_NODE_PEER_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_NODE_XPUB: ::flatbuffers::VOffsetT = 8;
  pub const VT_SIGNING_PUBLIC_KEY: ::flatbuffers::VOffsetT = 10;
  pub const VT_SIGNING_KEY_PATH: ::flatbuffers::VOffsetT = 12;
  pub const VT_SIGNATURE_ALGORITHM: ::flatbuffers::VOffsetT = 14;
  pub const VT_EPM_CID: ::flatbuffers::VOffsetT = 16;
  pub const VT_DNS_PROOF_RECORD_NAME: ::flatbuffers::VOffsetT = 18;
  pub const VT_DNS_PROOF_TXT: ::flatbuffers::VOffsetT = 20;
  pub const VT_DNS_PROOF_STATEMENT: ::flatbuffers::VOffsetT = 22;
  pub const VT_BOND_ADDRESSES: ::flatbuffers::VOffsetT = 24;
  pub const VT_BOND_ATTESTATION_URL: ::flatbuffers::VOffsetT = 26;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PMMTrustAnchor { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PMMTrustAnchorArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PMMTrustAnchor<'bldr>> {
    let mut builder = PMMTrustAnchorBuilder::new(_fbb);
    if let Some(x) = args.BOND_ATTESTATION_URL { builder.add_BOND_ATTESTATION_URL(x); }
    if let Some(x) = args.BOND_ADDRESSES { builder.add_BOND_ADDRESSES(x); }
    if let Some(x) = args.DNS_PROOF_STATEMENT { builder.add_DNS_PROOF_STATEMENT(x); }
    if let Some(x) = args.DNS_PROOF_TXT { builder.add_DNS_PROOF_TXT(x); }
    if let Some(x) = args.DNS_PROOF_RECORD_NAME { builder.add_DNS_PROOF_RECORD_NAME(x); }
    if let Some(x) = args.EPM_CID { builder.add_EPM_CID(x); }
    if let Some(x) = args.SIGNATURE_ALGORITHM { builder.add_SIGNATURE_ALGORITHM(x); }
    if let Some(x) = args.SIGNING_KEY_PATH { builder.add_SIGNING_KEY_PATH(x); }
    if let Some(x) = args.SIGNING_PUBLIC_KEY { builder.add_SIGNING_PUBLIC_KEY(x); }
    if let Some(x) = args.NODE_XPUB { builder.add_NODE_XPUB(x); }
    if let Some(x) = args.NODE_PEER_ID { builder.add_NODE_PEER_ID(x); }
    if let Some(x) = args.PROVIDER_DOMAIN { builder.add_PROVIDER_DOMAIN(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> PMMTrustAnchorT {
    let PROVIDER_DOMAIN = self.PROVIDER_DOMAIN().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let NODE_PEER_ID = self.NODE_PEER_ID().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let NODE_XPUB = self.NODE_XPUB().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let SIGNING_PUBLIC_KEY = self.SIGNING_PUBLIC_KEY().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let SIGNING_KEY_PATH = self.SIGNING_KEY_PATH().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let SIGNATURE_ALGORITHM = self.SIGNATURE_ALGORITHM().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let EPM_CID = self.EPM_CID().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let DNS_PROOF_RECORD_NAME = self.DNS_PROOF_RECORD_NAME().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let DNS_PROOF_TXT = self.DNS_PROOF_TXT().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let DNS_PROOF_STATEMENT = self.DNS_PROOF_STATEMENT().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let BOND_ADDRESSES = self.BOND_ADDRESSES().map(|x| {
      x.iter().map(|t| t.unpack()).collect()
    });
    let BOND_ATTESTATION_URL = self.BOND_ATTESTATION_URL().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    PMMTrustAnchorT {
      PROVIDER_DOMAIN,
      NODE_PEER_ID,
      NODE_XPUB,
      SIGNING_PUBLIC_KEY,
      SIGNING_KEY_PATH,
      SIGNATURE_ALGORITHM,
      EPM_CID,
      DNS_PROOF_RECORD_NAME,
      DNS_PROOF_TXT,
      DNS_PROOF_STATEMENT,
      BOND_ADDRESSES,
      BOND_ATTESTATION_URL,
    }
  }

  /// Domain the node key is bound to. MUST equal `PMM.PROVIDER_DOMAIN` and
  /// MUST equal the origin the manifest was fetched from.
  #[inline]
  pub fn PROVIDER_DOMAIN(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_PROVIDER_DOMAIN, None)}
  }
  /// libp2p peer id of the provider node.
  #[inline]
  pub fn NODE_PEER_ID(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_NODE_PEER_ID, None)}
  }
  /// BIP-32 account xpub of the node identity, verbatim as advertised in the
  /// node's `$EPM`.
  #[inline]
  pub fn NODE_XPUB(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_NODE_XPUB, None)}
  }
  /// Hex-encoded public key that verifies `PMM.SIGNATURE` and every
  /// `PMMModuleEntry.ARTIFACT_SIGNATURE`, derived from the node key.
  #[inline]
  pub fn SIGNING_PUBLIC_KEY(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_SIGNING_PUBLIC_KEY, None)}
  }
  /// HD derivation path of `SIGNING_PUBLIC_KEY` under `NODE_XPUB`.
  #[inline]
  pub fn SIGNING_KEY_PATH(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_SIGNING_KEY_PATH, None)}
  }
  /// Signature algorithm identifier, e.g. "ed25519",
  /// "secp256k1-compact-ethereum". Empty means "ed25519".
  #[inline]
  pub fn SIGNATURE_ALGORITHM(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_SIGNATURE_ALGORITHM, None)}
  }
  /// IPFS CID of the provider node's `$EPM`.
  #[inline]
  pub fn EPM_CID(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_EPM_CID, None)}
  }
  /// Fully-qualified DNS name of the TXT record carrying the signed
  /// domain-to-nodekey proof, e.g. "_sdnkey.example.org". A verifying client
  /// resolves this itself (DNS-over-HTTPS) rather than trusting the copy
  /// below.
  #[inline]
  pub fn DNS_PROOF_RECORD_NAME(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_DNS_PROOF_RECORD_NAME, None)}
  }
  /// Verbatim TXT value of that proof, carried only so a client can detect
  /// disagreement with what DNS returns. The resolved record always wins.
  #[inline]
  pub fn DNS_PROOF_TXT(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_DNS_PROOF_TXT, None)}
  }
  /// The canonical statement the DNS proof signs, verbatim, when the proof
  /// format keeps it out of the TXT value.
  #[inline]
  pub fn DNS_PROOF_STATEMENT(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_DNS_PROOF_STATEMENT, None)}
  }
  /// Chain addresses derived from this same node key that hold the provider's
  /// Adversarial-Security bond. Each entry proves, through `ChainProof`, that
  /// the address derives from the key that signed this manifest.
  #[inline]
  pub fn BOND_ADDRESSES(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ChainProof<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ChainProof>>>>(PMMTrustAnchor::VT_BOND_ADDRESSES, None)}
  }
  /// Optional URL of a machine-readable bond attestation (bonded value,
  /// duration unspent) for clients that price trust rather than gate on it.
  #[inline]
  pub fn BOND_ATTESTATION_URL(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMTrustAnchor::VT_BOND_ATTESTATION_URL, None)}
  }
}

impl ::flatbuffers::Verifiable for PMMTrustAnchor<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("PROVIDER_DOMAIN", Self::VT_PROVIDER_DOMAIN, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("NODE_PEER_ID", Self::VT_NODE_PEER_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("NODE_XPUB", Self::VT_NODE_XPUB, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("SIGNING_PUBLIC_KEY", Self::VT_SIGNING_PUBLIC_KEY, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("SIGNING_KEY_PATH", Self::VT_SIGNING_KEY_PATH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("SIGNATURE_ALGORITHM", Self::VT_SIGNATURE_ALGORITHM, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("EPM_CID", Self::VT_EPM_CID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("DNS_PROOF_RECORD_NAME", Self::VT_DNS_PROOF_RECORD_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("DNS_PROOF_TXT", Self::VT_DNS_PROOF_TXT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("DNS_PROOF_STATEMENT", Self::VT_DNS_PROOF_STATEMENT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<ChainProof>>>>("BOND_ADDRESSES", Self::VT_BOND_ADDRESSES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("BOND_ATTESTATION_URL", Self::VT_BOND_ATTESTATION_URL, false)?
     .finish();
    Ok(())
  }
}
pub struct PMMTrustAnchorArgs<'a> {
    pub PROVIDER_DOMAIN: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub NODE_PEER_ID: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub NODE_XPUB: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub SIGNING_PUBLIC_KEY: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub SIGNING_KEY_PATH: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub SIGNATURE_ALGORITHM: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub EPM_CID: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub DNS_PROOF_RECORD_NAME: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub DNS_PROOF_TXT: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub DNS_PROOF_STATEMENT: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub BOND_ADDRESSES: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<ChainProof<'a>>>>>,
    pub BOND_ATTESTATION_URL: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PMMTrustAnchorArgs<'a> {
  #[inline]
  fn default() -> Self {
    PMMTrustAnchorArgs {
      PROVIDER_DOMAIN: None,
      NODE_PEER_ID: None,
      NODE_XPUB: None,
      SIGNING_PUBLIC_KEY: None,
      SIGNING_KEY_PATH: None,
      SIGNATURE_ALGORITHM: None,
      EPM_CID: None,
      DNS_PROOF_RECORD_NAME: None,
      DNS_PROOF_TXT: None,
      DNS_PROOF_STATEMENT: None,
      BOND_ADDRESSES: None,
      BOND_ATTESTATION_URL: None,
    }
  }
}

pub struct PMMTrustAnchorBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PMMTrustAnchorBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_PROVIDER_DOMAIN(&mut self, PROVIDER_DOMAIN: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_PROVIDER_DOMAIN, PROVIDER_DOMAIN);
  }
  #[inline]
  pub fn add_NODE_PEER_ID(&mut self, NODE_PEER_ID: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_NODE_PEER_ID, NODE_PEER_ID);
  }
  #[inline]
  pub fn add_NODE_XPUB(&mut self, NODE_XPUB: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_NODE_XPUB, NODE_XPUB);
  }
  #[inline]
  pub fn add_SIGNING_PUBLIC_KEY(&mut self, SIGNING_PUBLIC_KEY: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_SIGNING_PUBLIC_KEY, SIGNING_PUBLIC_KEY);
  }
  #[inline]
  pub fn add_SIGNING_KEY_PATH(&mut self, SIGNING_KEY_PATH: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_SIGNING_KEY_PATH, SIGNING_KEY_PATH);
  }
  #[inline]
  pub fn add_SIGNATURE_ALGORITHM(&mut self, SIGNATURE_ALGORITHM: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_SIGNATURE_ALGORITHM, SIGNATURE_ALGORITHM);
  }
  #[inline]
  pub fn add_EPM_CID(&mut self, EPM_CID: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_EPM_CID, EPM_CID);
  }
  #[inline]
  pub fn add_DNS_PROOF_RECORD_NAME(&mut self, DNS_PROOF_RECORD_NAME: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_DNS_PROOF_RECORD_NAME, DNS_PROOF_RECORD_NAME);
  }
  #[inline]
  pub fn add_DNS_PROOF_TXT(&mut self, DNS_PROOF_TXT: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_DNS_PROOF_TXT, DNS_PROOF_TXT);
  }
  #[inline]
  pub fn add_DNS_PROOF_STATEMENT(&mut self, DNS_PROOF_STATEMENT: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_DNS_PROOF_STATEMENT, DNS_PROOF_STATEMENT);
  }
  #[inline]
  pub fn add_BOND_ADDRESSES(&mut self, BOND_ADDRESSES: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<ChainProof<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_BOND_ADDRESSES, BOND_ADDRESSES);
  }
  #[inline]
  pub fn add_BOND_ATTESTATION_URL(&mut self, BOND_ATTESTATION_URL: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMTrustAnchor::VT_BOND_ATTESTATION_URL, BOND_ATTESTATION_URL);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PMMTrustAnchorBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PMMTrustAnchorBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PMMTrustAnchor<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PMMTrustAnchor<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PMMTrustAnchor");
      ds.field("PROVIDER_DOMAIN", &self.PROVIDER_DOMAIN());
      ds.field("NODE_PEER_ID", &self.NODE_PEER_ID());
      ds.field("NODE_XPUB", &self.NODE_XPUB());
      ds.field("SIGNING_PUBLIC_KEY", &self.SIGNING_PUBLIC_KEY());
      ds.field("SIGNING_KEY_PATH", &self.SIGNING_KEY_PATH());
      ds.field("SIGNATURE_ALGORITHM", &self.SIGNATURE_ALGORITHM());
      ds.field("EPM_CID", &self.EPM_CID());
      ds.field("DNS_PROOF_RECORD_NAME", &self.DNS_PROOF_RECORD_NAME());
      ds.field("DNS_PROOF_TXT", &self.DNS_PROOF_TXT());
      ds.field("DNS_PROOF_STATEMENT", &self.DNS_PROOF_STATEMENT());
      ds.field("BOND_ADDRESSES", &self.BOND_ADDRESSES());
      ds.field("BOND_ATTESTATION_URL", &self.BOND_ATTESTATION_URL());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct PMMTrustAnchorT {
  pub PROVIDER_DOMAIN: Option<alloc::string::String>,
  pub NODE_PEER_ID: Option<alloc::string::String>,
  pub NODE_XPUB: Option<alloc::string::String>,
  pub SIGNING_PUBLIC_KEY: Option<alloc::string::String>,
  pub SIGNING_KEY_PATH: Option<alloc::string::String>,
  pub SIGNATURE_ALGORITHM: Option<alloc::string::String>,
  pub EPM_CID: Option<alloc::string::String>,
  pub DNS_PROOF_RECORD_NAME: Option<alloc::string::String>,
  pub DNS_PROOF_TXT: Option<alloc::string::String>,
  pub DNS_PROOF_STATEMENT: Option<alloc::string::String>,
  pub BOND_ADDRESSES: Option<alloc::vec::Vec<ChainProofT>>,
  pub BOND_ATTESTATION_URL: Option<alloc::string::String>,
}
impl Default for PMMTrustAnchorT {
  fn default() -> Self {
    Self {
      PROVIDER_DOMAIN: None,
      NODE_PEER_ID: None,
      NODE_XPUB: None,
      SIGNING_PUBLIC_KEY: None,
      SIGNING_KEY_PATH: None,
      SIGNATURE_ALGORITHM: None,
      EPM_CID: None,
      DNS_PROOF_RECORD_NAME: None,
      DNS_PROOF_TXT: None,
      DNS_PROOF_STATEMENT: None,
      BOND_ADDRESSES: None,
      BOND_ATTESTATION_URL: None,
    }
  }
}
impl PMMTrustAnchorT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<PMMTrustAnchor<'b>> {
    let PROVIDER_DOMAIN = self.PROVIDER_DOMAIN.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let NODE_PEER_ID = self.NODE_PEER_ID.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let NODE_XPUB = self.NODE_XPUB.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let SIGNING_PUBLIC_KEY = self.SIGNING_PUBLIC_KEY.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let SIGNING_KEY_PATH = self.SIGNING_KEY_PATH.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let SIGNATURE_ALGORITHM = self.SIGNATURE_ALGORITHM.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let EPM_CID = self.EPM_CID.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let DNS_PROOF_RECORD_NAME = self.DNS_PROOF_RECORD_NAME.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let DNS_PROOF_TXT = self.DNS_PROOF_TXT.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let DNS_PROOF_STATEMENT = self.DNS_PROOF_STATEMENT.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let BOND_ADDRESSES = self.BOND_ADDRESSES.as_ref().map(|x|{
      let w: alloc::vec::Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();_fbb.create_vector(&w)
    });
    let BOND_ATTESTATION_URL = self.BOND_ATTESTATION_URL.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    PMMTrustAnchor::create(_fbb, &PMMTrustAnchorArgs{
      PROVIDER_DOMAIN,
      NODE_PEER_ID,
      NODE_XPUB,
      SIGNING_PUBLIC_KEY,
      SIGNING_KEY_PATH,
      SIGNATURE_ALGORITHM,
      EPM_CID,
      DNS_PROOF_RECORD_NAME,
      DNS_PROOF_TXT,
      DNS_PROOF_STATEMENT,
      BOND_ADDRESSES,
      BOND_ATTESTATION_URL,
    })
  }
}
pub enum PMMModuleEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

/// One module the provider offers.
pub struct PMMModuleEntry<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PMMModuleEntry<'a> {
  type Inner = PMMModuleEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PMMModuleEntry<'a> {
  pub const VT_MODULE_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_PLUGIN_ID: ::flatbuffers::VOffsetT = 6;
  pub const VT_PLG_CID: ::flatbuffers::VOffsetT = 8;
  pub const VT_NAME: ::flatbuffers::VOffsetT = 10;
  pub const VT_DESCRIPTION: ::flatbuffers::VOffsetT = 12;
  pub const VT_VERSION: ::flatbuffers::VOffsetT = 14;
  pub const VT_EPOCH: ::flatbuffers::VOffsetT = 16;
  pub const VT_CONTENT_HASH: ::flatbuffers::VOffsetT = 18;
  pub const VT_ARTIFACT_SIZE_BYTES: ::flatbuffers::VOffsetT = 20;
  pub const VT_ARTIFACT_PATH: ::flatbuffers::VOffsetT = 22;
  pub const VT_ARTIFACT_CID: ::flatbuffers::VOffsetT = 24;
  pub const VT_ARTIFACT_SIGNATURE: ::flatbuffers::VOffsetT = 26;
  pub const VT_TRUST_TIER: ::flatbuffers::VOffsetT = 28;
  pub const VT_DEFAULT_ENABLED: ::flatbuffers::VOffsetT = 30;
  pub const VT_ACCESS_POLICY: ::flatbuffers::VOffsetT = 32;
  pub const VT_ENTRY_STATE: ::flatbuffers::VOffsetT = 34;
  pub const VT_RUNTIME_TARGETS: ::flatbuffers::VOffsetT = 36;
  pub const VT_REQUIRED_SCHEMAS: ::flatbuffers::VOffsetT = 38;
  pub const VT_MIN_PERMISSIONS: ::flatbuffers::VOffsetT = 40;
  pub const VT_LICENSE: ::flatbuffers::VOffsetT = 42;
  pub const VT_DOCUMENTATION_URL: ::flatbuffers::VOffsetT = 44;
  pub const VT_ICON_URL: ::flatbuffers::VOffsetT = 46;
  pub const VT_SUPERSEDES_CONTENT_HASH: ::flatbuffers::VOffsetT = 48;
  pub const VT_UPDATED_AT: ::flatbuffers::VOffsetT = 50;
  pub const VT_PLUGIN_TYPE: ::flatbuffers::VOffsetT = 52;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PMMModuleEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PMMModuleEntryArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PMMModuleEntry<'bldr>> {
    let mut builder = PMMModuleEntryBuilder::new(_fbb);
    builder.add_ARTIFACT_SIZE_BYTES(args.ARTIFACT_SIZE_BYTES);
    builder.add_EPOCH(args.EPOCH);
    if let Some(x) = args.UPDATED_AT { builder.add_UPDATED_AT(x); }
    if let Some(x) = args.SUPERSEDES_CONTENT_HASH { builder.add_SUPERSEDES_CONTENT_HASH(x); }
    if let Some(x) = args.ICON_URL { builder.add_ICON_URL(x); }
    if let Some(x) = args.DOCUMENTATION_URL { builder.add_DOCUMENTATION_URL(x); }
    if let Some(x) = args.LICENSE { builder.add_LICENSE(x); }
    if let Some(x) = args.MIN_PERMISSIONS { builder.add_MIN_PERMISSIONS(x); }
    if let Some(x) = args.REQUIRED_SCHEMAS { builder.add_REQUIRED_SCHEMAS(x); }
    if let Some(x) = args.RUNTIME_TARGETS { builder.add_RUNTIME_TARGETS(x); }
    if let Some(x) = args.ARTIFACT_SIGNATURE { builder.add_ARTIFACT_SIGNATURE(x); }
    if let Some(x) = args.ARTIFACT_CID { builder.add_ARTIFACT_CID(x); }
    if let Some(x) = args.ARTIFACT_PATH { builder.add_ARTIFACT_PATH(x); }
    if let Some(x) = args.CONTENT_HASH { builder.add_CONTENT_HASH(x); }
    if let Some(x) = args.VERSION { builder.add_VERSION(x); }
    if let Some(x) = args.DESCRIPTION { builder.add_DESCRIPTION(x); }
    if let Some(x) = args.NAME { builder.add_NAME(x); }
    if let Some(x) = args.PLG_CID { builder.add_PLG_CID(x); }
    if let Some(x) = args.PLUGIN_ID { builder.add_PLUGIN_ID(x); }
    if let Some(x) = args.MODULE_ID { builder.add_MODULE_ID(x); }
    builder.add_PLUGIN_TYPE(args.PLUGIN_TYPE);
    builder.add_ENTRY_STATE(args.ENTRY_STATE);
    builder.add_ACCESS_POLICY(args.ACCESS_POLICY);
    builder.add_DEFAULT_ENABLED(args.DEFAULT_ENABLED);
    builder.add_TRUST_TIER(args.TRUST_TIER);
    builder.finish()
  }

  pub fn unpack(&self) -> PMMModuleEntryT {
    let MODULE_ID = {
      let x = self.MODULE_ID();
      alloc::string::ToString::to_string(x)
    };
    let PLUGIN_ID = self.PLUGIN_ID().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let PLG_CID = self.PLG_CID().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let NAME = self.NAME().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let DESCRIPTION = self.DESCRIPTION().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let VERSION = self.VERSION().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let EPOCH = self.EPOCH();
    let CONTENT_HASH = self.CONTENT_HASH().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let ARTIFACT_SIZE_BYTES = self.ARTIFACT_SIZE_BYTES();
    let ARTIFACT_PATH = self.ARTIFACT_PATH().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let ARTIFACT_CID = self.ARTIFACT_CID().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let ARTIFACT_SIGNATURE = self.ARTIFACT_SIGNATURE().map(|x| {
      x.into_iter().collect()
    });
    let TRUST_TIER = self.TRUST_TIER();
    let DEFAULT_ENABLED = self.DEFAULT_ENABLED();
    let ACCESS_POLICY = self.ACCESS_POLICY();
    let ENTRY_STATE = self.ENTRY_STATE();
    let RUNTIME_TARGETS = self.RUNTIME_TARGETS().map(|x| {
      x.iter().map(|s| alloc::string::ToString::to_string(s)).collect()
    });
    let REQUIRED_SCHEMAS = self.REQUIRED_SCHEMAS().map(|x| {
      x.iter().map(|s| alloc::string::ToString::to_string(s)).collect()
    });
    let MIN_PERMISSIONS = self.MIN_PERMISSIONS().map(|x| {
      x.iter().map(|s| alloc::string::ToString::to_string(s)).collect()
    });
    let LICENSE = self.LICENSE().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let DOCUMENTATION_URL = self.DOCUMENTATION_URL().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let ICON_URL = self.ICON_URL().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let SUPERSEDES_CONTENT_HASH = self.SUPERSEDES_CONTENT_HASH().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let UPDATED_AT = self.UPDATED_AT().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let PLUGIN_TYPE = self.PLUGIN_TYPE();
    PMMModuleEntryT {
      MODULE_ID,
      PLUGIN_ID,
      PLG_CID,
      NAME,
      DESCRIPTION,
      VERSION,
      EPOCH,
      CONTENT_HASH,
      ARTIFACT_SIZE_BYTES,
      ARTIFACT_PATH,
      ARTIFACT_CID,
      ARTIFACT_SIGNATURE,
      TRUST_TIER,
      DEFAULT_ENABLED,
      ACCESS_POLICY,
      ENTRY_STATE,
      RUNTIME_TARGETS,
      REQUIRED_SCHEMAS,
      MIN_PERMISSIONS,
      LICENSE,
      DOCUMENTATION_URL,
      ICON_URL,
      SUPERSEDES_CONTENT_HASH,
      UPDATED_AT,
      PLUGIN_TYPE,
    }
  }

  /// Reverse-DNS module identity, e.g. "com.orbpro.sgp4-propagator". Stable
  /// across versions. Required and unique within the manifest.
  #[inline]
  pub fn MODULE_ID(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_MODULE_ID, None).unwrap()}
  }
  #[inline]
  pub fn key_compare_less_than(&self, o: &PMMModuleEntry) -> bool {
    self.MODULE_ID() < o.MODULE_ID()
  }

  #[inline]
  pub fn key_compare_with_value(&self, val: & str) -> ::core::cmp::Ordering {
    let key = self.MODULE_ID();
    key.cmp(val)
  }
  /// `$PLG.PLUGIN_ID` of the full listing for this module, when one is
  /// published.
  #[inline]
  pub fn PLUGIN_ID(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_PLUGIN_ID, None)}
  }
  /// IPFS CID of that `$PLG` record.
  #[inline]
  pub fn PLG_CID(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_PLG_CID, None)}
  }
  /// Display name.
  #[inline]
  pub fn NAME(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_NAME, None)}
  }
  /// Human-readable summary.
  #[inline]
  pub fn DESCRIPTION(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_DESCRIPTION, None)}
  }
  /// SemVer 2.0.0 version of the offered artifact.
  #[inline]
  pub fn VERSION(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_VERSION, None)}
  }
  /// Monotonic publication counter for this MODULE_ID. Increases on every
  /// re-publication, including a rebuild at the same VERSION.
  #[inline]
  pub fn EPOCH(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(PMMModuleEntry::VT_EPOCH, Some(0)).unwrap()}
  }
  /// 64 lowercase hexadecimal characters encoding SHA-256 of the module's
  /// portable (pre-AOT, publication-trailer-stripped) WASM bytes. Identical
  /// in meaning to `$APP.APPModuleRef.CONTENT_HASH`: this is the identity
  /// capability and signature policies key on.
  #[inline]
  pub fn CONTENT_HASH(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_CONTENT_HASH, None)}
  }
  /// Size of those portable WASM bytes.
  #[inline]
  pub fn ARTIFACT_SIZE_BYTES(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(PMMModuleEntry::VT_ARTIFACT_SIZE_BYTES, Some(0)).unwrap()}
  }
  /// Path, relative to the provider origin, from which the artifact is
  /// fetched. Relative on purpose: the bytes must come from the same origin
  /// whose domain the DNS proof binds.
  #[inline]
  pub fn ARTIFACT_PATH(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_ARTIFACT_PATH, None)}
  }
  /// IPFS CID of the artifact, for content-addressed retrieval.
  #[inline]
  pub fn ARTIFACT_CID(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_ARTIFACT_CID, None)}
  }
  /// Detached signature by the key in `PMMTrustAnchor.SIGNING_PUBLIC_KEY`
  /// over the 32 raw bytes of `CONTENT_HASH`. Lets a client reject an entry
  /// before spending a byte of bandwidth. The artifact's own publication
  /// trailer remains authoritative after download.
  #[inline]
  pub fn ARTIFACT_SIGNATURE(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(PMMModuleEntry::VT_ARTIFACT_SIGNATURE, None)}
  }
  /// Provider-declared standing. Gates anonymous loading.
  #[inline]
  pub fn TRUST_TIER(&self) -> pmmTrustTier {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<pmmTrustTier>(PMMModuleEntry::VT_TRUST_TIER, Some(pmmTrustTier::UNSPECIFIED)).unwrap()}
  }
  /// True when the provider ships this module enabled by default. A recorded
  /// user choice overrides it permanently.
  #[inline]
  pub fn DEFAULT_ENABLED(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(PMMModuleEntry::VT_DEFAULT_ENABLED, Some(false)).unwrap()}
  }
  /// What the client must hold to fetch and run it.
  #[inline]
  pub fn ACCESS_POLICY(&self) -> pmmAccessPolicy {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<pmmAccessPolicy>(PMMModuleEntry::VT_ACCESS_POLICY, Some(pmmAccessPolicy::AUTHENTICATED)).unwrap()}
  }
  /// Entry lifecycle.
  #[inline]
  pub fn ENTRY_STATE(&self) -> pmmEntryState {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<pmmEntryState>(PMMModuleEntry::VT_ENTRY_STATE, Some(pmmEntryState::ACTIVE)).unwrap()}
  }
  /// Opaque runtime-target tags this artifact is built for, e.g. "browser",
  /// "wasmedge". Same vocabulary as `$PLG.RUNTIME_TARGETS`.
  #[inline]
  pub fn RUNTIME_TARGETS(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(PMMModuleEntry::VT_RUNTIME_TARGETS, None)}
  }
  /// SDS schema codes at this module's invoke surface, e.g. "OMM", "OEM".
  #[inline]
  pub fn REQUIRED_SCHEMAS(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(PMMModuleEntry::VT_REQUIRED_SCHEMAS, None)}
  }
  /// Minimum host permissions the module needs, same vocabulary as
  /// `$PLG.MIN_PERMISSIONS`. Surfaced so a client can show what an
  /// anonymously-loaded CORE module is allowed to do.
  #[inline]
  pub fn MIN_PERMISSIONS(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(PMMModuleEntry::VT_MIN_PERMISSIONS, None)}
  }
  /// SPDX license identifier of the module.
  #[inline]
  pub fn LICENSE(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_LICENSE, None)}
  }
  /// URL to the module's documentation.
  #[inline]
  pub fn DOCUMENTATION_URL(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_DOCUMENTATION_URL, None)}
  }
  /// URL to the module's icon.
  #[inline]
  pub fn ICON_URL(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_ICON_URL, None)}
  }
  /// `CONTENT_HASH` this entry replaces, when it supersedes an earlier build.
  #[inline]
  pub fn SUPERSEDES_CONTENT_HASH(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_SUPERSEDES_CONTENT_HASH, None)}
  }
  /// RFC 3339 UTC fixed-millisecond timestamp (YYYY-MM-DDTHH:mm:ss.sssZ) of
  /// the last change to this entry.
  #[inline]
  pub fn UPDATED_AT(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMMModuleEntry::VT_UPDATED_AT, None)}
  }
  /// Family this module belongs to. Mirrors `$PLG.PLUGIN_TYPE` verbatim and
  /// is the ONLY sanctioned way to group an offering: a client grouping a
  /// catalogue MUST read this field and MUST NOT infer family from the shape
  /// of `MODULE_ID`, which carries no normative structure. Defaults to
  /// `Unspecified`, which a client MUST render as ungrouped — never silently
  /// as `Sensor`. Present here, rather than only on
  /// the linked `$PLG`, so an anonymous client can section the catalogue at
  /// boot without fetching one `$PLG` per module.
  #[inline]
  pub fn PLUGIN_TYPE(&self) -> pluginCategory {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<pluginCategory>(PMMModuleEntry::VT_PLUGIN_TYPE, Some(pluginCategory::Unspecified)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for PMMModuleEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("MODULE_ID", Self::VT_MODULE_ID, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("PLUGIN_ID", Self::VT_PLUGIN_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("PLG_CID", Self::VT_PLG_CID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("NAME", Self::VT_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("DESCRIPTION", Self::VT_DESCRIPTION, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("VERSION", Self::VT_VERSION, false)?
     .visit_field::<u64>("EPOCH", Self::VT_EPOCH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("CONTENT_HASH", Self::VT_CONTENT_HASH, false)?
     .visit_field::<u64>("ARTIFACT_SIZE_BYTES", Self::VT_ARTIFACT_SIZE_BYTES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("ARTIFACT_PATH", Self::VT_ARTIFACT_PATH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("ARTIFACT_CID", Self::VT_ARTIFACT_CID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("ARTIFACT_SIGNATURE", Self::VT_ARTIFACT_SIGNATURE, false)?
     .visit_field::<pmmTrustTier>("TRUST_TIER", Self::VT_TRUST_TIER, false)?
     .visit_field::<bool>("DEFAULT_ENABLED", Self::VT_DEFAULT_ENABLED, false)?
     .visit_field::<pmmAccessPolicy>("ACCESS_POLICY", Self::VT_ACCESS_POLICY, false)?
     .visit_field::<pmmEntryState>("ENTRY_STATE", Self::VT_ENTRY_STATE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("RUNTIME_TARGETS", Self::VT_RUNTIME_TARGETS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("REQUIRED_SCHEMAS", Self::VT_REQUIRED_SCHEMAS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("MIN_PERMISSIONS", Self::VT_MIN_PERMISSIONS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("LICENSE", Self::VT_LICENSE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("DOCUMENTATION_URL", Self::VT_DOCUMENTATION_URL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("ICON_URL", Self::VT_ICON_URL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("SUPERSEDES_CONTENT_HASH", Self::VT_SUPERSEDES_CONTENT_HASH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("UPDATED_AT", Self::VT_UPDATED_AT, false)?
     .visit_field::<pluginCategory>("PLUGIN_TYPE", Self::VT_PLUGIN_TYPE, false)?
     .finish();
    Ok(())
  }
}
pub struct PMMModuleEntryArgs<'a> {
    pub MODULE_ID: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub PLUGIN_ID: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub PLG_CID: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub NAME: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub DESCRIPTION: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub VERSION: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub EPOCH: u64,
    pub CONTENT_HASH: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub ARTIFACT_SIZE_BYTES: u64,
    pub ARTIFACT_PATH: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub ARTIFACT_CID: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub ARTIFACT_SIGNATURE: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub TRUST_TIER: pmmTrustTier,
    pub DEFAULT_ENABLED: bool,
    pub ACCESS_POLICY: pmmAccessPolicy,
    pub ENTRY_STATE: pmmEntryState,
    pub RUNTIME_TARGETS: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub REQUIRED_SCHEMAS: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub MIN_PERMISSIONS: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub LICENSE: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub DOCUMENTATION_URL: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub ICON_URL: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub SUPERSEDES_CONTENT_HASH: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub UPDATED_AT: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub PLUGIN_TYPE: pluginCategory,
}
impl<'a> Default for PMMModuleEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    PMMModuleEntryArgs {
      MODULE_ID: None, // required field
      PLUGIN_ID: None,
      PLG_CID: None,
      NAME: None,
      DESCRIPTION: None,
      VERSION: None,
      EPOCH: 0,
      CONTENT_HASH: None,
      ARTIFACT_SIZE_BYTES: 0,
      ARTIFACT_PATH: None,
      ARTIFACT_CID: None,
      ARTIFACT_SIGNATURE: None,
      TRUST_TIER: pmmTrustTier::UNSPECIFIED,
      DEFAULT_ENABLED: false,
      ACCESS_POLICY: pmmAccessPolicy::AUTHENTICATED,
      ENTRY_STATE: pmmEntryState::ACTIVE,
      RUNTIME_TARGETS: None,
      REQUIRED_SCHEMAS: None,
      MIN_PERMISSIONS: None,
      LICENSE: None,
      DOCUMENTATION_URL: None,
      ICON_URL: None,
      SUPERSEDES_CONTENT_HASH: None,
      UPDATED_AT: None,
      PLUGIN_TYPE: pluginCategory::Unspecified,
    }
  }
}

pub struct PMMModuleEntryBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PMMModuleEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_MODULE_ID(&mut self, MODULE_ID: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_MODULE_ID, MODULE_ID);
  }
  #[inline]
  pub fn add_PLUGIN_ID(&mut self, PLUGIN_ID: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_PLUGIN_ID, PLUGIN_ID);
  }
  #[inline]
  pub fn add_PLG_CID(&mut self, PLG_CID: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_PLG_CID, PLG_CID);
  }
  #[inline]
  pub fn add_NAME(&mut self, NAME: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_NAME, NAME);
  }
  #[inline]
  pub fn add_DESCRIPTION(&mut self, DESCRIPTION: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_DESCRIPTION, DESCRIPTION);
  }
  #[inline]
  pub fn add_VERSION(&mut self, VERSION: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_VERSION, VERSION);
  }
  #[inline]
  pub fn add_EPOCH(&mut self, EPOCH: u64) {
    self.fbb_.push_slot::<u64>(PMMModuleEntry::VT_EPOCH, EPOCH, 0);
  }
  #[inline]
  pub fn add_CONTENT_HASH(&mut self, CONTENT_HASH: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_CONTENT_HASH, CONTENT_HASH);
  }
  #[inline]
  pub fn add_ARTIFACT_SIZE_BYTES(&mut self, ARTIFACT_SIZE_BYTES: u64) {
    self.fbb_.push_slot::<u64>(PMMModuleEntry::VT_ARTIFACT_SIZE_BYTES, ARTIFACT_SIZE_BYTES, 0);
  }
  #[inline]
  pub fn add_ARTIFACT_PATH(&mut self, ARTIFACT_PATH: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_ARTIFACT_PATH, ARTIFACT_PATH);
  }
  #[inline]
  pub fn add_ARTIFACT_CID(&mut self, ARTIFACT_CID: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_ARTIFACT_CID, ARTIFACT_CID);
  }
  #[inline]
  pub fn add_ARTIFACT_SIGNATURE(&mut self, ARTIFACT_SIGNATURE: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_ARTIFACT_SIGNATURE, ARTIFACT_SIGNATURE);
  }
  #[inline]
  pub fn add_TRUST_TIER(&mut self, TRUST_TIER: pmmTrustTier) {
    self.fbb_.push_slot::<pmmTrustTier>(PMMModuleEntry::VT_TRUST_TIER, TRUST_TIER, pmmTrustTier::UNSPECIFIED);
  }
  #[inline]
  pub fn add_DEFAULT_ENABLED(&mut self, DEFAULT_ENABLED: bool) {
    self.fbb_.push_slot::<bool>(PMMModuleEntry::VT_DEFAULT_ENABLED, DEFAULT_ENABLED, false);
  }
  #[inline]
  pub fn add_ACCESS_POLICY(&mut self, ACCESS_POLICY: pmmAccessPolicy) {
    self.fbb_.push_slot::<pmmAccessPolicy>(PMMModuleEntry::VT_ACCESS_POLICY, ACCESS_POLICY, pmmAccessPolicy::AUTHENTICATED);
  }
  #[inline]
  pub fn add_ENTRY_STATE(&mut self, ENTRY_STATE: pmmEntryState) {
    self.fbb_.push_slot::<pmmEntryState>(PMMModuleEntry::VT_ENTRY_STATE, ENTRY_STATE, pmmEntryState::ACTIVE);
  }
  #[inline]
  pub fn add_RUNTIME_TARGETS(&mut self, RUNTIME_TARGETS: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_RUNTIME_TARGETS, RUNTIME_TARGETS);
  }
  #[inline]
  pub fn add_REQUIRED_SCHEMAS(&mut self, REQUIRED_SCHEMAS: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_REQUIRED_SCHEMAS, REQUIRED_SCHEMAS);
  }
  #[inline]
  pub fn add_MIN_PERMISSIONS(&mut self, MIN_PERMISSIONS: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_MIN_PERMISSIONS, MIN_PERMISSIONS);
  }
  #[inline]
  pub fn add_LICENSE(&mut self, LICENSE: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_LICENSE, LICENSE);
  }
  #[inline]
  pub fn add_DOCUMENTATION_URL(&mut self, DOCUMENTATION_URL: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_DOCUMENTATION_URL, DOCUMENTATION_URL);
  }
  #[inline]
  pub fn add_ICON_URL(&mut self, ICON_URL: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_ICON_URL, ICON_URL);
  }
  #[inline]
  pub fn add_SUPERSEDES_CONTENT_HASH(&mut self, SUPERSEDES_CONTENT_HASH: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_SUPERSEDES_CONTENT_HASH, SUPERSEDES_CONTENT_HASH);
  }
  #[inline]
  pub fn add_UPDATED_AT(&mut self, UPDATED_AT: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMMModuleEntry::VT_UPDATED_AT, UPDATED_AT);
  }
  #[inline]
  pub fn add_PLUGIN_TYPE(&mut self, PLUGIN_TYPE: pluginCategory) {
    self.fbb_.push_slot::<pluginCategory>(PMMModuleEntry::VT_PLUGIN_TYPE, PLUGIN_TYPE, pluginCategory::Unspecified);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PMMModuleEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PMMModuleEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PMMModuleEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, PMMModuleEntry::VT_MODULE_ID,"MODULE_ID");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PMMModuleEntry<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PMMModuleEntry");
      ds.field("MODULE_ID", &self.MODULE_ID());
      ds.field("PLUGIN_ID", &self.PLUGIN_ID());
      ds.field("PLG_CID", &self.PLG_CID());
      ds.field("NAME", &self.NAME());
      ds.field("DESCRIPTION", &self.DESCRIPTION());
      ds.field("VERSION", &self.VERSION());
      ds.field("EPOCH", &self.EPOCH());
      ds.field("CONTENT_HASH", &self.CONTENT_HASH());
      ds.field("ARTIFACT_SIZE_BYTES", &self.ARTIFACT_SIZE_BYTES());
      ds.field("ARTIFACT_PATH", &self.ARTIFACT_PATH());
      ds.field("ARTIFACT_CID", &self.ARTIFACT_CID());
      ds.field("ARTIFACT_SIGNATURE", &self.ARTIFACT_SIGNATURE());
      ds.field("TRUST_TIER", &self.TRUST_TIER());
      ds.field("DEFAULT_ENABLED", &self.DEFAULT_ENABLED());
      ds.field("ACCESS_POLICY", &self.ACCESS_POLICY());
      ds.field("ENTRY_STATE", &self.ENTRY_STATE());
      ds.field("RUNTIME_TARGETS", &self.RUNTIME_TARGETS());
      ds.field("REQUIRED_SCHEMAS", &self.REQUIRED_SCHEMAS());
      ds.field("MIN_PERMISSIONS", &self.MIN_PERMISSIONS());
      ds.field("LICENSE", &self.LICENSE());
      ds.field("DOCUMENTATION_URL", &self.DOCUMENTATION_URL());
      ds.field("ICON_URL", &self.ICON_URL());
      ds.field("SUPERSEDES_CONTENT_HASH", &self.SUPERSEDES_CONTENT_HASH());
      ds.field("UPDATED_AT", &self.UPDATED_AT());
      ds.field("PLUGIN_TYPE", &self.PLUGIN_TYPE());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct PMMModuleEntryT {
  pub MODULE_ID: alloc::string::String,
  pub PLUGIN_ID: Option<alloc::string::String>,
  pub PLG_CID: Option<alloc::string::String>,
  pub NAME: Option<alloc::string::String>,
  pub DESCRIPTION: Option<alloc::string::String>,
  pub VERSION: Option<alloc::string::String>,
  pub EPOCH: u64,
  pub CONTENT_HASH: Option<alloc::string::String>,
  pub ARTIFACT_SIZE_BYTES: u64,
  pub ARTIFACT_PATH: Option<alloc::string::String>,
  pub ARTIFACT_CID: Option<alloc::string::String>,
  pub ARTIFACT_SIGNATURE: Option<alloc::vec::Vec<u8>>,
  pub TRUST_TIER: pmmTrustTier,
  pub DEFAULT_ENABLED: bool,
  pub ACCESS_POLICY: pmmAccessPolicy,
  pub ENTRY_STATE: pmmEntryState,
  pub RUNTIME_TARGETS: Option<alloc::vec::Vec<alloc::string::String>>,
  pub REQUIRED_SCHEMAS: Option<alloc::vec::Vec<alloc::string::String>>,
  pub MIN_PERMISSIONS: Option<alloc::vec::Vec<alloc::string::String>>,
  pub LICENSE: Option<alloc::string::String>,
  pub DOCUMENTATION_URL: Option<alloc::string::String>,
  pub ICON_URL: Option<alloc::string::String>,
  pub SUPERSEDES_CONTENT_HASH: Option<alloc::string::String>,
  pub UPDATED_AT: Option<alloc::string::String>,
  pub PLUGIN_TYPE: pluginCategory,
}
impl Default for PMMModuleEntryT {
  fn default() -> Self {
    Self {
      MODULE_ID: alloc::string::ToString::to_string(""),
      PLUGIN_ID: None,
      PLG_CID: None,
      NAME: None,
      DESCRIPTION: None,
      VERSION: None,
      EPOCH: 0,
      CONTENT_HASH: None,
      ARTIFACT_SIZE_BYTES: 0,
      ARTIFACT_PATH: None,
      ARTIFACT_CID: None,
      ARTIFACT_SIGNATURE: None,
      TRUST_TIER: pmmTrustTier::UNSPECIFIED,
      DEFAULT_ENABLED: false,
      ACCESS_POLICY: pmmAccessPolicy::AUTHENTICATED,
      ENTRY_STATE: pmmEntryState::ACTIVE,
      RUNTIME_TARGETS: None,
      REQUIRED_SCHEMAS: None,
      MIN_PERMISSIONS: None,
      LICENSE: None,
      DOCUMENTATION_URL: None,
      ICON_URL: None,
      SUPERSEDES_CONTENT_HASH: None,
      UPDATED_AT: None,
      PLUGIN_TYPE: pluginCategory::Unspecified,
    }
  }
}
impl PMMModuleEntryT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<PMMModuleEntry<'b>> {
    let MODULE_ID = Some({
      let x = &self.MODULE_ID;
      _fbb.create_string(x)
    });
    let PLUGIN_ID = self.PLUGIN_ID.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let PLG_CID = self.PLG_CID.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let NAME = self.NAME.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let DESCRIPTION = self.DESCRIPTION.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let VERSION = self.VERSION.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let EPOCH = self.EPOCH;
    let CONTENT_HASH = self.CONTENT_HASH.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let ARTIFACT_SIZE_BYTES = self.ARTIFACT_SIZE_BYTES;
    let ARTIFACT_PATH = self.ARTIFACT_PATH.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let ARTIFACT_CID = self.ARTIFACT_CID.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let ARTIFACT_SIGNATURE = self.ARTIFACT_SIGNATURE.as_ref().map(|x|{
      _fbb.create_vector(x)
    });
    let TRUST_TIER = self.TRUST_TIER;
    let DEFAULT_ENABLED = self.DEFAULT_ENABLED;
    let ACCESS_POLICY = self.ACCESS_POLICY;
    let ENTRY_STATE = self.ENTRY_STATE;
    let RUNTIME_TARGETS = self.RUNTIME_TARGETS.as_ref().map(|x|{
      let w: alloc::vec::Vec<_> = x.iter().map(|s| _fbb.create_string(s)).collect();_fbb.create_vector(&w)
    });
    let REQUIRED_SCHEMAS = self.REQUIRED_SCHEMAS.as_ref().map(|x|{
      let w: alloc::vec::Vec<_> = x.iter().map(|s| _fbb.create_string(s)).collect();_fbb.create_vector(&w)
    });
    let MIN_PERMISSIONS = self.MIN_PERMISSIONS.as_ref().map(|x|{
      let w: alloc::vec::Vec<_> = x.iter().map(|s| _fbb.create_string(s)).collect();_fbb.create_vector(&w)
    });
    let LICENSE = self.LICENSE.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let DOCUMENTATION_URL = self.DOCUMENTATION_URL.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let ICON_URL = self.ICON_URL.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let SUPERSEDES_CONTENT_HASH = self.SUPERSEDES_CONTENT_HASH.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let UPDATED_AT = self.UPDATED_AT.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let PLUGIN_TYPE = self.PLUGIN_TYPE;
    PMMModuleEntry::create(_fbb, &PMMModuleEntryArgs{
      MODULE_ID,
      PLUGIN_ID,
      PLG_CID,
      NAME,
      DESCRIPTION,
      VERSION,
      EPOCH,
      CONTENT_HASH,
      ARTIFACT_SIZE_BYTES,
      ARTIFACT_PATH,
      ARTIFACT_CID,
      ARTIFACT_SIGNATURE,
      TRUST_TIER,
      DEFAULT_ENABLED,
      ACCESS_POLICY,
      ENTRY_STATE,
      RUNTIME_TARGETS,
      REQUIRED_SCHEMAS,
      MIN_PERMISSIONS,
      LICENSE,
      DOCUMENTATION_URL,
      ICON_URL,
      SUPERSEDES_CONTENT_HASH,
      UPDATED_AT,
      PLUGIN_TYPE,
    })
  }
}
pub enum PMMOffset {}
#[derive(Copy, Clone, PartialEq)]

/// Provider Module Manifest — what one provider node offers, signed by that
/// node's key.
pub struct PMM<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PMM<'a> {
  type Inner = PMM<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PMM<'a> {
  pub const VT_PROVIDER_DOMAIN: ::flatbuffers::VOffsetT = 4;
  pub const VT_PROVIDER_NAME: ::flatbuffers::VOffsetT = 6;
  pub const VT_DESCRIPTION: ::flatbuffers::VOffsetT = 8;
  pub const VT_EPOCH: ::flatbuffers::VOffsetT = 10;
  pub const VT_TRUST: ::flatbuffers::VOffsetT = 12;
  pub const VT_MODULES: ::flatbuffers::VOffsetT = 14;
  pub const VT_CANONICAL_URL: ::flatbuffers::VOffsetT = 16;
  pub const VT_CREATED_AT: ::flatbuffers::VOffsetT = 18;
  pub const VT_UPDATED_AT: ::flatbuffers::VOffsetT = 20;
  pub const VT_EXPIRES_AT: ::flatbuffers::VOffsetT = 22;
  pub const VT_SIGNATURE: ::flatbuffers::VOffsetT = 24;
  pub const VT_SIGNED_STATEMENT: ::flatbuffers::VOffsetT = 26;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PMM { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PMMArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PMM<'bldr>> {
    let mut builder = PMMBuilder::new(_fbb);
    builder.add_EPOCH(args.EPOCH);
    if let Some(x) = args.SIGNED_STATEMENT { builder.add_SIGNED_STATEMENT(x); }
    if let Some(x) = args.SIGNATURE { builder.add_SIGNATURE(x); }
    if let Some(x) = args.EXPIRES_AT { builder.add_EXPIRES_AT(x); }
    if let Some(x) = args.UPDATED_AT { builder.add_UPDATED_AT(x); }
    if let Some(x) = args.CREATED_AT { builder.add_CREATED_AT(x); }
    if let Some(x) = args.CANONICAL_URL { builder.add_CANONICAL_URL(x); }
    if let Some(x) = args.MODULES { builder.add_MODULES(x); }
    if let Some(x) = args.TRUST { builder.add_TRUST(x); }
    if let Some(x) = args.DESCRIPTION { builder.add_DESCRIPTION(x); }
    if let Some(x) = args.PROVIDER_NAME { builder.add_PROVIDER_NAME(x); }
    if let Some(x) = args.PROVIDER_DOMAIN { builder.add_PROVIDER_DOMAIN(x); }
    builder.finish()
  }

  pub fn unpack(&self) -> PMMT {
    let PROVIDER_DOMAIN = {
      let x = self.PROVIDER_DOMAIN();
      alloc::string::ToString::to_string(x)
    };
    let PROVIDER_NAME = self.PROVIDER_NAME().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let DESCRIPTION = self.DESCRIPTION().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let EPOCH = self.EPOCH();
    let TRUST = self.TRUST().map(|x| {
      alloc::boxed::Box::new(x.unpack())
    });
    let MODULES = self.MODULES().map(|x| {
      x.iter().map(|t| t.unpack()).collect()
    });
    let CANONICAL_URL = self.CANONICAL_URL().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let CREATED_AT = self.CREATED_AT().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let UPDATED_AT = self.UPDATED_AT().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let EXPIRES_AT = self.EXPIRES_AT().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    let SIGNATURE = self.SIGNATURE().map(|x| {
      x.into_iter().collect()
    });
    let SIGNED_STATEMENT = self.SIGNED_STATEMENT().map(|x| {
      alloc::string::ToString::to_string(x)
    });
    PMMT {
      PROVIDER_DOMAIN,
      PROVIDER_NAME,
      DESCRIPTION,
      EPOCH,
      TRUST,
      MODULES,
      CANONICAL_URL,
      CREATED_AT,
      UPDATED_AT,
      EXPIRES_AT,
      SIGNATURE,
      SIGNED_STATEMENT,
    }
  }

  /// Domain of the provider, e.g. "sdn.spaceaware.io". Required. MUST equal
  /// the origin the manifest was served from.
  #[inline]
  pub fn PROVIDER_DOMAIN(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMM::VT_PROVIDER_DOMAIN, None).unwrap()}
  }
  /// Display name of the provider.
  #[inline]
  pub fn PROVIDER_NAME(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMM::VT_PROVIDER_NAME, None)}
  }
  /// Human-readable summary of what the provider serves.
  #[inline]
  pub fn DESCRIPTION(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMM::VT_DESCRIPTION, None)}
  }
  /// Monotonic manifest epoch. A client MUST reject an epoch lower than the
  /// highest it has already verified for `PROVIDER_DOMAIN`.
  #[inline]
  pub fn EPOCH(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(PMM::VT_EPOCH, Some(0)).unwrap()}
  }
  /// The key identity and its external anchors.
  #[inline]
  pub fn TRUST(&self) -> Option<PMMTrustAnchor<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<PMMTrustAnchor>>(PMM::VT_TRUST, None)}
  }
  /// The offered modules.
  #[inline]
  pub fn MODULES(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PMMModuleEntry<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PMMModuleEntry>>>>(PMM::VT_MODULES, None)}
  }
  /// Canonical absolute URL this manifest is served from.
  #[inline]
  pub fn CANONICAL_URL(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMM::VT_CANONICAL_URL, None)}
  }
  /// RFC 3339 UTC fixed-millisecond timestamp (YYYY-MM-DDTHH:mm:ss.sssZ)
  /// when the manifest was created.
  #[inline]
  pub fn CREATED_AT(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMM::VT_CREATED_AT, None)}
  }
  /// RFC 3339 UTC fixed-millisecond timestamp (YYYY-MM-DDTHH:mm:ss.sssZ)
  /// when the manifest was last signed.
  #[inline]
  pub fn UPDATED_AT(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMM::VT_UPDATED_AT, None)}
  }
  /// RFC 3339 UTC fixed-millisecond timestamp (YYYY-MM-DDTHH:mm:ss.sssZ)
  /// after which a verifier MUST refuse anonymous CORE loading from this
  /// manifest and re-fetch. Required in practice for anonymous trust: an
  /// unexpiring signed manifest cannot be withdrawn.
  #[inline]
  pub fn EXPIRES_AT(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMM::VT_EXPIRES_AT, None)}
  }
  /// Signature by `TRUST.SIGNING_PUBLIC_KEY` over the canonical statement
  /// defined in this file's header.
  #[inline]
  pub fn SIGNATURE(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(PMM::VT_SIGNATURE, None)}
  }
  /// The canonical statement, verbatim. A verifier MUST rebuild it from this
  /// record and reject any difference.
  #[inline]
  pub fn SIGNED_STATEMENT(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(PMM::VT_SIGNED_STATEMENT, None)}
  }
}

impl ::flatbuffers::Verifiable for PMM<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("PROVIDER_DOMAIN", Self::VT_PROVIDER_DOMAIN, true)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("PROVIDER_NAME", Self::VT_PROVIDER_NAME, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("DESCRIPTION", Self::VT_DESCRIPTION, false)?
     .visit_field::<u64>("EPOCH", Self::VT_EPOCH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<PMMTrustAnchor>>("TRUST", Self::VT_TRUST, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<PMMModuleEntry>>>>("MODULES", Self::VT_MODULES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("CANONICAL_URL", Self::VT_CANONICAL_URL, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("CREATED_AT", Self::VT_CREATED_AT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("UPDATED_AT", Self::VT_UPDATED_AT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("EXPIRES_AT", Self::VT_EXPIRES_AT, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("SIGNATURE", Self::VT_SIGNATURE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("SIGNED_STATEMENT", Self::VT_SIGNED_STATEMENT, false)?
     .finish();
    Ok(())
  }
}
pub struct PMMArgs<'a> {
    pub PROVIDER_DOMAIN: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub PROVIDER_NAME: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub DESCRIPTION: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub EPOCH: u64,
    pub TRUST: Option<::flatbuffers::WIPOffset<PMMTrustAnchor<'a>>>,
    pub MODULES: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<PMMModuleEntry<'a>>>>>,
    pub CANONICAL_URL: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub CREATED_AT: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub UPDATED_AT: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub EXPIRES_AT: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub SIGNATURE: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub SIGNED_STATEMENT: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for PMMArgs<'a> {
  #[inline]
  fn default() -> Self {
    PMMArgs {
      PROVIDER_DOMAIN: None, // required field
      PROVIDER_NAME: None,
      DESCRIPTION: None,
      EPOCH: 0,
      TRUST: None,
      MODULES: None,
      CANONICAL_URL: None,
      CREATED_AT: None,
      UPDATED_AT: None,
      EXPIRES_AT: None,
      SIGNATURE: None,
      SIGNED_STATEMENT: None,
    }
  }
}

pub struct PMMBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PMMBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_PROVIDER_DOMAIN(&mut self, PROVIDER_DOMAIN: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMM::VT_PROVIDER_DOMAIN, PROVIDER_DOMAIN);
  }
  #[inline]
  pub fn add_PROVIDER_NAME(&mut self, PROVIDER_NAME: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMM::VT_PROVIDER_NAME, PROVIDER_NAME);
  }
  #[inline]
  pub fn add_DESCRIPTION(&mut self, DESCRIPTION: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMM::VT_DESCRIPTION, DESCRIPTION);
  }
  #[inline]
  pub fn add_EPOCH(&mut self, EPOCH: u64) {
    self.fbb_.push_slot::<u64>(PMM::VT_EPOCH, EPOCH, 0);
  }
  #[inline]
  pub fn add_TRUST(&mut self, TRUST: ::flatbuffers::WIPOffset<PMMTrustAnchor<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<PMMTrustAnchor>>(PMM::VT_TRUST, TRUST);
  }
  #[inline]
  pub fn add_MODULES(&mut self, MODULES: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<PMMModuleEntry<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMM::VT_MODULES, MODULES);
  }
  #[inline]
  pub fn add_CANONICAL_URL(&mut self, CANONICAL_URL: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMM::VT_CANONICAL_URL, CANONICAL_URL);
  }
  #[inline]
  pub fn add_CREATED_AT(&mut self, CREATED_AT: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMM::VT_CREATED_AT, CREATED_AT);
  }
  #[inline]
  pub fn add_UPDATED_AT(&mut self, UPDATED_AT: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMM::VT_UPDATED_AT, UPDATED_AT);
  }
  #[inline]
  pub fn add_EXPIRES_AT(&mut self, EXPIRES_AT: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMM::VT_EXPIRES_AT, EXPIRES_AT);
  }
  #[inline]
  pub fn add_SIGNATURE(&mut self, SIGNATURE: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMM::VT_SIGNATURE, SIGNATURE);
  }
  #[inline]
  pub fn add_SIGNED_STATEMENT(&mut self, SIGNED_STATEMENT: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PMM::VT_SIGNED_STATEMENT, SIGNED_STATEMENT);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PMMBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PMMBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PMM<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, PMM::VT_PROVIDER_DOMAIN,"PROVIDER_DOMAIN");
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PMM<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PMM");
      ds.field("PROVIDER_DOMAIN", &self.PROVIDER_DOMAIN());
      ds.field("PROVIDER_NAME", &self.PROVIDER_NAME());
      ds.field("DESCRIPTION", &self.DESCRIPTION());
      ds.field("EPOCH", &self.EPOCH());
      ds.field("TRUST", &self.TRUST());
      ds.field("MODULES", &self.MODULES());
      ds.field("CANONICAL_URL", &self.CANONICAL_URL());
      ds.field("CREATED_AT", &self.CREATED_AT());
      ds.field("UPDATED_AT", &self.UPDATED_AT());
      ds.field("EXPIRES_AT", &self.EXPIRES_AT());
      ds.field("SIGNATURE", &self.SIGNATURE());
      ds.field("SIGNED_STATEMENT", &self.SIGNED_STATEMENT());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct PMMT {
  pub PROVIDER_DOMAIN: alloc::string::String,
  pub PROVIDER_NAME: Option<alloc::string::String>,
  pub DESCRIPTION: Option<alloc::string::String>,
  pub EPOCH: u64,
  pub TRUST: Option<alloc::boxed::Box<PMMTrustAnchorT>>,
  pub MODULES: Option<alloc::vec::Vec<PMMModuleEntryT>>,
  pub CANONICAL_URL: Option<alloc::string::String>,
  pub CREATED_AT: Option<alloc::string::String>,
  pub UPDATED_AT: Option<alloc::string::String>,
  pub EXPIRES_AT: Option<alloc::string::String>,
  pub SIGNATURE: Option<alloc::vec::Vec<u8>>,
  pub SIGNED_STATEMENT: Option<alloc::string::String>,
}
impl Default for PMMT {
  fn default() -> Self {
    Self {
      PROVIDER_DOMAIN: alloc::string::ToString::to_string(""),
      PROVIDER_NAME: None,
      DESCRIPTION: None,
      EPOCH: 0,
      TRUST: None,
      MODULES: None,
      CANONICAL_URL: None,
      CREATED_AT: None,
      UPDATED_AT: None,
      EXPIRES_AT: None,
      SIGNATURE: None,
      SIGNED_STATEMENT: None,
    }
  }
}
impl PMMT {
  pub fn pack<'b, A: ::flatbuffers::Allocator + 'b>(
    &self,
    _fbb: &mut ::flatbuffers::FlatBufferBuilder<'b, A>
  ) -> ::flatbuffers::WIPOffset<PMM<'b>> {
    let PROVIDER_DOMAIN = Some({
      let x = &self.PROVIDER_DOMAIN;
      _fbb.create_string(x)
    });
    let PROVIDER_NAME = self.PROVIDER_NAME.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let DESCRIPTION = self.DESCRIPTION.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let EPOCH = self.EPOCH;
    let TRUST = self.TRUST.as_ref().map(|x|{
      x.pack(_fbb)
    });
    let MODULES = self.MODULES.as_ref().map(|x|{
      let w: alloc::vec::Vec<_> = x.iter().map(|t| t.pack(_fbb)).collect();_fbb.create_vector(&w)
    });
    let CANONICAL_URL = self.CANONICAL_URL.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let CREATED_AT = self.CREATED_AT.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let UPDATED_AT = self.UPDATED_AT.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let EXPIRES_AT = self.EXPIRES_AT.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    let SIGNATURE = self.SIGNATURE.as_ref().map(|x|{
      _fbb.create_vector(x)
    });
    let SIGNED_STATEMENT = self.SIGNED_STATEMENT.as_ref().map(|x|{
      _fbb.create_string(x)
    });
    PMM::create(_fbb, &PMMArgs{
      PROVIDER_DOMAIN,
      PROVIDER_NAME,
      DESCRIPTION,
      EPOCH,
      TRUST,
      MODULES,
      CANONICAL_URL,
      CREATED_AT,
      UPDATED_AT,
      EXPIRES_AT,
      SIGNATURE,
      SIGNED_STATEMENT,
    })
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `PMM`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pmm_unchecked`.
pub fn root_as_pmm(buf: &[u8]) -> Result<PMM<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<PMM>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `PMM` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_pmm_unchecked`.
pub fn size_prefixed_root_as_pmm(buf: &[u8]) -> Result<PMM<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<PMM>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `PMM` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pmm_unchecked`.
pub fn root_as_pmm_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<PMM<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<PMM<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `PMM` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_pmm_unchecked`.
pub fn size_prefixed_root_as_pmm_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<PMM<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<PMM<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a PMM and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `PMM`.
pub unsafe fn root_as_pmm_unchecked(buf: &[u8]) -> PMM<'_> {
  unsafe { ::flatbuffers::root_unchecked::<PMM>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed PMM and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `PMM`.
pub unsafe fn size_prefixed_root_as_pmm_unchecked(buf: &[u8]) -> PMM<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<PMM>(buf) }
}
pub const PMM_IDENTIFIER: &str = "$PMM";

#[inline]
pub fn pmm_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, PMM_IDENTIFIER, false)
}

#[inline]
pub fn pmm_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  ::flatbuffers::buffer_has_identifier(buf, PMM_IDENTIFIER, true)
}

#[inline]
pub fn finish_pmm_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<PMM<'a>>) {
  fbb.finish(root, Some(PMM_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_pmm_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<PMM<'a>>) {
  fbb.finish_size_prefixed(root, Some(PMM_IDENTIFIER));
}
