import * as flatbuffers from 'flatbuffers';
/**
 * Aircraft Dynamics
 */
export declare class ACR implements flatbuffers.IUnpackableObject<ACRT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): ACR;
    static getRootAsACR(bb: flatbuffers.ByteBuffer, obj?: ACR): ACR;
    static getSizePrefixedRootAsACR(bb: flatbuffers.ByteBuffer, obj?: ACR): ACR;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    POSITION_X(): number;
    POSITION_Y(): number;
    POSITION_Z(): number;
    VELOCITY_X(): number;
    VELOCITY_Y(): number;
    VELOCITY_Z(): number;
    ATTITUDE_X(): number;
    ATTITUDE_Y(): number;
    ATTITUDE_Z(): number;
    ATTITUDE_W(): number;
    OMEGA_X(): number;
    OMEGA_Y(): number;
    OMEGA_Z(): number;
    MASS(): number;
    CG_X(): number;
    CG_Z(): number;
    AERO(): string | null;
    AERO(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    CONTROLS(): string | null;
    CONTROLS(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ENGINE(): string | null;
    ENGINE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    GEAR_STATE(): number;
    GEAR_POSITION(): number;
    FLAP_POSITION(): number;
    SPEEDBRAKE_POS(): number;
    FLIGHT_PHASE(): number;
    AUTOPILOT_MODE(): number;
    WEIGHT_ON_WHEELS(): number;
    RESERVED(): number;
    static startACR(builder: flatbuffers.Builder): void;
    static addPositionX(builder: flatbuffers.Builder, POSITION_X: number): void;
    static addPositionY(builder: flatbuffers.Builder, POSITION_Y: number): void;
    static addPositionZ(builder: flatbuffers.Builder, POSITION_Z: number): void;
    static addVelocityX(builder: flatbuffers.Builder, VELOCITY_X: number): void;
    static addVelocityY(builder: flatbuffers.Builder, VELOCITY_Y: number): void;
    static addVelocityZ(builder: flatbuffers.Builder, VELOCITY_Z: number): void;
    static addAttitudeX(builder: flatbuffers.Builder, ATTITUDE_X: number): void;
    static addAttitudeY(builder: flatbuffers.Builder, ATTITUDE_Y: number): void;
    static addAttitudeZ(builder: flatbuffers.Builder, ATTITUDE_Z: number): void;
    static addAttitudeW(builder: flatbuffers.Builder, ATTITUDE_W: number): void;
    static addOmegaX(builder: flatbuffers.Builder, OMEGA_X: number): void;
    static addOmegaY(builder: flatbuffers.Builder, OMEGA_Y: number): void;
    static addOmegaZ(builder: flatbuffers.Builder, OMEGA_Z: number): void;
    static addMass(builder: flatbuffers.Builder, MASS: number): void;
    static addCgX(builder: flatbuffers.Builder, CG_X: number): void;
    static addCgZ(builder: flatbuffers.Builder, CG_Z: number): void;
    static addAero(builder: flatbuffers.Builder, AEROOffset: flatbuffers.Offset): void;
    static addControls(builder: flatbuffers.Builder, CONTROLSOffset: flatbuffers.Offset): void;
    static addEngine(builder: flatbuffers.Builder, ENGINEOffset: flatbuffers.Offset): void;
    static addGearState(builder: flatbuffers.Builder, GEAR_STATE: number): void;
    static addGearPosition(builder: flatbuffers.Builder, GEAR_POSITION: number): void;
    static addFlapPosition(builder: flatbuffers.Builder, FLAP_POSITION: number): void;
    static addSpeedbrakePos(builder: flatbuffers.Builder, SPEEDBRAKE_POS: number): void;
    static addFlightPhase(builder: flatbuffers.Builder, FLIGHT_PHASE: number): void;
    static addAutopilotMode(builder: flatbuffers.Builder, AUTOPILOT_MODE: number): void;
    static addWeightOnWheels(builder: flatbuffers.Builder, WEIGHT_ON_WHEELS: number): void;
    static addReserved(builder: flatbuffers.Builder, RESERVED: number): void;
    static endACR(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishACRBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedACRBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createACR(builder: flatbuffers.Builder, POSITION_X: number, POSITION_Y: number, POSITION_Z: number, VELOCITY_X: number, VELOCITY_Y: number, VELOCITY_Z: number, ATTITUDE_X: number, ATTITUDE_Y: number, ATTITUDE_Z: number, ATTITUDE_W: number, OMEGA_X: number, OMEGA_Y: number, OMEGA_Z: number, MASS: number, CG_X: number, CG_Z: number, AEROOffset: flatbuffers.Offset, CONTROLSOffset: flatbuffers.Offset, ENGINEOffset: flatbuffers.Offset, GEAR_STATE: number, GEAR_POSITION: number, FLAP_POSITION: number, SPEEDBRAKE_POS: number, FLIGHT_PHASE: number, AUTOPILOT_MODE: number, WEIGHT_ON_WHEELS: number, RESERVED: number): flatbuffers.Offset;
    unpack(): ACRT;
    unpackTo(_o: ACRT): void;
}
export declare class ACRT implements flatbuffers.IGeneratedObject {
    POSITION_X: number;
    POSITION_Y: number;
    POSITION_Z: number;
    VELOCITY_X: number;
    VELOCITY_Y: number;
    VELOCITY_Z: number;
    ATTITUDE_X: number;
    ATTITUDE_Y: number;
    ATTITUDE_Z: number;
    ATTITUDE_W: number;
    OMEGA_X: number;
    OMEGA_Y: number;
    OMEGA_Z: number;
    MASS: number;
    CG_X: number;
    CG_Z: number;
    AERO: string | Uint8Array | null;
    CONTROLS: string | Uint8Array | null;
    ENGINE: string | Uint8Array | null;
    GEAR_STATE: number;
    GEAR_POSITION: number;
    FLAP_POSITION: number;
    SPEEDBRAKE_POS: number;
    FLIGHT_PHASE: number;
    AUTOPILOT_MODE: number;
    WEIGHT_ON_WHEELS: number;
    RESERVED: number;
    constructor(POSITION_X?: number, POSITION_Y?: number, POSITION_Z?: number, VELOCITY_X?: number, VELOCITY_Y?: number, VELOCITY_Z?: number, ATTITUDE_X?: number, ATTITUDE_Y?: number, ATTITUDE_Z?: number, ATTITUDE_W?: number, OMEGA_X?: number, OMEGA_Y?: number, OMEGA_Z?: number, MASS?: number, CG_X?: number, CG_Z?: number, AERO?: string | Uint8Array | null, CONTROLS?: string | Uint8Array | null, ENGINE?: string | Uint8Array | null, GEAR_STATE?: number, GEAR_POSITION?: number, FLAP_POSITION?: number, SPEEDBRAKE_POS?: number, FLIGHT_PHASE?: number, AUTOPILOT_MODE?: number, WEIGHT_ON_WHEELS?: number, RESERVED?: number);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=ACR.d.ts.map