// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

/// Key Reference Frame
public struct KRF : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static KRF GetRootAsKRF(ByteBuffer _bb) { return GetRootAsKRF(_bb, new KRF()); }
  public static KRF GetRootAsKRF(ByteBuffer _bb, KRF obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool KRFBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "$KRF"); }
  public static bool VerifyKRF(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("$KRF", false, KRFVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public KRF __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// Logical key identifier used across publication and grant records.
  public string KEY_ID { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetKEY_IDBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetKEY_IDBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetKEY_IDArray() { return __p.__vector_as_array<byte>(4); }
  /// Host-managed key slot or key handle identifier.
  public string SLOT_ID { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSLOT_IDBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetSLOT_IDBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetSLOT_IDArray() { return __p.__vector_as_array<byte>(6); }
  /// Role the referenced key fulfills for the module flow.
  public keyReferenceRole ROLE { get { int o = __p.__offset(8); return o != 0 ? (keyReferenceRole)__p.bb.GetSbyte(o + __p.bb_pos) : keyReferenceRole.Unknown; } }
  /// Algorithm or key family for the referenced key.
  public keyReferenceAlgorithm ALGORITHM { get { int o = __p.__offset(10); return o != 0 ? (keyReferenceAlgorithm)__p.bb.GetSbyte(o + __p.bb_pos) : keyReferenceAlgorithm.Unknown; } }
  /// Optional public bytes for verification or peer identity binding.
  public byte PUBLIC_KEY(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int PUBLIC_KEYLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPUBLIC_KEYBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetPUBLIC_KEYBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetPUBLIC_KEYArray() { return __p.__vector_as_array<byte>(12); }
  /// Logical version of the referenced key.
  public uint VERSION { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  /// Expiration time in unix milliseconds, or 0 if unbounded.
  public ulong EXPIRES_AT { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  /// True when the secret material remains in the host key slot.
  public bool HOST_MANAGED { get { int o = __p.__offset(18); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }

  public static Offset<KRF> CreateKRF(FlatBufferBuilder builder,
      StringOffset KEY_IDOffset = default(StringOffset),
      StringOffset SLOT_IDOffset = default(StringOffset),
      keyReferenceRole ROLE = keyReferenceRole.Unknown,
      keyReferenceAlgorithm ALGORITHM = keyReferenceAlgorithm.Unknown,
      VectorOffset PUBLIC_KEYOffset = default(VectorOffset),
      uint VERSION = 0,
      ulong EXPIRES_AT = 0,
      bool HOST_MANAGED = true) {
    builder.StartTable(8);
    KRF.AddEXPIRES_AT(builder, EXPIRES_AT);
    KRF.AddVERSION(builder, VERSION);
    KRF.AddPUBLIC_KEY(builder, PUBLIC_KEYOffset);
    KRF.AddSLOT_ID(builder, SLOT_IDOffset);
    KRF.AddKEY_ID(builder, KEY_IDOffset);
    KRF.AddHOST_MANAGED(builder, HOST_MANAGED);
    KRF.AddALGORITHM(builder, ALGORITHM);
    KRF.AddROLE(builder, ROLE);
    return KRF.EndKRF(builder);
  }

  public static void StartKRF(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddKEY_ID(FlatBufferBuilder builder, StringOffset KEY_IDOffset) { builder.AddOffset(0, KEY_IDOffset.Value, 0); }
  public static void AddSLOT_ID(FlatBufferBuilder builder, StringOffset SLOT_IDOffset) { builder.AddOffset(1, SLOT_IDOffset.Value, 0); }
  public static void AddROLE(FlatBufferBuilder builder, keyReferenceRole ROLE) { builder.AddSbyte(2, (sbyte)ROLE, 0); }
  public static void AddALGORITHM(FlatBufferBuilder builder, keyReferenceAlgorithm ALGORITHM) { builder.AddSbyte(3, (sbyte)ALGORITHM, 0); }
  public static void AddPUBLIC_KEY(FlatBufferBuilder builder, VectorOffset PUBLIC_KEYOffset) { builder.AddOffset(4, PUBLIC_KEYOffset.Value, 0); }
  public static VectorOffset CreatePUBLIC_KEYVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePUBLIC_KEYVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePUBLIC_KEYVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePUBLIC_KEYVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPUBLIC_KEYVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddVERSION(FlatBufferBuilder builder, uint VERSION) { builder.AddUint(5, VERSION, 0); }
  public static void AddEXPIRES_AT(FlatBufferBuilder builder, ulong EXPIRES_AT) { builder.AddUlong(6, EXPIRES_AT, 0); }
  public static void AddHOST_MANAGED(FlatBufferBuilder builder, bool HOST_MANAGED) { builder.AddBool(7, HOST_MANAGED, true); }
  public static Offset<KRF> EndKRF(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<KRF>(o);
  }
  public static void FinishKRFBuffer(FlatBufferBuilder builder, Offset<KRF> offset) { builder.Finish(offset.Value, "$KRF"); }
  public static void FinishSizePrefixedKRFBuffer(FlatBufferBuilder builder, Offset<KRF> offset) { builder.FinishSizePrefixed(offset.Value, "$KRF"); }
  public KRFT UnPack() {
    var _o = new KRFT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(KRFT _o) {
    _o.KEY_ID = this.KEY_ID;
    _o.SLOT_ID = this.SLOT_ID;
    _o.ROLE = this.ROLE;
    _o.ALGORITHM = this.ALGORITHM;
    _o.PUBLIC_KEY = new List<byte>();
    for (var _j = 0; _j < this.PUBLIC_KEYLength; ++_j) {_o.PUBLIC_KEY.Add(this.PUBLIC_KEY(_j));}
    _o.VERSION = this.VERSION;
    _o.EXPIRES_AT = this.EXPIRES_AT;
    _o.HOST_MANAGED = this.HOST_MANAGED;
  }
  public static Offset<KRF> Pack(FlatBufferBuilder builder, KRFT _o) {
    if (_o == null) return default(Offset<KRF>);
    var _KEY_ID = _o.KEY_ID == null ? default(StringOffset) : builder.CreateString(_o.KEY_ID);
    var _SLOT_ID = _o.SLOT_ID == null ? default(StringOffset) : builder.CreateString(_o.SLOT_ID);
    var _PUBLIC_KEY = default(VectorOffset);
    if (_o.PUBLIC_KEY != null) {
      var __PUBLIC_KEY = _o.PUBLIC_KEY.ToArray();
      _PUBLIC_KEY = CreatePUBLIC_KEYVector(builder, __PUBLIC_KEY);
    }
    return CreateKRF(
      builder,
      _KEY_ID,
      _SLOT_ID,
      _o.ROLE,
      _o.ALGORITHM,
      _PUBLIC_KEY,
      _o.VERSION,
      _o.EXPIRES_AT,
      _o.HOST_MANAGED);
  }
}

public class KRFT
{
  public string KEY_ID { get; set; }
  public string SLOT_ID { get; set; }
  public keyReferenceRole ROLE { get; set; }
  public keyReferenceAlgorithm ALGORITHM { get; set; }
  public List<byte> PUBLIC_KEY { get; set; }
  public uint VERSION { get; set; }
  public ulong EXPIRES_AT { get; set; }
  public bool HOST_MANAGED { get; set; }

  public KRFT() {
    this.KEY_ID = null;
    this.SLOT_ID = null;
    this.ROLE = keyReferenceRole.Unknown;
    this.ALGORITHM = keyReferenceAlgorithm.Unknown;
    this.PUBLIC_KEY = null;
    this.VERSION = 0;
    this.EXPIRES_AT = 0;
    this.HOST_MANAGED = true;
  }
  public static KRFT DeserializeFromBinary(byte[] fbBuffer) {
    return KRF.GetRootAsKRF(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    KRF.FinishKRFBuffer(fbb, KRF.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


static public class KRFVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*KEY_ID*/, false)
      && verifier.VerifyString(tablePos, 6 /*SLOT_ID*/, false)
      && verifier.VerifyField(tablePos, 8 /*ROLE*/, 1 /*keyReferenceRole*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*ALGORITHM*/, 1 /*keyReferenceAlgorithm*/, 1, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*PUBLIC_KEY*/, 1 /*byte*/, false)
      && verifier.VerifyField(tablePos, 14 /*VERSION*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*EXPIRES_AT*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 18 /*HOST_MANAGED*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
