// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
/**
 * Storefront payment model for the plugin listing
 */
export var paymentModel;
(function (paymentModel) {
    /**
     * No payment required
     */
    paymentModel[paymentModel["Free"] = 0] = "Free";
    /**
     * Single one-time purchase
     */
    paymentModel[paymentModel["OneTime"] = 1] = "OneTime";
    /**
     * Recurring subscription purchase
     */
    paymentModel[paymentModel["Subscription"] = 2] = "Subscription";
})(paymentModel || (paymentModel = {}));
