// automatically generated by the FlatBuffers compiler, do not modify

/**
 * Orbital element parameterization for the first element (size/shape).
 */
@SuppressWarnings("unused")
public final class sizeShapeProfile {
  private sizeShapeProfile() { }
  /**
   * Semi-major axis (km). Standard for elliptical orbits.
   */
  public static final byte SMA = 0;
  /**
   * Radius of periapsis (km). Preferred for hyperbolic orbits.
   */
  public static final byte R_PERIAPSIS = 1;

  public static final String[] names = { "SMA", "R_PERIAPSIS", };

  public static String name(int e) { return names[e]; }
}

