import * as flatbuffers from 'flatbuffers';
/**
 * Track
 */
export declare class TRK implements flatbuffers.IUnpackableObject<TRKT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): TRK;
    static getRootAsTRK(bb: flatbuffers.ByteBuffer, obj?: TRK): TRK;
    static getSizePrefixedRootAsTRK(bb: flatbuffers.ByteBuffer, obj?: TRK): TRK;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    CNTCT(): string | null;
    CNTCT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MSG_TS(): string | null;
    MSG_TS(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MSN_ID(): string | null;
    MSN_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ASSET_NAT(): string | null;
    ASSET_NAT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ASSET(): string | null;
    ASSET(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SEN(): string | null;
    SEN(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SEN_QUAL(): string | null;
    SEN_QUAL(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRK_ID(): string | null;
    TRK_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRK_NUM(): string | null;
    TRK_NUM(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRK_STAT(): string | null;
    TRK_STAT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBJ_NAT(): string | null;
    OBJ_NAT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBJ_ID(): string | null;
    OBJ_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBJ_TYPE(): string | null;
    OBJ_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBJ_SPEC(): string | null;
    OBJ_SPEC(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBJ_PLAT(): string | null;
    OBJ_PLAT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBJ_ACT(): string | null;
    OBJ_ACT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MOD_TYPE(): string | null;
    MOD_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRK_ITM_ID(): string | null;
    TRK_ITM_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TS(): string | null;
    TS(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRK_QUAL(): number;
    TRK_PT_TYPE(): string | null;
    TRK_PT_TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OBJ_IDENT(): string | null;
    OBJ_IDENT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    IDENT_CRED(): number;
    IDENT_REL(): number;
    IDENT_AMP(): string | null;
    IDENT_AMP(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ENVIRONMENT(): string | null;
    ENVIRONMENT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ENVIRONMENT_CONF(): number;
    TRK_CONF(): number;
    ECEF_POS(index: number): string;
    ECEF_POS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    ecefPosLength(): number;
    ECEF_VEL(index: number): string;
    ECEF_VEL(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    ecefVelLength(): number;
    ECEF_ACC(index: number): string;
    ECEF_ACC(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    ecefAccLength(): number;
    LAT(): number;
    LON(): number;
    ALT(): number;
    SPD(): number;
    HDNG(): number;
    COURSE(): number;
    LCO(index: number): string;
    LCO(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    lcoLength(): number;
    LCS(index: number): string;
    LCS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    lcsLength(): number;
    LC_POS(index: number): string;
    LC_POS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    lcPosLength(): number;
    LC_VEL(index: number): string;
    LC_VEL(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    lcVelLength(): number;
    LC_ACC(index: number): string;
    LC_ACC(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    lcAccLength(): number;
    E_NUVEL(index: number): string;
    E_NUVEL(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    eNuvelLength(): number;
    E_NUPOS(index: number): string;
    E_NUPOS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    eNuposLength(): number;
    COV(index: number): string;
    COV(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    covLength(): number;
    ERR_ELLP(index: number): string;
    ERR_ELLP(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    errEllpLength(): number;
    SRC_TYPS(index: number): string;
    SRC_TYPS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    srcTypsLength(): number;
    SRC_IDS(index: number): string;
    SRC_IDS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    srcIdsLength(): number;
    CALL_SIGN(): string | null;
    CALL_SIGN(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MULTI_SOURCE(): boolean;
    J_SERIES(): string | null;
    J_SERIES(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    STRENGTH(): number;
    M1(): number;
    M1V(): number;
    M2(): number;
    M2V(): number;
    M3A(): number;
    M3AV(): number;
    TAGS(index: number): string;
    TAGS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    tagsLength(): number;
    static startTRK(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addCntct(builder: flatbuffers.Builder, CNTCTOffset: flatbuffers.Offset): void;
    static addMsgTs(builder: flatbuffers.Builder, MSG_TSOffset: flatbuffers.Offset): void;
    static addMsnId(builder: flatbuffers.Builder, MSN_IDOffset: flatbuffers.Offset): void;
    static addAssetNat(builder: flatbuffers.Builder, ASSET_NATOffset: flatbuffers.Offset): void;
    static addAsset(builder: flatbuffers.Builder, ASSETOffset: flatbuffers.Offset): void;
    static addSen(builder: flatbuffers.Builder, SENOffset: flatbuffers.Offset): void;
    static addSenQual(builder: flatbuffers.Builder, SEN_QUALOffset: flatbuffers.Offset): void;
    static addTrkId(builder: flatbuffers.Builder, TRK_IDOffset: flatbuffers.Offset): void;
    static addTrkNum(builder: flatbuffers.Builder, TRK_NUMOffset: flatbuffers.Offset): void;
    static addTrkStat(builder: flatbuffers.Builder, TRK_STATOffset: flatbuffers.Offset): void;
    static addObjNat(builder: flatbuffers.Builder, OBJ_NATOffset: flatbuffers.Offset): void;
    static addObjId(builder: flatbuffers.Builder, OBJ_IDOffset: flatbuffers.Offset): void;
    static addObjType(builder: flatbuffers.Builder, OBJ_TYPEOffset: flatbuffers.Offset): void;
    static addObjSpec(builder: flatbuffers.Builder, OBJ_SPECOffset: flatbuffers.Offset): void;
    static addObjPlat(builder: flatbuffers.Builder, OBJ_PLATOffset: flatbuffers.Offset): void;
    static addObjAct(builder: flatbuffers.Builder, OBJ_ACTOffset: flatbuffers.Offset): void;
    static addModType(builder: flatbuffers.Builder, MOD_TYPEOffset: flatbuffers.Offset): void;
    static addTrkItmId(builder: flatbuffers.Builder, TRK_ITM_IDOffset: flatbuffers.Offset): void;
    static addTs(builder: flatbuffers.Builder, TSOffset: flatbuffers.Offset): void;
    static addTrkQual(builder: flatbuffers.Builder, TRK_QUAL: number): void;
    static addTrkPtType(builder: flatbuffers.Builder, TRK_PT_TYPEOffset: flatbuffers.Offset): void;
    static addObjIdent(builder: flatbuffers.Builder, OBJ_IDENTOffset: flatbuffers.Offset): void;
    static addIdentCred(builder: flatbuffers.Builder, IDENT_CRED: number): void;
    static addIdentRel(builder: flatbuffers.Builder, IDENT_REL: number): void;
    static addIdentAmp(builder: flatbuffers.Builder, IDENT_AMPOffset: flatbuffers.Offset): void;
    static addEnvironment(builder: flatbuffers.Builder, ENVIRONMENTOffset: flatbuffers.Offset): void;
    static addEnvironmentConf(builder: flatbuffers.Builder, ENVIRONMENT_CONF: number): void;
    static addTrkConf(builder: flatbuffers.Builder, TRK_CONF: number): void;
    static addEcefPos(builder: flatbuffers.Builder, ECEF_POSOffset: flatbuffers.Offset): void;
    static createEcefPosVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startEcefPosVector(builder: flatbuffers.Builder, numElems: number): void;
    static addEcefVel(builder: flatbuffers.Builder, ECEF_VELOffset: flatbuffers.Offset): void;
    static createEcefVelVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startEcefVelVector(builder: flatbuffers.Builder, numElems: number): void;
    static addEcefAcc(builder: flatbuffers.Builder, ECEF_ACCOffset: flatbuffers.Offset): void;
    static createEcefAccVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startEcefAccVector(builder: flatbuffers.Builder, numElems: number): void;
    static addLat(builder: flatbuffers.Builder, LAT: number): void;
    static addLon(builder: flatbuffers.Builder, LON: number): void;
    static addAlt(builder: flatbuffers.Builder, ALT: number): void;
    static addSpd(builder: flatbuffers.Builder, SPD: number): void;
    static addHdng(builder: flatbuffers.Builder, HDNG: number): void;
    static addCourse(builder: flatbuffers.Builder, COURSE: number): void;
    static addLco(builder: flatbuffers.Builder, LCOOffset: flatbuffers.Offset): void;
    static createLcoVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startLcoVector(builder: flatbuffers.Builder, numElems: number): void;
    static addLcs(builder: flatbuffers.Builder, LCSOffset: flatbuffers.Offset): void;
    static createLcsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startLcsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addLcPos(builder: flatbuffers.Builder, LC_POSOffset: flatbuffers.Offset): void;
    static createLcPosVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startLcPosVector(builder: flatbuffers.Builder, numElems: number): void;
    static addLcVel(builder: flatbuffers.Builder, LC_VELOffset: flatbuffers.Offset): void;
    static createLcVelVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startLcVelVector(builder: flatbuffers.Builder, numElems: number): void;
    static addLcAcc(builder: flatbuffers.Builder, LC_ACCOffset: flatbuffers.Offset): void;
    static createLcAccVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startLcAccVector(builder: flatbuffers.Builder, numElems: number): void;
    static addENuvel(builder: flatbuffers.Builder, E_NUVELOffset: flatbuffers.Offset): void;
    static createENuvelVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startENuvelVector(builder: flatbuffers.Builder, numElems: number): void;
    static addENupos(builder: flatbuffers.Builder, E_NUPOSOffset: flatbuffers.Offset): void;
    static createENuposVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startENuposVector(builder: flatbuffers.Builder, numElems: number): void;
    static addCov(builder: flatbuffers.Builder, COVOffset: flatbuffers.Offset): void;
    static createCovVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startCovVector(builder: flatbuffers.Builder, numElems: number): void;
    static addErrEllp(builder: flatbuffers.Builder, ERR_ELLPOffset: flatbuffers.Offset): void;
    static createErrEllpVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startErrEllpVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSrcTyps(builder: flatbuffers.Builder, SRC_TYPSOffset: flatbuffers.Offset): void;
    static createSrcTypsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSrcTypsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSrcIds(builder: flatbuffers.Builder, SRC_IDSOffset: flatbuffers.Offset): void;
    static createSrcIdsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSrcIdsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addCallSign(builder: flatbuffers.Builder, CALL_SIGNOffset: flatbuffers.Offset): void;
    static addMultiSource(builder: flatbuffers.Builder, MULTI_SOURCE: boolean): void;
    static addJSeries(builder: flatbuffers.Builder, J_SERIESOffset: flatbuffers.Offset): void;
    static addStrength(builder: flatbuffers.Builder, STRENGTH: number): void;
    static addM1(builder: flatbuffers.Builder, M1: number): void;
    static addM1V(builder: flatbuffers.Builder, M1V: number): void;
    static addM2(builder: flatbuffers.Builder, M2: number): void;
    static addM2V(builder: flatbuffers.Builder, M2V: number): void;
    static addM3A(builder: flatbuffers.Builder, M3A: number): void;
    static addM3Av(builder: flatbuffers.Builder, M3AV: number): void;
    static addTags(builder: flatbuffers.Builder, TAGSOffset: flatbuffers.Offset): void;
    static createTagsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startTagsVector(builder: flatbuffers.Builder, numElems: number): void;
    static endTRK(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishTRKBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedTRKBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createTRK(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, CNTCTOffset: flatbuffers.Offset, MSG_TSOffset: flatbuffers.Offset, MSN_IDOffset: flatbuffers.Offset, ASSET_NATOffset: flatbuffers.Offset, ASSETOffset: flatbuffers.Offset, SENOffset: flatbuffers.Offset, SEN_QUALOffset: flatbuffers.Offset, TRK_IDOffset: flatbuffers.Offset, TRK_NUMOffset: flatbuffers.Offset, TRK_STATOffset: flatbuffers.Offset, OBJ_NATOffset: flatbuffers.Offset, OBJ_IDOffset: flatbuffers.Offset, OBJ_TYPEOffset: flatbuffers.Offset, OBJ_SPECOffset: flatbuffers.Offset, OBJ_PLATOffset: flatbuffers.Offset, OBJ_ACTOffset: flatbuffers.Offset, MOD_TYPEOffset: flatbuffers.Offset, TRK_ITM_IDOffset: flatbuffers.Offset, TSOffset: flatbuffers.Offset, TRK_QUAL: number, TRK_PT_TYPEOffset: flatbuffers.Offset, OBJ_IDENTOffset: flatbuffers.Offset, IDENT_CRED: number, IDENT_REL: number, IDENT_AMPOffset: flatbuffers.Offset, ENVIRONMENTOffset: flatbuffers.Offset, ENVIRONMENT_CONF: number, TRK_CONF: number, ECEF_POSOffset: flatbuffers.Offset, ECEF_VELOffset: flatbuffers.Offset, ECEF_ACCOffset: flatbuffers.Offset, LAT: number, LON: number, ALT: number, SPD: number, HDNG: number, COURSE: number, LCOOffset: flatbuffers.Offset, LCSOffset: flatbuffers.Offset, LC_POSOffset: flatbuffers.Offset, LC_VELOffset: flatbuffers.Offset, LC_ACCOffset: flatbuffers.Offset, E_NUVELOffset: flatbuffers.Offset, E_NUPOSOffset: flatbuffers.Offset, COVOffset: flatbuffers.Offset, ERR_ELLPOffset: flatbuffers.Offset, SRC_TYPSOffset: flatbuffers.Offset, SRC_IDSOffset: flatbuffers.Offset, CALL_SIGNOffset: flatbuffers.Offset, MULTI_SOURCE: boolean, J_SERIESOffset: flatbuffers.Offset, STRENGTH: number, M1: number, M1V: number, M2: number, M2V: number, M3A: number, M3AV: number, TAGSOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): TRKT;
    unpackTo(_o: TRKT): void;
}
export declare class TRKT implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    CNTCT: string | Uint8Array | null;
    MSG_TS: string | Uint8Array | null;
    MSN_ID: string | Uint8Array | null;
    ASSET_NAT: string | Uint8Array | null;
    ASSET: string | Uint8Array | null;
    SEN: string | Uint8Array | null;
    SEN_QUAL: string | Uint8Array | null;
    TRK_ID: string | Uint8Array | null;
    TRK_NUM: string | Uint8Array | null;
    TRK_STAT: string | Uint8Array | null;
    OBJ_NAT: string | Uint8Array | null;
    OBJ_ID: string | Uint8Array | null;
    OBJ_TYPE: string | Uint8Array | null;
    OBJ_SPEC: string | Uint8Array | null;
    OBJ_PLAT: string | Uint8Array | null;
    OBJ_ACT: string | Uint8Array | null;
    MOD_TYPE: string | Uint8Array | null;
    TRK_ITM_ID: string | Uint8Array | null;
    TS: string | Uint8Array | null;
    TRK_QUAL: number;
    TRK_PT_TYPE: string | Uint8Array | null;
    OBJ_IDENT: string | Uint8Array | null;
    IDENT_CRED: number;
    IDENT_REL: number;
    IDENT_AMP: string | Uint8Array | null;
    ENVIRONMENT: string | Uint8Array | null;
    ENVIRONMENT_CONF: number;
    TRK_CONF: number;
    ECEF_POS: (string)[];
    ECEF_VEL: (string)[];
    ECEF_ACC: (string)[];
    LAT: number;
    LON: number;
    ALT: number;
    SPD: number;
    HDNG: number;
    COURSE: number;
    LCO: (string)[];
    LCS: (string)[];
    LC_POS: (string)[];
    LC_VEL: (string)[];
    LC_ACC: (string)[];
    E_NUVEL: (string)[];
    E_NUPOS: (string)[];
    COV: (string)[];
    ERR_ELLP: (string)[];
    SRC_TYPS: (string)[];
    SRC_IDS: (string)[];
    CALL_SIGN: string | Uint8Array | null;
    MULTI_SOURCE: boolean;
    J_SERIES: string | Uint8Array | null;
    STRENGTH: number;
    M1: number;
    M1V: number;
    M2: number;
    M2V: number;
    M3A: number;
    M3AV: number;
    TAGS: (string)[];
    constructor(ID?: string | Uint8Array | null, CNTCT?: string | Uint8Array | null, MSG_TS?: string | Uint8Array | null, MSN_ID?: string | Uint8Array | null, ASSET_NAT?: string | Uint8Array | null, ASSET?: string | Uint8Array | null, SEN?: string | Uint8Array | null, SEN_QUAL?: string | Uint8Array | null, TRK_ID?: string | Uint8Array | null, TRK_NUM?: string | Uint8Array | null, TRK_STAT?: string | Uint8Array | null, OBJ_NAT?: string | Uint8Array | null, OBJ_ID?: string | Uint8Array | null, OBJ_TYPE?: string | Uint8Array | null, OBJ_SPEC?: string | Uint8Array | null, OBJ_PLAT?: string | Uint8Array | null, OBJ_ACT?: string | Uint8Array | null, MOD_TYPE?: string | Uint8Array | null, TRK_ITM_ID?: string | Uint8Array | null, TS?: string | Uint8Array | null, TRK_QUAL?: number, TRK_PT_TYPE?: string | Uint8Array | null, OBJ_IDENT?: string | Uint8Array | null, IDENT_CRED?: number, IDENT_REL?: number, IDENT_AMP?: string | Uint8Array | null, ENVIRONMENT?: string | Uint8Array | null, ENVIRONMENT_CONF?: number, TRK_CONF?: number, ECEF_POS?: (string)[], ECEF_VEL?: (string)[], ECEF_ACC?: (string)[], LAT?: number, LON?: number, ALT?: number, SPD?: number, HDNG?: number, COURSE?: number, LCO?: (string)[], LCS?: (string)[], LC_POS?: (string)[], LC_VEL?: (string)[], LC_ACC?: (string)[], E_NUVEL?: (string)[], E_NUPOS?: (string)[], COV?: (string)[], ERR_ELLP?: (string)[], SRC_TYPS?: (string)[], SRC_IDS?: (string)[], CALL_SIGN?: string | Uint8Array | null, MULTI_SOURCE?: boolean, J_SERIES?: string | Uint8Array | null, STRENGTH?: number, M1?: number, M1V?: number, M2?: number, M2V?: number, M3A?: number, M3AV?: number, TAGS?: (string)[]);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=TRK.d.ts.map