// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package SCC

import "strconv"

/// Satellite body alignment used by a 3D viewer when focused on a satellite.
type viewerSatelliteAlignmentMode int8

const (
	viewerSatelliteAlignmentModeUNKNOWN viewerSatelliteAlignmentMode = 0
	viewerSatelliteAlignmentModeORBITAL viewerSatelliteAlignmentMode = 1
	viewerSatelliteAlignmentModeNADIR   viewerSatelliteAlignmentMode = 2
)

var EnumNamesviewerSatelliteAlignmentMode = map[viewerSatelliteAlignmentMode]string{
	viewerSatelliteAlignmentModeUNKNOWN: "UNKNOWN",
	viewerSatelliteAlignmentModeORBITAL: "ORBITAL",
	viewerSatelliteAlignmentModeNADIR:   "NADIR",
}

var EnumValuesviewerSatelliteAlignmentMode = map[string]viewerSatelliteAlignmentMode{
	"UNKNOWN": viewerSatelliteAlignmentModeUNKNOWN,
	"ORBITAL": viewerSatelliteAlignmentModeORBITAL,
	"NADIR":   viewerSatelliteAlignmentModeNADIR,
}

func (v viewerSatelliteAlignmentMode) String() string {
	if s, ok := EnumNamesviewerSatelliteAlignmentMode[v]; ok {
		return s
	}
	return "viewerSatelliteAlignmentMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
