// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package REC

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Catalog query request payload.
type CAQRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCAQRequest(buf []byte, offset flatbuffers.UOffsetT) *CAQRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CAQRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishCAQRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCAQRequest(buf []byte, offset flatbuffers.UOffsetT) *CAQRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CAQRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCAQRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CAQRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CAQRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CAQRequest) KIND() catalogQueryKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return catalogQueryKind(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CAQRequest) Kind() catalogQueryKind {
	return rcv.KIND()
}

func (rcv *CAQRequest) MutateKIND(n catalogQueryKind) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *CAQRequest) MutateKind(n catalogQueryKind) bool {
	return rcv.MutateKIND(n)
}

/// Host-specific query string (for example a FlatSQL or DSL expression).
func (rcv *CAQRequest) QUERY() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CAQRequest) Query() []byte {
	return rcv.QUERY()
}

/// Host-specific query string (for example a FlatSQL or DSL expression).
/// Entity index for single-row queries.
func (rcv *CAQRequest) ENTITY_INDEX() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CAQRequest) EntityIndex() uint32 {
	return rcv.ENTITY_INDEX()
}

/// Entity index for single-row queries.
func (rcv *CAQRequest) MutateENTITY_INDEX(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *CAQRequest) MutateEntityIndex(n uint32) bool {
	return rcv.MutateENTITY_INDEX(n)
}

/// Upper bound on the number of rows / indices to return (0 = unbounded).
func (rcv *CAQRequest) MAX_COUNT() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CAQRequest) MaxCount() uint32 {
	return rcv.MAX_COUNT()
}

/// Upper bound on the number of rows / indices to return (0 = unbounded).
func (rcv *CAQRequest) MutateMAX_COUNT(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *CAQRequest) MutateMaxCount(n uint32) bool {
	return rcv.MutateMAX_COUNT(n)
}

/// Expected number of entities in the catalog at the time the request was
/// issued, used to size visibility masks.
func (rcv *CAQRequest) ENTITY_COUNT() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CAQRequest) EntityCount() uint32 {
	return rcv.ENTITY_COUNT()
}

/// Expected number of entities in the catalog at the time the request was
/// issued, used to size visibility masks.
func (rcv *CAQRequest) MutateENTITY_COUNT(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *CAQRequest) MutateEntityCount(n uint32) bool {
	return rcv.MutateENTITY_COUNT(n)
}

func CAQRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func CAQRequestAddKIND(builder *flatbuffers.Builder, KIND catalogQueryKind) {
	builder.PrependByteSlot(0, byte(KIND), 0)
}
func CAQRequestAddKind(builder *flatbuffers.Builder, KIND catalogQueryKind) {
	CAQRequestAddKIND(builder, KIND)
}
func CAQRequestAddQUERY(builder *flatbuffers.Builder, QUERY flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(QUERY), 0)
}
func CAQRequestAddQuery(builder *flatbuffers.Builder, QUERY flatbuffers.UOffsetT) {
	CAQRequestAddQUERY(builder, QUERY)
}
func CAQRequestAddENTITY_INDEX(builder *flatbuffers.Builder, ENTITY_INDEX uint32) {
	builder.PrependUint32Slot(2, ENTITY_INDEX, 0)
}
func CAQRequestAddEntityIndex(builder *flatbuffers.Builder, ENTITY_INDEX uint32) {
	CAQRequestAddENTITY_INDEX(builder, ENTITY_INDEX)
}
func CAQRequestAddMAX_COUNT(builder *flatbuffers.Builder, MAX_COUNT uint32) {
	builder.PrependUint32Slot(3, MAX_COUNT, 0)
}
func CAQRequestAddMaxCount(builder *flatbuffers.Builder, MAX_COUNT uint32) {
	CAQRequestAddMAX_COUNT(builder, MAX_COUNT)
}
func CAQRequestAddENTITY_COUNT(builder *flatbuffers.Builder, ENTITY_COUNT uint32) {
	builder.PrependUint32Slot(4, ENTITY_COUNT, 0)
}
func CAQRequestAddEntityCount(builder *flatbuffers.Builder, ENTITY_COUNT uint32) {
	CAQRequestAddENTITY_COUNT(builder, ENTITY_COUNT)
}
func CAQRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
