// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package REC

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Float parameter type
type FloatParameterType struct {
	_tab flatbuffers.Table
}

func GetRootAsFloatParameterType(buf []byte, offset flatbuffers.UOffsetT) *FloatParameterType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FloatParameterType{}
	x.Init(buf, n+offset)
	return x
}

func FinishFloatParameterTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFloatParameterType(buf []byte, offset flatbuffers.UOffsetT) *FloatParameterType {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FloatParameterType{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFloatParameterTypeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FloatParameterType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FloatParameterType) Table() flatbuffers.Table {
	return rcv._tab
}

/// Type name
func (rcv *FloatParameterType) NAME() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FloatParameterType) Name() []byte {
	return rcv.NAME()
}

/// Type name
/// Short description
func (rcv *FloatParameterType) SHORT_DESCRIPTION() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FloatParameterType) ShortDescription() []byte {
	return rcv.SHORT_DESCRIPTION()
}

/// Short description
/// Long description
func (rcv *FloatParameterType) LONG_DESCRIPTION() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FloatParameterType) LongDescription() []byte {
	return rcv.LONG_DESCRIPTION()
}

/// Long description
/// Units
func (rcv *FloatParameterType) UNITS(obj *Unit, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(Unit)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FloatParameterType) Units(obj *Unit, j int) bool {
	return rcv.UNITS(obj, j)
}

func (rcv *FloatParameterType) UNITSLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FloatParameterType) UnitsLength() int {
	return rcv.UNITSLength()
}

/// Units
/// Data encoding
func (rcv *FloatParameterType) DATA_ENCODING(obj *FloatDataEncoding) *FloatDataEncoding {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FloatDataEncoding)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *FloatParameterType) DataEncoding(obj *FloatDataEncoding) *FloatDataEncoding {
	return rcv.DATA_ENCODING(obj)
}

/// Data encoding
/// Default alarm
func (rcv *FloatParameterType) DEFAULT_ALARM(obj *DefaultAlarm) *DefaultAlarm {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DefaultAlarm)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *FloatParameterType) DefaultAlarm(obj *DefaultAlarm) *DefaultAlarm {
	return rcv.DEFAULT_ALARM(obj)
}

/// Default alarm
/// Context alarms
func (rcv *FloatParameterType) CONTEXT_ALARMS(obj *ContextAlarm, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		if obj == nil {
			obj = new(ContextAlarm)
		}
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FloatParameterType) ContextAlarms(obj *ContextAlarm, j int) bool {
	return rcv.CONTEXT_ALARMS(obj, j)
}

func (rcv *FloatParameterType) CONTEXT_ALARMSLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FloatParameterType) ContextAlarmsLength() int {
	return rcv.CONTEXT_ALARMSLength()
}

/// Context alarms
/// Minimum valid value
func (rcv *FloatParameterType) VALID_MIN() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FloatParameterType) ValidMin() float64 {
	return rcv.VALID_MIN()
}

/// Minimum valid value
func (rcv *FloatParameterType) MutateVALID_MIN(n float64) bool {
	return rcv._tab.MutateFloat64Slot(18, n)
}

func (rcv *FloatParameterType) MutateValidMin(n float64) bool {
	return rcv.MutateVALID_MIN(n)
}

/// Maximum valid value
func (rcv *FloatParameterType) VALID_MAX() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FloatParameterType) ValidMax() float64 {
	return rcv.VALID_MAX()
}

/// Maximum valid value
func (rcv *FloatParameterType) MutateVALID_MAX(n float64) bool {
	return rcv._tab.MutateFloat64Slot(20, n)
}

func (rcv *FloatParameterType) MutateValidMax(n float64) bool {
	return rcv.MutateVALID_MAX(n)
}

/// Size in bits (32 or 64)
func (rcv *FloatParameterType) SIZE_IN_BITS() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FloatParameterType) SizeInBits() uint16 {
	return rcv.SIZE_IN_BITS()
}

/// Size in bits (32 or 64)
func (rcv *FloatParameterType) MutateSIZE_IN_BITS(n uint16) bool {
	return rcv._tab.MutateUint16Slot(22, n)
}

func (rcv *FloatParameterType) MutateSizeInBits(n uint16) bool {
	return rcv.MutateSIZE_IN_BITS(n)
}

/// Initial/default value
func (rcv *FloatParameterType) INITIAL_VALUE() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FloatParameterType) InitialValue() float64 {
	return rcv.INITIAL_VALUE()
}

/// Initial/default value
func (rcv *FloatParameterType) MutateINITIAL_VALUE(n float64) bool {
	return rcv._tab.MutateFloat64Slot(24, n)
}

func (rcv *FloatParameterType) MutateInitialValue(n float64) bool {
	return rcv.MutateINITIAL_VALUE(n)
}

func FloatParameterTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func FloatParameterTypeAddNAME(builder *flatbuffers.Builder, NAME flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(NAME), 0)
}
func FloatParameterTypeAddName(builder *flatbuffers.Builder, NAME flatbuffers.UOffsetT) {
	FloatParameterTypeAddNAME(builder, NAME)
}
func FloatParameterTypeAddSHORT_DESCRIPTION(builder *flatbuffers.Builder, SHORT_DESCRIPTION flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(SHORT_DESCRIPTION), 0)
}
func FloatParameterTypeAddShortDescription(builder *flatbuffers.Builder, SHORT_DESCRIPTION flatbuffers.UOffsetT) {
	FloatParameterTypeAddSHORT_DESCRIPTION(builder, SHORT_DESCRIPTION)
}
func FloatParameterTypeAddLONG_DESCRIPTION(builder *flatbuffers.Builder, LONG_DESCRIPTION flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(LONG_DESCRIPTION), 0)
}
func FloatParameterTypeAddLongDescription(builder *flatbuffers.Builder, LONG_DESCRIPTION flatbuffers.UOffsetT) {
	FloatParameterTypeAddLONG_DESCRIPTION(builder, LONG_DESCRIPTION)
}
func FloatParameterTypeAddUNITS(builder *flatbuffers.Builder, UNITS flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(UNITS), 0)
}
func FloatParameterTypeAddUnits(builder *flatbuffers.Builder, UNITS flatbuffers.UOffsetT) {
	FloatParameterTypeAddUNITS(builder, UNITS)
}
func FloatParameterTypeStartUNITSVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FloatParameterTypeStartUnitsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return FloatParameterTypeStartUNITSVector(builder, numElems)
}
func FloatParameterTypeAddDATA_ENCODING(builder *flatbuffers.Builder, DATA_ENCODING flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(DATA_ENCODING), 0)
}
func FloatParameterTypeAddDataEncoding(builder *flatbuffers.Builder, DATA_ENCODING flatbuffers.UOffsetT) {
	FloatParameterTypeAddDATA_ENCODING(builder, DATA_ENCODING)
}
func FloatParameterTypeAddDEFAULT_ALARM(builder *flatbuffers.Builder, DEFAULT_ALARM flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(DEFAULT_ALARM), 0)
}
func FloatParameterTypeAddDefaultAlarm(builder *flatbuffers.Builder, DEFAULT_ALARM flatbuffers.UOffsetT) {
	FloatParameterTypeAddDEFAULT_ALARM(builder, DEFAULT_ALARM)
}
func FloatParameterTypeAddCONTEXT_ALARMS(builder *flatbuffers.Builder, CONTEXT_ALARMS flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(CONTEXT_ALARMS), 0)
}
func FloatParameterTypeAddContextAlarms(builder *flatbuffers.Builder, CONTEXT_ALARMS flatbuffers.UOffsetT) {
	FloatParameterTypeAddCONTEXT_ALARMS(builder, CONTEXT_ALARMS)
}
func FloatParameterTypeStartCONTEXT_ALARMSVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FloatParameterTypeStartContextAlarmsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return FloatParameterTypeStartCONTEXT_ALARMSVector(builder, numElems)
}
func FloatParameterTypeAddVALID_MIN(builder *flatbuffers.Builder, VALID_MIN float64) {
	builder.PrependFloat64Slot(7, VALID_MIN, 0.0)
}
func FloatParameterTypeAddValidMin(builder *flatbuffers.Builder, VALID_MIN float64) {
	FloatParameterTypeAddVALID_MIN(builder, VALID_MIN)
}
func FloatParameterTypeAddVALID_MAX(builder *flatbuffers.Builder, VALID_MAX float64) {
	builder.PrependFloat64Slot(8, VALID_MAX, 0.0)
}
func FloatParameterTypeAddValidMax(builder *flatbuffers.Builder, VALID_MAX float64) {
	FloatParameterTypeAddVALID_MAX(builder, VALID_MAX)
}
func FloatParameterTypeAddSIZE_IN_BITS(builder *flatbuffers.Builder, SIZE_IN_BITS uint16) {
	builder.PrependUint16Slot(9, SIZE_IN_BITS, 0)
}
func FloatParameterTypeAddSizeInBits(builder *flatbuffers.Builder, SIZE_IN_BITS uint16) {
	FloatParameterTypeAddSIZE_IN_BITS(builder, SIZE_IN_BITS)
}
func FloatParameterTypeAddINITIAL_VALUE(builder *flatbuffers.Builder, INITIAL_VALUE float64) {
	builder.PrependFloat64Slot(10, INITIAL_VALUE, 0.0)
}
func FloatParameterTypeAddInitialValue(builder *flatbuffers.Builder, INITIAL_VALUE float64) {
	FloatParameterTypeAddINITIAL_VALUE(builder, INITIAL_VALUE)
}
func FloatParameterTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
