// automatically generated by the FlatBuffers compiler, do not modify

@Suppress("unused")
class FuzeType private constructor() {
    companion object {
        const val CONTACT: Byte = 0
        const val DELAY: Byte = 1
        const val TIMED: Byte = 2
        const val PROXIMITY: Byte = 3
        const val AIRBURST: Byte = 4
        const val MAGNETIC: Byte = 5
        const val PRESSURE: Byte = 6
        const val SEISMIC: Byte = 7
    }
}
