import * as flatbuffers from 'flatbuffers';
/**
 * Spacecraft Maneuver
 */
export declare class MNV implements flatbuffers.IUnpackableObject<MNVT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): MNV;
    static getRootAsMNV(bb: flatbuffers.ByteBuffer, obj?: MNV): MNV;
    static getSizePrefixedRootAsMNV(bb: flatbuffers.ByteBuffer, obj?: MNV): MNV;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SAT_NO(): number;
    REPORT_TIME(): string | null;
    REPORT_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    EVENT_START_TIME(): string | null;
    EVENT_START_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    EVENT_END_TIME(): string | null;
    EVENT_END_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TOTAL_BURN_TIME(): number;
    OD_FIT_END_TIME(): string | null;
    OD_FIT_END_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ID_SENSOR(): string | null;
    ID_SENSOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    UCT(): boolean;
    MANEUVER_UNC(): number;
    CHARACTERIZATION(): string | null;
    CHARACTERIZATION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    CHARACTERIZATION_UNC(): number;
    EVENT_ID(): string | null;
    EVENT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_OBJECT_ID(): string | null;
    ORIG_OBJECT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_SENSOR_ID(): string | null;
    ORIG_SENSOR_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    STATUS(): string | null;
    STATUS(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DELTA_POS(): number;
    DELTA_POS_U(): number;
    DELTA_POS_V(): number;
    DELTA_POS_W(): number;
    DELTA_VEL(): number;
    DELTA_VEL_U(): number;
    DELTA_VEL_V(): number;
    DELTA_VEL_W(): number;
    DELTA_MASS(): number;
    PRE_EVENT_ID_ELSET(): string | null;
    PRE_EVENT_ID_ELSET(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    PRE_EVENT_ELSET(): string | null;
    PRE_EVENT_ELSET(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    PRE_EVENT_ID_STATE_VECTOR(): string | null;
    PRE_EVENT_ID_STATE_VECTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    PRE_EVENT_STATE_VECTOR(): string | null;
    PRE_EVENT_STATE_VECTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    PRE_POS_X(): number;
    PRE_POS_Y(): number;
    PRE_POS_Z(): number;
    PRE_VEL_X(): number;
    PRE_VEL_Y(): number;
    PRE_VEL_Z(): number;
    PRE_RADIATION_PRESS_COEFF(): number;
    PRE_BALLISTIC_COEFF(): number;
    PRE_APOGEE(): number;
    PRE_PERIGEE(): number;
    PRE_INCLINATION(): number;
    PRE_ECCENTRICITY(): number;
    PRE_PERIOD(): number;
    PRE_RAAN(): number;
    PRE_SMA(): number;
    PRE_GEO_LONGITUDE(): number;
    PRE_DRIFT_RATE(): number;
    PRE_SIGMA_U(): number;
    PRE_SIGMA_V(): number;
    PRE_SIGMA_W(): number;
    POST_EVENT_ID_ELSET(): string | null;
    POST_EVENT_ID_ELSET(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    POST_EVENT_ELSET(): string | null;
    POST_EVENT_ELSET(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    POST_EVENT_ID_STATE_VECTOR(): string | null;
    POST_EVENT_ID_STATE_VECTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    POST_EVENT_STATE_VECTOR(): string | null;
    POST_EVENT_STATE_VECTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    POST_POS_X(): number;
    POST_POS_Y(): number;
    POST_POS_Z(): number;
    POST_VEL_X(): number;
    POST_VEL_Y(): number;
    POST_VEL_Z(): number;
    POST_RADIATION_PRESS_COEFF(): number;
    POST_BALLISTIC_COEFF(): number;
    POST_APOGEE(): number;
    POST_PERIGEE(): number;
    POST_INCLINATION(): number;
    POST_ECCENTRICITY(): number;
    POST_PERIOD(): number;
    POST_RAAN(): number;
    POST_SMA(): number;
    POST_GEO_LONGITUDE(): number;
    POST_DRIFT_RATE(): number;
    POST_SIGMA_U(): number;
    POST_SIGMA_V(): number;
    POST_SIGMA_W(): number;
    COV(index: number): string;
    COV(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    covLength(): number;
    POST_MASS(): number;
    POST_AREA(): number;
    NUM_OBS(): number;
    DESCRIPTION(): string | null;
    DESCRIPTION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DESCRIPTOR(): string | null;
    DESCRIPTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    STATE_MODEL(): string | null;
    STATE_MODEL(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    STATE_MODEL_VERSION(): number;
    NUM_ACCEL_POINTS(): number;
    MNVR_ACCEL_TIMES(index: number): string;
    MNVR_ACCEL_TIMES(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    mnvrAccelTimesLength(): number;
    MNVR_ACCELS(index: number): string;
    MNVR_ACCELS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    mnvrAccelsLength(): number;
    MNVR_ACCEL_UNCS(index: number): string;
    MNVR_ACCEL_UNCS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    mnvrAccelUncsLength(): number;
    TAGS(index: number): string;
    TAGS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    tagsLength(): number;
    ALGORITHM(): string | null;
    ALGORITHM(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SOURCED_DATA(index: number): string;
    SOURCED_DATA(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    sourcedDataLength(): number;
    SOURCED_DATA_TYPES(): string | null;
    SOURCED_DATA_TYPES(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ON_ORBIT(): string | null;
    ON_ORBIT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRANSACTION_ID(): string | null;
    TRANSACTION_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    static startMNV(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addSatNo(builder: flatbuffers.Builder, SAT_NO: number): void;
    static addReportTime(builder: flatbuffers.Builder, REPORT_TIMEOffset: flatbuffers.Offset): void;
    static addEventStartTime(builder: flatbuffers.Builder, EVENT_START_TIMEOffset: flatbuffers.Offset): void;
    static addEventEndTime(builder: flatbuffers.Builder, EVENT_END_TIMEOffset: flatbuffers.Offset): void;
    static addTotalBurnTime(builder: flatbuffers.Builder, TOTAL_BURN_TIME: number): void;
    static addOdFitEndTime(builder: flatbuffers.Builder, OD_FIT_END_TIMEOffset: flatbuffers.Offset): void;
    static addIdSensor(builder: flatbuffers.Builder, ID_SENSOROffset: flatbuffers.Offset): void;
    static addUct(builder: flatbuffers.Builder, UCT: boolean): void;
    static addManeuverUnc(builder: flatbuffers.Builder, MANEUVER_UNC: number): void;
    static addCharacterization(builder: flatbuffers.Builder, CHARACTERIZATIONOffset: flatbuffers.Offset): void;
    static addCharacterizationUnc(builder: flatbuffers.Builder, CHARACTERIZATION_UNC: number): void;
    static addEventId(builder: flatbuffers.Builder, EVENT_IDOffset: flatbuffers.Offset): void;
    static addOrigObjectId(builder: flatbuffers.Builder, ORIG_OBJECT_IDOffset: flatbuffers.Offset): void;
    static addOrigSensorId(builder: flatbuffers.Builder, ORIG_SENSOR_IDOffset: flatbuffers.Offset): void;
    static addStatus(builder: flatbuffers.Builder, STATUSOffset: flatbuffers.Offset): void;
    static addDeltaPos(builder: flatbuffers.Builder, DELTA_POS: number): void;
    static addDeltaPosU(builder: flatbuffers.Builder, DELTA_POS_U: number): void;
    static addDeltaPosV(builder: flatbuffers.Builder, DELTA_POS_V: number): void;
    static addDeltaPosW(builder: flatbuffers.Builder, DELTA_POS_W: number): void;
    static addDeltaVel(builder: flatbuffers.Builder, DELTA_VEL: number): void;
    static addDeltaVelU(builder: flatbuffers.Builder, DELTA_VEL_U: number): void;
    static addDeltaVelV(builder: flatbuffers.Builder, DELTA_VEL_V: number): void;
    static addDeltaVelW(builder: flatbuffers.Builder, DELTA_VEL_W: number): void;
    static addDeltaMass(builder: flatbuffers.Builder, DELTA_MASS: number): void;
    static addPreEventIdElset(builder: flatbuffers.Builder, PRE_EVENT_ID_ELSETOffset: flatbuffers.Offset): void;
    static addPreEventElset(builder: flatbuffers.Builder, PRE_EVENT_ELSETOffset: flatbuffers.Offset): void;
    static addPreEventIdStateVector(builder: flatbuffers.Builder, PRE_EVENT_ID_STATE_VECTOROffset: flatbuffers.Offset): void;
    static addPreEventStateVector(builder: flatbuffers.Builder, PRE_EVENT_STATE_VECTOROffset: flatbuffers.Offset): void;
    static addPrePosX(builder: flatbuffers.Builder, PRE_POS_X: number): void;
    static addPrePosY(builder: flatbuffers.Builder, PRE_POS_Y: number): void;
    static addPrePosZ(builder: flatbuffers.Builder, PRE_POS_Z: number): void;
    static addPreVelX(builder: flatbuffers.Builder, PRE_VEL_X: number): void;
    static addPreVelY(builder: flatbuffers.Builder, PRE_VEL_Y: number): void;
    static addPreVelZ(builder: flatbuffers.Builder, PRE_VEL_Z: number): void;
    static addPreRadiationPressCoeff(builder: flatbuffers.Builder, PRE_RADIATION_PRESS_COEFF: number): void;
    static addPreBallisticCoeff(builder: flatbuffers.Builder, PRE_BALLISTIC_COEFF: number): void;
    static addPreApogee(builder: flatbuffers.Builder, PRE_APOGEE: number): void;
    static addPrePerigee(builder: flatbuffers.Builder, PRE_PERIGEE: number): void;
    static addPreInclination(builder: flatbuffers.Builder, PRE_INCLINATION: number): void;
    static addPreEccentricity(builder: flatbuffers.Builder, PRE_ECCENTRICITY: number): void;
    static addPrePeriod(builder: flatbuffers.Builder, PRE_PERIOD: number): void;
    static addPreRaan(builder: flatbuffers.Builder, PRE_RAAN: number): void;
    static addPreSma(builder: flatbuffers.Builder, PRE_SMA: number): void;
    static addPreGeoLongitude(builder: flatbuffers.Builder, PRE_GEO_LONGITUDE: number): void;
    static addPreDriftRate(builder: flatbuffers.Builder, PRE_DRIFT_RATE: number): void;
    static addPreSigmaU(builder: flatbuffers.Builder, PRE_SIGMA_U: number): void;
    static addPreSigmaV(builder: flatbuffers.Builder, PRE_SIGMA_V: number): void;
    static addPreSigmaW(builder: flatbuffers.Builder, PRE_SIGMA_W: number): void;
    static addPostEventIdElset(builder: flatbuffers.Builder, POST_EVENT_ID_ELSETOffset: flatbuffers.Offset): void;
    static addPostEventElset(builder: flatbuffers.Builder, POST_EVENT_ELSETOffset: flatbuffers.Offset): void;
    static addPostEventIdStateVector(builder: flatbuffers.Builder, POST_EVENT_ID_STATE_VECTOROffset: flatbuffers.Offset): void;
    static addPostEventStateVector(builder: flatbuffers.Builder, POST_EVENT_STATE_VECTOROffset: flatbuffers.Offset): void;
    static addPostPosX(builder: flatbuffers.Builder, POST_POS_X: number): void;
    static addPostPosY(builder: flatbuffers.Builder, POST_POS_Y: number): void;
    static addPostPosZ(builder: flatbuffers.Builder, POST_POS_Z: number): void;
    static addPostVelX(builder: flatbuffers.Builder, POST_VEL_X: number): void;
    static addPostVelY(builder: flatbuffers.Builder, POST_VEL_Y: number): void;
    static addPostVelZ(builder: flatbuffers.Builder, POST_VEL_Z: number): void;
    static addPostRadiationPressCoeff(builder: flatbuffers.Builder, POST_RADIATION_PRESS_COEFF: number): void;
    static addPostBallisticCoeff(builder: flatbuffers.Builder, POST_BALLISTIC_COEFF: number): void;
    static addPostApogee(builder: flatbuffers.Builder, POST_APOGEE: number): void;
    static addPostPerigee(builder: flatbuffers.Builder, POST_PERIGEE: number): void;
    static addPostInclination(builder: flatbuffers.Builder, POST_INCLINATION: number): void;
    static addPostEccentricity(builder: flatbuffers.Builder, POST_ECCENTRICITY: number): void;
    static addPostPeriod(builder: flatbuffers.Builder, POST_PERIOD: number): void;
    static addPostRaan(builder: flatbuffers.Builder, POST_RAAN: number): void;
    static addPostSma(builder: flatbuffers.Builder, POST_SMA: number): void;
    static addPostGeoLongitude(builder: flatbuffers.Builder, POST_GEO_LONGITUDE: number): void;
    static addPostDriftRate(builder: flatbuffers.Builder, POST_DRIFT_RATE: number): void;
    static addPostSigmaU(builder: flatbuffers.Builder, POST_SIGMA_U: number): void;
    static addPostSigmaV(builder: flatbuffers.Builder, POST_SIGMA_V: number): void;
    static addPostSigmaW(builder: flatbuffers.Builder, POST_SIGMA_W: number): void;
    static addCov(builder: flatbuffers.Builder, COVOffset: flatbuffers.Offset): void;
    static createCovVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startCovVector(builder: flatbuffers.Builder, numElems: number): void;
    static addPostMass(builder: flatbuffers.Builder, POST_MASS: number): void;
    static addPostArea(builder: flatbuffers.Builder, POST_AREA: number): void;
    static addNumObs(builder: flatbuffers.Builder, NUM_OBS: number): void;
    static addDescription(builder: flatbuffers.Builder, DESCRIPTIONOffset: flatbuffers.Offset): void;
    static addDescriptor(builder: flatbuffers.Builder, DESCRIPTOROffset: flatbuffers.Offset): void;
    static addStateModel(builder: flatbuffers.Builder, STATE_MODELOffset: flatbuffers.Offset): void;
    static addStateModelVersion(builder: flatbuffers.Builder, STATE_MODEL_VERSION: number): void;
    static addNumAccelPoints(builder: flatbuffers.Builder, NUM_ACCEL_POINTS: number): void;
    static addMnvrAccelTimes(builder: flatbuffers.Builder, MNVR_ACCEL_TIMESOffset: flatbuffers.Offset): void;
    static createMnvrAccelTimesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startMnvrAccelTimesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addMnvrAccels(builder: flatbuffers.Builder, MNVR_ACCELSOffset: flatbuffers.Offset): void;
    static createMnvrAccelsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startMnvrAccelsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addMnvrAccelUncs(builder: flatbuffers.Builder, MNVR_ACCEL_UNCSOffset: flatbuffers.Offset): void;
    static createMnvrAccelUncsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startMnvrAccelUncsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addTags(builder: flatbuffers.Builder, TAGSOffset: flatbuffers.Offset): void;
    static createTagsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startTagsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addAlgorithm(builder: flatbuffers.Builder, ALGORITHMOffset: flatbuffers.Offset): void;
    static addSourcedData(builder: flatbuffers.Builder, SOURCED_DATAOffset: flatbuffers.Offset): void;
    static createSourcedDataVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startSourcedDataVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSourcedDataTypes(builder: flatbuffers.Builder, SOURCED_DATA_TYPESOffset: flatbuffers.Offset): void;
    static addOnOrbit(builder: flatbuffers.Builder, ON_ORBITOffset: flatbuffers.Offset): void;
    static addTransactionId(builder: flatbuffers.Builder, TRANSACTION_IDOffset: flatbuffers.Offset): void;
    static endMNV(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishMNVBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedMNVBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createMNV(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, SAT_NO: number, REPORT_TIMEOffset: flatbuffers.Offset, EVENT_START_TIMEOffset: flatbuffers.Offset, EVENT_END_TIMEOffset: flatbuffers.Offset, TOTAL_BURN_TIME: number, OD_FIT_END_TIMEOffset: flatbuffers.Offset, ID_SENSOROffset: flatbuffers.Offset, UCT: boolean, MANEUVER_UNC: number, CHARACTERIZATIONOffset: flatbuffers.Offset, CHARACTERIZATION_UNC: number, EVENT_IDOffset: flatbuffers.Offset, ORIG_OBJECT_IDOffset: flatbuffers.Offset, ORIG_SENSOR_IDOffset: flatbuffers.Offset, STATUSOffset: flatbuffers.Offset, DELTA_POS: number, DELTA_POS_U: number, DELTA_POS_V: number, DELTA_POS_W: number, DELTA_VEL: number, DELTA_VEL_U: number, DELTA_VEL_V: number, DELTA_VEL_W: number, DELTA_MASS: number, PRE_EVENT_ID_ELSETOffset: flatbuffers.Offset, PRE_EVENT_ELSETOffset: flatbuffers.Offset, PRE_EVENT_ID_STATE_VECTOROffset: flatbuffers.Offset, PRE_EVENT_STATE_VECTOROffset: flatbuffers.Offset, PRE_POS_X: number, PRE_POS_Y: number, PRE_POS_Z: number, PRE_VEL_X: number, PRE_VEL_Y: number, PRE_VEL_Z: number, PRE_RADIATION_PRESS_COEFF: number, PRE_BALLISTIC_COEFF: number, PRE_APOGEE: number, PRE_PERIGEE: number, PRE_INCLINATION: number, PRE_ECCENTRICITY: number, PRE_PERIOD: number, PRE_RAAN: number, PRE_SMA: number, PRE_GEO_LONGITUDE: number, PRE_DRIFT_RATE: number, PRE_SIGMA_U: number, PRE_SIGMA_V: number, PRE_SIGMA_W: number, POST_EVENT_ID_ELSETOffset: flatbuffers.Offset, POST_EVENT_ELSETOffset: flatbuffers.Offset, POST_EVENT_ID_STATE_VECTOROffset: flatbuffers.Offset, POST_EVENT_STATE_VECTOROffset: flatbuffers.Offset, POST_POS_X: number, POST_POS_Y: number, POST_POS_Z: number, POST_VEL_X: number, POST_VEL_Y: number, POST_VEL_Z: number, POST_RADIATION_PRESS_COEFF: number, POST_BALLISTIC_COEFF: number, POST_APOGEE: number, POST_PERIGEE: number, POST_INCLINATION: number, POST_ECCENTRICITY: number, POST_PERIOD: number, POST_RAAN: number, POST_SMA: number, POST_GEO_LONGITUDE: number, POST_DRIFT_RATE: number, POST_SIGMA_U: number, POST_SIGMA_V: number, POST_SIGMA_W: number, COVOffset: flatbuffers.Offset, POST_MASS: number, POST_AREA: number, NUM_OBS: number, DESCRIPTIONOffset: flatbuffers.Offset, DESCRIPTOROffset: flatbuffers.Offset, STATE_MODELOffset: flatbuffers.Offset, STATE_MODEL_VERSION: number, NUM_ACCEL_POINTS: number, MNVR_ACCEL_TIMESOffset: flatbuffers.Offset, MNVR_ACCELSOffset: flatbuffers.Offset, MNVR_ACCEL_UNCSOffset: flatbuffers.Offset, TAGSOffset: flatbuffers.Offset, ALGORITHMOffset: flatbuffers.Offset, SOURCED_DATAOffset: flatbuffers.Offset, SOURCED_DATA_TYPESOffset: flatbuffers.Offset, ON_ORBITOffset: flatbuffers.Offset, TRANSACTION_IDOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): MNVT;
    unpackTo(_o: MNVT): void;
}
export declare class MNVT implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    SAT_NO: number;
    REPORT_TIME: string | Uint8Array | null;
    EVENT_START_TIME: string | Uint8Array | null;
    EVENT_END_TIME: string | Uint8Array | null;
    TOTAL_BURN_TIME: number;
    OD_FIT_END_TIME: string | Uint8Array | null;
    ID_SENSOR: string | Uint8Array | null;
    UCT: boolean;
    MANEUVER_UNC: number;
    CHARACTERIZATION: string | Uint8Array | null;
    CHARACTERIZATION_UNC: number;
    EVENT_ID: string | Uint8Array | null;
    ORIG_OBJECT_ID: string | Uint8Array | null;
    ORIG_SENSOR_ID: string | Uint8Array | null;
    STATUS: string | Uint8Array | null;
    DELTA_POS: number;
    DELTA_POS_U: number;
    DELTA_POS_V: number;
    DELTA_POS_W: number;
    DELTA_VEL: number;
    DELTA_VEL_U: number;
    DELTA_VEL_V: number;
    DELTA_VEL_W: number;
    DELTA_MASS: number;
    PRE_EVENT_ID_ELSET: string | Uint8Array | null;
    PRE_EVENT_ELSET: string | Uint8Array | null;
    PRE_EVENT_ID_STATE_VECTOR: string | Uint8Array | null;
    PRE_EVENT_STATE_VECTOR: string | Uint8Array | null;
    PRE_POS_X: number;
    PRE_POS_Y: number;
    PRE_POS_Z: number;
    PRE_VEL_X: number;
    PRE_VEL_Y: number;
    PRE_VEL_Z: number;
    PRE_RADIATION_PRESS_COEFF: number;
    PRE_BALLISTIC_COEFF: number;
    PRE_APOGEE: number;
    PRE_PERIGEE: number;
    PRE_INCLINATION: number;
    PRE_ECCENTRICITY: number;
    PRE_PERIOD: number;
    PRE_RAAN: number;
    PRE_SMA: number;
    PRE_GEO_LONGITUDE: number;
    PRE_DRIFT_RATE: number;
    PRE_SIGMA_U: number;
    PRE_SIGMA_V: number;
    PRE_SIGMA_W: number;
    POST_EVENT_ID_ELSET: string | Uint8Array | null;
    POST_EVENT_ELSET: string | Uint8Array | null;
    POST_EVENT_ID_STATE_VECTOR: string | Uint8Array | null;
    POST_EVENT_STATE_VECTOR: string | Uint8Array | null;
    POST_POS_X: number;
    POST_POS_Y: number;
    POST_POS_Z: number;
    POST_VEL_X: number;
    POST_VEL_Y: number;
    POST_VEL_Z: number;
    POST_RADIATION_PRESS_COEFF: number;
    POST_BALLISTIC_COEFF: number;
    POST_APOGEE: number;
    POST_PERIGEE: number;
    POST_INCLINATION: number;
    POST_ECCENTRICITY: number;
    POST_PERIOD: number;
    POST_RAAN: number;
    POST_SMA: number;
    POST_GEO_LONGITUDE: number;
    POST_DRIFT_RATE: number;
    POST_SIGMA_U: number;
    POST_SIGMA_V: number;
    POST_SIGMA_W: number;
    COV: (string)[];
    POST_MASS: number;
    POST_AREA: number;
    NUM_OBS: number;
    DESCRIPTION: string | Uint8Array | null;
    DESCRIPTOR: string | Uint8Array | null;
    STATE_MODEL: string | Uint8Array | null;
    STATE_MODEL_VERSION: number;
    NUM_ACCEL_POINTS: number;
    MNVR_ACCEL_TIMES: (string)[];
    MNVR_ACCELS: (string)[];
    MNVR_ACCEL_UNCS: (string)[];
    TAGS: (string)[];
    ALGORITHM: string | Uint8Array | null;
    SOURCED_DATA: (string)[];
    SOURCED_DATA_TYPES: string | Uint8Array | null;
    ON_ORBIT: string | Uint8Array | null;
    TRANSACTION_ID: string | Uint8Array | null;
    constructor(ID?: string | Uint8Array | null, SAT_NO?: number, REPORT_TIME?: string | Uint8Array | null, EVENT_START_TIME?: string | Uint8Array | null, EVENT_END_TIME?: string | Uint8Array | null, TOTAL_BURN_TIME?: number, OD_FIT_END_TIME?: string | Uint8Array | null, ID_SENSOR?: string | Uint8Array | null, UCT?: boolean, MANEUVER_UNC?: number, CHARACTERIZATION?: string | Uint8Array | null, CHARACTERIZATION_UNC?: number, EVENT_ID?: string | Uint8Array | null, ORIG_OBJECT_ID?: string | Uint8Array | null, ORIG_SENSOR_ID?: string | Uint8Array | null, STATUS?: string | Uint8Array | null, DELTA_POS?: number, DELTA_POS_U?: number, DELTA_POS_V?: number, DELTA_POS_W?: number, DELTA_VEL?: number, DELTA_VEL_U?: number, DELTA_VEL_V?: number, DELTA_VEL_W?: number, DELTA_MASS?: number, PRE_EVENT_ID_ELSET?: string | Uint8Array | null, PRE_EVENT_ELSET?: string | Uint8Array | null, PRE_EVENT_ID_STATE_VECTOR?: string | Uint8Array | null, PRE_EVENT_STATE_VECTOR?: string | Uint8Array | null, PRE_POS_X?: number, PRE_POS_Y?: number, PRE_POS_Z?: number, PRE_VEL_X?: number, PRE_VEL_Y?: number, PRE_VEL_Z?: number, PRE_RADIATION_PRESS_COEFF?: number, PRE_BALLISTIC_COEFF?: number, PRE_APOGEE?: number, PRE_PERIGEE?: number, PRE_INCLINATION?: number, PRE_ECCENTRICITY?: number, PRE_PERIOD?: number, PRE_RAAN?: number, PRE_SMA?: number, PRE_GEO_LONGITUDE?: number, PRE_DRIFT_RATE?: number, PRE_SIGMA_U?: number, PRE_SIGMA_V?: number, PRE_SIGMA_W?: number, POST_EVENT_ID_ELSET?: string | Uint8Array | null, POST_EVENT_ELSET?: string | Uint8Array | null, POST_EVENT_ID_STATE_VECTOR?: string | Uint8Array | null, POST_EVENT_STATE_VECTOR?: string | Uint8Array | null, POST_POS_X?: number, POST_POS_Y?: number, POST_POS_Z?: number, POST_VEL_X?: number, POST_VEL_Y?: number, POST_VEL_Z?: number, POST_RADIATION_PRESS_COEFF?: number, POST_BALLISTIC_COEFF?: number, POST_APOGEE?: number, POST_PERIGEE?: number, POST_INCLINATION?: number, POST_ECCENTRICITY?: number, POST_PERIOD?: number, POST_RAAN?: number, POST_SMA?: number, POST_GEO_LONGITUDE?: number, POST_DRIFT_RATE?: number, POST_SIGMA_U?: number, POST_SIGMA_V?: number, POST_SIGMA_W?: number, COV?: (string)[], POST_MASS?: number, POST_AREA?: number, NUM_OBS?: number, DESCRIPTION?: string | Uint8Array | null, DESCRIPTOR?: string | Uint8Array | null, STATE_MODEL?: string | Uint8Array | null, STATE_MODEL_VERSION?: number, NUM_ACCEL_POINTS?: number, MNVR_ACCEL_TIMES?: (string)[], MNVR_ACCELS?: (string)[], MNVR_ACCEL_UNCS?: (string)[], TAGS?: (string)[], ALGORITHM?: string | Uint8Array | null, SOURCED_DATA?: (string)[], SOURCED_DATA_TYPES?: string | Uint8Array | null, ON_ORBIT?: string | Uint8Array | null, TRANSACTION_ID?: string | Uint8Array | null);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=MNV.d.ts.map