import * as flatbuffers from 'flatbuffers';
/**
 * Guided Missiles
 */
export declare class MSL implements flatbuffers.IUnpackableObject<MSLT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): MSL;
    static getRootAsMSL(bb: flatbuffers.ByteBuffer, obj?: MSL): MSL;
    static getSizePrefixedRootAsMSL(bb: flatbuffers.ByteBuffer, obj?: MSL): MSL;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    POSITION_X(): number;
    POSITION_Y(): number;
    POSITION_Z(): number;
    VELOCITY_X(): number;
    VELOCITY_Y(): number;
    VELOCITY_Z(): number;
    ATTITUDE_X(): number;
    ATTITUDE_Y(): number;
    ATTITUDE_Z(): number;
    ATTITUDE_W(): number;
    OMEGA_X(): number;
    OMEGA_Y(): number;
    OMEGA_Z(): number;
    MASS(): number;
    MASS_INITIAL(): number;
    TARGET_POSITION_X(): number;
    TARGET_POSITION_Y(): number;
    TARGET_POSITION_Z(): number;
    TARGET_VELOCITY_X(): number;
    TARGET_VELOCITY_Y(): number;
    TARGET_VELOCITY_Z(): number;
    MISS_DISTANCE(): number;
    SEEKER(): string | null;
    SEEKER(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    MOTOR(): string | null;
    MOTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    GUIDANCE_CMD(): string | null;
    GUIDANCE_CMD(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    PHASE(): number;
    GUIDANCE_LAW(): number;
    TYPE(): number;
    ARMED(): number;
    TIME_OF_FLIGHT(): number;
    MAX_G(): number;
    RESERVED(index: number): number | null;
    reservedLength(): number;
    reservedArray(): Uint8Array | null;
    static startMSL(builder: flatbuffers.Builder): void;
    static addPositionX(builder: flatbuffers.Builder, POSITION_X: number): void;
    static addPositionY(builder: flatbuffers.Builder, POSITION_Y: number): void;
    static addPositionZ(builder: flatbuffers.Builder, POSITION_Z: number): void;
    static addVelocityX(builder: flatbuffers.Builder, VELOCITY_X: number): void;
    static addVelocityY(builder: flatbuffers.Builder, VELOCITY_Y: number): void;
    static addVelocityZ(builder: flatbuffers.Builder, VELOCITY_Z: number): void;
    static addAttitudeX(builder: flatbuffers.Builder, ATTITUDE_X: number): void;
    static addAttitudeY(builder: flatbuffers.Builder, ATTITUDE_Y: number): void;
    static addAttitudeZ(builder: flatbuffers.Builder, ATTITUDE_Z: number): void;
    static addAttitudeW(builder: flatbuffers.Builder, ATTITUDE_W: number): void;
    static addOmegaX(builder: flatbuffers.Builder, OMEGA_X: number): void;
    static addOmegaY(builder: flatbuffers.Builder, OMEGA_Y: number): void;
    static addOmegaZ(builder: flatbuffers.Builder, OMEGA_Z: number): void;
    static addMass(builder: flatbuffers.Builder, MASS: number): void;
    static addMassInitial(builder: flatbuffers.Builder, MASS_INITIAL: number): void;
    static addTargetPositionX(builder: flatbuffers.Builder, TARGET_POSITION_X: number): void;
    static addTargetPositionY(builder: flatbuffers.Builder, TARGET_POSITION_Y: number): void;
    static addTargetPositionZ(builder: flatbuffers.Builder, TARGET_POSITION_Z: number): void;
    static addTargetVelocityX(builder: flatbuffers.Builder, TARGET_VELOCITY_X: number): void;
    static addTargetVelocityY(builder: flatbuffers.Builder, TARGET_VELOCITY_Y: number): void;
    static addTargetVelocityZ(builder: flatbuffers.Builder, TARGET_VELOCITY_Z: number): void;
    static addMissDistance(builder: flatbuffers.Builder, MISS_DISTANCE: number): void;
    static addSeeker(builder: flatbuffers.Builder, SEEKEROffset: flatbuffers.Offset): void;
    static addMotor(builder: flatbuffers.Builder, MOTOROffset: flatbuffers.Offset): void;
    static addGuidanceCmd(builder: flatbuffers.Builder, GUIDANCE_CMDOffset: flatbuffers.Offset): void;
    static addPhase(builder: flatbuffers.Builder, PHASE: number): void;
    static addGuidanceLaw(builder: flatbuffers.Builder, GUIDANCE_LAW: number): void;
    static addType(builder: flatbuffers.Builder, TYPE: number): void;
    static addArmed(builder: flatbuffers.Builder, ARMED: number): void;
    static addTimeOfFlight(builder: flatbuffers.Builder, TIME_OF_FLIGHT: number): void;
    static addMaxG(builder: flatbuffers.Builder, MAX_G: number): void;
    static addReserved(builder: flatbuffers.Builder, RESERVEDOffset: flatbuffers.Offset): void;
    static createReservedVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset;
    static startReservedVector(builder: flatbuffers.Builder, numElems: number): void;
    static endMSL(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishMSLBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedMSLBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createMSL(builder: flatbuffers.Builder, POSITION_X: number, POSITION_Y: number, POSITION_Z: number, VELOCITY_X: number, VELOCITY_Y: number, VELOCITY_Z: number, ATTITUDE_X: number, ATTITUDE_Y: number, ATTITUDE_Z: number, ATTITUDE_W: number, OMEGA_X: number, OMEGA_Y: number, OMEGA_Z: number, MASS: number, MASS_INITIAL: number, TARGET_POSITION_X: number, TARGET_POSITION_Y: number, TARGET_POSITION_Z: number, TARGET_VELOCITY_X: number, TARGET_VELOCITY_Y: number, TARGET_VELOCITY_Z: number, MISS_DISTANCE: number, SEEKEROffset: flatbuffers.Offset, MOTOROffset: flatbuffers.Offset, GUIDANCE_CMDOffset: flatbuffers.Offset, PHASE: number, GUIDANCE_LAW: number, TYPE: number, ARMED: number, TIME_OF_FLIGHT: number, MAX_G: number, RESERVEDOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): MSLT;
    unpackTo(_o: MSLT): void;
}
export declare class MSLT implements flatbuffers.IGeneratedObject {
    POSITION_X: number;
    POSITION_Y: number;
    POSITION_Z: number;
    VELOCITY_X: number;
    VELOCITY_Y: number;
    VELOCITY_Z: number;
    ATTITUDE_X: number;
    ATTITUDE_Y: number;
    ATTITUDE_Z: number;
    ATTITUDE_W: number;
    OMEGA_X: number;
    OMEGA_Y: number;
    OMEGA_Z: number;
    MASS: number;
    MASS_INITIAL: number;
    TARGET_POSITION_X: number;
    TARGET_POSITION_Y: number;
    TARGET_POSITION_Z: number;
    TARGET_VELOCITY_X: number;
    TARGET_VELOCITY_Y: number;
    TARGET_VELOCITY_Z: number;
    MISS_DISTANCE: number;
    SEEKER: string | Uint8Array | null;
    MOTOR: string | Uint8Array | null;
    GUIDANCE_CMD: string | Uint8Array | null;
    PHASE: number;
    GUIDANCE_LAW: number;
    TYPE: number;
    ARMED: number;
    TIME_OF_FLIGHT: number;
    MAX_G: number;
    RESERVED: (number)[];
    constructor(POSITION_X?: number, POSITION_Y?: number, POSITION_Z?: number, VELOCITY_X?: number, VELOCITY_Y?: number, VELOCITY_Z?: number, ATTITUDE_X?: number, ATTITUDE_Y?: number, ATTITUDE_Z?: number, ATTITUDE_W?: number, OMEGA_X?: number, OMEGA_Y?: number, OMEGA_Z?: number, MASS?: number, MASS_INITIAL?: number, TARGET_POSITION_X?: number, TARGET_POSITION_Y?: number, TARGET_POSITION_Z?: number, TARGET_VELOCITY_X?: number, TARGET_VELOCITY_Y?: number, TARGET_VELOCITY_Z?: number, MISS_DISTANCE?: number, SEEKER?: string | Uint8Array | null, MOTOR?: string | Uint8Array | null, GUIDANCE_CMD?: string | Uint8Array | null, PHASE?: number, GUIDANCE_LAW?: number, TYPE?: number, ARMED?: number, TIME_OF_FLIGHT?: number, MAX_G?: number, RESERVED?: (number)[]);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=MSL.d.ts.map