import * as flatbuffers from 'flatbuffers';
/**
 * Naval Vessels
 */
export declare class NAV implements flatbuffers.IUnpackableObject<NAVT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): NAV;
    static getRootAsNAV(bb: flatbuffers.ByteBuffer, obj?: NAV): NAV;
    static getSizePrefixedRootAsNAV(bb: flatbuffers.ByteBuffer, obj?: NAV): NAV;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    POSITION_X(): number;
    POSITION_Y(): number;
    POSITION_Z(): number;
    VELOCITY_X(): number;
    VELOCITY_Y(): number;
    VELOCITY_Z(): number;
    ATTITUDE_X(): number;
    ATTITUDE_Y(): number;
    ATTITUDE_Z(): number;
    ATTITUDE_W(): number;
    OMEGA_X(): number;
    OMEGA_Y(): number;
    OMEGA_Z(): number;
    SPEED_KNOTS(): number;
    HEADING(): number;
    COURSE(): number;
    RUDDER_ANGLE(): number;
    HULL(): string | null;
    HULL(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    PROPULSION(): string | null;
    PROPULSION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DC_STATE(): number;
    FIRES_ACTIVE(): number;
    FLOODING_ACTIVE(): number;
    CREW_CASUALTIES(): number;
    HULL_INTEGRITY(): number;
    POWER_AVAILABLE(): number;
    WEAPONS_ONLINE(): number;
    SENSORS_ONLINE(): number;
    RESERVED1(): number;
    FUEL_REMAINING(): number;
    AMMO_MAIN(): number;
    MISSILES_REMAINING(): number;
    TORPEDOES_REMAINING(): number;
    VESSEL_TYPE(): number;
    PROPULSION_TYPE(): number;
    RESERVED(index: number): number | null;
    reservedLength(): number;
    reservedArray(): Uint8Array | null;
    static startNAV(builder: flatbuffers.Builder): void;
    static addPositionX(builder: flatbuffers.Builder, POSITION_X: number): void;
    static addPositionY(builder: flatbuffers.Builder, POSITION_Y: number): void;
    static addPositionZ(builder: flatbuffers.Builder, POSITION_Z: number): void;
    static addVelocityX(builder: flatbuffers.Builder, VELOCITY_X: number): void;
    static addVelocityY(builder: flatbuffers.Builder, VELOCITY_Y: number): void;
    static addVelocityZ(builder: flatbuffers.Builder, VELOCITY_Z: number): void;
    static addAttitudeX(builder: flatbuffers.Builder, ATTITUDE_X: number): void;
    static addAttitudeY(builder: flatbuffers.Builder, ATTITUDE_Y: number): void;
    static addAttitudeZ(builder: flatbuffers.Builder, ATTITUDE_Z: number): void;
    static addAttitudeW(builder: flatbuffers.Builder, ATTITUDE_W: number): void;
    static addOmegaX(builder: flatbuffers.Builder, OMEGA_X: number): void;
    static addOmegaY(builder: flatbuffers.Builder, OMEGA_Y: number): void;
    static addOmegaZ(builder: flatbuffers.Builder, OMEGA_Z: number): void;
    static addSpeedKnots(builder: flatbuffers.Builder, SPEED_KNOTS: number): void;
    static addHeading(builder: flatbuffers.Builder, HEADING: number): void;
    static addCourse(builder: flatbuffers.Builder, COURSE: number): void;
    static addRudderAngle(builder: flatbuffers.Builder, RUDDER_ANGLE: number): void;
    static addHull(builder: flatbuffers.Builder, HULLOffset: flatbuffers.Offset): void;
    static addPropulsion(builder: flatbuffers.Builder, PROPULSIONOffset: flatbuffers.Offset): void;
    static addDcState(builder: flatbuffers.Builder, DC_STATE: number): void;
    static addFiresActive(builder: flatbuffers.Builder, FIRES_ACTIVE: number): void;
    static addFloodingActive(builder: flatbuffers.Builder, FLOODING_ACTIVE: number): void;
    static addCrewCasualties(builder: flatbuffers.Builder, CREW_CASUALTIES: number): void;
    static addHullIntegrity(builder: flatbuffers.Builder, HULL_INTEGRITY: number): void;
    static addPowerAvailable(builder: flatbuffers.Builder, POWER_AVAILABLE: number): void;
    static addWeaponsOnline(builder: flatbuffers.Builder, WEAPONS_ONLINE: number): void;
    static addSensorsOnline(builder: flatbuffers.Builder, SENSORS_ONLINE: number): void;
    static addReserved1(builder: flatbuffers.Builder, RESERVED1: number): void;
    static addFuelRemaining(builder: flatbuffers.Builder, FUEL_REMAINING: number): void;
    static addAmmoMain(builder: flatbuffers.Builder, AMMO_MAIN: number): void;
    static addMissilesRemaining(builder: flatbuffers.Builder, MISSILES_REMAINING: number): void;
    static addTorpedoesRemaining(builder: flatbuffers.Builder, TORPEDOES_REMAINING: number): void;
    static addVesselType(builder: flatbuffers.Builder, VESSEL_TYPE: number): void;
    static addPropulsionType(builder: flatbuffers.Builder, PROPULSION_TYPE: number): void;
    static addReserved(builder: flatbuffers.Builder, RESERVEDOffset: flatbuffers.Offset): void;
    static createReservedVector(builder: flatbuffers.Builder, data: number[] | Uint8Array): flatbuffers.Offset;
    static startReservedVector(builder: flatbuffers.Builder, numElems: number): void;
    static endNAV(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishNAVBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedNAVBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createNAV(builder: flatbuffers.Builder, POSITION_X: number, POSITION_Y: number, POSITION_Z: number, VELOCITY_X: number, VELOCITY_Y: number, VELOCITY_Z: number, ATTITUDE_X: number, ATTITUDE_Y: number, ATTITUDE_Z: number, ATTITUDE_W: number, OMEGA_X: number, OMEGA_Y: number, OMEGA_Z: number, SPEED_KNOTS: number, HEADING: number, COURSE: number, RUDDER_ANGLE: number, HULLOffset: flatbuffers.Offset, PROPULSIONOffset: flatbuffers.Offset, DC_STATE: number, FIRES_ACTIVE: number, FLOODING_ACTIVE: number, CREW_CASUALTIES: number, HULL_INTEGRITY: number, POWER_AVAILABLE: number, WEAPONS_ONLINE: number, SENSORS_ONLINE: number, RESERVED1: number, FUEL_REMAINING: number, AMMO_MAIN: number, MISSILES_REMAINING: number, TORPEDOES_REMAINING: number, VESSEL_TYPE: number, PROPULSION_TYPE: number, RESERVEDOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): NAVT;
    unpackTo(_o: NAVT): void;
}
export declare class NAVT implements flatbuffers.IGeneratedObject {
    POSITION_X: number;
    POSITION_Y: number;
    POSITION_Z: number;
    VELOCITY_X: number;
    VELOCITY_Y: number;
    VELOCITY_Z: number;
    ATTITUDE_X: number;
    ATTITUDE_Y: number;
    ATTITUDE_Z: number;
    ATTITUDE_W: number;
    OMEGA_X: number;
    OMEGA_Y: number;
    OMEGA_Z: number;
    SPEED_KNOTS: number;
    HEADING: number;
    COURSE: number;
    RUDDER_ANGLE: number;
    HULL: string | Uint8Array | null;
    PROPULSION: string | Uint8Array | null;
    DC_STATE: number;
    FIRES_ACTIVE: number;
    FLOODING_ACTIVE: number;
    CREW_CASUALTIES: number;
    HULL_INTEGRITY: number;
    POWER_AVAILABLE: number;
    WEAPONS_ONLINE: number;
    SENSORS_ONLINE: number;
    RESERVED1: number;
    FUEL_REMAINING: number;
    AMMO_MAIN: number;
    MISSILES_REMAINING: number;
    TORPEDOES_REMAINING: number;
    VESSEL_TYPE: number;
    PROPULSION_TYPE: number;
    RESERVED: (number)[];
    constructor(POSITION_X?: number, POSITION_Y?: number, POSITION_Z?: number, VELOCITY_X?: number, VELOCITY_Y?: number, VELOCITY_Z?: number, ATTITUDE_X?: number, ATTITUDE_Y?: number, ATTITUDE_Z?: number, ATTITUDE_W?: number, OMEGA_X?: number, OMEGA_Y?: number, OMEGA_Z?: number, SPEED_KNOTS?: number, HEADING?: number, COURSE?: number, RUDDER_ANGLE?: number, HULL?: string | Uint8Array | null, PROPULSION?: string | Uint8Array | null, DC_STATE?: number, FIRES_ACTIVE?: number, FLOODING_ACTIVE?: number, CREW_CASUALTIES?: number, HULL_INTEGRITY?: number, POWER_AVAILABLE?: number, WEAPONS_ONLINE?: number, SENSORS_ONLINE?: number, RESERVED1?: number, FUEL_REMAINING?: number, AMMO_MAIN?: number, MISSILES_REMAINING?: number, TORPEDOES_REMAINING?: number, VESSEL_TYPE?: number, PROPULSION_TYPE?: number, RESERVED?: (number)[]);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=NAV.d.ts.map