// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

/// One SDS record type the app produces and/or consumes. Names an existing
/// spacedatastandards.org schema by its established code; the app manifest
/// defines no data schemas of its own.
public struct APPDataRef : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static APPDataRef GetRootAsAPPDataRef(ByteBuffer _bb) { return GetRootAsAPPDataRef(_bb, new APPDataRef()); }
  public static APPDataRef GetRootAsAPPDataRef(ByteBuffer _bb, APPDataRef obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public APPDataRef __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /// App-local stable reference for this data binding. Required, unique
  /// within the manifest.
  public string ID { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIDBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIDBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIDArray() { return __p.__vector_as_array<byte>(4); }
  /// Existing SDS schema code, for example OMM, CDM, or EPM. Required.
  public string SDS_TYPE { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSDS_TYPEBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetSDS_TYPEBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetSDS_TYPEArray() { return __p.__vector_as_array<byte>(6); }
  /// Data flow relative to the app.
  public appDataDirection DIRECTION { get { int o = __p.__offset(8); return o != 0 ? (appDataDirection)__p.bb.Get(o + __p.bb_pos) : appDataDirection.PRODUCES; } }
  /// When present, must equal an APPModuleRef.ID in the same manifest — the
  /// member module responsible for this data binding.
  public string MODULE_ID { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMODULE_IDBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetMODULE_IDBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetMODULE_IDArray() { return __p.__vector_as_array<byte>(10); }
  /// Human-readable summary.
  public string DESCRIPTION { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDESCRIPTIONBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetDESCRIPTIONBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetDESCRIPTIONArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<APPDataRef> CreateAPPDataRef(FlatBufferBuilder builder,
      StringOffset IDOffset = default(StringOffset),
      StringOffset SDS_TYPEOffset = default(StringOffset),
      appDataDirection DIRECTION = appDataDirection.PRODUCES,
      StringOffset MODULE_IDOffset = default(StringOffset),
      StringOffset DESCRIPTIONOffset = default(StringOffset)) {
    builder.StartTable(5);
    APPDataRef.AddDESCRIPTION(builder, DESCRIPTIONOffset);
    APPDataRef.AddMODULE_ID(builder, MODULE_IDOffset);
    APPDataRef.AddSDS_TYPE(builder, SDS_TYPEOffset);
    APPDataRef.AddID(builder, IDOffset);
    APPDataRef.AddDIRECTION(builder, DIRECTION);
    return APPDataRef.EndAPPDataRef(builder);
  }

  public static void StartAPPDataRef(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddID(FlatBufferBuilder builder, StringOffset IDOffset) { builder.AddOffset(0, IDOffset.Value, 0); }
  public static void AddSDS_TYPE(FlatBufferBuilder builder, StringOffset SDS_TYPEOffset) { builder.AddOffset(1, SDS_TYPEOffset.Value, 0); }
  public static void AddDIRECTION(FlatBufferBuilder builder, appDataDirection DIRECTION) { builder.AddByte(2, (byte)DIRECTION, 0); }
  public static void AddMODULE_ID(FlatBufferBuilder builder, StringOffset MODULE_IDOffset) { builder.AddOffset(3, MODULE_IDOffset.Value, 0); }
  public static void AddDESCRIPTION(FlatBufferBuilder builder, StringOffset DESCRIPTIONOffset) { builder.AddOffset(4, DESCRIPTIONOffset.Value, 0); }
  public static Offset<APPDataRef> EndAPPDataRef(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // ID
    builder.Required(o, 6);  // SDS_TYPE
    return new Offset<APPDataRef>(o);
  }

  public static VectorOffset CreateSortedVectorOfAPPDataRef(FlatBufferBuilder builder, Offset<APPDataRef>[] offsets) {
    Array.Sort(offsets,
      (Offset<APPDataRef> o1, Offset<APPDataRef> o2) =>
        string.CompareOrdinal(new APPDataRef().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer).ID, new APPDataRef().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer).ID));
    return builder.CreateVectorOfTables(offsets);
  }

  public static APPDataRef? __lookup_by_key(int vectorLocation, string key, ByteBuffer bb) {
    APPDataRef obj_ = new APPDataRef();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = string.CompareOrdinal(obj_.ID, key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
  public APPDataRefT UnPack() {
    var _o = new APPDataRefT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(APPDataRefT _o) {
    _o.ID = this.ID;
    _o.SDS_TYPE = this.SDS_TYPE;
    _o.DIRECTION = this.DIRECTION;
    _o.MODULE_ID = this.MODULE_ID;
    _o.DESCRIPTION = this.DESCRIPTION;
  }
  public static Offset<APPDataRef> Pack(FlatBufferBuilder builder, APPDataRefT _o) {
    if (_o == null) return default(Offset<APPDataRef>);
    var _ID = _o.ID == null ? default(StringOffset) : builder.CreateString(_o.ID);
    var _SDS_TYPE = _o.SDS_TYPE == null ? default(StringOffset) : builder.CreateString(_o.SDS_TYPE);
    var _MODULE_ID = _o.MODULE_ID == null ? default(StringOffset) : builder.CreateString(_o.MODULE_ID);
    var _DESCRIPTION = _o.DESCRIPTION == null ? default(StringOffset) : builder.CreateString(_o.DESCRIPTION);
    return CreateAPPDataRef(
      builder,
      _ID,
      _SDS_TYPE,
      _o.DIRECTION,
      _MODULE_ID,
      _DESCRIPTION);
  }
}

public class APPDataRefT
{
  public string ID { get; set; }
  public string SDS_TYPE { get; set; }
  public appDataDirection DIRECTION { get; set; }
  public string MODULE_ID { get; set; }
  public string DESCRIPTION { get; set; }

  public APPDataRefT() {
    this.ID = null;
    this.SDS_TYPE = null;
    this.DIRECTION = appDataDirection.PRODUCES;
    this.MODULE_ID = null;
    this.DESCRIPTION = null;
  }
}


static public class APPDataRefVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*ID*/, true)
      && verifier.VerifyString(tablePos, 6 /*SDS_TYPE*/, true)
      && verifier.VerifyField(tablePos, 8 /*DIRECTION*/, 1 /*appDataDirection*/, 1, false)
      && verifier.VerifyString(tablePos, 10 /*MODULE_ID*/, false)
      && verifier.VerifyString(tablePos, 12 /*DESCRIPTION*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
