<?php
// automatically generated by the FlatBuffers compiler, do not modify

/// Capability class represented by an emission-limit curve.
class rfeEmissionMaskClass
{
    const UNSPECIFIED = 0;
    const IN_BAND = 1;
    const OUT_OF_BAND = 2;
    const SPURIOUS = 3;
    const HARMONIC = 4;
    const BROADBAND_NOISE = 5;
    const CONDUCTED = 6;
    const RADIATED = 7;
    const SUSCEPTIBILITY = 8;

    private static $names = array(
        rfeEmissionMaskClass::UNSPECIFIED=>"UNSPECIFIED",
        rfeEmissionMaskClass::IN_BAND=>"IN_BAND",
        rfeEmissionMaskClass::OUT_OF_BAND=>"OUT_OF_BAND",
        rfeEmissionMaskClass::SPURIOUS=>"SPURIOUS",
        rfeEmissionMaskClass::HARMONIC=>"HARMONIC",
        rfeEmissionMaskClass::BROADBAND_NOISE=>"BROADBAND_NOISE",
        rfeEmissionMaskClass::CONDUCTED=>"CONDUCTED",
        rfeEmissionMaskClass::RADIATED=>"RADIATED",
        rfeEmissionMaskClass::SUSCEPTIBILITY=>"SUSCEPTIBILITY",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
