# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class RotorType(object):
    MAIN = 0
    TAIL = 1
    TANDEM_FRONT = 2
    TANDEM_REAR = 3
    COAXIAL_UPPER = 4
    COAXIAL_LOWER = 5
