// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * ImagePyramid for PhotoOverlay
 */
@Suppress("unused")
class KMLImagePyramid : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : KMLImagePyramid {
        __init(_i, _bb)
        return this
    }
    /**
     * Tile size in pixels
     */
    val TILE_SIZE : Int
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    /**
     * Maximum image width
     */
    val MAX_WIDTH : Int
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    /**
     * Maximum image height
     */
    val MAX_HEIGHT : Int
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    /**
     * Grid origin
     */
    val GRID_ORIGIN : Byte
        get() {
            val o = __offset(10)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_24_3_25()
        fun getRootAsKMLImagePyramid(_bb: ByteBuffer): KMLImagePyramid = getRootAsKMLImagePyramid(_bb, KMLImagePyramid())
        fun getRootAsKMLImagePyramid(_bb: ByteBuffer, obj: KMLImagePyramid): KMLImagePyramid {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createKMLImagePyramid(builder: FlatBufferBuilder, TILE_SIZE: Int, MAX_WIDTH: Int, MAX_HEIGHT: Int, GRID_ORIGIN: Byte) : Int {
            builder.startTable(4)
            addMAX_HEIGHT(builder, MAX_HEIGHT)
            addMAX_WIDTH(builder, MAX_WIDTH)
            addTILE_SIZE(builder, TILE_SIZE)
            addGRID_ORIGIN(builder, GRID_ORIGIN)
            return endKMLImagePyramid(builder)
        }
        fun startKMLImagePyramid(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addTILE_SIZE(builder: FlatBufferBuilder, TILE_SIZE: Int) = builder.addInt(0, TILE_SIZE, 0)
        fun addMAX_WIDTH(builder: FlatBufferBuilder, MAX_WIDTH: Int) = builder.addInt(1, MAX_WIDTH, 0)
        fun addMAX_HEIGHT(builder: FlatBufferBuilder, MAX_HEIGHT: Int) = builder.addInt(2, MAX_HEIGHT, 0)
        fun addGRID_ORIGIN(builder: FlatBufferBuilder, GRID_ORIGIN: Byte) = builder.addByte(3, GRID_ORIGIN, 0)
        fun endKMLImagePyramid(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
