import * as flatbuffers from 'flatbuffers';
/**
 * Ground Vehicles
 */
export declare class GVH implements flatbuffers.IUnpackableObject<GVHT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): GVH;
    static getRootAsGVH(bb: flatbuffers.ByteBuffer, obj?: GVH): GVH;
    static getSizePrefixedRootAsGVH(bb: flatbuffers.ByteBuffer, obj?: GVH): GVH;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    POSITION_X(): number;
    POSITION_Y(): number;
    POSITION_Z(): number;
    VELOCITY_X(): number;
    VELOCITY_Y(): number;
    VELOCITY_Z(): number;
    ATTITUDE_X(): number;
    ATTITUDE_Y(): number;
    ATTITUDE_Z(): number;
    ATTITUDE_W(): number;
    OMEGA_X(): number;
    OMEGA_Y(): number;
    OMEGA_Z(): number;
    SPEED(): number;
    HEADING(): number;
    LATERAL_G(): number;
    LONGITUDINAL_G(): number;
    TURRET(): string | null;
    TURRET(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DRIVETRAIN(): string | null;
    DRIVETRAIN(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SUSPENSION_LF(): string | null;
    SUSPENSION_LF(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SUSPENSION_RF(): string | null;
    SUSPENSION_RF(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SUSPENSION_LR(): string | null;
    SUSPENSION_LR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SUSPENSION_RR(): string | null;
    SUSPENSION_RR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    VEHICLE_TYPE(): number;
    DRIVE_TYPE(): number;
    ENGINE_RUNNING(): number;
    LIGHTS(): number;
    FUEL_LEVEL(): number;
    static startGVH(builder: flatbuffers.Builder): void;
    static addPositionX(builder: flatbuffers.Builder, POSITION_X: number): void;
    static addPositionY(builder: flatbuffers.Builder, POSITION_Y: number): void;
    static addPositionZ(builder: flatbuffers.Builder, POSITION_Z: number): void;
    static addVelocityX(builder: flatbuffers.Builder, VELOCITY_X: number): void;
    static addVelocityY(builder: flatbuffers.Builder, VELOCITY_Y: number): void;
    static addVelocityZ(builder: flatbuffers.Builder, VELOCITY_Z: number): void;
    static addAttitudeX(builder: flatbuffers.Builder, ATTITUDE_X: number): void;
    static addAttitudeY(builder: flatbuffers.Builder, ATTITUDE_Y: number): void;
    static addAttitudeZ(builder: flatbuffers.Builder, ATTITUDE_Z: number): void;
    static addAttitudeW(builder: flatbuffers.Builder, ATTITUDE_W: number): void;
    static addOmegaX(builder: flatbuffers.Builder, OMEGA_X: number): void;
    static addOmegaY(builder: flatbuffers.Builder, OMEGA_Y: number): void;
    static addOmegaZ(builder: flatbuffers.Builder, OMEGA_Z: number): void;
    static addSpeed(builder: flatbuffers.Builder, SPEED: number): void;
    static addHeading(builder: flatbuffers.Builder, HEADING: number): void;
    static addLateralG(builder: flatbuffers.Builder, LATERAL_G: number): void;
    static addLongitudinalG(builder: flatbuffers.Builder, LONGITUDINAL_G: number): void;
    static addTurret(builder: flatbuffers.Builder, TURRETOffset: flatbuffers.Offset): void;
    static addDrivetrain(builder: flatbuffers.Builder, DRIVETRAINOffset: flatbuffers.Offset): void;
    static addSuspensionLf(builder: flatbuffers.Builder, SUSPENSION_LFOffset: flatbuffers.Offset): void;
    static addSuspensionRf(builder: flatbuffers.Builder, SUSPENSION_RFOffset: flatbuffers.Offset): void;
    static addSuspensionLr(builder: flatbuffers.Builder, SUSPENSION_LROffset: flatbuffers.Offset): void;
    static addSuspensionRr(builder: flatbuffers.Builder, SUSPENSION_RROffset: flatbuffers.Offset): void;
    static addVehicleType(builder: flatbuffers.Builder, VEHICLE_TYPE: number): void;
    static addDriveType(builder: flatbuffers.Builder, DRIVE_TYPE: number): void;
    static addEngineRunning(builder: flatbuffers.Builder, ENGINE_RUNNING: number): void;
    static addLights(builder: flatbuffers.Builder, LIGHTS: number): void;
    static addFuelLevel(builder: flatbuffers.Builder, FUEL_LEVEL: number): void;
    static endGVH(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishGVHBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedGVHBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createGVH(builder: flatbuffers.Builder, POSITION_X: number, POSITION_Y: number, POSITION_Z: number, VELOCITY_X: number, VELOCITY_Y: number, VELOCITY_Z: number, ATTITUDE_X: number, ATTITUDE_Y: number, ATTITUDE_Z: number, ATTITUDE_W: number, OMEGA_X: number, OMEGA_Y: number, OMEGA_Z: number, SPEED: number, HEADING: number, LATERAL_G: number, LONGITUDINAL_G: number, TURRETOffset: flatbuffers.Offset, DRIVETRAINOffset: flatbuffers.Offset, SUSPENSION_LFOffset: flatbuffers.Offset, SUSPENSION_RFOffset: flatbuffers.Offset, SUSPENSION_LROffset: flatbuffers.Offset, SUSPENSION_RROffset: flatbuffers.Offset, VEHICLE_TYPE: number, DRIVE_TYPE: number, ENGINE_RUNNING: number, LIGHTS: number, FUEL_LEVEL: number): flatbuffers.Offset;
    unpack(): GVHT;
    unpackTo(_o: GVHT): void;
}
export declare class GVHT implements flatbuffers.IGeneratedObject {
    POSITION_X: number;
    POSITION_Y: number;
    POSITION_Z: number;
    VELOCITY_X: number;
    VELOCITY_Y: number;
    VELOCITY_Z: number;
    ATTITUDE_X: number;
    ATTITUDE_Y: number;
    ATTITUDE_Z: number;
    ATTITUDE_W: number;
    OMEGA_X: number;
    OMEGA_Y: number;
    OMEGA_Z: number;
    SPEED: number;
    HEADING: number;
    LATERAL_G: number;
    LONGITUDINAL_G: number;
    TURRET: string | Uint8Array | null;
    DRIVETRAIN: string | Uint8Array | null;
    SUSPENSION_LF: string | Uint8Array | null;
    SUSPENSION_RF: string | Uint8Array | null;
    SUSPENSION_LR: string | Uint8Array | null;
    SUSPENSION_RR: string | Uint8Array | null;
    VEHICLE_TYPE: number;
    DRIVE_TYPE: number;
    ENGINE_RUNNING: number;
    LIGHTS: number;
    FUEL_LEVEL: number;
    constructor(POSITION_X?: number, POSITION_Y?: number, POSITION_Z?: number, VELOCITY_X?: number, VELOCITY_Y?: number, VELOCITY_Z?: number, ATTITUDE_X?: number, ATTITUDE_Y?: number, ATTITUDE_Z?: number, ATTITUDE_W?: number, OMEGA_X?: number, OMEGA_Y?: number, OMEGA_Z?: number, SPEED?: number, HEADING?: number, LATERAL_G?: number, LONGITUDINAL_G?: number, TURRET?: string | Uint8Array | null, DRIVETRAIN?: string | Uint8Array | null, SUSPENSION_LF?: string | Uint8Array | null, SUSPENSION_RF?: string | Uint8Array | null, SUSPENSION_LR?: string | Uint8Array | null, SUSPENSION_RR?: string | Uint8Array | null, VEHICLE_TYPE?: number, DRIVE_TYPE?: number, ENGINE_RUNNING?: number, LIGHTS?: number, FUEL_LEVEL?: number);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=GVH.d.ts.map