import * as flatbuffers from 'flatbuffers';
/**
 * Difference of Arrival
 */
export declare class DOA implements flatbuffers.IUnpackableObject<DOAT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): DOA;
    static getRootAsDOA(bb: flatbuffers.ByteBuffer, obj?: DOA): DOA;
    static getSizePrefixedRootAsDOA(bb: flatbuffers.ByteBuffer, obj?: DOA): DOA;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OB_TIME(): string | null;
    OB_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ID_SENSOR1(): string | null;
    ID_SENSOR1(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ID_SENSOR2(): string | null;
    ID_SENSOR2(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SAT_NO(): number;
    TASK_ID(): string | null;
    TASK_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_OBJECT_ID(): string | null;
    ORIG_OBJECT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_SENSOR_ID1(): string | null;
    ORIG_SENSOR_ID1(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_SENSOR_ID2(): string | null;
    ORIG_SENSOR_ID2(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    UCT(): boolean;
    SENSOR1_DELAY(): number;
    SENSOR2_DELAY(): number;
    SENLAT(): number;
    SENLON(): number;
    SENALT(): number;
    SEN2LAT(): number;
    SEN2LON(): number;
    SEN2ALT(): number;
    FREQUENCY(): number;
    BANDWIDTH(): number;
    DELTA_RANGE(): number;
    DELTA_RANGE_UNC(): number;
    DELTA_RANGE_RATE(): number;
    DELTA_RANGE_RATE_UNC(): number;
    SNR(): number;
    TDOA(): number;
    TDOA_UNC(): number;
    FDOA(): number;
    FDOA_UNC(): number;
    COLLECTION_MODE(): string | null;
    COLLECTION_MODE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    RAW_FILE_URI(): string | null;
    RAW_FILE_URI(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TAGS(index: number): string;
    TAGS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    tagsLength(): number;
    ON_ORBIT(): string | null;
    ON_ORBIT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DESCRIPTOR(): string | null;
    DESCRIPTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRANSACTION_ID(): string | null;
    TRANSACTION_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    static startDOA(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addObTime(builder: flatbuffers.Builder, OB_TIMEOffset: flatbuffers.Offset): void;
    static addIdSensor1(builder: flatbuffers.Builder, ID_SENSOR1Offset: flatbuffers.Offset): void;
    static addIdSensor2(builder: flatbuffers.Builder, ID_SENSOR2Offset: flatbuffers.Offset): void;
    static addSatNo(builder: flatbuffers.Builder, SAT_NO: number): void;
    static addTaskId(builder: flatbuffers.Builder, TASK_IDOffset: flatbuffers.Offset): void;
    static addOrigObjectId(builder: flatbuffers.Builder, ORIG_OBJECT_IDOffset: flatbuffers.Offset): void;
    static addOrigSensorId1(builder: flatbuffers.Builder, ORIG_SENSOR_ID1Offset: flatbuffers.Offset): void;
    static addOrigSensorId2(builder: flatbuffers.Builder, ORIG_SENSOR_ID2Offset: flatbuffers.Offset): void;
    static addUct(builder: flatbuffers.Builder, UCT: boolean): void;
    static addSensor1Delay(builder: flatbuffers.Builder, SENSOR1_DELAY: number): void;
    static addSensor2Delay(builder: flatbuffers.Builder, SENSOR2_DELAY: number): void;
    static addSenlat(builder: flatbuffers.Builder, SENLAT: number): void;
    static addSenlon(builder: flatbuffers.Builder, SENLON: number): void;
    static addSenalt(builder: flatbuffers.Builder, SENALT: number): void;
    static addSen2Lat(builder: flatbuffers.Builder, SEN2LAT: number): void;
    static addSen2Lon(builder: flatbuffers.Builder, SEN2LON: number): void;
    static addSen2Alt(builder: flatbuffers.Builder, SEN2ALT: number): void;
    static addFrequency(builder: flatbuffers.Builder, FREQUENCY: number): void;
    static addBandwidth(builder: flatbuffers.Builder, BANDWIDTH: number): void;
    static addDeltaRange(builder: flatbuffers.Builder, DELTA_RANGE: number): void;
    static addDeltaRangeUnc(builder: flatbuffers.Builder, DELTA_RANGE_UNC: number): void;
    static addDeltaRangeRate(builder: flatbuffers.Builder, DELTA_RANGE_RATE: number): void;
    static addDeltaRangeRateUnc(builder: flatbuffers.Builder, DELTA_RANGE_RATE_UNC: number): void;
    static addSnr(builder: flatbuffers.Builder, SNR: number): void;
    static addTdoa(builder: flatbuffers.Builder, TDOA: number): void;
    static addTdoaUnc(builder: flatbuffers.Builder, TDOA_UNC: number): void;
    static addFdoa(builder: flatbuffers.Builder, FDOA: number): void;
    static addFdoaUnc(builder: flatbuffers.Builder, FDOA_UNC: number): void;
    static addCollectionMode(builder: flatbuffers.Builder, COLLECTION_MODEOffset: flatbuffers.Offset): void;
    static addRawFileUri(builder: flatbuffers.Builder, RAW_FILE_URIOffset: flatbuffers.Offset): void;
    static addTags(builder: flatbuffers.Builder, TAGSOffset: flatbuffers.Offset): void;
    static createTagsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startTagsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addOnOrbit(builder: flatbuffers.Builder, ON_ORBITOffset: flatbuffers.Offset): void;
    static addDescriptor(builder: flatbuffers.Builder, DESCRIPTOROffset: flatbuffers.Offset): void;
    static addTransactionId(builder: flatbuffers.Builder, TRANSACTION_IDOffset: flatbuffers.Offset): void;
    static endDOA(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishDOABuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedDOABuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createDOA(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, OB_TIMEOffset: flatbuffers.Offset, ID_SENSOR1Offset: flatbuffers.Offset, ID_SENSOR2Offset: flatbuffers.Offset, SAT_NO: number, TASK_IDOffset: flatbuffers.Offset, ORIG_OBJECT_IDOffset: flatbuffers.Offset, ORIG_SENSOR_ID1Offset: flatbuffers.Offset, ORIG_SENSOR_ID2Offset: flatbuffers.Offset, UCT: boolean, SENSOR1_DELAY: number, SENSOR2_DELAY: number, SENLAT: number, SENLON: number, SENALT: number, SEN2LAT: number, SEN2LON: number, SEN2ALT: number, FREQUENCY: number, BANDWIDTH: number, DELTA_RANGE: number, DELTA_RANGE_UNC: number, DELTA_RANGE_RATE: number, DELTA_RANGE_RATE_UNC: number, SNR: number, TDOA: number, TDOA_UNC: number, FDOA: number, FDOA_UNC: number, COLLECTION_MODEOffset: flatbuffers.Offset, RAW_FILE_URIOffset: flatbuffers.Offset, TAGSOffset: flatbuffers.Offset, ON_ORBITOffset: flatbuffers.Offset, DESCRIPTOROffset: flatbuffers.Offset, TRANSACTION_IDOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): DOAT;
    unpackTo(_o: DOAT): void;
}
export declare class DOAT implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    OB_TIME: string | Uint8Array | null;
    ID_SENSOR1: string | Uint8Array | null;
    ID_SENSOR2: string | Uint8Array | null;
    SAT_NO: number;
    TASK_ID: string | Uint8Array | null;
    ORIG_OBJECT_ID: string | Uint8Array | null;
    ORIG_SENSOR_ID1: string | Uint8Array | null;
    ORIG_SENSOR_ID2: string | Uint8Array | null;
    UCT: boolean;
    SENSOR1_DELAY: number;
    SENSOR2_DELAY: number;
    SENLAT: number;
    SENLON: number;
    SENALT: number;
    SEN2LAT: number;
    SEN2LON: number;
    SEN2ALT: number;
    FREQUENCY: number;
    BANDWIDTH: number;
    DELTA_RANGE: number;
    DELTA_RANGE_UNC: number;
    DELTA_RANGE_RATE: number;
    DELTA_RANGE_RATE_UNC: number;
    SNR: number;
    TDOA: number;
    TDOA_UNC: number;
    FDOA: number;
    FDOA_UNC: number;
    COLLECTION_MODE: string | Uint8Array | null;
    RAW_FILE_URI: string | Uint8Array | null;
    TAGS: (string)[];
    ON_ORBIT: string | Uint8Array | null;
    DESCRIPTOR: string | Uint8Array | null;
    TRANSACTION_ID: string | Uint8Array | null;
    constructor(ID?: string | Uint8Array | null, OB_TIME?: string | Uint8Array | null, ID_SENSOR1?: string | Uint8Array | null, ID_SENSOR2?: string | Uint8Array | null, SAT_NO?: number, TASK_ID?: string | Uint8Array | null, ORIG_OBJECT_ID?: string | Uint8Array | null, ORIG_SENSOR_ID1?: string | Uint8Array | null, ORIG_SENSOR_ID2?: string | Uint8Array | null, UCT?: boolean, SENSOR1_DELAY?: number, SENSOR2_DELAY?: number, SENLAT?: number, SENLON?: number, SENALT?: number, SEN2LAT?: number, SEN2LON?: number, SEN2ALT?: number, FREQUENCY?: number, BANDWIDTH?: number, DELTA_RANGE?: number, DELTA_RANGE_UNC?: number, DELTA_RANGE_RATE?: number, DELTA_RANGE_RATE_UNC?: number, SNR?: number, TDOA?: number, TDOA_UNC?: number, FDOA?: number, FDOA_UNC?: number, COLLECTION_MODE?: string | Uint8Array | null, RAW_FILE_URI?: string | Uint8Array | null, TAGS?: (string)[], ON_ORBIT?: string | Uint8Array | null, DESCRIPTOR?: string | Uint8Array | null, TRANSACTION_ID?: string | Uint8Array | null);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=DOA.d.ts.map