import * as flatbuffers from 'flatbuffers';
/**
 * Radar Observation
 */
export declare class RDO implements flatbuffers.IUnpackableObject<RDOT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): RDO;
    static getRootAsRDO(bb: flatbuffers.ByteBuffer, obj?: RDO): RDO;
    static getSizePrefixedRootAsRDO(bb: flatbuffers.ByteBuffer, obj?: RDO): RDO;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    ID(): string | null;
    ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OB_TIME(): string | null;
    OB_TIME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ID_SENSOR(): string | null;
    ID_SENSOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SAT_NO(): number;
    TASK_ID(): string | null;
    TASK_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRANSACTION_ID(): string | null;
    TRANSACTION_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TRACK_ID(): string | null;
    TRACK_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    OB_POSITION(): string | null;
    OB_POSITION(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_OBJECT_ID(): string | null;
    ORIG_OBJECT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ORIG_SENSOR_ID(): string | null;
    ORIG_SENSOR_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    UCT(): boolean;
    AZIMUTH(): number;
    AZIMUTH_UNC(): number;
    AZIMUTH_BIAS(): number;
    AZIMUTH_RATE(): number;
    ELEVATION(): number;
    ELEVATION_UNC(): number;
    ELEVATION_BIAS(): number;
    ELEVATION_RATE(): number;
    RANGE(): number;
    RANGE_ACCEL(): number;
    RANGE_ACCEL_UNC(): number;
    RANGE_UNC(): number;
    RANGE_BIAS(): number;
    RANGE_RATE(): number;
    RANGE_RATE_UNC(): number;
    DOPPLER(): number;
    DOPPLER_UNC(): number;
    RA(): number;
    DECLINATION(): number;
    X(): number;
    Y(): number;
    Z(): number;
    XVEL(): number;
    YVEL(): number;
    ZVEL(): number;
    SENX(): number;
    SENY(): number;
    SENZ(): number;
    RCS(): number;
    RCS_UNC(): number;
    ORTHOGONAL_RCS(): number;
    ORTHOGONAL_RCS_UNC(): number;
    SNR(): number;
    BEAM(): number;
    TIMING_BIAS(): number;
    RAW_FILE_URI(): string | null;
    RAW_FILE_URI(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TAGS(index: number): string;
    TAGS(index: number, optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    tagsLength(): number;
    ON_ORBIT(): string | null;
    ON_ORBIT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    SEN_REFERENCE_FRAME(): string | null;
    SEN_REFERENCE_FRAME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    DESCRIPTOR(): string | null;
    DESCRIPTOR(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    TYPE(): string | null;
    TYPE(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    static startRDO(builder: flatbuffers.Builder): void;
    static addId(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset): void;
    static addObTime(builder: flatbuffers.Builder, OB_TIMEOffset: flatbuffers.Offset): void;
    static addIdSensor(builder: flatbuffers.Builder, ID_SENSOROffset: flatbuffers.Offset): void;
    static addSatNo(builder: flatbuffers.Builder, SAT_NO: number): void;
    static addTaskId(builder: flatbuffers.Builder, TASK_IDOffset: flatbuffers.Offset): void;
    static addTransactionId(builder: flatbuffers.Builder, TRANSACTION_IDOffset: flatbuffers.Offset): void;
    static addTrackId(builder: flatbuffers.Builder, TRACK_IDOffset: flatbuffers.Offset): void;
    static addObPosition(builder: flatbuffers.Builder, OB_POSITIONOffset: flatbuffers.Offset): void;
    static addOrigObjectId(builder: flatbuffers.Builder, ORIG_OBJECT_IDOffset: flatbuffers.Offset): void;
    static addOrigSensorId(builder: flatbuffers.Builder, ORIG_SENSOR_IDOffset: flatbuffers.Offset): void;
    static addUct(builder: flatbuffers.Builder, UCT: boolean): void;
    static addAzimuth(builder: flatbuffers.Builder, AZIMUTH: number): void;
    static addAzimuthUnc(builder: flatbuffers.Builder, AZIMUTH_UNC: number): void;
    static addAzimuthBias(builder: flatbuffers.Builder, AZIMUTH_BIAS: number): void;
    static addAzimuthRate(builder: flatbuffers.Builder, AZIMUTH_RATE: number): void;
    static addElevation(builder: flatbuffers.Builder, ELEVATION: number): void;
    static addElevationUnc(builder: flatbuffers.Builder, ELEVATION_UNC: number): void;
    static addElevationBias(builder: flatbuffers.Builder, ELEVATION_BIAS: number): void;
    static addElevationRate(builder: flatbuffers.Builder, ELEVATION_RATE: number): void;
    static addRange(builder: flatbuffers.Builder, RANGE: number): void;
    static addRangeAccel(builder: flatbuffers.Builder, RANGE_ACCEL: number): void;
    static addRangeAccelUnc(builder: flatbuffers.Builder, RANGE_ACCEL_UNC: number): void;
    static addRangeUnc(builder: flatbuffers.Builder, RANGE_UNC: number): void;
    static addRangeBias(builder: flatbuffers.Builder, RANGE_BIAS: number): void;
    static addRangeRate(builder: flatbuffers.Builder, RANGE_RATE: number): void;
    static addRangeRateUnc(builder: flatbuffers.Builder, RANGE_RATE_UNC: number): void;
    static addDoppler(builder: flatbuffers.Builder, DOPPLER: number): void;
    static addDopplerUnc(builder: flatbuffers.Builder, DOPPLER_UNC: number): void;
    static addRa(builder: flatbuffers.Builder, RA: number): void;
    static addDeclination(builder: flatbuffers.Builder, DECLINATION: number): void;
    static addX(builder: flatbuffers.Builder, X: number): void;
    static addY(builder: flatbuffers.Builder, Y: number): void;
    static addZ(builder: flatbuffers.Builder, Z: number): void;
    static addXvel(builder: flatbuffers.Builder, XVEL: number): void;
    static addYvel(builder: flatbuffers.Builder, YVEL: number): void;
    static addZvel(builder: flatbuffers.Builder, ZVEL: number): void;
    static addSenx(builder: flatbuffers.Builder, SENX: number): void;
    static addSeny(builder: flatbuffers.Builder, SENY: number): void;
    static addSenz(builder: flatbuffers.Builder, SENZ: number): void;
    static addRcs(builder: flatbuffers.Builder, RCS: number): void;
    static addRcsUnc(builder: flatbuffers.Builder, RCS_UNC: number): void;
    static addOrthogonalRcs(builder: flatbuffers.Builder, ORTHOGONAL_RCS: number): void;
    static addOrthogonalRcsUnc(builder: flatbuffers.Builder, ORTHOGONAL_RCS_UNC: number): void;
    static addSnr(builder: flatbuffers.Builder, SNR: number): void;
    static addBeam(builder: flatbuffers.Builder, BEAM: number): void;
    static addTimingBias(builder: flatbuffers.Builder, TIMING_BIAS: number): void;
    static addRawFileUri(builder: flatbuffers.Builder, RAW_FILE_URIOffset: flatbuffers.Offset): void;
    static addTags(builder: flatbuffers.Builder, TAGSOffset: flatbuffers.Offset): void;
    static createTagsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startTagsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addOnOrbit(builder: flatbuffers.Builder, ON_ORBITOffset: flatbuffers.Offset): void;
    static addSenReferenceFrame(builder: flatbuffers.Builder, SEN_REFERENCE_FRAMEOffset: flatbuffers.Offset): void;
    static addDescriptor(builder: flatbuffers.Builder, DESCRIPTOROffset: flatbuffers.Offset): void;
    static addType(builder: flatbuffers.Builder, TYPEOffset: flatbuffers.Offset): void;
    static endRDO(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishRDOBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedRDOBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static createRDO(builder: flatbuffers.Builder, IDOffset: flatbuffers.Offset, OB_TIMEOffset: flatbuffers.Offset, ID_SENSOROffset: flatbuffers.Offset, SAT_NO: number, TASK_IDOffset: flatbuffers.Offset, TRANSACTION_IDOffset: flatbuffers.Offset, TRACK_IDOffset: flatbuffers.Offset, OB_POSITIONOffset: flatbuffers.Offset, ORIG_OBJECT_IDOffset: flatbuffers.Offset, ORIG_SENSOR_IDOffset: flatbuffers.Offset, UCT: boolean, AZIMUTH: number, AZIMUTH_UNC: number, AZIMUTH_BIAS: number, AZIMUTH_RATE: number, ELEVATION: number, ELEVATION_UNC: number, ELEVATION_BIAS: number, ELEVATION_RATE: number, RANGE: number, RANGE_ACCEL: number, RANGE_ACCEL_UNC: number, RANGE_UNC: number, RANGE_BIAS: number, RANGE_RATE: number, RANGE_RATE_UNC: number, DOPPLER: number, DOPPLER_UNC: number, RA: number, DECLINATION: number, X: number, Y: number, Z: number, XVEL: number, YVEL: number, ZVEL: number, SENX: number, SENY: number, SENZ: number, RCS: number, RCS_UNC: number, ORTHOGONAL_RCS: number, ORTHOGONAL_RCS_UNC: number, SNR: number, BEAM: number, TIMING_BIAS: number, RAW_FILE_URIOffset: flatbuffers.Offset, TAGSOffset: flatbuffers.Offset, ON_ORBITOffset: flatbuffers.Offset, SEN_REFERENCE_FRAMEOffset: flatbuffers.Offset, DESCRIPTOROffset: flatbuffers.Offset, TYPEOffset: flatbuffers.Offset): flatbuffers.Offset;
    unpack(): RDOT;
    unpackTo(_o: RDOT): void;
}
export declare class RDOT implements flatbuffers.IGeneratedObject {
    ID: string | Uint8Array | null;
    OB_TIME: string | Uint8Array | null;
    ID_SENSOR: string | Uint8Array | null;
    SAT_NO: number;
    TASK_ID: string | Uint8Array | null;
    TRANSACTION_ID: string | Uint8Array | null;
    TRACK_ID: string | Uint8Array | null;
    OB_POSITION: string | Uint8Array | null;
    ORIG_OBJECT_ID: string | Uint8Array | null;
    ORIG_SENSOR_ID: string | Uint8Array | null;
    UCT: boolean;
    AZIMUTH: number;
    AZIMUTH_UNC: number;
    AZIMUTH_BIAS: number;
    AZIMUTH_RATE: number;
    ELEVATION: number;
    ELEVATION_UNC: number;
    ELEVATION_BIAS: number;
    ELEVATION_RATE: number;
    RANGE: number;
    RANGE_ACCEL: number;
    RANGE_ACCEL_UNC: number;
    RANGE_UNC: number;
    RANGE_BIAS: number;
    RANGE_RATE: number;
    RANGE_RATE_UNC: number;
    DOPPLER: number;
    DOPPLER_UNC: number;
    RA: number;
    DECLINATION: number;
    X: number;
    Y: number;
    Z: number;
    XVEL: number;
    YVEL: number;
    ZVEL: number;
    SENX: number;
    SENY: number;
    SENZ: number;
    RCS: number;
    RCS_UNC: number;
    ORTHOGONAL_RCS: number;
    ORTHOGONAL_RCS_UNC: number;
    SNR: number;
    BEAM: number;
    TIMING_BIAS: number;
    RAW_FILE_URI: string | Uint8Array | null;
    TAGS: (string)[];
    ON_ORBIT: string | Uint8Array | null;
    SEN_REFERENCE_FRAME: string | Uint8Array | null;
    DESCRIPTOR: string | Uint8Array | null;
    TYPE: string | Uint8Array | null;
    constructor(ID?: string | Uint8Array | null, OB_TIME?: string | Uint8Array | null, ID_SENSOR?: string | Uint8Array | null, SAT_NO?: number, TASK_ID?: string | Uint8Array | null, TRANSACTION_ID?: string | Uint8Array | null, TRACK_ID?: string | Uint8Array | null, OB_POSITION?: string | Uint8Array | null, ORIG_OBJECT_ID?: string | Uint8Array | null, ORIG_SENSOR_ID?: string | Uint8Array | null, UCT?: boolean, AZIMUTH?: number, AZIMUTH_UNC?: number, AZIMUTH_BIAS?: number, AZIMUTH_RATE?: number, ELEVATION?: number, ELEVATION_UNC?: number, ELEVATION_BIAS?: number, ELEVATION_RATE?: number, RANGE?: number, RANGE_ACCEL?: number, RANGE_ACCEL_UNC?: number, RANGE_UNC?: number, RANGE_BIAS?: number, RANGE_RATE?: number, RANGE_RATE_UNC?: number, DOPPLER?: number, DOPPLER_UNC?: number, RA?: number, DECLINATION?: number, X?: number, Y?: number, Z?: number, XVEL?: number, YVEL?: number, ZVEL?: number, SENX?: number, SENY?: number, SENZ?: number, RCS?: number, RCS_UNC?: number, ORTHOGONAL_RCS?: number, ORTHOGONAL_RCS_UNC?: number, SNR?: number, BEAM?: number, TIMING_BIAS?: number, RAW_FILE_URI?: string | Uint8Array | null, TAGS?: (string)[], ON_ORBIT?: string | Uint8Array | null, SEN_REFERENCE_FRAME?: string | Uint8Array | null, DESCRIPTOR?: string | Uint8Array | null, TYPE?: string | Uint8Array | null);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=RDO.d.ts.map