// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Collection of Entity Profile Messages
 */
@SuppressWarnings("unused")
public final class EPMCOLLECTION extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_3_3(); }
  public static EPMCOLLECTION getRootAsEPMCOLLECTION(ByteBuffer _bb) { return getRootAsEPMCOLLECTION(_bb, new EPMCOLLECTION()); }
  public static EPMCOLLECTION getRootAsEPMCOLLECTION(ByteBuffer _bb, EPMCOLLECTION obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public static boolean EPMCOLLECTIONBufferHasIdentifier(ByteBuffer _bb) { return __has_identifier(_bb, "$EPM"); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EPMCOLLECTION __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  /**
   * Records of Entity Profile Messages
   */
  public EPM RECORDS(int j) { return RECORDS(new EPM(), j); }
  public EPM RECORDS(EPM obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int RECORDSLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public EPM.Vector recordsVector() { return recordsVector(new EPM.Vector()); }
  public EPM.Vector recordsVector(EPM.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createEPMCOLLECTION(FlatBufferBuilder builder,
      int RECORDSOffset) {
    builder.startTable(1);
    EPMCOLLECTION.addRecords(builder, RECORDSOffset);
    return EPMCOLLECTION.endEPMCOLLECTION(builder);
  }

  public static void startEPMCOLLECTION(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addRecords(FlatBufferBuilder builder, int RECORDSOffset) { builder.addOffset(0, RECORDSOffset, 0); }
  public static int createRecordsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRecordsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endEPMCOLLECTION(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishEPMCOLLECTIONBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset, "$EPM"); }
  public static void finishSizePrefixedEPMCOLLECTIONBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset, "$EPM"); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EPMCOLLECTION get(int j) { return get(new EPMCOLLECTION(), j); }
    public EPMCOLLECTION get(EPMCOLLECTION obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

