// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * One flow trigger (e.g. a host timer or HTTP route) that starts a drain.
 */
export class PLGFlowTrigger implements flatbuffers.IUnpackableObject<PLGFlowTriggerT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PLGFlowTrigger {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPLGFlowTrigger(bb:flatbuffers.ByteBuffer, obj?:PLGFlowTrigger):PLGFlowTrigger {
  return (obj || new PLGFlowTrigger()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPLGFlowTrigger(bb:flatbuffers.ByteBuffer, obj?:PLGFlowTrigger):PLGFlowTrigger {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PLGFlowTrigger()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Stable trigger identifier
 */
TRIGGER_ID():string
TRIGGER_ID(optionalEncoding:flatbuffers.Encoding):string|Uint8Array
TRIGGER_ID(optionalEncoding?:any):string|Uint8Array {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return this.bb!.__string(this.bb_pos + offset, optionalEncoding);
}

/**
 * Trigger kind, e.g. "timer", "http"
 */
KIND():string|null
KIND(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
KIND(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Trigger source, e.g. "host-cron"
 */
SOURCE():string|null
SOURCE(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
SOURCE(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Default firing interval in milliseconds (timer triggers)
 */
DEFAULT_INTERVAL_MS():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

/**
 * Mounted HTTP path (http triggers)
 */
HTTP_PATH():string|null
HTTP_PATH(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
HTTP_PATH(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startPLGFlowTrigger(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addTriggerId(builder:flatbuffers.Builder, TRIGGER_IDOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, TRIGGER_IDOffset, 0);
}

static addKind(builder:flatbuffers.Builder, KINDOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, KINDOffset, 0);
}

static addSource(builder:flatbuffers.Builder, SOURCEOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, SOURCEOffset, 0);
}

static addDefaultIntervalMs(builder:flatbuffers.Builder, DEFAULT_INTERVAL_MS:bigint) {
  builder.addFieldInt64(3, DEFAULT_INTERVAL_MS, BigInt('0'));
}

static addHttpPath(builder:flatbuffers.Builder, HTTP_PATHOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, HTTP_PATHOffset, 0);
}

static endPLGFlowTrigger(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // TRIGGER_ID
  return offset;
}

static createPLGFlowTrigger(builder:flatbuffers.Builder, TRIGGER_IDOffset:flatbuffers.Offset, KINDOffset:flatbuffers.Offset, SOURCEOffset:flatbuffers.Offset, DEFAULT_INTERVAL_MS:bigint, HTTP_PATHOffset:flatbuffers.Offset):flatbuffers.Offset {
  PLGFlowTrigger.startPLGFlowTrigger(builder);
  PLGFlowTrigger.addTriggerId(builder, TRIGGER_IDOffset);
  PLGFlowTrigger.addKind(builder, KINDOffset);
  PLGFlowTrigger.addSource(builder, SOURCEOffset);
  PLGFlowTrigger.addDefaultIntervalMs(builder, DEFAULT_INTERVAL_MS);
  PLGFlowTrigger.addHttpPath(builder, HTTP_PATHOffset);
  return PLGFlowTrigger.endPLGFlowTrigger(builder);
}

unpack(): PLGFlowTriggerT {
  return new PLGFlowTriggerT(
    this.TRIGGER_ID(),
    this.KIND(),
    this.SOURCE(),
    this.DEFAULT_INTERVAL_MS(),
    this.HTTP_PATH()
  );
}


unpackTo(_o: PLGFlowTriggerT): void {
  _o.TRIGGER_ID = this.TRIGGER_ID();
  _o.KIND = this.KIND();
  _o.SOURCE = this.SOURCE();
  _o.DEFAULT_INTERVAL_MS = this.DEFAULT_INTERVAL_MS();
  _o.HTTP_PATH = this.HTTP_PATH();
}
}

export class PLGFlowTriggerT implements flatbuffers.IGeneratedObject {
constructor(
  public TRIGGER_ID: string|Uint8Array|null = null,
  public KIND: string|Uint8Array|null = null,
  public SOURCE: string|Uint8Array|null = null,
  public DEFAULT_INTERVAL_MS: bigint = BigInt('0'),
  public HTTP_PATH: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const TRIGGER_ID = (this.TRIGGER_ID !== null ? builder.createString(this.TRIGGER_ID!) : 0);
  const KIND = (this.KIND !== null ? builder.createString(this.KIND!) : 0);
  const SOURCE = (this.SOURCE !== null ? builder.createString(this.SOURCE!) : 0);
  const HTTP_PATH = (this.HTTP_PATH !== null ? builder.createString(this.HTTP_PATH!) : 0);

  return PLGFlowTrigger.createPLGFlowTrigger(builder,
    TRIGGER_ID,
    KIND,
    SOURCE,
    this.DEFAULT_INTERVAL_MS,
    HTTP_PATH
  );
}
}
