// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SPW, SPWT } from './SPW.js';


export class SPWCOLLECTION implements flatbuffers.IUnpackableObject<SPWCOLLECTIONT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SPWCOLLECTION {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSPWCOLLECTION(bb:flatbuffers.ByteBuffer, obj?:SPWCOLLECTION):SPWCOLLECTION {
  return (obj || new SPWCOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSPWCOLLECTION(bb:flatbuffers.ByteBuffer, obj?:SPWCOLLECTION):SPWCOLLECTION {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SPWCOLLECTION()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

RECORDS(index: number, obj?:SPW):SPW|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new SPW()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

recordsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSPWCOLLECTION(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRecords(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, RECORDSOffset, 0);
}

static createRecordsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRecordsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSPWCOLLECTION(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSPWCOLLECTION(builder:flatbuffers.Builder, RECORDSOffset:flatbuffers.Offset):flatbuffers.Offset {
  SPWCOLLECTION.startSPWCOLLECTION(builder);
  SPWCOLLECTION.addRecords(builder, RECORDSOffset);
  return SPWCOLLECTION.endSPWCOLLECTION(builder);
}

unpack(): SPWCOLLECTIONT {
  return new SPWCOLLECTIONT(
    this.bb!.createObjList<SPW, SPWT>(this.RECORDS.bind(this), this.recordsLength())
  );
}


unpackTo(_o: SPWCOLLECTIONT): void {
  _o.RECORDS = this.bb!.createObjList<SPW, SPWT>(this.RECORDS.bind(this), this.recordsLength());
}
}

export class SPWCOLLECTIONT implements flatbuffers.IGeneratedObject {
constructor(
  public RECORDS: (SPWT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const RECORDS = SPWCOLLECTION.createRecordsVector(builder, builder.createObjectOffsetList(this.RECORDS));

  return SPWCOLLECTION.createSPWCOLLECTION(builder,
    RECORDS
  );
}
}
