import * as flatbuffers from 'flatbuffers';
import { SLPAttestation, SLPAttestationT } from './SLPAttestation.js';
import { SLPGoal, SLPGoalT } from './SLPGoal.js';
import { SLPNonlinearConstraint, SLPNonlinearConstraintT } from './SLPNonlinearConstraint.js';
import { SLPObjective, SLPObjectiveT } from './SLPObjective.js';
import { SLPSolverReport, SLPSolverReportT } from './SLPSolverReport.js';
import { SLPSolverSettings, SLPSolverSettingsT } from './SLPSolverSettings.js';
import { SLPVariable, SLPVariableT } from './SLPVariable.js';
import { slpProblemKind } from './slpProblemKind.js';
export declare class SLP implements flatbuffers.IUnpackableObject<SLPT> {
    bb: flatbuffers.ByteBuffer | null;
    bb_pos: number;
    __init(i: number, bb: flatbuffers.ByteBuffer): SLP;
    static getRootAsSLP(bb: flatbuffers.ByteBuffer, obj?: SLP): SLP;
    static getSizePrefixedRootAsSLP(bb: flatbuffers.ByteBuffer, obj?: SLP): SLP;
    static bufferHasIdentifier(bb: flatbuffers.ByteBuffer): boolean;
    PROBLEM_ID(): string;
    PROBLEM_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    NAME(): string | null;
    NAME(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    KIND(): slpProblemKind;
    PROPAGATOR_PORT_ID(): string;
    PROPAGATOR_PORT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array;
    OBJECTIVE_EVALUATOR_PORT_ID(): string | null;
    OBJECTIVE_EVALUATOR_PORT_ID(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    VARIABLES(index: number, obj?: SLPVariable): SLPVariable | null;
    variablesLength(): number;
    GOALS(index: number, obj?: SLPGoal): SLPGoal | null;
    goalsLength(): number;
    OBJECTIVE(obj?: SLPObjective): SLPObjective | null;
    CONSTRAINTS(index: number, obj?: SLPNonlinearConstraint): SLPNonlinearConstraint | null;
    constraintsLength(): number;
    SETTINGS(obj?: SLPSolverSettings): SLPSolverSettings | null;
    REPORT(obj?: SLPSolverReport): SLPSolverReport | null;
    CREATED_AT(): string | null;
    CREATED_AT(optionalEncoding: flatbuffers.Encoding): string | Uint8Array | null;
    ATTESTATION(obj?: SLPAttestation): SLPAttestation | null;
    static startSLP(builder: flatbuffers.Builder): void;
    static addProblemId(builder: flatbuffers.Builder, PROBLEM_IDOffset: flatbuffers.Offset): void;
    static addName(builder: flatbuffers.Builder, NAMEOffset: flatbuffers.Offset): void;
    static addKind(builder: flatbuffers.Builder, KIND: slpProblemKind): void;
    static addPropagatorPortId(builder: flatbuffers.Builder, PROPAGATOR_PORT_IDOffset: flatbuffers.Offset): void;
    static addObjectiveEvaluatorPortId(builder: flatbuffers.Builder, OBJECTIVE_EVALUATOR_PORT_IDOffset: flatbuffers.Offset): void;
    static addVariables(builder: flatbuffers.Builder, VARIABLESOffset: flatbuffers.Offset): void;
    static createVariablesVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startVariablesVector(builder: flatbuffers.Builder, numElems: number): void;
    static addGoals(builder: flatbuffers.Builder, GOALSOffset: flatbuffers.Offset): void;
    static createGoalsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startGoalsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addObjective(builder: flatbuffers.Builder, OBJECTIVEOffset: flatbuffers.Offset): void;
    static addConstraints(builder: flatbuffers.Builder, CONSTRAINTSOffset: flatbuffers.Offset): void;
    static createConstraintsVector(builder: flatbuffers.Builder, data: flatbuffers.Offset[]): flatbuffers.Offset;
    static startConstraintsVector(builder: flatbuffers.Builder, numElems: number): void;
    static addSettings(builder: flatbuffers.Builder, SETTINGSOffset: flatbuffers.Offset): void;
    static addReport(builder: flatbuffers.Builder, REPORTOffset: flatbuffers.Offset): void;
    static addCreatedAt(builder: flatbuffers.Builder, CREATED_ATOffset: flatbuffers.Offset): void;
    static addAttestation(builder: flatbuffers.Builder, ATTESTATIONOffset: flatbuffers.Offset): void;
    static endSLP(builder: flatbuffers.Builder): flatbuffers.Offset;
    static finishSLPBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    static finishSizePrefixedSLPBuffer(builder: flatbuffers.Builder, offset: flatbuffers.Offset): void;
    unpack(): SLPT;
    unpackTo(_o: SLPT): void;
}
export declare class SLPT implements flatbuffers.IGeneratedObject {
    PROBLEM_ID: string | Uint8Array | null;
    NAME: string | Uint8Array | null;
    KIND: slpProblemKind;
    PROPAGATOR_PORT_ID: string | Uint8Array | null;
    OBJECTIVE_EVALUATOR_PORT_ID: string | Uint8Array | null;
    VARIABLES: (SLPVariableT)[];
    GOALS: (SLPGoalT)[];
    OBJECTIVE: SLPObjectiveT | null;
    CONSTRAINTS: (SLPNonlinearConstraintT)[];
    SETTINGS: SLPSolverSettingsT | null;
    REPORT: SLPSolverReportT | null;
    CREATED_AT: string | Uint8Array | null;
    ATTESTATION: SLPAttestationT | null;
    constructor(PROBLEM_ID?: string | Uint8Array | null, NAME?: string | Uint8Array | null, KIND?: slpProblemKind, PROPAGATOR_PORT_ID?: string | Uint8Array | null, OBJECTIVE_EVALUATOR_PORT_ID?: string | Uint8Array | null, VARIABLES?: (SLPVariableT)[], GOALS?: (SLPGoalT)[], OBJECTIVE?: SLPObjectiveT | null, CONSTRAINTS?: (SLPNonlinearConstraintT)[], SETTINGS?: SLPSolverSettingsT | null, REPORT?: SLPSolverReportT | null, CREATED_AT?: string | Uint8Array | null, ATTESTATION?: SLPAttestationT | null);
    pack(builder: flatbuffers.Builder): flatbuffers.Offset;
}
//# sourceMappingURL=SLP.d.ts.map