// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * GeoJSON Feature object
 */
@Suppress("unused")
class GJNFeature : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : GJNFeature {
        __init(_i, _bb)
        return this
    }
    /**
     * Feature identifier (optional, string form)
     */
    val id : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val idAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun idInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    /**
     * Geometry of the feature
     */
    val geometry : GJNGeometry? get() = geometry(GJNGeometry())
    fun geometry(obj: GJNGeometry) : GJNGeometry? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    /**
     * Properties as key-value pairs
     */
    fun properties(j: Int) : GJNProperty? = properties(GJNProperty(), j)
    fun properties(obj: GJNProperty, j: Int) : GJNProperty? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val propertiesLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    /**
     * Numeric feature identifier (use when ID_IS_NUMERIC is true)
     */
    val numId : Double
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getDouble(o + bb_pos) else 0.0
        }
    /**
     * True if the feature id is numeric rather than string
     */
    val idIsNumeric : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    /**
     * True if the feature has a geometry (false means geometry was JSON null)
     */
    val hasGeometry : Boolean
        get() {
            val o = __offset(14)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    /**
     * True if properties was JSON null (vs empty object)
     */
    val propertiesIsNull : Boolean
        get() {
            val o = __offset(16)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    /**
     * Bounding box (optional, per RFC 7946 Section 5)
     */
    val bbox : GJNBoundingBox? get() = bbox(GJNBoundingBox())
    fun bbox(obj: GJNBoundingBox) : GJNBoundingBox? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_12_19()
        fun getRootAsGJNFeature(_bb: ByteBuffer): GJNFeature = getRootAsGJNFeature(_bb, GJNFeature())
        fun getRootAsGJNFeature(_bb: ByteBuffer, obj: GJNFeature): GJNFeature {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createGJNFeature(builder: FlatBufferBuilder, idOffset: Int, geometryOffset: Int, propertiesOffset: Int, numId: Double, idIsNumeric: Boolean, hasGeometry: Boolean, propertiesIsNull: Boolean, bboxOffset: Int) : Int {
            builder.startTable(8)
            addNUMID(builder, numId)
            addBBOX(builder, bboxOffset)
            addPROPERTIES(builder, propertiesOffset)
            addGEOMETRY(builder, geometryOffset)
            addID(builder, idOffset)
            addPROPERTIESISNULL(builder, propertiesIsNull)
            addHASGEOMETRY(builder, hasGeometry)
            addIDISNUMERIC(builder, idIsNumeric)
            return endGJNFeature(builder)
        }
        fun startGJNFeature(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addID(builder: FlatBufferBuilder, id: Int) = builder.addOffset(0, id, 0)
        fun addGEOMETRY(builder: FlatBufferBuilder, geometry: Int) = builder.addOffset(1, geometry, 0)
        fun addPROPERTIES(builder: FlatBufferBuilder, properties: Int) = builder.addOffset(2, properties, 0)
        fun createPropertiesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startPropertiesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addNUMID(builder: FlatBufferBuilder, numId: Double) = builder.addDouble(3, numId, 0.0)
        fun addIDISNUMERIC(builder: FlatBufferBuilder, idIsNumeric: Boolean) = builder.addBoolean(4, idIsNumeric, false)
        fun addHASGEOMETRY(builder: FlatBufferBuilder, hasGeometry: Boolean) = builder.addBoolean(5, hasGeometry, false)
        fun addPROPERTIESISNULL(builder: FlatBufferBuilder, propertiesIsNull: Boolean) = builder.addBoolean(6, propertiesIsNull, false)
        fun addBBOX(builder: FlatBufferBuilder, bbox: Int) = builder.addOffset(7, bbox, 0)
        fun endGJNFeature(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
